// The engine's own operations, typed. **Generated by
// `cargo xtask engine`. Do not edit.**
//
// From the engine's own description at version `0.1.0`.
// Which of its functions are here is a measurement, not a choice:
// `docs/03-design/engine-passthrough-measured.md` classifies all of
// them into what is callable, what this adapter will never hand over,
// and what is queued behind one more shape.
//
// A method's arguments are named the way this language names things;
// the keys that cross are the engine's own, which is what
// `sdk.engine.signature(name)` reads. A call through here is to a
// named engine and does not survive changing it — which is why it is
// taken as a value rather than laid over `sdk.engine` (ADR-0030).

/** `tm_datetime` as the engine answers it, spelled as a consumer reads it. */
const readTmDatetime = (value) => ({ year: value.year, month: value.month, day: value.day, hour: value.hour, minute: value.minute, second: value.second });

/** `tm_datetime` as a consumer writes it, keyed as the engine reads it. */
const writeTmDatetime = (value) => ({ year: value.year, month: value.month, day: value.day, hour: value.hour, minute: value.minute, second: value.second });

/** `tm_observer` as the engine answers it, spelled as a consumer reads it. */
const readTmObserver = (value) => ({ longitudeDeg: value.longitude_deg, latitudeDeg: value.latitude_deg, altitudeM: value.altitude_m });

/** `tm_observer` as a consumer writes it, keyed as the engine reads it. */
const writeTmObserver = (value) => ({ longitude_deg: value.longitudeDeg, latitude_deg: value.latitudeDeg, altitude_m: value.altitudeM });

/** `tm_position` as the engine answers it, spelled as a consumer reads it. */
const readTmPosition = (value) => ({ lon: value.lon, lat: value.lat, dist: value.dist, lonSpeed: value.lon_speed, latSpeed: value.lat_speed, distSpeed: value.dist_speed, flagsUsed: value.flags_used, status: value.status });

/** `tm_position` as a consumer writes it, keyed as the engine reads it. */
const writeTmPosition = (value) => ({ lon: value.lon, lat: value.lat, dist: value.dist, lon_speed: value.lonSpeed, lat_speed: value.latSpeed, dist_speed: value.distSpeed, flags_used: value.flagsUsed, status: value.status });

/** `tm_atmosphere` as the engine answers it, spelled as a consumer reads it. */
const readTmAtmosphere = (value) => ({ pressureMbar: value.pressure_mbar, temperatureC: value.temperature_c, lapseRateKPerM: value.lapse_rate_k_per_m });

/** `tm_atmosphere` as a consumer writes it, keyed as the engine reads it. */
const writeTmAtmosphere = (value) => ({ pressure_mbar: value.pressureMbar, temperature_c: value.temperatureC, lapse_rate_k_per_m: value.lapseRateKPerM });

/** `tm_refraction` as the engine answers it, spelled as a consumer reads it. */
const readTmRefraction = (value) => ({ altitudeTrue: value.altitude_true, altitudeApparent: value.altitude_apparent, refraction: value.refraction, horizonDip: value.horizon_dip, observable: value.observable });

/** `tm_refraction` as a consumer writes it, keyed as the engine reads it. */
const writeTmRefraction = (value) => ({ altitude_true: value.altitudeTrue, altitude_apparent: value.altitudeApparent, refraction: value.refraction, horizon_dip: value.horizonDip, observable: value.observable });

/** `tm_obliquity` as the engine answers it, spelled as a consumer reads it. */
const readTmObliquity = (value) => ({ trueObliquity: value.true_obliquity, meanObliquity: value.mean_obliquity, nutationLon: value.nutation_lon, nutationObl: value.nutation_obl });

/** `tm_obliquity` as a consumer writes it, keyed as the engine reads it. */
const writeTmObliquity = (value) => ({ true_obliquity: value.trueObliquity, mean_obliquity: value.meanObliquity, nutation_lon: value.nutationLon, nutation_obl: value.nutationObl });

/** `tm_horizontal` as the engine answers it, spelled as a consumer reads it. */
const readTmHorizontal = (value) => ({ azimuth: value.azimuth, azimuthNorth: value.azimuth_north, altitudeTrue: value.altitude_true, altitudeApparent: value.altitude_apparent });

/** `tm_horizontal` as a consumer writes it, keyed as the engine reads it. */
const writeTmHorizontal = (value) => ({ azimuth: value.azimuth, azimuth_north: value.azimuthNorth, altitude_true: value.altitudeTrue, altitude_apparent: value.altitudeApparent });

/** `tm_coord` as the engine answers it, spelled as a consumer reads it. */
const readTmCoord = (value) => ({ lon: value.lon, lat: value.lat });

/** `tm_coord` as a consumer writes it, keyed as the engine reads it. */
const writeTmCoord = (value) => ({ lon: value.lon, lat: value.lat });

/** `tm_coverage` as the engine answers it, spelled as a consumer reads it. */
const readTmCoverage = (value) => ({ jdStart: value.jd_start, jdEnd: value.jd_end, contiguous: value.contiguous, fileCount: value.file_count });

/** `tm_coverage` as a consumer writes it, keyed as the engine reads it. */
const writeTmCoverage = (value) => ({ jd_start: value.jdStart, jd_end: value.jdEnd, contiguous: value.contiguous, file_count: value.fileCount });

/** `tm_fallback_stats` as the engine answers it, spelled as a consumer reads it. */
const readTmFallbackStats = (value) => ({ moshierCalls: value.moshier_calls, refusedCalls: value.refused_calls, lastBody: value.last_body, lastJd: value.last_jd });

/** `tm_fallback_stats` as a consumer writes it, keyed as the engine reads it. */
const writeTmFallbackStats = (value) => ({ moshier_calls: value.moshierCalls, refused_calls: value.refusedCalls, last_body: value.lastBody, last_jd: value.lastJd });

/** `tm_nodes_apsides` as the engine answers it, spelled as a consumer reads it. */
const readTmNodesApsides = (value) => ({ ascending: readTmPosition(value.ascending), descending: readTmPosition(value.descending), perihelion: readTmPosition(value.perihelion), aphelion: readTmPosition(value.aphelion), usedMean: value.used_mean, flagsUsed: value.flags_used, status: value.status });

/** `tm_nodes_apsides` as a consumer writes it, keyed as the engine reads it. */
const writeTmNodesApsides = (value) => ({ ascending: writeTmPosition(value.ascending), descending: writeTmPosition(value.descending), perihelion: writeTmPosition(value.perihelion), aphelion: writeTmPosition(value.aphelion), used_mean: value.usedMean, flags_used: value.flagsUsed, status: value.status });

/** `tm_orbital_elements` as the engine answers it, spelled as a consumer reads it. */
const readTmOrbitalElements = (value) => ({ semiMajorAxis: value.semi_major_axis, eccentricity: value.eccentricity, inclination: value.inclination, node: value.node, argPerihelion: value.arg_perihelion, lonPerihelion: value.lon_perihelion, meanAnomaly: value.mean_anomaly, trueAnomaly: value.true_anomaly, eccentricAnomaly: value.eccentric_anomaly, meanLongitude: value.mean_longitude, periodSidereal: value.period_sidereal, dailyMotion: value.daily_motion, periodTropical: value.period_tropical, periodSynodic: value.period_synodic, perihelionTime: value.perihelion_time, perihelionDistance: value.perihelion_distance, aphelionDistance: value.aphelion_distance, status: value.status });

/** `tm_orbital_elements` as a consumer writes it, keyed as the engine reads it. */
const writeTmOrbitalElements = (value) => ({ semi_major_axis: value.semiMajorAxis, eccentricity: value.eccentricity, inclination: value.inclination, node: value.node, arg_perihelion: value.argPerihelion, lon_perihelion: value.lonPerihelion, mean_anomaly: value.meanAnomaly, true_anomaly: value.trueAnomaly, eccentric_anomaly: value.eccentricAnomaly, mean_longitude: value.meanLongitude, period_sidereal: value.periodSidereal, daily_motion: value.dailyMotion, period_tropical: value.periodTropical, period_synodic: value.periodSynodic, perihelion_time: value.perihelionTime, perihelion_distance: value.perihelionDistance, aphelion_distance: value.aphelionDistance, status: value.status });

/** `tm_orbit_distances` as the engine answers it, spelled as a consumer reads it. */
const readTmOrbitDistances = (value) => ({ maxDistance: value.max_distance, minDistance: value.min_distance, trueDistance: value.true_distance, status: value.status });

/** `tm_orbit_distances` as a consumer writes it, keyed as the engine reads it. */
const writeTmOrbitDistances = (value) => ({ max_distance: value.maxDistance, min_distance: value.minDistance, true_distance: value.trueDistance, status: value.status });

/** `tm_phenomena` as the engine answers it, spelled as a consumer reads it. */
const readTmPhenomena = (value) => ({ phaseAngle: value.phase_angle, phase: value.phase, elongation: value.elongation, diameter: value.diameter, magnitude: value.magnitude, horizontalParallax: value.horizontal_parallax, magnitudeOutOfRange: value.magnitude_out_of_range, flagsUsed: value.flags_used, status: value.status, magnitudeState: value.magnitude_state });

/** `tm_phenomena` as a consumer writes it, keyed as the engine reads it. */
const writeTmPhenomena = (value) => ({ phase_angle: value.phaseAngle, phase: value.phase, elongation: value.elongation, diameter: value.diameter, magnitude: value.magnitude, horizontal_parallax: value.horizontalParallax, magnitude_out_of_range: value.magnitudeOutOfRange, flags_used: value.flagsUsed, status: value.status, magnitude_state: value.magnitudeState });

/** `tm_star` as the engine answers it, spelled as a consumer reads it. */
const readTmStar = (value) => ({ id: value.id, catalogueGeneration: value.catalogue_generation, magnitude: value.magnitude, epoch: value.epoch, raDeg: value.ra_deg, decDeg: value.dec_deg, pmRaArcsecPerCentury: value.pm_ra_arcsec_per_century, pmDecArcsecPerCentury: value.pm_dec_arcsec_per_century, radialVelocityAuPerCentury: value.radial_velocity_au_per_century, parallaxArcsec: value.parallax_arcsec });

/** `tm_star` as a consumer writes it, keyed as the engine reads it. */
const writeTmStar = (value) => ({ id: value.id, catalogue_generation: value.catalogueGeneration, magnitude: value.magnitude, epoch: value.epoch, ra_deg: value.raDeg, dec_deg: value.decDeg, pm_ra_arcsec_per_century: value.pmRaArcsecPerCentury, pm_dec_arcsec_per_century: value.pmDecArcsecPerCentury, radial_velocity_au_per_century: value.radialVelocityAuPerCentury, parallax_arcsec: value.parallaxArcsec });

/** `tm_eclipse_attributes` as the engine answers it, spelled as a consumer reads it. */
const readTmEclipseAttributes = (value) => ({ magnitude: value.magnitude, diameterRatio: value.diameter_ratio, obscuration: value.obscuration, coreShadowKm: value.core_shadow_km, azimuth: value.azimuth, azimuthNorth: value.azimuth_north, altitudeTrue: value.altitude_true, altitudeApparent: value.altitude_apparent, separation: value.separation, magnitudeNasa: value.magnitude_nasa, sarosKnown: value.saros_known, sarosSeries: value.saros_series, sarosMember: value.saros_member });

/** `tm_eclipse_attributes` as a consumer writes it, keyed as the engine reads it. */
const writeTmEclipseAttributes = (value) => ({ magnitude: value.magnitude, diameter_ratio: value.diameterRatio, obscuration: value.obscuration, core_shadow_km: value.coreShadowKm, azimuth: value.azimuth, azimuth_north: value.azimuthNorth, altitude_true: value.altitudeTrue, altitude_apparent: value.altitudeApparent, separation: value.separation, magnitude_nasa: value.magnitudeNasa, saros_known: value.sarosKnown, saros_series: value.sarosSeries, saros_member: value.sarosMember });

/** `tm_lunar_eclipse_attributes` as the engine answers it, spelled as a consumer reads it. */
const readTmLunarEclipseAttributes = (value) => ({ umbralMagnitude: value.umbral_magnitude, penumbralMagnitude: value.penumbral_magnitude, azimuth: value.azimuth, azimuthNorth: value.azimuth_north, altitudeTrue: value.altitude_true, altitudeApparent: value.altitude_apparent, opposition: value.opposition, sarosKnown: value.saros_known, sarosSeries: value.saros_series, sarosMember: value.saros_member });

/** `tm_lunar_eclipse_attributes` as a consumer writes it, keyed as the engine reads it. */
const writeTmLunarEclipseAttributes = (value) => ({ umbral_magnitude: value.umbralMagnitude, penumbral_magnitude: value.penumbralMagnitude, azimuth: value.azimuth, azimuth_north: value.azimuthNorth, altitude_true: value.altitudeTrue, altitude_apparent: value.altitudeApparent, opposition: value.opposition, saros_known: value.sarosKnown, saros_series: value.sarosSeries, saros_member: value.sarosMember });

/** `tm_eclipse_location` as the engine answers it, spelled as a consumer reads it. */
const readTmEclipseLocation = (value) => ({ longitude: value.longitude, latitude: value.latitude, coreShadowKm: value.core_shadow_km, penumbraKm: value.penumbra_km, axisDistanceKm: value.axis_distance_km, umbraFundamentalKm: value.umbra_fundamental_km, penumbraFundamentalKm: value.penumbra_fundamental_km });

/** `tm_eclipse_location` as a consumer writes it, keyed as the engine reads it. */
const writeTmEclipseLocation = (value) => ({ longitude: value.longitude, latitude: value.latitude, core_shadow_km: value.coreShadowKm, penumbra_km: value.penumbraKm, axis_distance_km: value.axisDistanceKm, umbra_fundamental_km: value.umbraFundamentalKm, penumbra_fundamental_km: value.penumbraFundamentalKm });

/** `tm_visibility_atmosphere` as the engine answers it, spelled as a consumer reads it. */
const readTmVisibilityAtmosphere = (value) => ({ pressureMbar: value.pressure_mbar, temperatureC: value.temperature_c, humidityPct: value.humidity_pct, haze: value.haze });

/** `tm_visibility_atmosphere` as a consumer writes it, keyed as the engine reads it. */
const writeTmVisibilityAtmosphere = (value) => ({ pressure_mbar: value.pressureMbar, temperature_c: value.temperatureC, humidity_pct: value.humidityPct, haze: value.haze });

/** `tm_observer_eye` as the engine answers it, spelled as a consumer reads it. */
const readTmObserverEye = (value) => ({ ageYears: value.age_years, snellen: value.snellen, monocular: value.monocular, useOptics: value.use_optics, magnification: value.magnification, apertureMm: value.aperture_mm, transmission: value.transmission });

/** `tm_observer_eye` as a consumer writes it, keyed as the engine reads it. */
const writeTmObserverEye = (value) => ({ age_years: value.ageYears, snellen: value.snellen, monocular: value.monocular, use_optics: value.useOptics, magnification: value.magnification, aperture_mm: value.apertureMm, transmission: value.transmission });

/** `tm_visibility` as the engine answers it, spelled as a consumer reads it. */
const readTmVisibility = (value) => ({ limitingMagnitude: value.limiting_magnitude, objectMagnitude: value.object_magnitude, objectAltitude: value.object_altitude, objectAzimuth: value.object_azimuth, objectAzimuthNorth: value.object_azimuth_north, sunAltitude: value.sun_altitude, sunAzimuth: value.sun_azimuth, moonAltitude: value.moon_altitude, moonAzimuth: value.moon_azimuth, scotopic: value.scotopic, nearSwitch: value.near_switch, aboveHorizon: value.above_horizon, status: value.status });

/** `tm_visibility` as a consumer writes it, keyed as the engine reads it. */
const writeTmVisibility = (value) => ({ limiting_magnitude: value.limitingMagnitude, object_magnitude: value.objectMagnitude, object_altitude: value.objectAltitude, object_azimuth: value.objectAzimuth, object_azimuth_north: value.objectAzimuthNorth, sun_altitude: value.sunAltitude, sun_azimuth: value.sunAzimuth, moon_altitude: value.moonAltitude, moon_azimuth: value.moonAzimuth, scotopic: value.scotopic, near_switch: value.nearSwitch, above_horizon: value.aboveHorizon, status: value.status });

/** `tm_visibility_best` as the engine answers it, spelled as a consumer reads it. */
const readTmVisibilityBest = (value) => ({ objectAltitude: value.object_altitude, arcus: value.arcus, sunAltitude: value.sun_altitude });

/** `tm_visibility_best` as a consumer writes it, keyed as the engine reads it. */
const writeTmVisibilityBest = (value) => ({ object_altitude: value.objectAltitude, arcus: value.arcus, sun_altitude: value.sunAltitude });

/** `tm_crossing_request` as the engine answers it, spelled as a consumer reads it. */
const readTmCrossingRequest = (value) => ({ jdStart: value.jd_start, scale: value.scale, body: value.body, targetDeg: value.target_deg, flags: value.flags, backward: value.backward, jdEnd: value.jd_end, quantity: value.quantity, stepDeg: value.step_deg, bodyB: value.body_b, coeffA: value.coeff_a, coeffB: value.coeff_b });

/** `tm_crossing_request` as a consumer writes it, keyed as the engine reads it. */
const writeTmCrossingRequest = (value) => ({ jd_start: value.jdStart, scale: value.scale, body: value.body, target_deg: value.targetDeg, flags: value.flags, backward: value.backward, jd_end: value.jdEnd, quantity: value.quantity, step_deg: value.stepDeg, body_b: value.bodyB, coeff_a: value.coeffA, coeff_b: value.coeffB });

/** `tm_crossing` as the engine answers it, spelled as a consumer reads it. */
const readTmCrossing = (value) => ({ jd: value.jd, longitude: value.longitude, latitude: value.latitude, status: value.status });

/** `tm_crossing` as a consumer writes it, keyed as the engine reads it. */
const writeTmCrossing = (value) => ({ jd: value.jd, longitude: value.longitude, latitude: value.latitude, status: value.status });

/** `tm_angle_parts` as the engine answers it, spelled as a consumer reads it. */
const readTmAngleParts = (value) => ({ negative: value.negative, degrees: value.degrees, minutes: value.minutes, seconds: value.seconds, secondFraction: value.second_fraction, zodiacSign: value.zodiac_sign, nakshatra: value.nakshatra, pada: value.pada });

/** `tm_angle_parts` as a consumer writes it, keyed as the engine reads it. */
const writeTmAngleParts = (value) => ({ negative: value.negative, degrees: value.degrees, minutes: value.minutes, seconds: value.seconds, second_fraction: value.secondFraction, zodiac_sign: value.zodiacSign, nakshatra: value.nakshatra, pada: value.pada });

export class TeimerisEngine {
  #engine;

  constructor(engine) {
    this.#engine = engine;
    Object.freeze(this);
  }

  /**
   * `tm_status_name`.
   */
  tmStatusName({ s }) {
    return this.#engine.call('tm_status_name', { s }).return;
  }

  /**
   * `tm_context_release_caches`.
   */
  tmContextReleaseCaches() {
    this.#engine.call('tm_context_release_caches', {});
  }

  /**
   * `tm_version_string`.
   */
  tmVersionString() {
    return this.#engine.call('tm_version_string', {}).return;
  }

  /**
   * `tm_version`.
   */
  tmVersion() {
    const answered = this.#engine.call('tm_version', {});
    return { major: answered.major, minor: answered.minor, patch: answered.patch };
  }

  /**
   * `tm_body_name`.
   */
  tmBodyName({ body }) {
    return this.#engine.call('tm_body_name', { body }).buf;
  }

  /**
   * `tm_julian_day`.
   */
  tmJulianDay({ dt, cal }) {
    return this.#engine.call('tm_julian_day', { dt: dt == null ? null : writeTmDatetime(dt), cal }).out_jd;
  }

  /**
   * `tm_calendar_date`.
   */
  tmCalendarDate({ jd, cal }) {
    return readTmDatetime(this.#engine.call('tm_calendar_date', { jd, cal }).out);
  }

  /**
   * `tm_utc_to_jd`.
   */
  tmUtcToJd({ utc, cal }) {
    const answered = this.#engine.call('tm_utc_to_jd', { utc: utc == null ? null : writeTmDatetime(utc), cal });
    return { outJdTt: answered.out_jd_tt, outJdUt1: answered.out_jd_ut1 };
  }

  /**
   * `tm_jd_to_utc`.
   */
  tmJdToUtc({ jd, scale, cal }) {
    return readTmDatetime(this.#engine.call('tm_jd_to_utc', { jd, scale, cal }).out);
  }

  /**
   * `tm_delta_t`.
   */
  tmDeltaT({ jdUt1 }) {
    return this.#engine.call('tm_delta_t', { jd_ut1: jdUt1 }).out_seconds;
  }

  /**
   * `tm_sidereal_time`.
   */
  tmSiderealTime({ jdUt1, geoLonDeg }) {
    return this.#engine.call('tm_sidereal_time', { jd_ut1: jdUt1, geo_lon_deg: geoLonDeg }).out_hours;
  }

  /**
   * `tm_day_of_week`.
   */
  tmDayOfWeek({ jd }) {
    return this.#engine.call('tm_day_of_week', { jd }).return;
  }

  /**
   * `tm_weekday_name`.
   */
  tmWeekdayName({ day }) {
    return this.#engine.call('tm_weekday_name', { day }).return;
  }

  /**
   * `tm_julian_day_many`.
   */
  tmJulianDayMany({ dts, cal }) {
    return this.#engine.call('tm_julian_day_many', { dts: dts.map(writeTmDatetime), cal }).out_jd;
  }

  /**
   * `tm_calendar_date_many`.
   */
  tmCalendarDateMany({ jds, cal }) {
    return this.#engine.call('tm_calendar_date_many', { jds, cal }).out.map(readTmDatetime);
  }

  /**
   * `tm_delta_t_many`.
   */
  tmDeltaTMany({ jdsUt1 }) {
    return this.#engine.call('tm_delta_t_many', { jds_ut1: jdsUt1 }).out_seconds;
  }

  /**
   * `tm_sidereal_time_many`.
   */
  tmSiderealTimeMany({ jdsUt1, geoLonDeg }) {
    return this.#engine.call('tm_sidereal_time_many', { jds_ut1: jdsUt1, geo_lon_deg: geoLonDeg }).out_hours;
  }

  /**
   * `tm_equation_of_time`.
   */
  tmEquationOfTime({ jdUt1 }) {
    return this.#engine.call('tm_equation_of_time', { jd_ut1: jdUt1 }).out_seconds;
  }

  /**
   * `tm_local_mean_to_apparent`.
   */
  tmLocalMeanToApparent({ jdLocalMean, geoLonDeg }) {
    return this.#engine.call('tm_local_mean_to_apparent', { jd_local_mean: jdLocalMean, geo_lon_deg: geoLonDeg }).out_jd_local_apparent;
  }

  /**
   * `tm_local_apparent_to_mean`.
   */
  tmLocalApparentToMean({ jdLocalApparent, geoLonDeg }) {
    return this.#engine.call('tm_local_apparent_to_mean', { jd_local_apparent: jdLocalApparent, geo_lon_deg: geoLonDeg }).out_jd_local_mean;
  }

  /**
   * `tm_local_to_utc`.
   */
  tmLocalToUtc({ local, utcOffsetHours, cal }) {
    return readTmDatetime(this.#engine.call('tm_local_to_utc', { local: local == null ? null : writeTmDatetime(local), utc_offset_hours: utcOffsetHours, cal }).out_utc);
  }

  /**
   * `tm_utc_to_local`.
   */
  tmUtcToLocal({ utc, utcOffsetHours, cal }) {
    return readTmDatetime(this.#engine.call('tm_utc_to_local', { utc: utc == null ? null : writeTmDatetime(utc), utc_offset_hours: utcOffsetHours, cal }).out_local);
  }

  /**
   * `tm_position_value`.
   */
  tmPositionValue({ jd, scale, body, flags, field }) {
    return this.#engine.call('tm_position_value', { jd, scale, body, flags, field }).out;
  }

  /**
   * `tm_position_calc_grid`.
   */
  tmPositionCalcGrid({ bodies, jds, scale, flags, observer }) {
    return this.#engine.call('tm_position_calc_grid', { bodies, jds, scale, flags, observer: observer == null ? null : writeTmObserver(observer) }).out.map(readTmPosition);
  }

  /**
   * `tm_house_cusp_count`.
   */
  tmHouseCuspCount({ sys }) {
    return this.#engine.call('tm_house_cusp_count', { sys }).return;
  }

  /**
   * `tm_house_system_name`.
   */
  tmHouseSystemName({ sys }) {
    return this.#engine.call('tm_house_system_name', { sys }).return;
  }

  /**
   * `tm_house_system_count`.
   */
  tmHouseSystemCount() {
    return this.#engine.call('tm_house_system_count', {}).return;
  }

  /**
   * `tm_house_position`.
   */
  tmHousePosition({ armc, geoLatDeg, obliquityDeg, sys, lonDeg, latDeg }) {
    return this.#engine.call('tm_house_position', { armc, geo_lat_deg: geoLatDeg, obliquity_deg: obliquityDeg, sys, lon_deg: lonDeg, lat_deg: latDeg }).out_house;
  }

  /**
   * `tm_chart_default_bodies`.
   */
  tmChartDefaultBodies() {
    return this.#engine.call('tm_chart_default_bodies', {}).out_bodies;
  }

  /**
   * `tm_set_jpl_file`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetJplFile({ filename }) {
    this.#engine.call('tm_set_jpl_file', { filename });
  }

  /**
   * `tm_jpl_info`.
   */
  tmJplInfo() {
    const answered = this.#engine.call('tm_jpl_info', {});
    return { outDenum: answered.out_denum, outJdStart: answered.out_jd_start, outJdEnd: answered.out_jd_end, outSegmentDays: answered.out_segment_days };
  }

  /**
   * `tm_set_ayanamsha`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetAyanamsha({ mode, t0, ayanT0 }) {
    this.#engine.call('tm_set_ayanamsha', { mode, t0, ayan_t0: ayanT0 });
  }

  /**
   * `tm_ayanamsha_value`.
   */
  tmAyanamshaValue({ jd, scale, flags }) {
    return this.#engine.call('tm_ayanamsha_value', { jd, scale, flags }).out_degrees;
  }

  /**
   * `tm_ayanamsha_name`.
   */
  tmAyanamshaName({ mode }) {
    return this.#engine.call('tm_ayanamsha_name', { mode }).return;
  }

  /**
   * `tm_ayanamsha_count`.
   */
  tmAyanamshaCount() {
    return this.#engine.call('tm_ayanamsha_count', {}).return;
  }

  /**
   * `tm_set_model`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetModel({ kind, model }) {
    this.#engine.call('tm_set_model', { kind, model });
  }

  /**
   * `tm_get_model`.
   */
  tmGetModel({ kind }) {
    return this.#engine.call('tm_get_model', { kind }).out_model;
  }

  /**
   * `tm_model_name`.
   */
  tmModelName({ kind, model }) {
    return this.#engine.call('tm_model_name', { kind, model }).return;
  }

  /**
   * `tm_model_kind_name`.
   */
  tmModelKindName({ kind }) {
    return this.#engine.call('tm_model_kind_name', { kind }).return;
  }

  /**
   * `tm_model_count`.
   */
  tmModelCount({ kind }) {
    return this.#engine.call('tm_model_count', { kind }).return;
  }

  /**
   * `tm_set_tidal_acceleration`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetTidalAcceleration({ arcsecPerCentury2 }) {
    this.#engine.call('tm_set_tidal_acceleration', { arcsec_per_century2: arcsecPerCentury2 });
  }

  /**
   * `tm_clear_tidal_acceleration`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmClearTidalAcceleration() {
    this.#engine.call('tm_clear_tidal_acceleration', {});
  }

  /**
   * `tm_get_tidal_acceleration`.
   */
  tmGetTidalAcceleration() {
    const answered = this.#engine.call('tm_get_tidal_acceleration', {});
    return { outValue: answered.out_value, outIsSet: answered.out_is_set };
  }

  /**
   * `tm_set_delta_t_override`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetDeltaTOverride({ seconds }) {
    this.#engine.call('tm_set_delta_t_override', { seconds });
  }

  /**
   * `tm_clear_delta_t_override`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmClearDeltaTOverride() {
    this.#engine.call('tm_clear_delta_t_override', {});
  }

  /**
   * `tm_get_delta_t_override`.
   */
  tmGetDeltaTOverride() {
    const answered = this.#engine.call('tm_get_delta_t_override', {});
    return { outSeconds: answered.out_seconds, outIsSet: answered.out_is_set };
  }

  /**
   * `tm_set_nutation_interpolation`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetNutationInterpolation({ enable }) {
    this.#engine.call('tm_set_nutation_interpolation', { enable });
  }

  /**
   * `tm_get_nutation_interpolation`.
   */
  tmGetNutationInterpolation() {
    return this.#engine.call('tm_get_nutation_interpolation', {}).out;
  }

  /**
   * `tm_atmosphere_init_sized`.
   */
  tmAtmosphereInitSized({ altitudeM, structSize }) {
    return readTmAtmosphere(this.#engine.call('tm_atmosphere_init_sized', { altitude_m: altitudeM, struct_size: structSize }).atm);
  }

  /**
   * `tm_refract`.
   */
  tmRefract({ model, dir, altitudeDeg, obs, atm }) {
    return readTmRefraction(this.#engine.call('tm_refract', { model, dir, altitude_deg: altitudeDeg, obs: obs == null ? null : writeTmObserver(obs), atm: atm == null ? null : writeTmAtmosphere(atm) }).out);
  }

  /**
   * `tm_refract_many`.
   */
  tmRefractMany({ model, dir, altitudesDeg, obs, atm }) {
    return this.#engine.call('tm_refract_many', { model, dir, altitudes_deg: altitudesDeg, obs: obs == null ? null : writeTmObserver(obs), atm: atm == null ? null : writeTmAtmosphere(atm) }).out.map(readTmRefraction);
  }

  /**
   * `tm_obliquity_calc`.
   */
  tmObliquityCalc({ jd, scale }) {
    return readTmObliquity(this.#engine.call('tm_obliquity_calc', { jd, scale }).out);
  }

  /**
   * `tm_coord_rotate`.
   */
  tmCoordRotate({ direction, obliquityDeg, positions }) {
    return this.#engine.call('tm_coord_rotate', { direction, obliquity_deg: obliquityDeg, positions: positions.map(writeTmPosition) }).out.map(readTmPosition);
  }

  /**
   * `tm_to_horizontal`.
   */
  tmToHorizontal({ jd, scale, system, obs, atm, lonDeg, latDeg }) {
    return readTmHorizontal(this.#engine.call('tm_to_horizontal', { jd, scale, system, obs: obs == null ? null : writeTmObserver(obs), atm: atm == null ? null : writeTmAtmosphere(atm), lon_deg: lonDeg, lat_deg: latDeg }).out);
  }

  /**
   * `tm_to_horizontal_many`.
   */
  tmToHorizontalMany({ jd, scale, system, obs, atm, coords }) {
    return this.#engine.call('tm_to_horizontal_many', { jd, scale, system, obs: obs == null ? null : writeTmObserver(obs), atm: atm == null ? null : writeTmAtmosphere(atm), coords: coords.map(writeTmCoord) }).out.map(readTmHorizontal);
  }

  /**
   * `tm_from_horizontal`.
   */
  tmFromHorizontal({ jd, scale, system, obs, azimuthDeg, altitudeDeg }) {
    const answered = this.#engine.call('tm_from_horizontal', { jd, scale, system, obs: obs == null ? null : writeTmObserver(obs), azimuth_deg: azimuthDeg, altitude_deg: altitudeDeg });
    return { outLonDeg: answered.out_lon_deg, outLatDeg: answered.out_lat_deg };
  }

  /**
   * `tm_embedded_coverage`.
   */
  tmEmbeddedCoverage() {
    const answered = this.#engine.call('tm_embedded_coverage', {});
    return { outJdStart: answered.out_jd_start, outJdEnd: answered.out_jd_end };
  }

  /**
   * `tm_body_coverage`.
   */
  tmBodyCoverage({ body }) {
    return readTmCoverage(this.#engine.call('tm_body_coverage', { body }).out);
  }

  /**
   * `tm_fallback_stats_get`.
   */
  tmFallbackStatsGet() {
    return readTmFallbackStats(this.#engine.call('tm_fallback_stats_get', {}).out);
  }

  /**
   * `tm_fallback_stats_reset`.
   */
  tmFallbackStatsReset() {
    this.#engine.call('tm_fallback_stats_reset', {});
  }

  /**
   * `tm_cache_dir_default`.
   */
  tmCacheDirDefault() {
    return this.#engine.call('tm_cache_dir_default', {}).buf;
  }

  /**
   * `tm_nodes_apsides_calc`.
   */
  tmNodesApsidesCalc({ jd, scale, body, flags, method, apsis, observer }) {
    return readTmNodesApsides(this.#engine.call('tm_nodes_apsides_calc', { jd, scale, body, flags, method, apsis, observer: observer == null ? null : writeTmObserver(observer) }).out);
  }

  /**
   * `tm_nodes_apsides_calc_many`.
   */
  tmNodesApsidesCalcMany({ jd, scale, bodies, flags, method, apsis, observer }) {
    return this.#engine.call('tm_nodes_apsides_calc_many', { jd, scale, bodies, flags, method, apsis, observer: observer == null ? null : writeTmObserver(observer) }).out.map(readTmNodesApsides);
  }

  /**
   * `tm_orbital_elements_calc`.
   */
  tmOrbitalElementsCalc({ jd, scale, body, flags, masses }) {
    return readTmOrbitalElements(this.#engine.call('tm_orbital_elements_calc', { jd, scale, body, flags, masses }).out);
  }

  /**
   * `tm_orbital_elements_calc_many`.
   */
  tmOrbitalElementsCalcMany({ jd, scale, bodies, flags, masses }) {
    return this.#engine.call('tm_orbital_elements_calc_many', { jd, scale, bodies, flags, masses }).out.map(readTmOrbitalElements);
  }

  /**
   * `tm_orbit_distances_calc`.
   */
  tmOrbitDistancesCalc({ jd, scale, body, flags }) {
    return readTmOrbitDistances(this.#engine.call('tm_orbit_distances_calc', { jd, scale, body, flags }).out);
  }

  /**
   * `tm_orbit_distances_calc_many`.
   */
  tmOrbitDistancesCalcMany({ jd, scale, bodies, flags }) {
    return this.#engine.call('tm_orbit_distances_calc_many', { jd, scale, bodies, flags }).out.map(readTmOrbitDistances);
  }

  /**
   * `tm_phenomena_calc`.
   */
  tmPhenomenaCalc({ jd, scale, body, flags, observer }) {
    return readTmPhenomena(this.#engine.call('tm_phenomena_calc', { jd, scale, body, flags, observer: observer == null ? null : writeTmObserver(observer) }).out);
  }

  /**
   * `tm_phenomena_calc_many`.
   */
  tmPhenomenaCalcMany({ jd, scale, bodies, flags, observer }) {
    return this.#engine.call('tm_phenomena_calc_many', { jd, scale, bodies, flags, observer: observer == null ? null : writeTmObserver(observer) }).out.map(readTmPhenomena);
  }

  /**
   * `tm_star_name`.
   */
  tmStarName({ star }) {
    return this.#engine.call('tm_star_name', { star: star == null ? null : writeTmStar(star) }).buf;
  }

  /**
   * `tm_star_designation`.
   */
  tmStarDesignation({ star }) {
    return this.#engine.call('tm_star_designation', { star: star == null ? null : writeTmStar(star) }).buf;
  }

  /**
   * `tm_star_load_catalogue`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmStarLoadCatalogue({ path }) {
    this.#engine.call('tm_star_load_catalogue', { path });
  }

  /**
   * `tm_star_count`.
   */
  tmStarCount() {
    return this.#engine.call('tm_star_count', {}).return;
  }

  /**
   * `tm_star_find`.
   */
  tmStarFind({ name }) {
    return readTmStar(this.#engine.call('tm_star_find', { name }).out);
  }

  /**
   * `tm_star_find_all`.
   */
  tmStarFindAll({ name }) {
    return this.#engine.call('tm_star_find_all', { name }).out.map(readTmStar);
  }

  /**
   * `tm_star_calc`.
   */
  tmStarCalc({ jd, scale, name, flags, observer }) {
    return readTmPosition(this.#engine.call('tm_star_calc', { jd, scale, name, flags, observer: observer == null ? null : writeTmObserver(observer) }).out);
  }

  /**
   * `tm_star_calc_many`.
   */
  tmStarCalcMany({ jd, scale, stars, flags, observer }) {
    return this.#engine.call('tm_star_calc_many', { jd, scale, stars: stars.map(writeTmStar), flags, observer: observer == null ? null : writeTmObserver(observer) }).out.map(readTmPosition);
  }

  /**
   * `tm_eclipse_type_name`.
   */
  tmEclipseTypeName({ bit }) {
    return this.#engine.call('tm_eclipse_type_name', { bit }).return;
  }

  /**
   * `tm_solar_eclipse_where`.
   */
  tmSolarEclipseWhere({ jd, scale, flags }) {
    const answered = this.#engine.call('tm_solar_eclipse_where', { jd, scale, flags });
    return { outLocation: readTmEclipseLocation(answered.out_location), outAttributes: readTmEclipseAttributes(answered.out_attributes), outType: answered.out_type };
  }

  /**
   * `tm_occultation_where`.
   */
  tmOccultationWhere({ jd, scale, body, star, flags }) {
    const answered = this.#engine.call('tm_occultation_where', { jd, scale, body, star, flags });
    return { outLocation: readTmEclipseLocation(answered.out_location), outAttributes: readTmEclipseAttributes(answered.out_attributes), outType: answered.out_type };
  }

  /**
   * `tm_solar_eclipse_how`.
   */
  tmSolarEclipseHow({ jd, scale, flags, observer }) {
    const answered = this.#engine.call('tm_solar_eclipse_how', { jd, scale, flags, observer: observer == null ? null : writeTmObserver(observer) });
    return { outAttributes: readTmEclipseAttributes(answered.out_attributes), outType: answered.out_type };
  }

  /**
   * `tm_occultation_how`.
   */
  tmOccultationHow({ jd, scale, body, star, flags, observer }) {
    const answered = this.#engine.call('tm_occultation_how', { jd, scale, body, star, flags, observer: observer == null ? null : writeTmObserver(observer) });
    return { outAttributes: readTmEclipseAttributes(answered.out_attributes), outType: answered.out_type };
  }

  /**
   * `tm_lunar_eclipse_how`.
   */
  tmLunarEclipseHow({ jd, scale, flags, observer }) {
    const answered = this.#engine.call('tm_lunar_eclipse_how', { jd, scale, flags, observer: observer == null ? null : writeTmObserver(observer) });
    return { outAttributes: readTmLunarEclipseAttributes(answered.out_attributes), outType: answered.out_type };
  }

  /**
   * `tm_event_kind_name`.
   */
  tmEventKindName({ kind }) {
    return this.#engine.call('tm_event_kind_name', { kind }).return;
  }

  /**
   * `tm_gauquelin_sector`.
   */
  tmGauquelinSector({ jd, scale, body, star, flags, method, refraction, discCenter, observer, atmosphere }) {
    return this.#engine.call('tm_gauquelin_sector', { jd, scale, body, star, flags, method, refraction, disc_center: discCenter, observer: observer == null ? null : writeTmObserver(observer), atmosphere: atmosphere == null ? null : writeTmAtmosphere(atmosphere) }).out_sector;
  }

  /**
   * `tm_visibility_defaults`.
   */
  tmVisibilityDefaults({ observer }) {
    const answered = this.#engine.call('tm_visibility_defaults', { observer: observer == null ? null : writeTmObserver(observer) });
    return { atmosphere: readTmVisibilityAtmosphere(answered.atmosphere), eye: readTmObserverEye(answered.eye) };
  }

  /**
   * `tm_visibility_limit`.
   */
  tmVisibilityLimit({ jd, scale, body, star, flags, observer, atmosphere, eye }) {
    return readTmVisibility(this.#engine.call('tm_visibility_limit', { jd, scale, body, star, flags, observer: observer == null ? null : writeTmObserver(observer), atmosphere: atmosphere == null ? null : writeTmVisibilityAtmosphere(atmosphere), eye: eye == null ? null : writeTmObserverEye(eye) }).out);
  }

  /**
   * `tm_visibility_arcus`.
   */
  tmVisibilityArcus({ jd, scale, flags, observer, atmosphere, eye, magnitude, objectAltitudeDeg, objectAzimuthDeg, sunAzimuthDeg, moonAltitudeDeg, moonAzimuthDeg }) {
    return this.#engine.call('tm_visibility_arcus', { jd, scale, flags, observer: observer == null ? null : writeTmObserver(observer), atmosphere: atmosphere == null ? null : writeTmVisibilityAtmosphere(atmosphere), eye: eye == null ? null : writeTmObserverEye(eye), magnitude, object_altitude_deg: objectAltitudeDeg, object_azimuth_deg: objectAzimuthDeg, sun_azimuth_deg: sunAzimuthDeg, moon_altitude_deg: moonAltitudeDeg, moon_azimuth_deg: moonAzimuthDeg }).out_arcus_deg;
  }

  /**
   * `tm_visibility_best_altitude`.
   */
  tmVisibilityBestAltitude({ jd, scale, flags, observer, atmosphere, eye, magnitude, objectAzimuthDeg, sunAzimuthDeg, moonAltitudeDeg, moonAzimuthDeg }) {
    return readTmVisibilityBest(this.#engine.call('tm_visibility_best_altitude', { jd, scale, flags, observer: observer == null ? null : writeTmObserver(observer), atmosphere: atmosphere == null ? null : writeTmVisibilityAtmosphere(atmosphere), eye: eye == null ? null : writeTmObserverEye(eye), magnitude, object_azimuth_deg: objectAzimuthDeg, sun_azimuth_deg: sunAzimuthDeg, moon_altitude_deg: moonAltitudeDeg, moon_azimuth_deg: moonAzimuthDeg }).out);
  }

  /**
   * `tm_crossing_request_init_sized`.
   */
  tmCrossingRequestInitSized() {
    return readTmCrossingRequest(this.#engine.call('tm_crossing_request_init_sized', {}).req);
  }

  /**
   * `tm_crossing_search`.
   */
  tmCrossingSearch({ req, outCapacity }) {
    return this.#engine.call('tm_crossing_search', { req: req == null ? null : writeTmCrossingRequest(req), out_capacity: outCapacity }).out.map(readTmCrossing);
  }

  /**
   * `tm_node_crossing_search`.
   */
  tmNodeCrossingSearch({ req, outCapacity }) {
    return this.#engine.call('tm_node_crossing_search', { req: req == null ? null : writeTmCrossingRequest(req), out_capacity: outCapacity }).out.map(readTmCrossing);
  }

  /**
   * `tm_angle_normalize_deg`.
   */
  tmAngleNormalizeDeg({ deg }) {
    return this.#engine.call('tm_angle_normalize_deg', { deg }).return;
  }

  /**
   * `tm_angle_normalize_rad`.
   */
  tmAngleNormalizeRad({ rad }) {
    return this.#engine.call('tm_angle_normalize_rad', { rad }).return;
  }

  /**
   * `tm_angle_diff_deg`.
   */
  tmAngleDiffDeg({ a, b }) {
    return this.#engine.call('tm_angle_diff_deg', { a, b }).return;
  }

  /**
   * `tm_angle_diff_deg_positive`.
   */
  tmAngleDiffDegPositive({ a, b }) {
    return this.#engine.call('tm_angle_diff_deg_positive', { a, b }).return;
  }

  /**
   * `tm_angle_diff_rad`.
   */
  tmAngleDiffRad({ a, b }) {
    return this.#engine.call('tm_angle_diff_rad', { a, b }).return;
  }

  /**
   * `tm_angle_midpoint_deg`.
   */
  tmAngleMidpointDeg({ a, b }) {
    return this.#engine.call('tm_angle_midpoint_deg', { a, b }).return;
  }

  /**
   * `tm_angle_midpoint_rad`.
   */
  tmAngleMidpointRad({ a, b }) {
    return this.#engine.call('tm_angle_midpoint_rad', { a, b }).return;
  }

  /**
   * `tm_degrees_to_centiseconds`.
   */
  tmDegreesToCentiseconds({ deg }) {
    return this.#engine.call('tm_degrees_to_centiseconds', { deg }).return;
  }

  /**
   * `tm_centiseconds_to_degrees`.
   */
  tmCentisecondsToDegrees({ centiseconds }) {
    return this.#engine.call('tm_centiseconds_to_degrees', { centiseconds }).return;
  }

  /**
   * `tm_centiseconds_normalize`.
   */
  tmCentisecondsNormalize({ cs }) {
    return this.#engine.call('tm_centiseconds_normalize', { cs }).return;
  }

  /**
   * `tm_centiseconds_diff`.
   */
  tmCentisecondsDiff({ a, b }) {
    return this.#engine.call('tm_centiseconds_diff', { a, b }).return;
  }

  /**
   * `tm_centiseconds_diff_signed`.
   */
  tmCentisecondsDiffSigned({ a, b }) {
    return this.#engine.call('tm_centiseconds_diff_signed', { a, b }).return;
  }

  /**
   * `tm_centiseconds_round_seconds`.
   */
  tmCentisecondsRoundSeconds({ cs }) {
    return this.#engine.call('tm_centiseconds_round_seconds', { cs }).return;
  }

  /**
   * `tm_round_half_away`.
   */
  tmRoundHalfAway({ x }) {
    return this.#engine.call('tm_round_half_away', { x }).return;
  }

  /**
   * `tm_angle_split`.
   */
  tmAngleSplit({ deg, options }) {
    return readTmAngleParts(this.#engine.call('tm_angle_split', { deg, options }).out);
  }

  /**
   * `tm_angle_format`.
   */
  tmAngleFormat({ deg, style, decimals }) {
    return this.#engine.call('tm_angle_format', { deg, style, decimals }).buf;
  }

  /**
   * `tm_zodiac_sign_name`.
   */
  tmZodiacSignName({ sign }) {
    return this.#engine.call('tm_zodiac_sign_name', { sign }).return;
  }

  /**
   * `tm_nakshatra_name`.
   */
  tmNakshatraName({ nakshatra }) {
    return this.#engine.call('tm_nakshatra_name', { nakshatra }).return;
  }

  /**
   * `tm_nakshatra_lord`.
   */
  tmNakshatraLord({ nakshatra }) {
    return this.#engine.call('tm_nakshatra_lord', { nakshatra }).return;
  }

  /**
   * `tm_chart_blob_size`.
   */
  tmChartBlobSize({ bodyCount, cuspCount, withCuspSpeeds, withAngles }) {
    return this.#engine.call('tm_chart_blob_size', { body_count: bodyCount, cusp_count: cuspCount, with_cusp_speeds: withCuspSpeeds, with_angles: withAngles }).return;
  }

}

/**
 * The engine's own operations, typed.
 *
 * Pass `sdk.engine`; what comes back has a method per operation this
 * adapter offers, each calling the engine by its own name.
 */
export const teimeris = (engine) => new TeimerisEngine(engine);
