// The engine's own operations, typed. **Generated by
// `cargo xtask engine`. Do not edit.**
//
// From the engine's own description at version `0.1.0`.
// Which of its functions are here is a measurement, not a choice:
// `docs/03-design/engine-passthrough-measured.md` classifies all of
// them into what is callable, what this adapter will never hand over,
// and what is queued behind one more shape.
//
// A method's arguments are named the way this language names things;
// the keys that cross are the engine's own, which is what
// `sdk.engine.signature(name)` reads. A call through here is to a
// named engine and does not survive changing it — which is why it is
// taken as a value rather than laid over `sdk.engine` (ADR-0030).

import type { Engine } from '@teistro/sdk';

/** The engine's own operations, typed. */
export declare class TeimerisEngine {
  /**
   * `tm_status_name`.
   */
  tmStatusName(args: { readonly s: number }): string;
  /**
   * `tm_context_release_caches`.
   */
  tmContextReleaseCaches(): void;
  /**
   * `tm_version_string`.
   */
  tmVersionString(): string;
  /**
   * `tm_version`.
   */
  tmVersion(): { readonly major: number; readonly minor: number; readonly patch: number };
  /**
   * `tm_body_name`.
   */
  tmBodyName(args: { readonly body: number }): string;
  /**
   * `tm_delta_t`.
   */
  tmDeltaT(args: { readonly jdUt1: number }): number;
  /**
   * `tm_sidereal_time`.
   */
  tmSiderealTime(args: { readonly jdUt1: number; readonly geoLonDeg: number }): number;
  /**
   * `tm_day_of_week`.
   */
  tmDayOfWeek(args: { readonly jd: number }): number;
  /**
   * `tm_weekday_name`.
   */
  tmWeekdayName(args: { readonly day: number }): string;
  /**
   * `tm_equation_of_time`.
   */
  tmEquationOfTime(args: { readonly jdUt1: number }): number;
  /**
   * `tm_local_mean_to_apparent`.
   */
  tmLocalMeanToApparent(args: { readonly jdLocalMean: number; readonly geoLonDeg: number }): number;
  /**
   * `tm_local_apparent_to_mean`.
   */
  tmLocalApparentToMean(args: { readonly jdLocalApparent: number; readonly geoLonDeg: number }): number;
  /**
   * `tm_position_value`.
   */
  tmPositionValue(args: { readonly jd: number; readonly scale: number; readonly body: number; readonly flags: number; readonly field: number }): number;
  /**
   * `tm_house_cusp_count`.
   */
  tmHouseCuspCount(args: { readonly sys: number }): number;
  /**
   * `tm_house_system_name`.
   */
  tmHouseSystemName(args: { readonly sys: number }): string;
  /**
   * `tm_house_system_count`.
   */
  tmHouseSystemCount(): number;
  /**
   * `tm_house_position`.
   */
  tmHousePosition(args: { readonly armc: number; readonly geoLatDeg: number; readonly obliquityDeg: number; readonly sys: number; readonly lonDeg: number; readonly latDeg: number }): number;
  /**
   * `tm_set_jpl_file`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetJplFile(args: { readonly filename: string }): void;
  /**
   * `tm_jpl_info`.
   */
  tmJplInfo(): { readonly outDenum: number; readonly outJdStart: number; readonly outJdEnd: number; readonly outSegmentDays: number };
  /**
   * `tm_set_ayanamsha`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetAyanamsha(args: { readonly mode: number; readonly t0: number; readonly ayanT0: number }): void;
  /**
   * `tm_ayanamsha_value`.
   */
  tmAyanamshaValue(args: { readonly jd: number; readonly scale: number; readonly flags: number }): number;
  /**
   * `tm_ayanamsha_name`.
   */
  tmAyanamshaName(args: { readonly mode: number }): string;
  /**
   * `tm_ayanamsha_count`.
   */
  tmAyanamshaCount(): number;
  /**
   * `tm_set_model`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetModel(args: { readonly kind: number; readonly model: number }): void;
  /**
   * `tm_get_model`.
   */
  tmGetModel(args: { readonly kind: number }): number;
  /**
   * `tm_model_name`.
   */
  tmModelName(args: { readonly kind: number; readonly model: number }): string;
  /**
   * `tm_model_kind_name`.
   */
  tmModelKindName(args: { readonly kind: number }): string;
  /**
   * `tm_model_count`.
   */
  tmModelCount(args: { readonly kind: number }): number;
  /**
   * `tm_set_tidal_acceleration`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetTidalAcceleration(args: { readonly arcsecPerCentury2: number }): void;
  /**
   * `tm_clear_tidal_acceleration`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmClearTidalAcceleration(): void;
  /**
   * `tm_get_tidal_acceleration`.
   */
  tmGetTidalAcceleration(): { readonly outValue: number; readonly outIsSet: number };
  /**
   * `tm_set_delta_t_override`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetDeltaTOverride(args: { readonly seconds: number }): void;
  /**
   * `tm_clear_delta_t_override`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmClearDeltaTOverride(): void;
  /**
   * `tm_get_delta_t_override`.
   */
  tmGetDeltaTOverride(): { readonly outSeconds: number; readonly outIsSet: number };
  /**
   * `tm_set_nutation_interpolation`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmSetNutationInterpolation(args: { readonly enable: number }): void;
  /**
   * `tm_get_nutation_interpolation`.
   */
  tmGetNutationInterpolation(): number;
  /**
   * `tm_embedded_coverage`.
   */
  tmEmbeddedCoverage(): { readonly outJdStart: number; readonly outJdEnd: number };
  /**
   * `tm_fallback_stats_reset`.
   */
  tmFallbackStatsReset(): void;
  /**
   * `tm_cache_dir_default`.
   */
  tmCacheDirDefault(): string;
  /**
   * `tm_star_load_catalogue`.
   *
   * Changes engine state the SDK's provenance does not record: a chart cast afterwards says it was computed one way and was computed another.
   */
  tmStarLoadCatalogue(args: { readonly path: string }): void;
  /**
   * `tm_star_count`.
   */
  tmStarCount(): number;
  /**
   * `tm_eclipse_type_name`.
   */
  tmEclipseTypeName(args: { readonly bit: number }): string;
  /**
   * `tm_event_kind_name`.
   */
  tmEventKindName(args: { readonly kind: number }): string;
  /**
   * `tm_angle_normalize_deg`.
   */
  tmAngleNormalizeDeg(args: { readonly deg: number }): number;
  /**
   * `tm_angle_normalize_rad`.
   */
  tmAngleNormalizeRad(args: { readonly rad: number }): number;
  /**
   * `tm_angle_diff_deg`.
   */
  tmAngleDiffDeg(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_angle_diff_deg_positive`.
   */
  tmAngleDiffDegPositive(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_angle_diff_rad`.
   */
  tmAngleDiffRad(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_angle_midpoint_deg`.
   */
  tmAngleMidpointDeg(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_angle_midpoint_rad`.
   */
  tmAngleMidpointRad(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_degrees_to_centiseconds`.
   */
  tmDegreesToCentiseconds(args: { readonly deg: number }): number;
  /**
   * `tm_centiseconds_to_degrees`.
   */
  tmCentisecondsToDegrees(args: { readonly centiseconds: number }): number;
  /**
   * `tm_centiseconds_normalize`.
   */
  tmCentisecondsNormalize(args: { readonly cs: number }): number;
  /**
   * `tm_centiseconds_diff`.
   */
  tmCentisecondsDiff(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_centiseconds_diff_signed`.
   */
  tmCentisecondsDiffSigned(args: { readonly a: number; readonly b: number }): number;
  /**
   * `tm_centiseconds_round_seconds`.
   */
  tmCentisecondsRoundSeconds(args: { readonly cs: number }): number;
  /**
   * `tm_round_half_away`.
   */
  tmRoundHalfAway(args: { readonly x: number }): number;
  /**
   * `tm_angle_format`.
   */
  tmAngleFormat(args: { readonly deg: number; readonly style: number; readonly decimals: number }): string;
  /**
   * `tm_zodiac_sign_name`.
   */
  tmZodiacSignName(args: { readonly sign: number }): string;
  /**
   * `tm_nakshatra_name`.
   */
  tmNakshatraName(args: { readonly nakshatra: number }): string;
  /**
   * `tm_nakshatra_lord`.
   */
  tmNakshatraLord(args: { readonly nakshatra: number }): string;
  /**
   * `tm_chart_blob_size`.
   */
  tmChartBlobSize(args: { readonly bodyCount: number; readonly cuspCount: number; readonly withCuspSpeeds: number; readonly withAngles: number }): number;
}

/** The engine's own operations, typed. Pass `sdk.engine`. */
export declare function teimeris(engine: Engine): TeimerisEngine;
