// The Teimeris adapter's types. HAND-WRITTEN; `engine.d.ts` beside it is
// generated by `cargo xtask engine`.

import type { EphemerisChoice } from '@teistro/sdk';

export { teimeris as engine, TeimerisEngine } from './engine.js';

/**
 * The npm package that carries this host's prebuilt adapter, as
 * `@teistro/ephemeris-teimeris-<platform>-<arch>`.
 */
export declare function platformPackage(): string;

/**
 * The adapter's platform binary: the one a path names, then the one npm
 * installed for this host, then this repository's own build. Throws
 * naming every place it looked when there is none.
 */
export declare function binary(named?: string): string;

/** What `teimeris(...)` takes. */
export interface TeimerisOptions {
  /**
   * Where the engine's data files are. It looks beside its own build
   * when this is omitted.
   */
  readonly dataDir?: string;
  /** The engine's own accuracy profile. */
  readonly profile?: string;
  /**
   * The platform binary, when a caller would rather name it than let
   * this package find it.
   */
  readonly binary?: string;
}

/**
 * The descriptor an `ephemeris` chain takes (ADR-0029).
 *
 * ```ts
 * import teimeris from '@teistro/ephemeris-teimeris';
 *
 * const sdk = new Context({ ephemeris: [teimeris({ dataDir: './ephe' })] });
 * ```
 *
 * It fails **here**, in the line that names the engine, when the adapter
 * is not installed — rather than when a chart is cast.
 */
export default function teimeris(options?: TeimerisOptions): EphemerisChoice;
