//! The adapter's marshalling, generated: the manifest, one arm per
//! callable function, and a reader and writer per struct it passes.

use std::fmt::Write as _;

use super::classify::{
    Standing, declared_return, describe, fills_a_string, has_role, returns_a_string,
};
use super::idl::{Function, Idl, Param, STRUCT_SIZE, Shape, Vocabulary};

/// The Rust spelling of an IDL type, as the `sys` crate names it.
///
/// The engine's enums are `c_int` aliases in `sys`, so a name that is not
/// a scalar is an alias and passes through unchanged: the cast does the
/// work and nothing here has to carry a table of forty enums.
pub(crate) fn rust_type(base: &str) -> String {
    match base {
        "double" => "f64".to_string(),
        "float" => "f32".to_string(),
        "int32_t" => "i32".to_string(),
        "uint32_t" => "u32".to_string(),
        "int64_t" => "i64".to_string(),
        "uint64_t" => "u64".to_string(),
        "size_t" => "usize".to_string(),
        "int" => "::core::ffi::c_int".to_string(),
        "bool" => "bool".to_string(),
        other => format!("sys::{other}"),
    }
}

/// The marshalling: one arm per callable function, generated.
pub(crate) fn dispatch(
    idl: &Idl,
    classified: &[(&Function, Standing, &'static str)],
    vocabulary: &Vocabulary,
) -> String {
    let callable: Vec<&Function> = classified
        .iter()
        .filter(|(_, standing, _)| *standing == Standing::Callable)
        .map(|(function, _, _)| *function)
        .collect();

    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! The engine's own functions, reachable by name. **Generated by\n\
         //! `cargo xtask engine`. Do not edit.**\n\
         //!\n\
         //! One arm per function the marshaller can carry, from the engine's\n\
         //! own description at version `{}`. What is here and what is not is\n\
         //! measured in `docs/03-design/engine-passthrough-measured.md`: the\n\
         //! functions this adapter will never offer are excluded by what they\n\
         //! touch, and the rest are a queue for the generator.\n\
         //!\n\
         //! This is the adapter's only `unsafe`. Everything else goes through\n\
         //! the safe binding; these are the calls that binding does not wrap,\n\
         //! which is the whole reason a consumer would reach for them.\n\
         \n\
         #![allow(\n    \
         unsafe_code,\n    \
         clippy::too_many_lines,\n    \
         reason = \"generated: one arm per engine function\"\n\
         )]\n\
         \n\
         use serde_json::{{Map, Value, json}};\n\
         use teimeris::sys;\n\
         use teistro_port_ephemeris::ProviderError;\n\
         \n\
         {PASSTHROUGH_IMPORTS}\n",
        idl.version
    );

    // The manifest: what a caller may ask for, and the role of each
    // parameter, which is what `sdk.engine.signature(name)` reads.
    let mut functions_json = Vec::new();
    for function in &callable {
        let described = describe(function);
        // The manifest keeps `role` as `in`/`out` because that is what a
        // consumer reading `sdk.engine.signature(name)` needs, and the
        // description above is already grouped that way.
        let params: Vec<String> = described
            .takes
            .iter()
            .map(|(name, declared)| {
                // `optional` only where it is true, so the manifest of a
                // function with none reads as it always has.
                let optional = if described.nullable(name) {
                    ",\"optional\":true"
                } else {
                    ""
                };
                format!("{{\"name\":\"{name}\",\"role\":\"in\",\"type\":\"{declared}\"{optional}}}")
            })
            .chain(
                described
                    .gives
                    .iter()
                    .filter(|(name, _)| *name != "return")
                    .map(|(name, declared)| {
                        format!("{{\"name\":\"{name}\",\"role\":\"out\",\"type\":\"{declared}\"}}")
                    }),
            )
            .collect();
        functions_json.push(format!(
            "{{\"name\":\"{}\",\"params\":[{}],\"returns\":\"{}\",\"mutatesEngineState\":{}}}",
            described.name,
            params.join(","),
            declared_return(function),
            described.mutates
        ));
    }
    let _ = writeln!(
        out,
        "/// What this adapter offers of the engine's own surface, as the\n\
         /// port's `native_manifest` answers it.\n\
         ///\n\
         /// `mutatesEngineState` is the flag a consumer needs and no other\n\
         /// manifest would carry: after such a call the engine answers under\n\
         /// settings the SDK's provenance does not record.\n\
         pub(crate) const MANIFEST: &str = r#\"{{\"engine\":\"teimeris\",\"version\":\"{}\",\"functions\":[{}]}}\"#;\n",
        idl.version,
        functions_json.join(",")
    );

    let _ = writeln!(
        out,
        "/// Calls one of them by name.\n\
         ///\n\
         /// # Errors\n\
         ///\n\
         /// `Unsupported` for a name this adapter does not offer, `Invalid`\n\
         /// for an argument missing or of the wrong kind, and the engine's\n\
         /// own refusal otherwise.\n\
         pub(crate) fn call(\n    \
         context: *mut sys::tm_context,\n    \
         function: &str,\n    \
         args: &Map<String, Value>,\n\
         ) -> Result<Value, ProviderError> {{\n    \
         match function {{"
    );
    for function in &callable {
        out.push_str(&arm(function, vocabulary));
    }
    let _ = writeln!(
        out,
        "        other => Err(ProviderError::unsupported(format!(\n            \
         \"the engine offers no `{{other}}` through this adapter; \\\n             \
         `native_manifest` lists what it does\"\n        ))),\n    \
         }}\n\
         }}"
    );
    out.push_str(&marshalling(&callable, vocabulary));
    out.replace(PASSTHROUGH_IMPORTS, &passthrough_imports(&out))
}

/// Where the `use` of the passthrough's helpers goes, filled in once the
/// file is written.
pub(crate) const PASSTHROUGH_IMPORTS: &str = "// the passthrough's helpers";

/// The helpers the generated file actually calls, and only those.
///
/// Read off the file rather than kept in step with the arms by hand: a
/// helper an engine version never needs — `object`, when every struct it
/// takes is optional — would otherwise be an unused import in the one
/// file nobody edits.
pub(crate) fn passthrough_imports(generated: &str) -> String {
    /// Every helper, with the text a use of it contains.
    const HELPERS: [(&str, &str); 9] = [
        ("Within", "Within<"),
        ("borrowed", "borrowed(answered"),
        ("fill", "fill(\""),
        ("narrow", "narrow(args"),
        ("number", "number(args"),
        ("object", " object(args"),
        ("optional_object", "optional_object(args"),
        ("status", "status(answered"),
        ("text", "text(args"),
    ];
    let used: Vec<&str> = HELPERS
        .iter()
        .filter(|(_, marker)| generated.contains(marker))
        .map(|(name, _)| *name)
        .collect();
    format!("use crate::passthrough::{{{}}};", used.join(", "))
}

/// The structs one role reaches, with every struct they nest, in the
/// order the engine declares them.
///
/// Emitted for exactly these and no others, so a reader is generated
/// only where something reads one: a struct nothing callable mentions
/// would be dead code in the adapter and a name in four façades.
///
/// # Panics
///
/// When a struct nests one the engine declares after it. The façades
/// that need declaration order rely on the engine's header order, and
/// this is where that assumption is checked rather than believed.
pub(crate) fn reached<'v>(
    callable: &[&Function],
    roles: &[&str],
    vocabulary: &'v Vocabulary,
) -> Vec<&'v Shape> {
    let mut names: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    let mut pending: Vec<&str> = callable
        .iter()
        .flat_map(|function| function.params.iter())
        .filter(|param| roles.contains(&param.role.as_str()))
        .map(|param| param.type_ref.base.as_str())
        .collect();
    while let Some(name) = pending.pop() {
        let Some(shape) = vocabulary.shape(name) else {
            continue;
        };
        if names.insert(&shape.name) {
            pending.extend(
                shape
                    .fields
                    .iter()
                    .filter(|field| field.pointer == 0)
                    .map(|field| field.base.as_str()),
            );
        }
    }
    let ordered: Vec<&Shape> = vocabulary
        .declared()
        .filter(|shape| names.contains(shape.name.as_str()))
        .collect();
    for (at, shape) in ordered.iter().enumerate() {
        for field in shape.fields.iter().filter(|field| field.pointer == 0) {
            if let Some(nested) = ordered.iter().position(|one| one.name == field.base) {
                assert!(
                    nested < at,
                    "`{}` nests `{}`, which the engine declares after it",
                    shape.name,
                    field.base
                );
            }
        }
    }
    ordered
}

/// A reader and a writer for every struct a callable function passes.
pub(crate) fn marshalling(callable: &[&Function], vocabulary: &Vocabulary) -> String {
    let mut out = String::new();
    for shape in reached(callable, &["struct_in"], vocabulary) {
        out.push_str(&reader(shape, vocabulary));
    }
    for shape in reached(callable, &["struct_out"], vocabulary) {
        out.push_str(&writer(shape, vocabulary));
    }
    out
}

/// One struct read out of the object a caller passed, every field
/// required.
pub(crate) fn reader(shape: &Shape, vocabulary: &Vocabulary) -> String {
    let name = &shape.name;
    let mut fields = Vec::new();
    if shape.sized() {
        fields.push(format!(
            "        {STRUCT_SIZE}: core::mem::size_of::<sys::{name}>(),"
        ));
    }
    for field in shape.crossing() {
        let key = &field.name;
        let read = if vocabulary.shape(&field.base).is_some() {
            format!("read_{}(&within.nested(\"{key}\")?)?", field.base)
        } else if vocabulary.is_float(&field.base) {
            let ty = rust_type(&field.base);
            if ty == "f64" {
                format!("within.number(\"{key}\")?")
            } else {
                format!("within.number(\"{key}\")? as {ty}")
            }
        } else {
            format!("within.narrow(\"{key}\")?")
        };
        fields.push(format!("        {key}: {read},"));
    }
    format!(
        "\n/// A `{name}` read out of the object a caller passed.\n\
         fn read_{name}(within: &Within<'_>) -> Result<sys::{name}, ProviderError> {{\n    \
         Ok(sys::{name} {{\n{}\n    }})\n}}\n",
        fields.join("\n")
    )
}

/// One struct written into the object a caller gets back.
pub(crate) fn writer(shape: &Shape, vocabulary: &Vocabulary) -> String {
    let name = &shape.name;
    let fields: Vec<String> = shape
        .crossing()
        .map(|field| {
            let key = &field.name;
            if vocabulary.shape(&field.base).is_some() {
                format!("        \"{key}\": write_{}(&value.{key}),", field.base)
            } else {
                format!("        \"{key}\": value.{key},")
            }
        })
        .collect();
    format!(
        "\n/// A `{name}` as the object a caller gets back.\n\
         fn write_{name}(value: &sys::{name}) -> Value {{\n    \
         json!({{\n{}\n    }})\n}}\n",
        fields.join("\n")
    )
}

/// One function's arm: read the arguments, call, answer.
pub(crate) fn arm(function: &Function, vocabulary: &Vocabulary) -> String {
    let mut out = String::new();
    let name = &function.name;
    let _ = writeln!(out, "        \"{name}\" => {{");

    let mut call_args: Vec<String> = Vec::new();
    // Each out-parameter as the answer's `"key": expression`.
    let mut outs: Vec<String> = Vec::new();
    let structs: Vec<&Param> = function
        .params
        .iter()
        .filter(|p| matches!(p.role.as_str(), "struct_in" | "struct_out"))
        .collect();
    // The buffer of a fill, if there is one: its name is what the string
    // comes back under, and the call is made inside a closure so the
    // protocol can run it twice.
    let mut buffer: Option<&str> = None;
    for param in &function.params {
        match param.role.as_str() {
            "handle" => call_args.push("context".to_string()),
            "string_in" => {
                // Bound, not inlined: the `CString` must outlive the call
                // and a temporary would be dropped at the semicolon.
                let _ = writeln!(
                    out,
                    "            let {} = text(args, \"{}\")?;",
                    param.name, param.name
                );
                call_args.push(format!("{}.as_ptr()", param.name));
            }
            "string_out" => {
                buffer = Some(param.name.as_str());
                call_args.push("buffer".to_string());
            }
            "string_cap" => call_args.push("capacity".to_string()),
            "value" => {
                let ty = rust_type(&param.type_ref.base);
                // A float is read as one; anything else is **narrowed** to
                // the width the engine declares, and refused when it does
                // not fit rather than silently keeping the low bits.
                let _ = if vocabulary.is_float(&param.type_ref.base) {
                    // `number` answers `f64` already; only a `float`
                    // parameter needs narrowing, and that one is lossy by
                    // the engine's own declaration rather than by ours.
                    let cast = if ty == "f64" {
                        String::new()
                    } else {
                        format!(" as {ty}")
                    };
                    writeln!(
                        out,
                        "            let {}: {ty} = number(args, \"{}\")?{cast};",
                        param.name, param.name
                    )
                } else {
                    writeln!(
                        out,
                        "            let {}: {ty} = narrow(args, \"{}\")?;",
                        param.name, param.name
                    )
                };
                call_args.push(param.name.clone());
            }
            "scalar_out" => {
                let ty = rust_type(&param.type_ref.base);
                let zero = if vocabulary.is_float(&param.type_ref.base) {
                    "0.0"
                } else {
                    "0"
                };
                let _ = writeln!(out, "            let mut {}: {ty} = {zero};", param.name);
                call_args.push(format!("&raw mut {}", param.name));
                outs.push(format!("\"{0}\": {0}", param.name));
            }
            "struct_in" | "struct_out" | "out_struct_size" => {
                struct_param(param, &structs, &mut out, &mut call_args, &mut outs);
            }
            other => unreachable!("a callable function has no `{other}` parameter"),
        }
    }

    let call = format!("sys::{name}({})", call_args.join(", "));
    let safety = safety(function);
    if let Some(buffer) = buffer {
        // The fill protocol owns the buffer and the count, and runs the
        // call again only if the first answer did not fit.
        let indented = safety.replace('\n', "\n                ");
        let _ = writeln!(
            out,
            "            let {buffer} = fill(\"{name}\", |buffer, capacity| {{\n                \
             {indented}\n                unsafe {{ {call} }}\n            }})?;"
        );
    } else {
        let binding = if function.returns.base == "void" {
            String::new()
        } else {
            "let answered = ".to_string()
        };
        let indented = safety.replace('\n', "\n            ");
        let _ = writeln!(
            out,
            "            {indented}\n            {binding}unsafe {{ {call} }};"
        );
        if function.returns.base == "tm_status" {
            let _ = writeln!(out, "            status(answered, \"{name}\")?;");
        }
    }
    let fields = answer(function, outs, buffer);
    let _ = writeln!(out, "            Ok(json!({{{}}}))", fields.join(", "));
    let _ = writeln!(out, "        }}");
    out
}

/// What an arm answers with, as `"key": expression` pairs: its
/// out-parameters, then a filled string or the function's own return.
pub(crate) fn answer(function: &Function, outs: Vec<String>, buffer: Option<&str>) -> Vec<String> {
    // No cast on a number: `serde_json` serialises every primitive
    // numeric, and the widths here are the engine's own. A cast would be
    // a claim about which of them was declared.
    let mut fields = outs;
    // A filled string comes back under its parameter's own name, like
    // every other out-parameter. The length the function answered is the
    // protocol's and is not reported: the string it describes is already
    // here in full.
    if let Some(buffer) = buffer {
        fields.push(format!("\"{buffer}\": {buffer}"));
    } else if returns_a_string(function) {
        // `None` for null, which is how the engine says there is no such
        // name, and which JSON has a word for.
        fields.push("\"return\": borrowed(answered)".to_string());
    } else if !matches!(function.returns.base.as_str(), "tm_status" | "void") {
        fields.push("\"return\": answered".to_string());
    }
    fields
}

/// One struct parameter's part of an arm: the local it binds, what the
/// call is passed, and what the answer reports.
pub(crate) fn struct_param(
    param: &Param,
    structs: &[&Param],
    out: &mut String,
    call_args: &mut Vec<String>,
    outs: &mut Vec<String>,
) {
    let name = &param.name;
    let base = &param.type_ref.base;
    match param.role.as_str() {
        "struct_in" if param.nullable() => {
            // Left out or null crosses as a null pointer, and the engine
            // decides whether that is allowed: an observer is optional
            // unless the flags ask for a topocentric answer, and a
            // datetime never is. Both are the engine's refusal to make.
            let _ = writeln!(
                out,
                "            let {name} = optional_object(args, \"{name}\")?\n                \
                 .map(|within| read_{base}(&within))\n                .transpose()?;"
            );
            call_args.push(format!(
                "{name}.as_ref().map_or(core::ptr::null(), core::ptr::from_ref)"
            ));
        }
        "struct_in" => {
            let _ = writeln!(
                out,
                "            let {name} = read_{base}(&object(args, \"{name}\")?)?;"
            );
            call_args.push(format!("&raw const {name}"));
        }
        "struct_out" => {
            // `default()` and not zeroed: it is the binding's own way of
            // filling the extent the engine reads before it writes.
            let _ = writeln!(
                out,
                "            let mut {name}: sys::{base} = sys::{base}::default();"
            );
            call_args.push(format!("&raw mut {name}"));
            outs.push(format!("\"{name}\": write_{base}(&{name})"));
        }
        // The one struct an extent measures. Asserted rather than
        // guessed: a function with two structs and one extent would have
        // to say which, and none does.
        _ => {
            let [measured] = structs else {
                panic!(
                    "`{name}` passes a struct's extent beside {} structs; the generator knows \
                     which struct it measures only when there is one",
                    structs.len()
                );
            };
            call_args.push(format!("core::mem::size_of_val(&{})", measured.name));
        }
    }
}

/// The SAFETY note for one arm, naming **what that arm actually
/// passes** and nothing else.
///
/// A generated note that lists an out-parameter the call does not have,
/// or a context it is not given, is worse than none: the whole reason
/// this file is allowed its `unsafe` is that the note beside each call
/// can be checked against the call.
pub(crate) fn safety(function: &Function) -> String {
    let mut clauses: Vec<&str> = Vec::new();
    if has_role(function, "handle") {
        clauses.push("the context is the adapter's own and live for this call");
    }
    if has_role(function, "scalar_out") {
        clauses.push("every out-parameter is a local of the width the engine declares");
    }
    if has_role(function, "string_in") {
        clauses.push("every string argument is a `CString` that outlives the call");
    }
    if has_role(function, "struct_in") {
        clauses.push("every struct argument is a local of the type the engine declares, its extent filled by the arm");
    }
    if has_role(function, "struct_out") {
        clauses.push("every struct out-parameter is a local of the type the engine declares, its extent filled by `default`");
    }
    if has_role(function, "out_struct_size") {
        clauses.push("the extent passed is the size of that local");
    }
    if fills_a_string(function) {
        clauses.push(
            "the buffer and its capacity are the fill protocol's own, and it passes the length \
             of what it allocated",
        );
    }
    if clauses.is_empty() {
        // Nothing is lent and nothing is written through: the arm passes
        // numbers the engine declared and that is the whole of it.
        clauses.push("the call takes nothing but values of the widths the engine declares");
    }
    wrapped(&format!("SAFETY: {}.", clauses.join("; ")))
}

/// A note as comment lines no wider than the project's own limit.
///
/// Unindented; the caller indents to the depth its arm sits at.
pub(crate) fn wrapped(note: &str) -> String {
    /// What is left for text once `            // ` is in front of it.
    const ROOM: usize = 60;

    let mut lines: Vec<String> = vec![String::new()];
    for word in note.split_whitespace() {
        let line = lines
            .last_mut()
            .unwrap_or_else(|| unreachable!("never empty"));
        if line.is_empty() {
            line.push_str(word);
        } else if line.len() + 1 + word.len() <= ROOM {
            line.push(' ');
            line.push_str(word);
        } else {
            lines.push(word.to_string());
        }
    }
    lines
        .iter()
        .map(|line| format!("// {line}"))
        .collect::<Vec<_>>()
        .join("\n")
}
