//! The adapter's marshalling, generated: the manifest, one arm per
//! callable function, and a reader and writer per struct it passes.

use std::fmt::Write as _;

use super::classify::{
    Counted, Crossing, Sizing, Standing, crossing, declared_return, describe, fills_a_string,
    has_role, returns_a_string, returns_the_count, sizing, totals,
};
use super::idl::{Function, Idl, Param, STRUCT_SIZE, Shape, Vocabulary};

/// The Rust spelling of an IDL type, as the `sys` crate names it.
///
/// The engine's enums are `c_int` aliases in `sys`, so a name that is not
/// a scalar is an alias and passes through unchanged: the cast does the
/// work and nothing here has to carry a table of forty enums.
pub(crate) fn rust_type(base: &str) -> String {
    match base {
        "double" => "f64".to_string(),
        "float" => "f32".to_string(),
        "int32_t" => "i32".to_string(),
        "uint32_t" => "u32".to_string(),
        "int64_t" => "i64".to_string(),
        "uint64_t" => "u64".to_string(),
        "size_t" => "usize".to_string(),
        "int" => "::core::ffi::c_int".to_string(),
        "bool" => "bool".to_string(),
        other => format!("sys::{other}"),
    }
}

/// The marshalling: one arm per callable function, generated.
pub(crate) fn dispatch(
    idl: &Idl,
    classified: &[(&Function, Standing, &'static str)],
    vocabulary: &Vocabulary,
) -> String {
    let callable: Vec<&Function> = classified
        .iter()
        .filter(|(_, standing, _)| *standing == Standing::Callable)
        .map(|(function, _, _)| *function)
        .collect();

    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! The engine's own functions, reachable by name. **Generated by\n\
         //! `cargo xtask engine`. Do not edit.**\n\
         //!\n\
         //! One arm per function the marshaller can carry, from the engine's\n\
         //! own description at version `{}`. What is here and what is not is\n\
         //! measured in `docs/03-design/engine-passthrough-measured.md`: the\n\
         //! functions this adapter will never offer are excluded by what they\n\
         //! touch, and the rest are a queue for the generator.\n\
         //!\n\
         //! This is the adapter's only `unsafe`. Everything else goes through\n\
         //! the safe binding; these are the calls that binding does not wrap,\n\
         //! which is the whole reason a consumer would reach for them.\n\
         \n\
         #![allow(\n    \
         unsafe_code,\n    \
         clippy::too_many_lines,\n    \
         reason = \"generated: one arm per engine function\"\n\
         )]\n\
         \n\
         use serde_json::{{Map, Value, json}};\n\
         use teimeris::sys;\n\
         use teistro_port_ephemeris::ProviderError;\n\
         \n\
         {PASSTHROUGH_IMPORTS}\n",
        idl.version
    );

    // The manifest: what a caller may ask for, and the role of each
    // parameter, which is what `sdk.engine.signature(name)` reads.
    let mut functions_json = Vec::new();
    for function in &callable {
        let described = describe(function);
        // The manifest keeps `role` as `in`/`out` because that is what a
        // consumer reading `sdk.engine.signature(name)` needs, and the
        // description above is already grouped that way.
        let params: Vec<String> = described
            .takes
            .iter()
            .map(|(name, declared)| {
                // `optional` only where it is true, so the manifest of a
                // function with none reads as it always has.
                let optional = if described.nullable(name) {
                    ",\"optional\":true"
                } else {
                    ""
                };
                format!("{{\"name\":\"{name}\",\"role\":\"in\",\"type\":\"{declared}\"{optional}}}")
            })
            .chain(
                described
                    .gives
                    .iter()
                    .filter(|(name, _)| *name != "return")
                    .map(|(name, declared)| {
                        format!("{{\"name\":\"{name}\",\"role\":\"out\",\"type\":\"{declared}\"}}")
                    }),
            )
            .collect();
        functions_json.push(format!(
            "{{\"name\":\"{}\",\"params\":[{}],\"returns\":\"{}\",\"mutatesEngineState\":{}}}",
            described.name,
            params.join(","),
            declared_return(function),
            described.mutates
        ));
    }
    let _ = writeln!(
        out,
        "/// What this adapter offers of the engine's own surface, as the\n\
         /// port's `native_manifest` answers it.\n\
         ///\n\
         /// `mutatesEngineState` is the flag a consumer needs and no other\n\
         /// manifest would carry: after such a call the engine answers under\n\
         /// settings the SDK's provenance does not record.\n\
         pub(crate) const MANIFEST: &str = r#\"{{\"engine\":\"teimeris\",\"version\":\"{}\",\"functions\":[{}]}}\"#;\n",
        idl.version,
        functions_json.join(",")
    );

    let _ = writeln!(
        out,
        "/// Calls one of them by name.\n\
         ///\n\
         /// # Errors\n\
         ///\n\
         /// `Unsupported` for a name this adapter does not offer, `Invalid`\n\
         /// for an argument missing or of the wrong kind, and the engine's\n\
         /// own refusal otherwise.\n\
         pub(crate) fn call(\n    \
         context: *mut sys::tm_context,\n    \
         function: &str,\n    \
         args: &Map<String, Value>,\n\
         ) -> Result<Value, ProviderError> {{\n    \
         match function {{"
    );
    for function in &callable {
        out.push_str(&arm(function, vocabulary));
    }
    let _ = writeln!(
        out,
        "        other => Err(ProviderError::unsupported(format!(\n            \
         \"the engine offers no `{{other}}` through this adapter; \\\n             \
         `native_manifest` lists what it does\"\n        ))),\n    \
         }}\n\
         }}"
    );
    out.push_str(&marshalling(&callable, vocabulary));
    out.replace(PASSTHROUGH_IMPORTS, &passthrough_imports(&out))
}

/// Where the `use` of the passthrough's helpers goes, filled in once the
/// file is written.
pub(crate) const PASSTHROUGH_IMPORTS: &str = "// the passthrough's helpers";

/// The helpers the generated file actually calls, and only those.
///
/// Read off the file rather than kept in step with the arms by hand: a
/// helper an engine version never needs — `object`, when every struct it
/// takes is optional — would otherwise be an unused import in the one
/// file nobody edits.
pub(crate) fn passthrough_imports(generated: &str) -> String {
    /// Every helper, with the text a use of it contains.
    const HELPERS: [(&str, &str); 15] = [
        ("Within", "Within<"),
        ("borrowed", "borrowed(answered"),
        ("extent", "extent(&["),
        ("fill", "fill(\""),
        ("gather", "gather::<"),
        ("narrow", "narrow(args"),
        ("number", "number(args"),
        ("numbers", "numbers(args"),
        ("object", " object(args"),
        ("objects", "objects(args"),
        ("optional_object", "optional_object(args"),
        ("room", "room("),
        ("status", "status(answered"),
        ("text", "text(args"),
        ("wholes", "wholes(args"),
    ];
    let used: Vec<&str> = HELPERS
        .iter()
        .filter(|(_, marker)| generated.contains(marker))
        .map(|(name, _)| *name)
        .collect();
    format!("use crate::passthrough::{{{}}};", used.join(", "))
}

/// The structs one role reaches, with every struct they nest, in the
/// order the engine declares them.
///
/// Emitted for exactly these and no others, so a reader is generated
/// only where something reads one: a struct nothing callable mentions
/// would be dead code in the adapter and a name in four façades.
///
/// # Panics
///
/// When a struct nests one the engine declares after it. The façades
/// that need declaration order rely on the engine's header order, and
/// this is where that assumption is checked rather than believed.
pub(crate) fn reached<'v>(
    callable: &[&Function],
    roles: &[&str],
    vocabulary: &'v Vocabulary,
) -> Vec<&'v Shape> {
    let mut names: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    let mut pending: Vec<&str> = callable
        .iter()
        .flat_map(|function| function.params.iter())
        .filter(|param| roles.contains(&param.role.as_str()))
        .map(|param| param.type_ref.base.as_str())
        .collect();
    while let Some(name) = pending.pop() {
        let Some(shape) = vocabulary.shape(name) else {
            continue;
        };
        if names.insert(&shape.name) {
            pending.extend(
                shape
                    .fields
                    .iter()
                    .filter(|field| field.pointer == 0)
                    .map(|field| field.base.as_str()),
            );
        }
    }
    let ordered: Vec<&Shape> = vocabulary
        .declared()
        .filter(|shape| names.contains(shape.name.as_str()))
        .collect();
    for (at, shape) in ordered.iter().enumerate() {
        for field in shape.fields.iter().filter(|field| field.pointer == 0) {
            if let Some(nested) = ordered.iter().position(|one| one.name == field.base) {
                assert!(
                    nested < at,
                    "`{}` nests `{}`, which the engine declares after it",
                    shape.name,
                    field.base
                );
            }
        }
    }
    ordered
}

/// A reader and a writer for every struct a callable function passes.
pub(crate) fn marshalling(callable: &[&Function], vocabulary: &Vocabulary) -> String {
    let mut out = String::new();
    for shape in reached(callable, &["struct_in", "array_in"], vocabulary) {
        out.push_str(&reader(shape, vocabulary));
    }
    for shape in reached(callable, &["struct_out", "array_out"], vocabulary) {
        out.push_str(&writer(shape, vocabulary));
    }
    out
}

/// One struct read out of the object a caller passed, every field
/// required.
pub(crate) fn reader(shape: &Shape, vocabulary: &Vocabulary) -> String {
    let name = &shape.name;
    let mut fields = Vec::new();
    if shape.sized() {
        fields.push(format!(
            "        {STRUCT_SIZE}: core::mem::size_of::<sys::{name}>(),"
        ));
    }
    for field in shape.crossing() {
        let key = &field.name;
        let read = if vocabulary.shape(&field.base).is_some() {
            format!("read_{}(&within.nested(\"{key}\")?)?", field.base)
        } else if vocabulary.is_float(&field.base) {
            let ty = rust_type(&field.base);
            if ty == "f64" {
                format!("within.number(\"{key}\")?")
            } else {
                format!("within.number(\"{key}\")? as {ty}")
            }
        } else {
            format!("within.narrow(\"{key}\")?")
        };
        fields.push(format!("        {key}: {read},"));
    }
    format!(
        "\n/// A `{name}` read out of the object a caller passed.\n\
         fn read_{name}(within: &Within<'_>) -> Result<sys::{name}, ProviderError> {{\n    \
         Ok(sys::{name} {{\n{}\n    }})\n}}\n",
        fields.join("\n")
    )
}

/// One struct written into the object a caller gets back.
pub(crate) fn writer(shape: &Shape, vocabulary: &Vocabulary) -> String {
    let name = &shape.name;
    let fields: Vec<String> = shape
        .crossing()
        .map(|field| {
            let key = &field.name;
            if vocabulary.shape(&field.base).is_some() {
                format!("        \"{key}\": write_{}(&value.{key}),", field.base)
            } else {
                format!("        \"{key}\": value.{key},")
            }
        })
        .collect();
    format!(
        "\n/// A `{name}` as the object a caller gets back.\n\
         fn write_{name}(value: &sys::{name}) -> Value {{\n    \
         json!({{\n{}\n    }})\n}}\n",
        fields.join("\n")
    )
}

/// One function's arm: read the arguments, call, answer.
pub(crate) fn arm(function: &Function, vocabulary: &Vocabulary) -> String {
    let mut arm = Arm::new(function, vocabulary);
    for param in &function.params {
        arm.param(param);
    }
    arm.finish()
}

/// How an arm makes its call.
enum Protocol<'a> {
    /// Once, straight through.
    Direct,
    /// Through the fill protocol, into a buffer it owns; the string
    /// comes back under the buffer parameter's name.
    Fill { buffer: &'a str },
    /// Through the gather protocol, into a room it owns, run again when
    /// the engine says there are more than fitted.
    Gather {
        output: &'a Param,
        count: Counted<'a>,
    },
}

impl<'a> Protocol<'a> {
    /// The protocol a function's parameters call for. The classifier
    /// has already refused a function that would need two.
    fn of(function: &'a Function) -> Self {
        if let Some(buffer) = function.params.iter().find(|p| p.role == "string_out") {
            return Self::Fill {
                buffer: &buffer.name,
            };
        }
        match totals(function).next() {
            Some((output, count)) => Self::Gather { output, count },
            None => Self::Direct,
        }
    }
}

/// One arm, as it is assembled: what is bound before the call, what the
/// call is passed, and what the answer holds.
struct Arm<'a> {
    function: &'a Function,
    vocabulary: &'a Vocabulary,
    protocol: Protocol<'a>,
    /// Lines before the call, in parameter order.
    before: String,
    /// Lines inside the protocol's closure, before the call.
    inside: Vec<String>,
    /// The call's arguments, in parameter order.
    call_args: Vec<String>,
    /// Lines after the call has succeeded.
    after: Vec<String>,
    /// The answer, as `"key": expression` pairs.
    answers: Vec<String>,
}

impl<'a> Arm<'a> {
    fn new(function: &'a Function, vocabulary: &'a Vocabulary) -> Self {
        Self {
            function,
            vocabulary,
            protocol: Protocol::of(function),
            before: String::new(),
            inside: Vec::new(),
            call_args: Vec::new(),
            after: Vec::new(),
            answers: Vec::new(),
        }
    }

    /// One line bound before the call.
    fn bind(&mut self, line: &str) {
        let _ = writeln!(self.before, "            {line}");
    }

    /// Whether this parameter is the output the gather protocol owns.
    fn gathered(&self, param: &Param) -> bool {
        matches!(self.protocol, Protocol::Gather { output, .. } if output.name == param.name)
    }

    fn param(&mut self, param: &'a Param) {
        let name = param.name.as_str();
        match param.role.as_str() {
            "handle" => self.call_args.push("context".to_string()),
            "string_in" => {
                // Bound, not inlined: the `CString` must outlive the call
                // and a temporary would be dropped at the semicolon.
                self.bind(&format!("let {name} = text(args, \"{name}\")?;"));
                self.call_args.push(format!("{name}.as_ptr()"));
            }
            "string_out" => self.call_args.push("buffer".to_string()),
            "string_cap" => self.call_args.push("capacity".to_string()),
            "value" => self.value(param),
            "scalar_out" => self.scalar_out(param),
            "struct_in" | "struct_out" | "out_struct_size" => self.structure(param),
            "array_in" => self.array_in(param),
            "array_len" => {
                let of = param.of.as_deref().unwrap_or_else(|| {
                    panic!(
                        "`{name}` on `{}` is a length of nothing",
                        self.function.name
                    )
                });
                self.call_args.push(format!("{of}.len()"));
            }
            "array_out" => self.array_out(param),
            "array_cap" => {
                let of = param.of.as_deref().unwrap_or_else(|| {
                    panic!(
                        "`{name}` on `{}` is a capacity of nothing",
                        self.function.name
                    )
                });
                self.call_args.push(if self.gathered_name(of) {
                    "room.len()".to_string()
                } else {
                    format!("{of}.len()")
                });
            }
            other => unreachable!("a callable function has no `{other}` parameter"),
        }
    }

    fn gathered_name(&self, name: &str) -> bool {
        matches!(self.protocol, Protocol::Gather { output, .. } if output.name == name)
    }

    /// A number the caller passes.
    fn value(&mut self, param: &Param) {
        let name = &param.name;
        let base = &param.type_ref.base;
        let ty = rust_type(base);
        // A float is read as one; anything else is **narrowed** to the
        // width the engine declares, and refused when it does not fit
        // rather than silently keeping the low bits.
        if self.vocabulary.is_float(base) {
            // `number` answers `f64` already; only a `float` parameter
            // needs narrowing, and that one is lossy by the engine's own
            // declaration rather than by ours.
            let cast = if ty == "f64" {
                String::new()
            } else {
                format!(" as {ty}")
            };
            self.bind(&format!(
                "let {name}: {ty} = number(args, \"{name}\")?{cast};"
            ));
        } else {
            self.bind(&format!("let {name}: {ty} = narrow(args, \"{name}\")?;"));
        }
        self.call_args.push(name.clone());
    }

    /// A number the engine writes: reported, unless it is the count of an
    /// output whose own length already says it.
    fn scalar_out(&mut self, param: &Param) {
        let name = &param.name;
        let base = &param.type_ref.base;
        let ty = rust_type(base);
        let zero = if self.vocabulary.is_float(base) {
            "0.0"
        } else {
            "0"
        };
        let line = format!("let mut {name}: {ty} = {zero};");
        let counted_by_gather = matches!(self.protocol, Protocol::Gather { count: Counted::Param(count), .. } if count == name);
        if counted_by_gather {
            self.inside.push(line);
        } else {
            self.bind(&line);
        }
        self.call_args.push(format!("&raw mut {name}"));
        if crossing(self.function, param) == Crossing::Gives {
            self.answers.push(format!("\"{name}\": {name}"));
        }
    }

    /// One struct parameter: the local it binds, what the call is passed,
    /// and what the answer reports.
    fn structure(&mut self, param: &Param) {
        let name = &param.name;
        let base = &param.type_ref.base;
        match param.role.as_str() {
            "struct_in" if param.nullable() => {
                // Left out or null crosses as a null pointer, and the
                // engine decides whether that is allowed: an observer is
                // optional unless the flags ask for a topocentric answer,
                // and a datetime never is. Both are the engine's refusal.
                self.bind(&format!(
                    "let {name} = optional_object(args, \"{name}\")?\n                \
                     .map(|within| read_{base}(&within))\n                .transpose()?;"
                ));
                self.call_args.push(format!(
                    "{name}.as_ref().map_or(core::ptr::null(), core::ptr::from_ref)"
                ));
            }
            "struct_in" => {
                self.bind(&format!(
                    "let {name} = read_{base}(&object(args, \"{name}\")?)?;"
                ));
                self.call_args.push(format!("&raw const {name}"));
            }
            "struct_out" => {
                // `default()` and not zeroed: it is the binding's own way
                // of filling the extent the engine reads before it writes.
                self.bind(&format!(
                    "let mut {name}: sys::{base} = sys::{base}::default();"
                ));
                self.call_args.push(format!("&raw mut {name}"));
                self.answers
                    .push(format!("\"{name}\": write_{base}(&{name})"));
            }
            // The one struct an extent measures. Asserted rather than
            // guessed: a function with two structs and one extent would
            // have to say which, and none does.
            _ => {
                let structs: Vec<&Param> = self
                    .function
                    .params
                    .iter()
                    .filter(|p| matches!(p.role.as_str(), "struct_in" | "struct_out"))
                    .collect();
                let [measured] = structs.as_slice() else {
                    panic!(
                        "`{name}` passes a struct's extent beside {} structs; the generator \
                         knows which struct it measures only when there is one",
                        structs.len()
                    );
                };
                self.call_args
                    .push(format!("core::mem::size_of_val(&{})", measured.name));
            }
        }
    }

    /// The Rust type of one element of an array.
    fn element(&self, param: &Param) -> String {
        let base = &param.type_ref.base;
        if self.vocabulary.shape(base).is_some() {
            format!("sys::{base}")
        } else {
            rust_type(base)
        }
    }

    /// An array the caller passes, read element by element and refused
    /// by the element's own path.
    fn array_in(&mut self, param: &Param) {
        let name = &param.name;
        let base = &param.type_ref.base;
        let ty = self.element(param);
        let read = if self.vocabulary.shape(base).is_some() {
            format!("objects(args, \"{name}\", read_{base})?")
        } else if !self.vocabulary.is_float(base) {
            format!("wholes(args, \"{name}\")?")
        } else if ty == "f64" {
            format!("numbers(args, \"{name}\")?")
        } else {
            format!("numbers(args, \"{name}\")?.into_iter().map(|one| one as {ty}).collect()")
        };
        self.bind(&format!("let {name}: Vec<{ty}> = {read};"));
        self.call_args.push(format!("{name}.as_ptr()"));
    }

    /// An array the engine writes: sized by its extent, and reported in
    /// full, or cut to the count the engine gave.
    fn array_out(&mut self, param: &'a Param) {
        let name = &param.name;
        let base = &param.type_ref.base;
        let ty = self.element(param);
        match sizing(self.function, param) {
            Some(Sizing::Inputs(inputs)) => {
                let length = match inputs.as_slice() {
                    [one] => format!("{one}.len()"),
                    many => format!(
                        "extent(&[{}], \"{name}\")?",
                        many.iter()
                            .map(|input| format!("{input}.len()"))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                };
                self.bind(&format!(
                    "let mut {name}: Vec<{ty}> = room({length}, \"{name}\")?;"
                ));
                self.call_args.push(format!("{name}.as_mut_ptr()"));
            }
            Some(Sizing::Asked { capacity, count }) => {
                self.bind(&format!(
                    "let {capacity}: usize = narrow(args, \"{capacity}\")?;"
                ));
                self.bind(&format!(
                    "let mut {name}: Vec<{ty}> = room({capacity}, \"{name}\")?;"
                ));
                self.call_args.push(format!("{name}.as_mut_ptr()"));
                // `truncate` and not a slice: the engine never writes more
                // than it was given room for, and a count that claimed to
                // would keep what is there rather than panic.
                self.after.push(format!("{name}.truncate({count});"));
            }
            Some(Sizing::Total { .. }) if self.gathered(param) => {
                self.call_args.push("room.as_mut_ptr()".to_string());
            }
            _ => unreachable!(
                "`{name}` on `{}` is an output the classifier cannot size",
                self.function.name
            ),
        }
        self.answers.push(if self.vocabulary.shape(base).is_some() {
            format!("\"{name}\": {name}.iter().map(write_{base}).collect::<Vec<_>>()")
        } else {
            // No cast: `serde_json` serialises a `Vec` of any primitive
            // numeric, at the width the engine declared.
            format!("\"{name}\": {name}")
        });
    }

    /// The arm's text: the bindings, the call through its protocol, what
    /// follows it, and the answer.
    fn finish(self) -> String {
        let function = self.function;
        let name = &function.name;
        let call = format!("sys::{name}({})", self.call_args.join(", "));
        let safety = safety(function);
        let returns_status = function.returns.base == "tm_status";
        let mut out = format!("        \"{name}\" => {{\n{}", self.before);
        match &self.protocol {
            Protocol::Fill { buffer } => {
                // The fill protocol owns the buffer and the count, and runs
                // the call again only if the first answer did not fit.
                let indented = safety.replace('\n', "\n                ");
                let _ = writeln!(
                    out,
                    "            let {buffer} = fill(\"{name}\", |buffer, capacity| {{\n                \
                     {indented}\n                unsafe {{ {call} }}\n            }})?;"
                );
            }
            Protocol::Gather { output, count } => {
                // The gather protocol owns the room and asks again only if
                // the engine said there were more than fitted.
                let ty = self.element(output);
                let indented = safety.replace('\n', "\n                ");
                let mut inside = String::new();
                for line in &self.inside {
                    let _ = write!(inside, "\n                {line}");
                }
                let (binding, check, counted) = match count {
                    Counted::Param(count) if returns_status => (
                        "let answered = ",
                        format!("\n                status(answered, \"{name}\")?;"),
                        (*count).to_string(),
                    ),
                    Counted::Param(count) => ("", String::new(), (*count).to_string()),
                    Counted::Return => ("let answered = ", String::new(), "answered".to_string()),
                };
                let _ = writeln!(
                    out,
                    "            let {} = gather::<{ty}>(\"{name}\", |room| {{{inside}\n                \
                     {indented}\n                {binding}unsafe {{ {call} }};{check}\n                \
                     Ok({counted})\n            }})?;",
                    output.name
                );
            }
            Protocol::Direct => {
                let binding = if function.returns.base == "void" {
                    ""
                } else {
                    "let answered = "
                };
                let indented = safety.replace('\n', "\n            ");
                let _ = writeln!(
                    out,
                    "            {indented}\n            {binding}unsafe {{ {call} }};"
                );
                if returns_status {
                    let _ = writeln!(out, "            status(answered, \"{name}\")?;");
                }
            }
        }
        for line in &self.after {
            let _ = writeln!(out, "            {line}");
        }
        let fields = answer(function, self.answers, &self.protocol);
        let _ = writeln!(
            out,
            "            Ok(json!({{{}}}))\n        }}",
            fields.join(", ")
        );
        out
    }
}

/// What an arm answers with, as `"key": expression` pairs: its
/// out-parameters, then a filled string or the function's own return.
fn answer(function: &Function, outs: Vec<String>, protocol: &Protocol<'_>) -> Vec<String> {
    let mut fields = outs;
    // A filled string comes back under its parameter's own name, like
    // every other out-parameter. The length the function answered is the
    // protocol's and is not reported: the string it describes is already
    // here in full.
    if let Protocol::Fill { buffer } = protocol {
        fields.push(format!("\"{buffer}\": {buffer}"));
    } else if returns_a_string(function) {
        // `None` for null, which is how the engine says there is no such
        // name, and which JSON has a word for.
        fields.push("\"return\": borrowed(answered)".to_string());
    } else if !matches!(function.returns.base.as_str(), "tm_status" | "void")
        && !returns_the_count(function)
    {
        fields.push("\"return\": answered".to_string());
    }
    fields
}

/// The SAFETY note for one arm, naming **what that arm actually
/// passes** and nothing else.
///
/// A generated note that lists an out-parameter the call does not have,
/// or a context it is not given, is worse than none: the whole reason
/// this file is allowed its `unsafe` is that the note beside each call
/// can be checked against the call.
pub(crate) fn safety(function: &Function) -> String {
    let mut clauses: Vec<&str> = Vec::new();
    if has_role(function, "handle") {
        clauses.push("the context is the adapter's own and live for this call");
    }
    if has_role(function, "scalar_out") {
        clauses.push("every out-parameter is a local of the width the engine declares");
    }
    if has_role(function, "string_in") {
        clauses.push("every string argument is a `CString` that outlives the call");
    }
    if has_role(function, "struct_in") {
        clauses.push("every struct argument is a local of the type the engine declares, its extent filled by the arm");
    }
    if has_role(function, "struct_out") {
        clauses.push("every struct out-parameter is a local of the type the engine declares, its extent filled by `default`");
    }
    if has_role(function, "out_struct_size") {
        clauses.push("the extent passed is the size of that local");
    }
    if fills_a_string(function) {
        clauses.push(
            "the buffer and its capacity are the fill protocol's own, and it passes the length \
             of what it allocated",
        );
    }
    if has_role(function, "array_in") {
        clauses.push("every input array is a `Vec` the arm owns, passed with its own length");
    }
    if totals(function).next().is_some() {
        clauses.push("the output room is the gather protocol's own, passed with its own length");
    }
    let sized_here = function.params.iter().any(|param| {
        param.role == "array_out" && !matches!(sizing(function, param), Some(Sizing::Total { .. }))
    });
    if sized_here {
        clauses.push(
            "every output array is a `Vec` the arm sized to the engine's stated extent, passed \
             with its own length",
        );
    }
    if clauses.is_empty() {
        // Nothing is lent and nothing is written through: the arm passes
        // numbers the engine declared and that is the whole of it.
        clauses.push("the call takes nothing but values of the widths the engine declares");
    }
    wrapped(&format!("SAFETY: {}.", clauses.join("; ")))
}

/// A note as comment lines no wider than the project's own limit.
///
/// Unindented; the caller indents to the depth its arm sits at.
pub(crate) fn wrapped(note: &str) -> String {
    /// What is left for text once `            // ` is in front of it.
    const ROOM: usize = 60;

    let mut lines: Vec<String> = vec![String::new()];
    for word in note.split_whitespace() {
        let line = lines
            .last_mut()
            .unwrap_or_else(|| unreachable!("never empty"));
        if line.is_empty() {
            line.push_str(word);
        } else if line.len() + 1 + word.len() <= ROOM {
            line.push(' ');
            line.push_str(word);
        } else {
            lines.push(word.to_string());
        }
    }
    lines
        .iter()
        .map(|line| format!("// {line}"))
        .collect::<Vec<_>>()
        .join("\n")
}
