// generated by diplomat-tool
import type { BodyPosition } from "./BodyPosition"
import type { DashaRow } from "./DashaRow"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A computed chart, read through accessors.
 */
export class Chart {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * The instant the chart was computed for.
     */
    get jdUt(): number;

    /**
     * The ayanamsha value applied, in degrees.
     */
    get ayanamshaDeg(): number;

    /**
     * The number of positions, nine.
     */
    get positionCount(): number;

    /**
     * One position by index.
     */
    position(index: number): BodyPosition | null;

    /**
     * The number of tree rows.
     */
    get dashaRowCount(): number;

    /**
     * One row of the tree by index, in pre-order.
     */
    dashaRow(index: number): DashaRow | null;
}