// generated by diplomat-tool
import type { Chart } from "./Chart"
import type { ErrorCode } from "./ErrorCode"
import type { Settings } from "./Settings"
import type { Settings_obj } from "./Settings"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A context: settings plus a provider.
 */
export class Context {
    /** @internal */
    get ffiValue(): pointer;


    /**
     * The settings the context was built with.
     */
    settings(): Settings;

    /**
     * The one batch call.
     */
    computeChart(jdUt: number): Chart;

    /**
     * Creates a context over the built-in analytic test provider.
     */
    constructor(settings: Settings_obj);
}