// Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary
// crates; do not edit. ABI version 1, SDK 0.0.0.
// The description this file was rendered from ships as idl/api.json.

const MAGIC = 0x42525354; // "TSRB"
const VERSION = 1;
const HEADER_LEN = 32;
const ENTRY_LEN = 16;
const SLOT = 8;

const VIEWS = {
  u8: Uint8Array,
  i8: Int8Array,
  u16: Uint16Array,
  i16: Int16Array,
  u32: Uint32Array,
  i32: Int32Array,
  u64: BigUint64Array,
  i64: BigInt64Array,
  f32: Float32Array,
  f64: Float64Array,
};

const READERS = {
  u8: (dv, at) => dv.getUint8(at),
  i8: (dv, at) => dv.getInt8(at),
  u16: (dv, at) => dv.getUint16(at, true),
  i16: (dv, at) => dv.getInt16(at, true),
  u32: (dv, at) => dv.getUint32(at, true),
  i32: (dv, at) => dv.getInt32(at, true),
  u64: (dv, at) => dv.getBigUint64(at, true),
  i64: (dv, at) => dv.getBigInt64(at, true),
  f32: (dv, at) => dv.getFloat32(at, true),
  f64: (dv, at) => dv.getFloat64(at, true),
};

const TEXT = new TextDecoder('utf-8', { fatal: true });

/**
 * The bytes as an 8-aligned view. A buffer the runtime handed us at an
 * odd offset is copied once, because a typed array must start on its
 * element's alignment; everything else is a view.
 */
function aligned(bytes) {
  if (!(bytes instanceof Uint8Array)) {
    throw new TypeError(`expected a Uint8Array, got ${Object.prototype.toString.call(bytes)}`);
  }
  if (bytes.byteOffset % SLOT === 0) return bytes;
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  return copy;
}

/** Reads the header and the table of contents, checking every offset. */
function open(input, schemaId, schemaName) {
  const bytes = aligned(input);
  const dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (bytes.byteLength < HEADER_LEN || dv.getUint32(0, true) !== MAGIC) {
    throw new TypeError('not a Teistro result blob');
  }
  const version = dv.getUint32(4, true);
  if (version !== VERSION) {
    throw new TypeError(`blob layout version ${version}, this decoder reads version ${VERSION}`);
  }
  const total = dv.getUint32(12, true);
  if (total !== bytes.byteLength) {
    throw new TypeError(`the header says ${total} bytes, ${bytes.byteLength} were given`);
  }
  const id = dv.getUint32(16, true);
  if (id !== schemaId) {
    throw new TypeError(`blob schema ${id}, expected ${schemaId} (${schemaName})`);
  }
  const count = dv.getUint32(8, true);
  const sections = new Map();
  for (let i = 0; i < count; i += 1) {
    const at = HEADER_LEN + i * ENTRY_LEN;
    const entry = {
      offset: dv.getUint32(at + 4, true),
      length: dv.getUint32(at + 8, true),
      count: dv.getUint32(at + 12, true),
    };
    if (entry.offset + entry.length > total) {
      throw new TypeError(`section ${dv.getUint32(at, true)} runs past the end of the blob`);
    }
    sections.set(dv.getUint32(at, true), entry);
  }
  return { bytes, dv, sections };
}

/** The section with an id, or a `TypeError` naming what is missing. */
function section(blob, id, name) {
  const found = blob.sections.get(id);
  if (!found) throw new TypeError(`the blob carries no \`${name}\` section`);
  return found;
}

/** One column of a column section, as a view over the blob's bytes. */
function column(blob, at, index, type, count) {
  const offset = at.offset + blob.dv.getUint32(at.offset + index * 4, true);
  return new VIEWS[type](blob.bytes.buffer, blob.bytes.byteOffset + offset, count);
}

/** A bytes section as text. */
function text(blob, at) {
  return TEXT.decode(new Uint8Array(blob.bytes.buffer, blob.bytes.byteOffset + at.offset, at.count));
}

/**
 * Decodes a Positions blob: Positions over a grid of instants and bodies, instants outermost: cell `i * body_count + j` is instant `i`, body `j`.
 *
 * @param {Uint8Array} bytes the blob the library returned
 */
export function decodePositions(bytes) {
  const blob = open(bytes, 1, 'positions');
  const out = {};
  {
    const at = section(blob, 1, 'summary');
    out.frameBits = READERS.u32(blob.dv, at.offset + 0);
    out.jdCount = READERS.u32(blob.dv, at.offset + 8);
    out.bodyCount = READERS.u32(blob.dv, at.offset + 16);
    out.scale = READERS.u32(blob.dv, at.offset + 24);
  }
  {
    const at = section(blob, 2, 'instants');
    out.instants = {
      jd: column(blob, at, 0, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 3, 'bodies');
    out.bodies = {
      body: column(blob, at, 0, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 4, 'cells');
    out.cells = {
      lon: column(blob, at, 0, 'f64', at.count),
      lat: column(blob, at, 1, 'f64', at.count),
      dist: column(blob, at, 2, 'f64', at.count),
      lonSpeed: column(blob, at, 3, 'f64', at.count),
      latSpeed: column(blob, at, 4, 'f64', at.count),
      distSpeed: column(blob, at, 5, 'f64', at.count),
      status: column(blob, at, 6, 'i32', at.count),
      source: column(blob, at, 7, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 5, 'steps');
    out.steps = text(blob, at);
  }
  {
    const at = section(blob, 6, 'provenance_json');
    out.provenanceJson = text(blob, at);
  }
  return out;
}

/**
 * Decodes a IntlRender blob: A rendered message.
 *
 * @param {Uint8Array} bytes the blob the library returned
 */
export function decodeIntlRender(bytes) {
  const blob = open(bytes, 2, 'intl_render');
  const out = {};
  {
    const at = section(blob, 1, 'flags');
    out.isFallback = READERS.u8(blob.dv, at.offset + 0);
    out.isOverride = READERS.u8(blob.dv, at.offset + 8);
    out.warningCount = READERS.u32(blob.dv, at.offset + 16);
  }
  {
    const at = section(blob, 2, 'text');
    out.text = text(blob, at);
  }
  {
    const at = section(blob, 3, 'resolved_from');
    out.resolvedFrom = text(blob, at);
  }
  {
    const at = section(blob, 4, 'warnings');
    out.warnings = text(blob, at);
  }
  {
    const at = section(blob, 5, 'parts');
    out.parts = text(blob, at);
  }
  return out;
}

/**
 * Decodes a Charts blob: A batch of founded charts at one place: the grahas placed, the bhavas under both readings, the zodiac, the day and the timing. Every per-chart section runs charts outermost, and a batch of one is the ordinary case.
 *
 * @param {Uint8Array} bytes the blob the library returned
 */
export function decodeCharts(bytes) {
  const blob = open(bytes, 3, 'charts');
  const out = {};
  {
    const at = section(blob, 1, 'summary');
    out.kind = READERS.u16(blob.dv, at.offset + 0);
    out.chartCount = READERS.u32(blob.dv, at.offset + 8);
    out.grahaCount = READERS.u32(blob.dv, at.offset + 16);
    out.vargaCount = READERS.u32(blob.dv, at.offset + 24);
    out.dashaCount = READERS.u32(blob.dv, at.offset + 32);
    out.latitudeDeg = READERS.f64(blob.dv, at.offset + 40);
    out.longitudeDeg = READERS.f64(blob.dv, at.offset + 48);
    out.altitudeM = READERS.f64(blob.dv, at.offset + 56);
  }
  {
    const at = section(blob, 2, 'cast');
    out.cast = {
      instant: column(blob, at, 0, 'f64', at.count),
      lagnaDeg: column(blob, at, 1, 'f64', at.count),
      dayLagnaDeg: column(blob, at, 2, 'f64', at.count),
      ayanamshaOffsetDeg: column(blob, at, 3, 'f64', at.count),
      dayPart: column(blob, at, 4, 'u8', at.count),
      dayElapsed: column(blob, at, 5, 'f64', at.count),
      pointCount: column(blob, at, 6, 'u32', at.count),
      aspectCount: column(blob, at, 7, 'u32', at.count),
      praveshaCount: column(blob, at, 8, 'u32', at.count),
      natalSahamCount: column(blob, at, 9, 'u32', at.count),
      hitCount: column(blob, at, 10, 'u32', at.count),
      sadeSatiVisitCount: column(blob, at, 11, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 3, 'grahas');
    out.grahas = {
      graha: column(blob, at, 0, 'u16', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      tropicalDeg: column(blob, at, 2, 'f64', at.count),
      latitudeDeg: column(blob, at, 3, 'f64', at.count),
      distanceAu: column(blob, at, 4, 'f64', at.count),
      speedDegPerDay: column(blob, at, 5, 'f64', at.count),
      houseBhava: column(blob, at, 6, 'u8', at.count),
      houseMethod: column(blob, at, 7, 'u16', at.count),
      houseThrough: column(blob, at, 8, 'f64', at.count),
      houseFromMadhyaDeg: column(blob, at, 9, 'f64', at.count),
      placementBhava: column(blob, at, 10, 'u8', at.count),
      placementMethod: column(blob, at, 11, 'u16', at.count),
      placementThrough: column(blob, at, 12, 'f64', at.count),
      placementFromMadhyaDeg: column(blob, at, 13, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 4, 'readings');
    out.housesMethod = READERS.u16(blob.dv, at.offset + 0);
    out.housesSource = READERS.u16(blob.dv, at.offset + 8);
    out.housesReading = READERS.u8(blob.dv, at.offset + 16);
    out.chalitMethod = READERS.u16(blob.dv, at.offset + 24);
    out.chalitSource = READERS.u16(blob.dv, at.offset + 32);
    out.chalitReading = READERS.u8(blob.dv, at.offset + 40);
  }
  {
    const at = section(blob, 5, 'houses');
    out.houses = {
      madhyaDeg: column(blob, at, 0, 'f64', at.count),
      sandhiDeg: column(blob, at, 1, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 6, 'chalit');
    out.chalit = {
      madhyaDeg: column(blob, at, 0, 'f64', at.count),
      sandhiDeg: column(blob, at, 1, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 7, 'zodiac');
    out.frameBits = READERS.u32(blob.dv, at.offset + 0);
    out.ayanamshaKind = READERS.u8(blob.dv, at.offset + 8);
    out.ayanamsha = READERS.u16(blob.dv, at.offset + 16);
  }
  {
    const at = section(blob, 8, 'day');
    out.day = {
      sunrise: column(blob, at, 0, 'f64', at.count),
      sunset: column(blob, at, 1, 'f64', at.count),
      nextSunrise: column(blob, at, 2, 'f64', at.count),
      vara: column(blob, at, 3, 'u16', at.count),
      calendar: column(blob, at, 4, 'u16', at.count),
      era: column(blob, at, 5, 'u16', at.count),
      year: column(blob, at, 6, 'i32', at.count),
      eraYear: column(blob, at, 7, 'i32', at.count),
      month: column(blob, at, 8, 'u8', at.count),
      dayOfMonth: column(blob, at, 9, 'u8', at.count),
      resolution: column(blob, at, 10, 'u8', at.count),
      computedMonth: column(blob, at, 11, 'u8', at.count),
      computedDay: column(blob, at, 12, 'u8', at.count),
      stateKind: column(blob, at, 13, 'u8', at.count),
      statePolarKind: column(blob, at, 14, 'u8', at.count),
      statePolarPolicy: column(blob, at, 15, 'u8', at.count),
      conventionKind: column(blob, at, 16, 'u8', at.count),
      conventionValue: column(blob, at, 17, 'f64', at.count),
      airPressureHpa: column(blob, at, 18, 'f64', at.count),
      airTemperatureC: column(blob, at, 19, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 9, 'timing');
    out.timing = {
      ghati: column(blob, at, 0, 'u8', at.count),
      pala: column(blob, at, 1, 'u8', at.count),
      vipala: column(blob, at, 2, 'u8', at.count),
      ghatiReckoning: column(blob, at, 3, 'u8', at.count),
      horaNumber: column(blob, at, 4, 'u8', at.count),
      horaLord: column(blob, at, 5, 'u16', at.count),
      horaStart: column(blob, at, 6, 'f64', at.count),
      horaEnd: column(blob, at, 7, 'f64', at.count),
      horaReckoning: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 10, 'model');
    out.model = text(blob, at);
  }
  {
    const at = section(blob, 11, 'steps');
    out.steps = text(blob, at);
  }
  {
    const at = section(blob, 12, 'provenance_json');
    out.provenanceJson = text(blob, at);
  }
  {
    const at = section(blob, 13, 'vargas');
    out.vargas = {
      varga: column(blob, at, 0, 'u16', at.count),
      lagnaRashi: column(blob, at, 1, 'u16', at.count),
      lagnaPart: column(blob, at, 2, 'u16', at.count),
      lagnaSign: column(blob, at, 3, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 14, 'varga_grahas');
    out.vargaGrahas = {
      rashi: column(blob, at, 0, 'u16', at.count),
      part: column(blob, at, 1, 'u16', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 15, 'aspects');
    out.aspects = {
      from: column(blob, at, 0, 'u16', at.count),
      to: column(blob, at, 1, 'u16', at.count),
      houses: column(blob, at, 2, 'u8', at.count),
      strength: column(blob, at, 3, 'u8', at.count),
      fromSignDeg: column(blob, at, 4, 'f64', at.count),
      fromNakshatraDeg: column(blob, at, 5, 'f64', at.count),
      fromPadaDeg: column(blob, at, 6, 'f64', at.count),
      toSignDeg: column(blob, at, 7, 'f64', at.count),
      toNakshatraDeg: column(blob, at, 8, 'f64', at.count),
      toPadaDeg: column(blob, at, 9, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 16, 'drishti_table');
    out.drishtiTable = text(blob, at);
  }
  {
    const at = section(blob, 17, 'points');
    out.points = {
      point: column(blob, at, 0, 'u16', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      signDeg: column(blob, at, 3, 'f64', at.count),
      nakshatraDeg: column(blob, at, 4, 'f64', at.count),
      padaDeg: column(blob, at, 5, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 18, 'bhavas');
    out.bhavas = {
      sign: column(blob, at, 0, 'u16', at.count),
      lord: column(blob, at, 1, 'u16', at.count),
      quadrant: column(blob, at, 2, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 19, 'states');
    out.states = {
      graha: column(blob, at, 0, 'u16', at.count),
      sign: column(blob, at, 1, 'u16', at.count),
      house: column(blob, at, 2, 'u8', at.count),
      dignity: column(blob, at, 3, 'u16', at.count),
      natural: column(blob, at, 4, 'u16', at.count),
      temporary: column(blob, at, 5, 'u16', at.count),
      compound: column(blob, at, 6, 'u16', at.count),
      hasDispositor: column(blob, at, 7, 'u8', at.count),
      dispositor: column(blob, at, 8, 'u16', at.count),
      burning: column(blob, at, 9, 'u8', at.count),
      hasFromSun: column(blob, at, 10, 'u8', at.count),
      fromSunDeg: column(blob, at, 11, 'f64', at.count),
      hasOrbs: column(blob, at, 12, 'u8', at.count),
      orbDeg: column(blob, at, 13, 'f64', at.count),
      hasDeepOrb: column(blob, at, 14, 'u8', at.count),
      deepOrbDeg: column(blob, at, 15, 'f64', at.count),
      age: column(blob, at, 16, 'u16', at.count),
      wakefulness: column(blob, at, 17, 'u16', at.count),
      hasDeeptadi: column(blob, at, 18, 'u8', at.count),
      deeptadi: column(blob, at, 19, 'u16', at.count),
      lajjitadiHolding: column(blob, at, 20, 'u32', at.count),
      lajjitadiRuledOut: column(blob, at, 21, 'u32', at.count),
      lajjitadiUndecided: column(blob, at, 22, 'u32', at.count),
      hasWar: column(blob, at, 23, 'u8', at.count),
      warOpponent: column(blob, at, 24, 'u16', at.count),
      warWon: column(blob, at, 25, 'u8', at.count),
      warApartDeg: column(blob, at, 26, 'f64', at.count),
      signDeg: column(blob, at, 27, 'f64', at.count),
      nakshatraDeg: column(blob, at, 28, 'f64', at.count),
      padaDeg: column(blob, at, 29, 'f64', at.count),
      hasSayanadi: column(blob, at, 30, 'u8', at.count),
      sayanadi: column(blob, at, 31, 'u16', at.count),
      cheshta1: column(blob, at, 32, 'u16', at.count),
      cheshta2: column(blob, at, 33, 'u16', at.count),
      cheshta3: column(blob, at, 34, 'u16', at.count),
      cheshta4: column(blob, at, 35, 'u16', at.count),
      cheshta5: column(blob, at, 36, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 20, 'combustion_orbs');
    out.combustionOrbs = text(blob, at);
  }
  {
    const at = section(blob, 21, 'drawings');
    out.drawings = text(blob, at);
  }
  {
    const at = section(blob, 22, 'svgs');
    out.svgs = text(blob, at);
  }
  {
    const at = section(blob, 23, 'dashas');
    out.dashas = {
      system: column(blob, at, 0, 'u16', at.count),
      seeded: column(blob, at, 1, 'u8', at.count),
      signed: column(blob, at, 2, 'u8', at.count),
      seed: column(blob, at, 3, 'u16', at.count),
      firstLord: column(blob, at, 4, 'u16', at.count),
      overflow: column(blob, at, 5, 'u8', at.count),
      balance: column(blob, at, 6, 'u8', at.count),
      remaining: column(blob, at, 7, 'f64', at.count),
      balanceDays: column(blob, at, 8, 'f64', at.count),
      balanceYears: column(blob, at, 9, 'u32', at.count),
      balanceMonths: column(blob, at, 10, 'u8', at.count),
      balanceDayCount: column(blob, at, 11, 'u8', at.count),
      balanceHours: column(blob, at, 12, 'u8', at.count),
      balanceMinutes: column(blob, at, 13, 'u8', at.count),
      moonSpanFrom: column(blob, at, 14, 'f64', at.count),
      moonSpanTo: column(blob, at, 15, 'f64', at.count),
      depth: column(blob, at, 16, 'u8', at.count),
      periodCount: column(blob, at, 17, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 24, 'dasha_periods');
    out.dashaPeriods = {
      level: column(blob, at, 0, 'u8', at.count),
      index: column(blob, at, 1, 'u8', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      lord: column(blob, at, 3, 'u16', at.count),
      fromJd: column(blob, at, 4, 'f64', at.count),
      toJd: column(blob, at, 5, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 25, 'ashtakavarga');
    out.ashtakavarga = {
      graha: column(blob, at, 0, 'u16', at.count),
      shodhana: column(blob, at, 1, 'u8', at.count),
      ekadhipatya: column(blob, at, 2, 'u8', at.count),
      rashiPinda: column(blob, at, 3, 'u32', at.count),
      grahaPinda: column(blob, at, 4, 'u32', at.count),
      yogaPinda: column(blob, at, 5, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 26, 'ashtakavarga_bindus');
    out.ashtakavargaBindus = {
      bindus: column(blob, at, 0, 'u8', at.count),
      reduced: column(blob, at, 1, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 27, 'sarvashtakavarga');
    out.sarvashtakavarga = {
      sarva: column(blob, at, 0, 'u16', at.count),
      trikona: column(blob, at, 1, 'u16', at.count),
      reduced: column(blob, at, 2, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 28, 'vimshopaka');
    out.vimshopaka = {
      graha: column(blob, at, 0, 'u16', at.count),
      scoring: column(blob, at, 1, 'u8', at.count),
      shadvarga: column(blob, at, 2, 'f64', at.count),
      saptavarga: column(blob, at, 3, 'f64', at.count),
      dashavarga: column(blob, at, 4, 'f64', at.count),
      shodashavarga: column(blob, at, 5, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 29, 'shadbala');
    out.shadbala = {
      graha: column(blob, at, 0, 'u16', at.count),
      uchcha: column(blob, at, 1, 'f64', at.count),
      saptavargaja: column(blob, at, 2, 'f64', at.count),
      ojayugma: column(blob, at, 3, 'f64', at.count),
      kendradi: column(blob, at, 4, 'f64', at.count),
      drekkana: column(blob, at, 5, 'f64', at.count),
      dig: column(blob, at, 6, 'f64', at.count),
      nathonnatha: column(blob, at, 7, 'f64', at.count),
      paksha: column(blob, at, 8, 'f64', at.count),
      tribhaga: column(blob, at, 9, 'f64', at.count),
      abda: column(blob, at, 10, 'f64', at.count),
      masa: column(blob, at, 11, 'f64', at.count),
      vara: column(blob, at, 12, 'f64', at.count),
      hora: column(blob, at, 13, 'f64', at.count),
      ayana: column(blob, at, 14, 'f64', at.count),
      yuddha: column(blob, at, 15, 'f64', at.count),
      cheshta: column(blob, at, 16, 'f64', at.count),
      naisargika: column(blob, at, 17, 'f64', at.count),
      drik: column(blob, at, 18, 'f64', at.count),
      virupas: column(blob, at, 19, 'f64', at.count),
      rupas: column(blob, at, 20, 'f64', at.count),
      requiredRupas: column(blob, at, 21, 'f64', at.count),
      ishta: column(blob, at, 22, 'f64', at.count),
      kashta: column(blob, at, 23, 'f64', at.count),
      subhaRashmi: column(blob, at, 24, 'f64', at.count),
      ashubhaRashmi: column(blob, at, 25, 'f64', at.count),
      strong: column(blob, at, 26, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 30, 'bhava_bala');
    out.bhavaBala = {
      lord: column(blob, at, 0, 'u16', at.count),
      adhipati: column(blob, at, 1, 'f64', at.count),
      dig: column(blob, at, 2, 'f64', at.count),
      drishti: column(blob, at, 3, 'f64', at.count),
      special: column(blob, at, 4, 'f64', at.count),
      virupas: column(blob, at, 5, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 31, 'vaiseshikamsa');
    out.vaiseshikamsa = {
      graha: column(blob, at, 0, 'u16', at.count),
      impaired: column(blob, at, 1, 'u8', at.count),
      shadvargaGood: column(blob, at, 2, 'u8', at.count),
      shadvargaName: column(blob, at, 3, 'u16', at.count),
      saptavargaGood: column(blob, at, 4, 'u8', at.count),
      saptavargaName: column(blob, at, 5, 'u16', at.count),
      dashavargaGood: column(blob, at, 6, 'u8', at.count),
      dashavargaName: column(blob, at, 7, 'u16', at.count),
      shodashavargaGood: column(blob, at, 8, 'u8', at.count),
      shodashavargaName: column(blob, at, 9, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 32, 'dasha_phala');
    out.dashaPhala = {
      graha: column(blob, at, 0, 'u16', at.count),
      subhankaD1: column(blob, at, 1, 'f64', at.count),
      subhankaD2: column(blob, at, 2, 'f64', at.count),
      subhankaD3: column(blob, at, 3, 'f64', at.count),
      subhankaD7: column(blob, at, 4, 'f64', at.count),
      subhankaD9: column(blob, at, 5, 'f64', at.count),
      subhankaD12: column(blob, at, 6, 'f64', at.count),
      subhankaD30: column(blob, at, 7, 'f64', at.count),
      subhanka: column(blob, at, 8, 'f64', at.count),
      asubhanka: column(blob, at, 9, 'f64', at.count),
      nature: column(blob, at, 10, 'u16', at.count),
      phase: column(blob, at, 11, 'u8', at.count),
      favourable: column(blob, at, 12, 'u8', at.count),
      unfavourable: column(blob, at, 13, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 33, 'rules');
    out.rules = text(blob, at);
  }
  {
    const at = section(blob, 34, 'plans');
    out.plans = text(blob, at);
  }
  {
    const at = section(blob, 35, 'praveshas');
    out.praveshas = {
      year: column(blob, at, 0, 'u16', at.count),
      jd: column(blob, at, 1, 'f64', at.count),
      munthaSign: column(blob, at, 2, 'u16', at.count),
      munthaLord: column(blob, at, 3, 'u16', at.count),
      munthaDeg: column(blob, at, 4, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 36, 'annual_charts');
    out.annualCharts = {
      lagnaDeg: column(blob, at, 0, 'f64', at.count),
      daylight: column(blob, at, 1, 'u8', at.count),
      janmaLagnaLord: column(blob, at, 2, 'u16', at.count),
      varshaLagnaLord: column(blob, at, 3, 'u16', at.count),
      triRashiLord: column(blob, at, 4, 'u16', at.count),
      dinaRatriLord: column(blob, at, 5, 'u16', at.count),
      yearLord: column(blob, at, 6, 'u16', at.count),
      yearLordChosen: column(blob, at, 7, 'u8', at.count),
      yearLordVishwa: column(blob, at, 8, 'i32', at.count),
      moonPassedOver: column(blob, at, 9, 'u8', at.count),
      claimCount: column(blob, at, 10, 'u8', at.count),
      yogaCount: column(blob, at, 11, 'u8', at.count),
      retrograde: column(blob, at, 12, 'u8', at.count),
      combust: column(blob, at, 13, 'u8', at.count),
      matterCount: column(blob, at, 14, 'u8', at.count),
      sahamCount: column(blob, at, 15, 'u8', at.count),
      dashaCount: column(blob, at, 16, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 37, 'year_claims');
    out.yearClaims = {
      graha: column(blob, at, 0, 'u16', at.count),
      vishwa: column(blob, at, 1, 'i32', at.count),
      portfolios: column(blob, at, 2, 'u8', at.count),
      aspectsLagna: column(blob, at, 3, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 38, 'year_yogas');
    out.yearYogas = {
      faster: column(blob, at, 0, 'u16', at.count),
      slower: column(blob, at, 1, 'u16', at.count),
      drishti: column(blob, at, 2, 'u8', at.count),
      yoga: column(blob, at, 3, 'u8', at.count),
      orbDeg: column(blob, at, 4, 'f64', at.count),
      apartDeg: column(blob, at, 5, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 39, 'year_matters');
    out.yearMatters = {
      house: column(blob, at, 0, 'u8', at.count),
      sign: column(blob, at, 1, 'u16', at.count),
      lagnesha: column(blob, at, 2, 'u16', at.count),
      karyesha: column(blob, at, 3, 'u16', at.count),
      sameLord: column(blob, at, 4, 'u8', at.count),
      pairFaster: column(blob, at, 5, 'u16', at.count),
      pairSlower: column(blob, at, 6, 'u16', at.count),
      pairDrishti: column(blob, at, 7, 'u8', at.count),
      pairYoga: column(blob, at, 8, 'u8', at.count),
      pairYogaPresent: column(blob, at, 9, 'u8', at.count),
      pairOrbDeg: column(blob, at, 10, 'f64', at.count),
      pairApartDeg: column(blob, at, 11, 'f64', at.count),
      unanswered: column(blob, at, 12, 'u16', at.count),
      heldCount: column(blob, at, 13, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 40, 'matter_yogas');
    out.matterYogas = {
      yoga: column(blob, at, 0, 'u8', at.count),
      byPair: column(blob, at, 1, 'u8', at.count),
      through: column(blob, at, 2, 'u16', at.count),
      throughPresent: column(blob, at, 3, 'u8', at.count),
      entering: column(blob, at, 4, 'u16', at.count),
      enteringPresent: column(blob, at, 5, 'u8', at.count),
      afflictionsPresent: column(blob, at, 6, 'u8', at.count),
      lagneshaAfflictions: column(blob, at, 7, 'u8', at.count),
      karyeshaAfflictions: column(blob, at, 8, 'u8', at.count),
      legCount: column(blob, at, 9, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 41, 'matter_legs');
    out.matterLegs = {
      faster: column(blob, at, 0, 'u16', at.count),
      slower: column(blob, at, 1, 'u16', at.count),
      drishti: column(blob, at, 2, 'u8', at.count),
      yoga: column(blob, at, 3, 'u8', at.count),
      yogaPresent: column(blob, at, 4, 'u8', at.count),
      orbDeg: column(blob, at, 5, 'f64', at.count),
      apartDeg: column(blob, at, 6, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 42, 'year_sahams');
    out.yearSahams = {
      saham: column(blob, at, 0, 'u8', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      lord: column(blob, at, 3, 'u16', at.count),
      house: column(blob, at, 4, 'u8', at.count),
      addedSign: column(blob, at, 5, 'u8', at.count),
      strong: column(blob, at, 6, 'u16', at.count),
      weak: column(blob, at, 7, 'u8', at.count),
      lordVishwa: column(blob, at, 8, 'i32', at.count),
      lordHarsha: column(blob, at, 9, 'u8', at.count),
      nodeAxis: column(blob, at, 10, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 43, 'year_saham_seven');
    out.yearSahamSeven = {
      graha: column(blob, at, 0, 'u16', at.count),
      drishti: column(blob, at, 1, 'u8', at.count),
      relation: column(blob, at, 2, 'u8', at.count),
      company: column(blob, at, 3, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 44, 'year_harsha');
    out.yearHarsha = {
      graha: column(blob, at, 0, 'u16', at.count),
      house: column(blob, at, 1, 'u8', at.count),
      sthana: column(blob, at, 2, 'u8', at.count),
      uchchaSwakshetra: column(blob, at, 3, 'u8', at.count),
      striPurusha: column(blob, at, 4, 'u8', at.count),
      dinaRatri: column(blob, at, 5, 'u8', at.count),
      total: column(blob, at, 6, 'u8', at.count),
      grade: column(blob, at, 7, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 45, 'natal_sahams');
    out.natalSahams = {
      saham: column(blob, at, 0, 'u8', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      lord: column(blob, at, 3, 'u16', at.count),
      house: column(blob, at, 4, 'u8', at.count),
      addedSign: column(blob, at, 5, 'u8', at.count),
      strong: column(blob, at, 6, 'u16', at.count),
      weak: column(blob, at, 7, 'u8', at.count),
      lordVishwa: column(blob, at, 8, 'i32', at.count),
      lordHarsha: column(blob, at, 9, 'u8', at.count),
      nodeAxis: column(blob, at, 10, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 46, 'natal_saham_seven');
    out.natalSahamSeven = {
      graha: column(blob, at, 0, 'u16', at.count),
      drishti: column(blob, at, 1, 'u8', at.count),
      relation: column(blob, at, 2, 'u8', at.count),
      company: column(blob, at, 3, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 47, 'year_dashas');
    out.yearDashas = {
      system: column(blob, at, 0, 'u16', at.count),
      seeded: column(blob, at, 1, 'u8', at.count),
      seed: column(blob, at, 2, 'u16', at.count),
      first: column(blob, at, 3, 'u8', at.count),
      remaining: column(blob, at, 4, 'f64', at.count),
      fromJd: column(blob, at, 5, 'f64', at.count),
      toJd: column(blob, at, 6, 'f64', at.count),
      shareCount: column(blob, at, 7, 'u8', at.count),
      periodCount: column(blob, at, 8, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 48, 'year_dasha_shares');
    out.yearDashaShares = {
      lord: column(blob, at, 0, 'u16', at.count),
      hasSign: column(blob, at, 1, 'u8', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      weight: column(blob, at, 3, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 49, 'year_dasha_periods');
    out.yearDashaPeriods = {
      level: column(blob, at, 0, 'u8', at.count),
      index: column(blob, at, 1, 'u8', at.count),
      hasSign: column(blob, at, 2, 'u8', at.count),
      sign: column(blob, at, 3, 'u16', at.count),
      lord: column(blob, at, 4, 'u16', at.count),
      fromJd: column(blob, at, 5, 'f64', at.count),
      toJd: column(blob, at, 6, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 50, 'content_hashes');
    out.contentHashes = text(blob, at);
  }
  {
    const at = section(blob, 51, 'jaimini');
    out.jaimini = {
      atmakaraka: column(blob, at, 0, 'u16', at.count),
      karakamsha: column(blob, at, 1, 'u16', at.count),
      brahmaRule: column(blob, at, 2, 'u8', at.count),
      countedFrom: column(blob, at, 3, 'u16', at.count),
      qualified: column(blob, at, 4, 'u16', at.count),
      brahma: column(blob, at, 5, 'u16', at.count),
      brahmaOutcome: column(blob, at, 6, 'u8', at.count),
      passedFrom: column(blob, at, 7, 'u16', at.count),
      passedFromPresent: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 52, 'jaimini_grahas');
    out.jaiminiGrahas = {
      graha: column(blob, at, 0, 'u16', at.count),
      inRasi: column(blob, at, 1, 'u8', at.count),
      inNavamsha: column(blob, at, 2, 'u8', at.count),
      arudha: column(blob, at, 3, 'u16', at.count),
      arudhaPresent: column(blob, at, 4, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 53, 'gochar');
    out.gochar = {
      instant: column(blob, at, 0, 'f64', at.count),
      reference: column(blob, at, 1, 'u16', at.count),
      countedFrom: column(blob, at, 2, 'u8', at.count),
      nodeVedha: column(blob, at, 3, 'u8', at.count),
      nodeObstruction: column(blob, at, 4, 'u8', at.count),
      ashtakavargaGoodFrom: column(blob, at, 5, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 54, 'gochar_grahas');
    out.gocharGrahas = {
      graha: column(blob, at, 0, 'u16', at.count),
      sign: column(blob, at, 1, 'u16', at.count),
      degrees: column(blob, at, 2, 'f64', at.count),
      house: column(blob, at, 3, 'u8', at.count),
      goodHouse: column(blob, at, 4, 'u8', at.count),
      vedhaHouse: column(blob, at, 5, 'u8', at.count),
      obstructedBy: column(blob, at, 6, 'u16', at.count),
      verdict: column(blob, at, 7, 'u8', at.count),
      fruition: column(blob, at, 8, 'u8', at.count),
      fruitfulNow: column(blob, at, 9, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 55, 'gochar_ashtakavarga');
    out.gocharAshtakavarga = {
      graha: column(blob, at, 0, 'u16', at.count),
      bindus: column(blob, at, 1, 'u8', at.count),
      good: column(blob, at, 2, 'u8', at.count),
      kakshya: column(blob, at, 3, 'u8', at.count),
      kakshyaLord: column(blob, at, 4, 'u8', at.count),
      kakshyaBindu: column(blob, at, 5, 'u8', at.count),
      sarva: column(blob, at, 6, 'u16', at.count),
      sarvaStanding: column(blob, at, 7, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 56, 'hits');
    out.hits = {
      instant: column(blob, at, 0, 'f64', at.count),
      graha: column(blob, at, 1, 'u16', at.count),
      kind: column(blob, at, 2, 'u8', at.count),
      into: column(blob, at, 3, 'u16', at.count),
      motion: column(blob, at, 4, 'u8', at.count),
      toLagna: column(blob, at, 5, 'u8', at.count),
      toGraha: column(blob, at, 6, 'u16', at.count),
      angle: column(blob, at, 7, 'u16', at.count),
      phase: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 57, 'sade_sati');
    out.sadeSati = {
      reference: column(blob, at, 0, 'u16', at.count),
      countedFrom: column(blob, at, 1, 'u8', at.count),
      reckoning: column(blob, at, 2, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 58, 'sade_sati_visits');
    out.sadeSatiVisits = {
      period: column(blob, at, 0, 'u16', at.count),
      house: column(blob, at, 1, 'u8', at.count),
      from: column(blob, at, 2, 'f64', at.count),
      to: column(blob, at, 3, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 59, 'kp');
    out.kp = text(blob, at);
  }
  {
    const at = section(blob, 60, 'dignities');
    out.dignities = {
      sect: column(blob, at, 0, 'u8', at.count),
      sectRule: column(blob, at, 1, 'u8', at.count),
      terms: column(blob, at, 2, 'u8', at.count),
      triplicities: column(blob, at, 3, 'u8', at.count),
      scoreHouse: column(blob, at, 4, 'i8', at.count),
      scoreExaltation: column(blob, at, 5, 'i8', at.count),
      scoreTriplicity: column(blob, at, 6, 'i8', at.count),
      scoreTerm: column(blob, at, 7, 'i8', at.count),
      scoreFace: column(blob, at, 8, 'i8', at.count),
      scoreDetriment: column(blob, at, 9, 'i8', at.count),
      scoreFall: column(blob, at, 10, 'i8', at.count),
      scorePeregrine: column(blob, at, 11, 'i8', at.count),
      receptionCount: column(blob, at, 12, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 61, 'dignity_planets');
    out.dignityPlanets = {
      planet: column(blob, at, 0, 'u16', at.count),
      longitude: column(blob, at, 1, 'f64', at.count),
      house: column(blob, at, 2, 'u8', at.count),
      exaltation: column(blob, at, 3, 'u8', at.count),
      triplicity: column(blob, at, 4, 'u8', at.count),
      term: column(blob, at, 5, 'u8', at.count),
      face: column(blob, at, 6, 'u8', at.count),
      detriment: column(blob, at, 7, 'u8', at.count),
      fall: column(blob, at, 8, 'u8', at.count),
      score: column(blob, at, 9, 'i16', at.count),
      reception: column(blob, at, 10, 'i16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 62, 'dignity_receptions');
    out.dignityReceptions = {
      first: column(blob, at, 0, 'u16', at.count),
      second: column(blob, at, 1, 'u16', at.count),
      firstInHouse: column(blob, at, 2, 'u8', at.count),
      firstInExaltation: column(blob, at, 3, 'u8', at.count),
      firstInTriplicity: column(blob, at, 4, 'u8', at.count),
      firstInTerm: column(blob, at, 5, 'u8', at.count),
      firstInFace: column(blob, at, 6, 'u8', at.count),
      firstInDetriment: column(blob, at, 7, 'u8', at.count),
      firstInFall: column(blob, at, 8, 'u8', at.count),
      secondInHouse: column(blob, at, 9, 'u8', at.count),
      secondInExaltation: column(blob, at, 10, 'u8', at.count),
      secondInTriplicity: column(blob, at, 11, 'u8', at.count),
      secondInTerm: column(blob, at, 12, 'u8', at.count),
      secondInFace: column(blob, at, 13, 'u8', at.count),
      secondInDetriment: column(blob, at, 14, 'u8', at.count),
      secondInFall: column(blob, at, 15, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 63, 'fortitudes');
    out.fortitudes = {
      houses: column(blob, at, 0, 'u16', at.count),
      ascendant: column(blob, at, 1, 'f64', at.count),
      midheaven: column(blob, at, 2, 'f64', at.count),
      northNode: column(blob, at, 3, 'f64', at.count),
      regulus: column(blob, at, 4, 'f64', at.count),
      spica: column(blob, at, 5, 'f64', at.count),
      algol: column(blob, at, 6, 'f64', at.count),
      combustionOrb: column(blob, at, 7, 'f64', at.count),
      combustionInSign: column(blob, at, 8, 'u8', at.count),
      beamsOrb: column(blob, at, 9, 'f64', at.count),
      cazimiOrb: column(blob, at, 10, 'f64', at.count),
      cuspOrb: column(blob, at, 11, 'f64', at.count),
      starOrb: column(blob, at, 12, 'f64', at.count),
      partile: column(blob, at, 13, 'u8', at.count),
      partileOrb: column(blob, at, 14, 'f64', at.count),
      siege: column(blob, at, 15, 'u8', at.count),
      siegeSpan: column(blob, at, 16, 'f64', at.count),
      almutenPlace: column(blob, at, 17, 'u8', at.count),
      almutenFortune: column(blob, at, 18, 'u8', at.count),
      fortune: column(blob, at, 19, 'f64', at.count),
      scoreDirect: column(blob, at, 20, 'i8', at.count),
      scoreRetrograde: column(blob, at, 21, 'i8', at.count),
      scoreSwift: column(blob, at, 22, 'i8', at.count),
      scoreSlow: column(blob, at, 23, 'i8', at.count),
      scoreSuperiorOriental: column(blob, at, 24, 'i8', at.count),
      scoreSuperiorOccidental: column(blob, at, 25, 'i8', at.count),
      scoreInferiorOriental: column(blob, at, 26, 'i8', at.count),
      scoreInferiorOccidental: column(blob, at, 27, 'i8', at.count),
      scoreIncreasing: column(blob, at, 28, 'i8', at.count),
      scoreDecreasing: column(blob, at, 29, 'i8', at.count),
      scoreFreeFromCombustion: column(blob, at, 30, 'i8', at.count),
      scoreCazimi: column(blob, at, 31, 'i8', at.count),
      scoreCombust: column(blob, at, 32, 'i8', at.count),
      scoreUnderBeams: column(blob, at, 33, 'i8', at.count),
      scoreConjunctBenefic: column(blob, at, 34, 'i8', at.count),
      scoreConjunctNorthNode: column(blob, at, 35, 'i8', at.count),
      scoreTrineBenefic: column(blob, at, 36, 'i8', at.count),
      scoreSextileBenefic: column(blob, at, 37, 'i8', at.count),
      scoreConjunctMalefic: column(blob, at, 38, 'i8', at.count),
      scoreConjunctSouthNode: column(blob, at, 39, 'i8', at.count),
      scoreOpposedMalefic: column(blob, at, 40, 'i8', at.count),
      scoreSquareMalefic: column(blob, at, 41, 'i8', at.count),
      scoreBesieged: column(blob, at, 42, 'i8', at.count),
      scoreRegulus: column(blob, at, 43, 'i8', at.count),
      scoreSpica: column(blob, at, 44, 'i8', at.count),
      scoreAlgol: column(blob, at, 45, 'i8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 64, 'fortitude_houses');
    out.fortitudeHouses = {
      cusp: column(blob, at, 0, 'f64', at.count),
      score: column(blob, at, 1, 'i8', at.count),
      almutenSaturn: column(blob, at, 2, 'i16', at.count),
      almutenJupiter: column(blob, at, 3, 'i16', at.count),
      almutenMars: column(blob, at, 4, 'i16', at.count),
      almutenSun: column(blob, at, 5, 'i16', at.count),
      almutenVenus: column(blob, at, 6, 'i16', at.count),
      almutenMercury: column(blob, at, 7, 'i16', at.count),
      almutenMoon: column(blob, at, 8, 'i16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 65, 'fortitude_planets');
    out.fortitudePlanets = {
      planet: column(blob, at, 0, 'u16', at.count),
      speed: column(blob, at, 1, 'f64', at.count),
      meanMotion: column(blob, at, 2, 'f64', at.count),
      house: column(blob, at, 3, 'u8', at.count),
      fortitude: column(blob, at, 4, 'i16', at.count),
      debility: column(blob, at, 5, 'i16', at.count),
      places: column(blob, at, 6, 'i16', at.count),
      accidentCount: column(blob, at, 7, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 66, 'fortitude_accidents');
    out.fortitudeAccidents = {
      accident: column(blob, at, 0, 'u8', at.count),
      points: column(blob, at, 1, 'i8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 67, 'lots');
    out.lots = {
      sect: column(blob, at, 0, 'u8', at.count),
      sectRule: column(blob, at, 1, 'u8', at.count),
      fortune: column(blob, at, 2, 'u8', at.count),
      fortuneReversed: column(blob, at, 3, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 68, 'lot_places');
    out.lotPlaces = {
      lot: column(blob, at, 0, 'u8', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      sign: column(blob, at, 2, 'u16', at.count),
      lord: column(blob, at, 3, 'u16', at.count),
      house: column(blob, at, 4, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 69, 'considerations');
    out.considerations = {
      hourLord: column(blob, at, 0, 'u16', at.count),
      ascendantLord: column(blob, at, 1, 'u16', at.count),
      radicalGrounds: column(blob, at, 2, 'u8', at.count),
      ascendantSign: column(blob, at, 3, 'u16', at.count),
      ascendantDegree: column(blob, at, 4, 'f64', at.count),
      ascendantEarly: column(blob, at, 5, 'u8', at.count),
      ascendantLate: column(blob, at, 6, 'u8', at.count),
      shortAscension: column(blob, at, 7, 'u8', at.count),
      moonSign: column(blob, at, 8, 'u16', at.count),
      moonDegree: column(blob, at, 9, 'f64', at.count),
      moonLate: column(blob, at, 10, 'u8', at.count),
      moonLateSign: column(blob, at, 11, 'u8', at.count),
      viaCombusta: column(blob, at, 12, 'u8', at.count),
      daysInSign: column(blob, at, 13, 'f64', at.count),
      eased: column(blob, at, 14, 'u8', at.count),
      seventhCuspDeg: column(blob, at, 15, 'f64', at.count),
      seventhLord: column(blob, at, 16, 'u16', at.count),
      seventhInfortunes: column(blob, at, 17, 'u8', at.count),
      seventhLordRetrograde: column(blob, at, 18, 'u8', at.count),
      seventhLordCombust: column(blob, at, 19, 'u8', at.count),
      seventhLordInFall: column(blob, at, 20, 'u8', at.count),
      seventhLordInInfortuneTerm: column(blob, at, 21, 'u8', at.count),
      seventhLordNet: column(blob, at, 22, 'i16', at.count),
      saturnHouse: column(blob, at, 23, 'u8', at.count),
      saturnRetrograde: column(blob, at, 24, 'u8', at.count),
      ascendantLordCombust: column(blob, at, 25, 'u8', at.count),
      moonLateFromDeg: column(blob, at, 26, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 70, 'consideration_perfections');
    out.considerationPerfections = {
      present: column(blob, at, 0, 'u8', at.count),
      planet: column(blob, at, 1, 'u16', at.count),
      aspect: column(blob, at, 2, 'u8', at.count),
      days: column(blob, at, 3, 'f64', at.count),
      gapDeg: column(blob, at, 4, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 71, 'consideration_orbs');
    out.considerationOrbs = {
      orbDeg: column(blob, at, 0, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 72, 'perfection');
    out.perfection = {
      querent: column(blob, at, 0, 'u16', at.count),
      quesited: column(blob, at, 1, 'u16', at.count),
      horizonDays: column(blob, at, 2, 'f64', at.count),
      horizonRuleDays: column(blob, at, 3, 'f64', at.count),
      withinSignRule: column(blob, at, 4, 'u8', at.count),
      applicationPresent: column(blob, at, 5, 'u8', at.count),
      applicationAspect: column(blob, at, 6, 'u8', at.count),
      applicationDays: column(blob, at, 7, 'f64', at.count),
      applying: column(blob, at, 8, 'u16', at.count),
      applicationKind: column(blob, at, 9, 'u8', at.count),
      gapDeg: column(blob, at, 10, 'f64', at.count),
      withinMoieties: column(blob, at, 11, 'u8', at.count),
      separationPresent: column(blob, at, 12, 'u8', at.count),
      separationAspect: column(blob, at, 13, 'u8', at.count),
      separationPastDeg: column(blob, at, 14, 'f64', at.count),
      querentHouse: column(blob, at, 15, 'u8', at.count),
      querentDignity: column(blob, at, 16, 'u8', at.count),
      quesitedHouse: column(blob, at, 17, 'u8', at.count),
      quesitedDignity: column(blob, at, 18, 'u8', at.count),
      mutualByHouse: column(blob, at, 19, 'u8', at.count),
      infortunesBetween: column(blob, at, 20, 'u8', at.count),
      moonRelays: column(blob, at, 21, 'u8', at.count),
      quesitedInAscendant: column(blob, at, 22, 'u8', at.count),
      waysHeld: column(blob, at, 23, 'u8', at.count),
      impedimentCount: column(blob, at, 24, 'u32', at.count),
      translationCount: column(blob, at, 25, 'u32', at.count),
      collectionCount: column(blob, at, 26, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 73, 'perfection_impediments');
    out.perfectionImpediments = {
      kind: column(blob, at, 0, 'u8', at.count),
      significator: column(blob, at, 1, 'u16', at.count),
      thirdPresent: column(blob, at, 2, 'u8', at.count),
      third: column(blob, at, 3, 'u16', at.count),
      aspect: column(blob, at, 4, 'u8', at.count),
      days: column(blob, at, 5, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 74, 'perfection_translations');
    out.perfectionTranslations = {
      translator: column(blob, at, 0, 'u16', at.count),
      from: column(blob, at, 1, 'u16', at.count),
      to: column(blob, at, 2, 'u16', at.count),
      separatingAspect: column(blob, at, 3, 'u8', at.count),
      separatingPastDeg: column(blob, at, 4, 'f64', at.count),
      aspect: column(blob, at, 5, 'u8', at.count),
      days: column(blob, at, 6, 'f64', at.count),
      received: column(blob, at, 7, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 75, 'perfection_collections');
    out.perfectionCollections = {
      collector: column(blob, at, 0, 'u16', at.count),
      fromQuerentAspect: column(blob, at, 1, 'u8', at.count),
      fromQuerentDays: column(blob, at, 2, 'f64', at.count),
      fromQuesitedAspect: column(blob, at, 3, 'u8', at.count),
      fromQuesitedDays: column(blob, at, 4, 'f64', at.count),
      collectorInQuerent: column(blob, at, 5, 'u8', at.count),
      collectorInQuesited: column(blob, at, 6, 'u8', at.count),
      querentInCollector: column(blob, at, 7, 'u8', at.count),
      quesitedInCollector: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 76, 'perfection_orbs');
    out.perfectionOrbs = {
      orbDeg: column(blob, at, 0, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 77, 'progressions');
    out.progressions = {
      life: column(blob, at, 0, 'f64', at.count),
      sky: column(blob, at, 1, 'f64', at.count),
      armcDeg: column(blob, at, 2, 'f64', at.count),
      ascendantDeg: column(blob, at, 3, 'f64', at.count),
      midheavenDeg: column(blob, at, 4, 'f64', at.count),
      arcDeg: column(blob, at, 5, 'f64', at.count),
      directedAscendantDeg: column(blob, at, 6, 'f64', at.count),
      directedMidheavenDeg: column(blob, at, 7, 'f64', at.count),
      contactCount: column(blob, at, 8, 'u32', at.count),
      contactsAsked: column(blob, at, 9, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 78, 'progressed_grahas');
    out.progressedGrahas = {
      graha: column(blob, at, 0, 'u16', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      tropicalDeg: column(blob, at, 2, 'f64', at.count),
      speedDegPerDay: column(blob, at, 3, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 79, 'directed_grahas');
    out.directedGrahas = {
      graha: column(blob, at, 0, 'u16', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 80, 'progressed_contacts');
    out.progressedContacts = {
      life: column(blob, at, 0, 'f64', at.count),
      sky: column(blob, at, 1, 'f64', at.count),
      graha: column(blob, at, 2, 'u16', at.count),
      toLagna: column(blob, at, 3, 'u8', at.count),
      toGraha: column(blob, at, 4, 'u16', at.count),
      angle: column(blob, at, 5, 'u16', at.count),
      motion: column(blob, at, 6, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 81, 'outer');
    out.outer = {
      graha: column(blob, at, 0, 'u16', at.count),
      longitudeDeg: column(blob, at, 1, 'f64', at.count),
      tropicalDeg: column(blob, at, 2, 'f64', at.count),
      latitudeDeg: column(blob, at, 3, 'f64', at.count),
      distanceAu: column(blob, at, 4, 'f64', at.count),
      speedDegPerDay: column(blob, at, 5, 'f64', at.count),
      houseBhava: column(blob, at, 6, 'u8', at.count),
      houseMethod: column(blob, at, 7, 'u16', at.count),
      houseThrough: column(blob, at, 8, 'f64', at.count),
      houseFromMadhyaDeg: column(blob, at, 9, 'f64', at.count),
      placementBhava: column(blob, at, 10, 'u8', at.count),
      placementMethod: column(blob, at, 11, 'u16', at.count),
      placementThrough: column(blob, at, 12, 'f64', at.count),
      placementFromMadhyaDeg: column(blob, at, 13, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 82, 'western_aspects');
    out.westernAspects = {
      count: column(blob, at, 0, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 83, 'western_aspect_rows');
    out.westernAspectRows = {
      first: column(blob, at, 0, 'u16', at.count),
      second: column(blob, at, 1, 'u16', at.count),
      aspect: column(blob, at, 2, 'u8', at.count),
      apartDeg: column(blob, at, 3, 'f64', at.count),
      fromExactDeg: column(blob, at, 4, 'f64', at.count),
      orbDeg: column(blob, at, 5, 'f64', at.count),
      applying: column(blob, at, 6, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 84, 'synastry');
    out.synastry = {
      count: column(blob, at, 0, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 85, 'synastry_rows');
    out.synastryRows = {
      firstLagna: column(blob, at, 0, 'u8', at.count),
      firstGraha: column(blob, at, 1, 'u16', at.count),
      secondLagna: column(blob, at, 2, 'u8', at.count),
      secondGraha: column(blob, at, 3, 'u16', at.count),
      aspect: column(blob, at, 4, 'u8', at.count),
      apartDeg: column(blob, at, 5, 'f64', at.count),
      fromExactDeg: column(blob, at, 6, 'f64', at.count),
      orbDeg: column(blob, at, 7, 'f64', at.count),
      length: at.count,
    };
  }
  return out;
}

/**
 * Decodes a Panchanga blob: A batch of daily panchangas at one place: the day, the four moving limbs, the periods, the lunar month, what the Moon and the Sun did, and what the day is said to be. Every per-day list is concatenated across the batch, with `counts` saying how many rows are each day's.
 *
 * @param {Uint8Array} bytes the blob the library returned
 */
export function decodePanchanga(bytes) {
  const blob = open(bytes, 4, 'panchanga');
  const out = {};
  {
    const at = section(blob, 1, 'summary');
    out.dayCount = READERS.u32(blob.dv, at.offset + 0);
    out.latitudeDeg = READERS.f64(blob.dv, at.offset + 8);
    out.longitudeDeg = READERS.f64(blob.dv, at.offset + 16);
    out.altitudeM = READERS.f64(blob.dv, at.offset + 24);
    out.calendar = READERS.u16(blob.dv, at.offset + 32);
    out.lunarMonth = READERS.u8(blob.dv, at.offset + 40);
  }
  {
    const at = section(blob, 2, 'days');
    out.days = {
      windowFrom: column(blob, at, 0, 'f64', at.count),
      windowTo: column(blob, at, 1, 'f64', at.count),
      month: column(blob, at, 2, 'u16', at.count),
      amanta: column(blob, at, 3, 'u16', at.count),
      purnimanta: column(blob, at, 4, 'u16', at.count),
      paksha: column(blob, at, 5, 'u16', at.count),
      monthKind: column(blob, at, 6, 'u8', at.count),
      ayana: column(blob, at, 7, 'u16', at.count),
      ritu: column(blob, at, 8, 'u16', at.count),
      dishaShool: column(blob, at, 9, 'u16', at.count),
      hasSankranti: column(blob, at, 10, 'u8', at.count),
      sankranti: column(blob, at, 11, 'f64', at.count),
      hasAbhijit: column(blob, at, 12, 'u8', at.count),
      abhijitFrom: column(blob, at, 13, 'f64', at.count),
      abhijitTo: column(blob, at, 14, 'f64', at.count),
      abhijitEffective: column(blob, at, 15, 'u8', at.count),
      hasBrahma: column(blob, at, 16, 'u8', at.count),
      brahmaFrom: column(blob, at, 17, 'f64', at.count),
      brahmaTo: column(blob, at, 18, 'f64', at.count),
      moonWindowFrom: column(blob, at, 19, 'f64', at.count),
      moonWindowTo: column(blob, at, 20, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 3, 'counts');
    out.counts = {
      tithi: column(blob, at, 0, 'u32', at.count),
      nakshatra: column(blob, at, 1, 'u32', at.count),
      yoga: column(blob, at, 2, 'u32', at.count),
      karana: column(blob, at, 3, 'u32', at.count),
      panchaka: column(blob, at, 4, 'u32', at.count),
      moonSigns: column(blob, at, 5, 'u32', at.count),
      sunSigns: column(blob, at, 6, 'u32', at.count),
      kaalas: column(blob, at, 7, 'u32', at.count),
      choghadiya: column(blob, at, 8, 'u32', at.count),
      horas: column(blob, at, 9, 'u32', at.count),
      muhurtas: column(blob, at, 10, 'u32', at.count),
      moonEvents: column(blob, at, 11, 'u32', at.count),
      muhurtaYogas: column(blob, at, 12, 'u32', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 4, 'day');
    out.day = {
      sunrise: column(blob, at, 0, 'f64', at.count),
      sunset: column(blob, at, 1, 'f64', at.count),
      nextSunrise: column(blob, at, 2, 'f64', at.count),
      vara: column(blob, at, 3, 'u16', at.count),
      calendar: column(blob, at, 4, 'u16', at.count),
      era: column(blob, at, 5, 'u16', at.count),
      year: column(blob, at, 6, 'i32', at.count),
      eraYear: column(blob, at, 7, 'i32', at.count),
      month: column(blob, at, 8, 'u8', at.count),
      dayOfMonth: column(blob, at, 9, 'u8', at.count),
      resolution: column(blob, at, 10, 'u8', at.count),
      computedMonth: column(blob, at, 11, 'u8', at.count),
      computedDay: column(blob, at, 12, 'u8', at.count),
      stateKind: column(blob, at, 13, 'u8', at.count),
      statePolarKind: column(blob, at, 14, 'u8', at.count),
      statePolarPolicy: column(blob, at, 15, 'u8', at.count),
      conventionKind: column(blob, at, 16, 'u8', at.count),
      conventionValue: column(blob, at, 17, 'f64', at.count),
      airPressureHpa: column(blob, at, 18, 'f64', at.count),
      airTemperatureC: column(blob, at, 19, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 5, 'tithi');
    out.tithi = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 6, 'nakshatra');
    out.nakshatra = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 7, 'yoga');
    out.yoga = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 8, 'karana');
    out.karana = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 9, 'panchaka');
    out.panchaka = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 10, 'moon_signs');
    out.moonSigns = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 11, 'sun_signs');
    out.sunSigns = {
      member: column(blob, at, 0, 'u16', at.count),
      wholeFrom: column(blob, at, 1, 'f64', at.count),
      wholeTo: column(blob, at, 2, 'f64', at.count),
      insideFrom: column(blob, at, 3, 'f64', at.count),
      insideTo: column(blob, at, 4, 'f64', at.count),
      sunrises: column(blob, at, 5, 'u8', at.count),
      endsGhati: column(blob, at, 6, 'u8', at.count),
      endsPala: column(blob, at, 7, 'u8', at.count),
      endsVipala: column(blob, at, 8, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 12, 'kaalas');
    out.kaalas = {
      kaala: column(blob, at, 0, 'u16', at.count),
      from: column(blob, at, 1, 'f64', at.count),
      to: column(blob, at, 2, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 13, 'choghadiya');
    out.choghadiya = {
      choghadiya: column(blob, at, 0, 'u16', at.count),
      lord: column(blob, at, 1, 'u16', at.count),
      from: column(blob, at, 2, 'f64', at.count),
      to: column(blob, at, 3, 'f64', at.count),
      daytime: column(blob, at, 4, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 14, 'horas');
    out.horas = {
      number: column(blob, at, 0, 'u8', at.count),
      lord: column(blob, at, 1, 'u16', at.count),
      start: column(blob, at, 2, 'f64', at.count),
      end: column(blob, at, 3, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 15, 'muhurtas');
    out.muhurtas = {
      from: column(blob, at, 0, 'f64', at.count),
      to: column(blob, at, 1, 'f64', at.count),
      daylight: column(blob, at, 2, 'u8', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 16, 'moon_events');
    out.moonEvents = {
      kind: column(blob, at, 0, 'u8', at.count),
      instant: column(blob, at, 1, 'f64', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 17, 'muhurta_yogas');
    out.muhurtaYogas = {
      yoga: column(blob, at, 0, 'u16', at.count),
      from: column(blob, at, 1, 'f64', at.count),
      to: column(blob, at, 2, 'f64', at.count),
      becauseKind: column(blob, at, 3, 'u8', at.count),
      becauseVara: column(blob, at, 4, 'u16', at.count),
      becauseTithi: column(blob, at, 5, 'u16', at.count),
      becauseNakshatra: column(blob, at, 6, 'u16', at.count),
      length: at.count,
    };
  }
  {
    const at = section(blob, 18, 'model');
    out.model = text(blob, at);
  }
  {
    const at = section(blob, 19, 'provenance_json');
    out.provenanceJson = text(blob, at);
  }
  {
    const at = section(blob, 20, 'content_hashes');
    out.contentHashes = text(blob, at);
  }
  {
    const at = section(blob, 21, 'muhurta');
    out.muhurta = text(blob, at);
  }
  {
    const at = section(blob, 22, 'festivals');
    out.festivals = text(blob, at);
  }
  {
    const at = section(blob, 23, 'years');
    out.years = text(blob, at);
  }
  {
    const at = section(blob, 24, 'eclipses');
    out.eclipses = text(blob, at);
  }
  {
    const at = section(blob, 25, 'nepal_sambat');
    out.nepalSambat = text(blob, at);
  }
  return out;
}

