// Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary
// crates; do not edit. ABI version 1, SDK 0.0.0.
// The description this file was rendered from ships as idl/api.json.

/**
 * The `instants` section of a Positions blob: one typed array per column, each a
 * view over the blob's bytes rather than a copy.
 *
 * The instants of the request, in order.
 */
export interface PositionsInstants {
  /**
   * A Julian day on the request's scale.
   */
  readonly jd: Float64Array;
  /** The number of rows every column holds. */
  readonly length: number;
}

/**
 * The `bodies` section of a Positions blob: one typed array per column, each a
 * view over the blob's bytes rather than a copy.
 *
 * The bodies of the request, in order.
 */
export interface PositionsBodies {
  /**
   * A body id.
   * The values are `Body` ids.
   */
  readonly body: Uint16Array;
  /** The number of rows every column holds. */
  readonly length: number;
}

/**
 * The `cells` section of a Positions blob: one typed array per column, each a
 * view over the blob's bytes rather than a copy.
 *
 * One row per cell, instants outermost; a cell whose status is not zero carries no value.
 */
export interface PositionsCells {
  /**
   * Longitude in degrees, 0 to 360.
   */
  readonly lon: Float64Array;
  /**
   * Latitude in degrees.
   */
  readonly lat: Float64Array;
  /**
   * Distance in the provider's unit.
   */
  readonly dist: Float64Array;
  /**
   * Longitude speed in degrees per day; zero when speeds were not asked for.
   */
  readonly lonSpeed: Float64Array;
  /**
   * Latitude speed in degrees per day.
   */
  readonly latSpeed: Float64Array;
  /**
   * Distance speed per day.
   */
  readonly distSpeed: Float64Array;
  /**
   * The cell's status code; zero is a value.
   */
  readonly status: Int32Array;
  /**
   * What computed the cell, packed as the port packs it.
   */
  readonly source: Uint32Array;
  /** The number of rows every column holds. */
  readonly length: number;
}

/**
 * A decoded Positions blob.
 *
 * Positions over a grid of instants and bodies, instants outermost: cell `i * body_count + j` is instant `i`, body `j`.
 */
export interface Positions {
  /**
   * The frame the values are in, packed as the port packs it.
   */
  readonly frameBits: number;
  /**
   * The number of instants.
   */
  readonly jdCount: number;
  /**
   * The number of bodies.
   */
  readonly bodyCount: number;
  /**
   * The time scale of the instants.
   * The value is a `TimeScale` id.
   */
  readonly scale: number;
  /**
   * The instants of the request, in order.
   */
  readonly instants: PositionsInstants;
  /**
   * The bodies of the request, in order.
   */
  readonly bodies: PositionsBodies;
  /**
   * One row per cell, instants outermost; a cell whose status is not zero carries no value.
   */
  readonly cells: PositionsCells;
  /**
   * UTF-8 JSON: the completion steps applied, in order, each `{"name", "implementation"}`.
   */
  readonly steps: string;
  /**
   * UTF-8 JSON: the provenance envelope of the result, canonical.
   */
  readonly provenance: string;
}

/**
 * Decodes a Positions blob. The columns are views over `bytes`, so the
 * buffer must outlive the result; a blob of another layout version or
 * another schema is a `TypeError`.
 */
export declare function decodePositions(bytes: Uint8Array): Positions;

/**
 * A decoded IntlRender blob.
 *
 * A rendered message.
 */
export interface IntlRender {
  /**
   * Non-zero when a fallback locale answered.
   */
  readonly isFallback: number;
  /**
   * Non-zero when a runtime override answered.
   */
  readonly isOverride: number;
  /**
   * The number of warnings.
   */
  readonly warningCount: number;
  /**
   * UTF-8: the plain text, markup stripped.
   */
  readonly text: string;
  /**
   * UTF-8: the locale whose message answered; empty when none had it.
   */
  readonly resolvedFrom: string;
  /**
   * UTF-8 JSON: an array of strings, one per problem met.
   */
  readonly warnings: string;
}

/**
 * Decodes a IntlRender blob. The columns are views over `bytes`, so the
 * buffer must outlive the result; a blob of another layout version or
 * another schema is a `TypeError`.
 */
export declare function decodeIntlRender(bytes: Uint8Array): IntlRender;

