// Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary
// crates; do not edit. ABI version 1, SDK 0.0.0.
// The description this file was rendered from ships as idl/api.json.

import type { Status, TimeScale, Body, Ayanamsha, Centre, Equinox, Coordinates, Calendar, Era, Resolution, ZoneKind, ZoneWarning, ZoneSource, ZoneEra, Dst, Chosen, Scale, DeltaTSource, Longitude, Latitude, Altitude } from './catalogue.js';

/**
 * A C observer: degrees and metres, validated into a `Place` on the
 * way in.
 */
export interface Observer {
  /**
   * Degrees, east positive.
   * @unit deg
   * @range [-180,180]
   * @example 85.3240
   */
  readonly longitudeDeg: Longitude;
  /**
   * Degrees, north positive.
   * @unit deg
   * @range [-90,90]
   * @example 27.7172
   */
  readonly latitudeDeg: Latitude;
  /**
   * Metres above sea level.
   * @unit m
   * @range [-500,12000]
   * @example 1400
   */
  readonly altitudeM: Altitude;
}

/**
 * A C position request over a grid.
 */
export interface PositionRequest {
  /**
   * The scale the instants are on.
   * @enum TimeScale
   * @example 0
   */
  readonly scale: TimeScale;
  /**
   * The frame the positions are wanted in, packed; `ts_frame_pack`
   * builds it from a frame's fields and `ts_frame_unpack` reads it back.
   * @example 0
   */
  readonly frameBits: number;
  /**
   * Whether speeds are wanted.
   * @example 1
   */
  readonly speeds: boolean;
  /**
   * The observer, which a topocentric frame needs.
   */
  readonly observer?: Observer;
  /**
   * The instants, on the request's scale.
   * @unit jd
   */
  readonly jds: Float64Array | readonly number[];
  /**
   * The bodies.
   * @enum Body
   */
  readonly bodies: readonly Body[];
}

/**
 * C columns the provider fills: caller-owned arrays of `capacity` cells,
 * instants outermost.
 */
export interface PositionColumns {
  /**
   * Written by the provider: `Frame::to_bits` of the values.
   */
  readonly frameBits: number;
  /**
   * Longitudes.
   * @unit deg
   */
  readonly lon: Float64Array;
  /**
   * Latitudes.
   * @unit deg
   */
  readonly lat: Float64Array;
  /**
   * Distances.
   */
  readonly dist: Float64Array;
  /**
   * Longitude speeds.
   * @unit deg/day
   */
  readonly lonSpeed: Float64Array;
  /**
   * Latitude speeds.
   * @unit deg/day
   */
  readonly latSpeed: Float64Array;
  /**
   * Distance speeds.
   */
  readonly distSpeed: Float64Array;
  /**
   * Per-cell status codes (`CellStatus::code`).
   */
  readonly status: Int32Array;
  /**
   * Per-cell sources (`Source::to_bits`).
   */
  readonly source: Uint32Array;
}

/**
 * A C obliquity.
 */
export interface Obliquity {
  /**
   * Mean obliquity, degrees.
   */
  readonly meanDeg: number;
  /**
   * True obliquity, degrees.
   */
  readonly trueDeg: number;
  /**
   * Nutation in longitude, degrees.
   */
  readonly nutationLonDeg: number;
  /**
   * Nutation in obliquity, degrees.
   */
  readonly nutationOblDeg: number;
}

/**
 * A C horizon-event request.
 */
export interface HorizonRequest {
  /**
   * `Body::id`.
   */
  readonly body: number;
  /**
   * `HorizonEventKind::id`.
   */
  readonly kind: number;
  /**
   * `DiscPoint::id`.
   */
  readonly disc: number;
  /**
   * `Refraction::id`.
   */
  readonly refraction: number;
  /**
   * The place.
   */
  readonly observer: Observer;
  /**
   * The search begins here, UT1.
   */
  readonly fromJdUt1: number;
  /**
   * The search ends this many days later.
   */
  readonly windowDays: number;
  /**
   * The altitude of the disc point at the event, degrees.
   */
  readonly altitudeDeg: number;
}

/**
 * A C crossings request.
 */
export interface CrossingRequest {
  /**
   * `Frame::to_bits`.
   */
  readonly frameBits: number;
  /**
   * `Quantity::kind_id`: 0 a longitude, 1 a speed, 2 a composite.
   */
  readonly quantityKind: number;
  /**
   * Whether `observer` is set.
   */
  readonly hasObserver: number;
  /**
   * `Body::id` of the first body.
   */
  readonly firstBody: number;
  /**
   * `Body::id` of the second body of a composite; else zero.
   */
  readonly secondBody: number;
  /**
   * The first body's coefficient in a composite.
   */
  readonly coefficientA: number;
  /**
   * The second body's coefficient in a composite.
   */
  readonly coefficientB: number;
  /**
   * The lattice's first line, degrees.
   */
  readonly originDeg: number;
  /**
   * The lattice's spacing, degrees; zero for a single target.
   */
  readonly stepDeg: number;
  /**
   * The window's start, UT1.
   */
  readonly fromJdUt1: number;
  /**
   * The window's end, UT1.
   */
  readonly toJdUt1: number;
  /**
   * How closely each instant is placed, days.
   */
  readonly toleranceDays: number;
  /**
   * The observer, read when `has_observer` is set.
   */
  readonly observer: Observer;
}

/**
 * A C crossing event.
 */
export interface CrossingEvent {
  /**
   * The instant, UT1.
   */
  readonly jdUt1: number;
  /**
   * The boundary reached, degrees.
   */
  readonly boundaryDeg: number;
  /**
   * `Direction::id`.
   */
  readonly direction: number;
}

/**
 * A C data hash.
 */
export interface DataHash {
  /**
   * The file name, NUL-terminated.
   */
  readonly file: string;
  /**
   * SHA-256 as hex, NUL-terminated.
   */
  readonly sha256: string;
  /**
   * The size in bytes.
   */
  readonly bytes: bigint;
}

/**
 * C capabilities; every pointer is owned by the provider and valid for
 * its lifetime.
 */
export interface Capabilities {
  /**
   * Whether speeds are returned.
   */
  readonly speeds: boolean;
  /**
   * Whether identical requests give identical bits.
   */
  readonly deterministic: boolean;
  /**
   * The tier plus one, zero for none (`Source::to_bits` encoding).
   */
  readonly tier: number;
  /**
   * `DistanceUnit::id`.
   */
  readonly distanceUnit: number;
  /**
   * `SpeedModel::id`.
   */
  readonly speedModel: number;
  /**
   * `Astronomy::id`.
   */
  readonly astronomy: number;
  /**
   * The name, NUL-terminated.
   */
  readonly name: string;
  /**
   * The version, NUL-terminated.
   */
  readonly version: string;
  /**
   * The data version, NUL-terminated.
   */
  readonly dataVersion: string;
  /**
   * Coverage start, UT1.
   */
  readonly jdMin: number;
  /**
   * Coverage end, UT1.
   */
  readonly jdMax: number;
  /**
   * The bodies as ids.
   * @enum Body
   */
  readonly bodies: readonly Body[];
  /**
   * `Frame::to_bits` of the native frame.
   */
  readonly nativeFrameBits: number;
  /**
   * `Overrides::bits`.
   */
  readonly overrides: number;
  /**
   * The ayanamshas the override knows, as catalogue ids.
   * @enum Ayanamsha
   */
  readonly ayanamshas: readonly Ayanamsha[];
  /**
   * The data hashes.
   */
  readonly hashes: Uint8Array | readonly number[];
}

/**
 * A SHA-256 as thirty-two bytes; every hash the SDK reports in
 * provenance is one, rendered as sixty-four hex digits in JSON.
 */
export interface Hash {
  /**
   * The digest.
   */
  readonly bytes: readonly [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
}

/**
 * How a context is built. Every field may be left at its zero value: a
 * null `profile` selects `ts_default_profile`, a null `settings_json`
 * patches nothing, a null `locale` renders in the base locale.
 */
export interface ContextOptions {
  /**
   * `TS_CONTEXT_*` flags, or zero.
   * @example 0
   */
  readonly flags: number;
  /**
   * The shipped profile's id (`parashari-classical`, `nepali-default`,
   * `kp-default`, `western-tropical-default`, `conformance-baseline`).
   * @example parashari-classical
   * @nullable
   */
  readonly profile?: string;
  /**
   * A JSON settings patch over the profile: an object whose groups and
   * knobs are the settings document's, every one optional; an unknown
   * knob or a value outside its type is `INVALID_ARG` naming it.
   * @nullable
   */
  readonly settingsJson?: string;
  /**
   * The locale every render resolves from (`ne-Deva-NP`).
   * @example en-Latn
   * @nullable
   */
  readonly locale?: string;
}

/**
 * The last error of a call on a context: the status, the detail, and the
 * message, field, hint and message key as strings the context lends
 * until its next call; an `OK` record has empty strings.
 */
export interface Error {
  /**
   * The status code.
   * @enum Status
   */
  readonly status: Status;
  /**
   * The provider's own code when the status is `PROVIDER`, else zero.
   */
  readonly providerCode: number;
  /**
   * The detail's name (`UNKNOWN_KEY`), or null.
   * @nullable
   */
  readonly detail?: string;
  /**
   * The English message naming the field and the range.
   */
  readonly message: string;
  /**
   * The field involved, or null.
   * @nullable
   */
  readonly field?: string;
  /**
   * A hint (`did you mean ...`), or null.
   * @nullable
   */
  readonly hint?: string;
  /**
   * The localisable message key, or null.
   * @nullable
   */
  readonly key?: string;
}

/**
 * A frame by name: what a position is seen from, in which equinox and
 * coordinates, in which zodiac, with which corrections applied.
 */
export interface Frame {
  /**
   * The ayanamsha, read only when `sidereal` is set; `0xFFFF` names
   * none, which is what a tropical frame carries.
   * @enum Ayanamsha
   * @example 0
   * @nullable
   */
  readonly ayanamsha?: Ayanamsha;
  /**
   * Where the position is seen from; a topocentric frame needs the
   * request's observer.
   * @enum Centre
   * @example 0
   */
  readonly centre: Centre;
  /**
   * Which equinox the coordinates refer to.
   * @enum Equinox
   * @example 0
   */
  readonly equinox: Equinox;
  /**
   * Ecliptic or equatorial.
   * @enum Coordinates
   * @example 0
   */
  readonly coordinates: Coordinates;
  /**
   * The sidereal zodiac, which uses `ayanamsha`; tropical otherwise.
   * @example 0
   */
  readonly sidereal: boolean;
  /**
   * Whether light time is applied.
   * @example 1
   */
  readonly lightTime: boolean;
  /**
   * Whether annual aberration is applied.
   * @example 1
   */
  readonly aberration: boolean;
  /**
   * Whether relativistic deflection is applied.
   * @example 0
   */
  readonly deflection: boolean;
  /**
   * Whether nutation is applied.
   * @example 1
   */
  readonly nutation: boolean;
}

/**
 * A date in a calendar. Years are astronomical (1 BCE is 0); the era view
 * is presentation only and is filled by the library, ignored on input.
 */
export interface CalendarDate {
  /**
   * The calendar's id.
   * @enum Calendar
   * @example 0
   */
  readonly calendar: Calendar;
  /**
   * The era the calendar attaches, `0xFFFF` for none; filled by the
   * library and ignored on input.
   * @enum Era
   * @example 7
   * @nullable
   */
  readonly era?: Era;
  /**
   * The astronomical year.
   * @example 2026
   */
  readonly year: number;
  /**
   * The year in the era, 1-based; meaningful when `era` is set.
   * @example 2026
   */
  readonly eraYear: number;
  /**
   * The month, 1-based; for the ISO week date, the week.
   * @range [1,53]
   * @example 9
   */
  readonly month: number;
  /**
   * The day, 1-based; for the ISO week date, the weekday 1 to 7.
   * @range [1,32]
   * @example 6
   */
  readonly day: number;
  /**
   * How the date was resolved.
   * @enum Resolution
   * @example 0
   */
  readonly resolution: Resolution;
  /**
   * The engine's month when the resolution is divergent, else zero.
   */
  readonly computedMonth: number;
  /**
   * The engine's day when the resolution is divergent, else zero.
   */
  readonly computedDay: number;
}

/**
 * A time of day, or none when the birth time is unknown.
 */
export interface CivilTime {
  /**
   * The hour.
   * @range [0,23]
   * @example 6
   */
  readonly hour: number;
  /**
   * The minute.
   * @range [0,59]
   * @example 15
   */
  readonly minute: number;
  /**
   * The second; `60` only for a leap second the table has.
   * @range [0,60]
   * @example 0
   */
  readonly second: number;
  /**
   * Whether the time is given; a date-only civil time has none, and the
   * context's unknown-time policy decides what to do.
   * @example 1
   */
  readonly hasTime: boolean;
  /**
   * Nanoseconds within the second.
   * @range [0,999999999]
   * @example 0
   */
  readonly nanos: number;
}

/**
 * A civil date and time in a calendar.
 */
export interface CivilDateTime {
  /**
   * The date.
   */
  readonly date: CalendarDate;
  /**
   * The time of day.
   */
  readonly time: CivilTime;
}

/**
 * A zone: an IANA name, a fixed offset, or local mean time at a longitude.
 */
export interface ZoneSpec {
  /**
   * Which field applies.
   * @enum ZoneKind
   * @example 0
   */
  readonly kind: ZoneKind;
  /**
   * The offset east of UTC in seconds, for a fixed offset.
   * @unit s
   * @range [-86400,86400]
   * @example 20700
   */
  readonly offsetSeconds: number;
  /**
   * The longitude east-positive in degrees, for local mean time.
   * @unit deg
   * @range [-180,180]
   * @example 85.3240
   */
  readonly longitudeDeg: Longitude;
  /**
   * The IANA name, for a database zone.
   * @example Asia/Kathmandu
   * @nullable
   */
  readonly zone?: string;
}

/**
 * What a resolution applied, enough to reproduce it after the zone
 * database changes.
 */
export interface ZoneResolution {
  /**
   * The offset east of UTC applied, seconds.
   * @unit s
   * @example 20700
   */
  readonly offsetSeconds: number;
  /**
   * How far a civil time inside a gap was shifted forward, seconds.
   * @unit s
   * @example 0
   */
  readonly dstShiftSeconds: number;
  /**
   * What the resolution wants the consumer to know.
   * @example 0
   */
  readonly warnings: readonly ZoneWarning[];
  /**
   * The instant on UTC.
   * @unit jd
   * @example 2446431.2743
   */
  readonly instantJdUtc: number;
  /**
   * The zone database version (`2026c`), `manual` or `lmt`; lent until
   * the next call on the context.
   */
  readonly tzdbVersion: string;
  /**
   * The zone's abbreviation at the instant (`NPT`), or null; lent until
   * the next call on the context.
   * @nullable
   */
  readonly abbreviation?: string;
  /**
   * Where the offset came from.
   * @enum ZoneSource
   * @example 0
   */
  readonly source: ZoneSource;
  /**
   * Which rules produced it.
   * @enum ZoneEra
   * @example 0
   */
  readonly era: ZoneEra;
  /**
   * What the daylight-saving policy did.
   * @enum Dst
   * @example 0
   */
  readonly dst: Dst;
  /**
   * Which occurrence an overlap resolved to; meaningful when `dst` is
   * an overlap.
   * @enum Chosen
   * @example 0
   */
  readonly chosen: Chosen;
  /**
   * Whether the time was given rather than supplied by a policy.
   */
  readonly timeKnown: boolean;
}

/**
 * A conversion between time scales with what it applied.
 */
export interface TimeConversion {
  /**
   * The scale converted from.
   * @enum Scale
   * @example 2
   */
  readonly from: Scale;
  /**
   * The scale converted to.
   * @enum Scale
   * @example 1
   */
  readonly to: Scale;
  /**
   * What produced the Delta T applied.
   * @enum DeltaTSource
   * @example 0
   */
  readonly deltaTSource: DeltaTSource;
  /**
   * Whether UTC before 1972 was read as UT1.
   */
  readonly prolepticUtc: boolean;
  /**
   * Whether `uncertainty_seconds` is meaningful.
   */
  readonly hasUncertainty: boolean;
  /**
   * The instant on the target scale.
   * @unit jd
   * @example 2451545.0007
   */
  readonly jd: number;
  /**
   * The Delta T applied, seconds; zero for a conversion that needs none.
   * @unit s
   * @example 63.83
   */
  readonly deltaTSeconds: number;
  /**
   * Delta T's one-sigma uncertainty, seconds, when `has_uncertainty`.
   * @unit s
   * @example 0.0
   */
  readonly uncertaintySeconds: number;
  /**
   * UT1 less UTC applied, seconds: zero until a provider supplies the
   * IERS bulletins.
   * @unit s
   * @example 0.0
   */
  readonly dut1Seconds: number;
  /**
   * The Delta T model's key (`TABLE_THEN_MODEL`); lent until the next
   * call on the context.
   */
  readonly deltaTModel: string;
}

/**
 * Delta T at an instant with what produced it.
 */
export interface DeltaT {
  /**
   * What produced it.
   * @enum DeltaTSource
   * @example 0
   */
  readonly source: DeltaTSource;
  /**
   * Whether `uncertainty_seconds` is meaningful.
   */
  readonly hasUncertainty: boolean;
  /**
   * TT less UT1, seconds.
   * @unit s
   * @example 63.83
   */
  readonly seconds: number;
  /**
   * The one-sigma uncertainty, seconds, when `has_uncertainty`.
   * @unit s
   * @example 0.0
   */
  readonly uncertaintySeconds: number;
  /**
   * The model's key; lent until the next call on the context.
   */
  readonly model: string;
}

/**
 * What a loaded pack or bundle carried.
 */
export interface IntlLoaded {
  /**
   * The entries the file carried.
   */
  readonly entries: number;
  /**
   * The entries that replaced ones already loaded.
   */
  readonly replaced: number;
  /**
   * The locale; lent until the next call on the context.
   */
  readonly locale: string;
  /**
   * The file's SHA-256 as sixty-four hex digits; lent until the next
   * call on the context.
   */
  readonly sha256: string;
}

/**
 * A failed call. `status` is the stable code's name and `code` its
 * number, the same in every binding; `field`, `hint` and `messageKey`
 * are present when the library named them.
 */
export declare class TeistroError extends Error {
  /** The status. */
  readonly status: Status;
  /** The stable numeric code. */
  readonly code: number;
  /** What, more precisely, went wrong. */
  readonly detail: string | null;
  /** The field involved. */
  readonly field: string | null;
  /** A suggestion (`did you mean ...`). */
  readonly hint: string | null;
  /** The localisable message key. */
  readonly messageKey: string | null;
  /** The provider's own code when the status is `PROVIDER`. */
  readonly providerCode: number;
}

