//! The C header: the contract every other binding is generated against
//! and the one C, C++, Java (FFM), Swift and Kotlin consume directly.
//! Every type, member and function carries its documentation; every
//! struct's 64-bit size is asserted so a compiler that lays it out
//! differently refuses the header instead of corrupting memory.

use std::fmt::Write;

use crate::emit::{DocStyle, block_comment, field_doc_with};
use crate::layout::{Target, struct_layout};
use crate::model::{Api, FieldDef, FunctionDef, Role, TypeRef};
use crate::names::{c_constant_name, c_enum_member, c_type_name};
use crate::rules::has_handshake;

/// Renders the header.
#[must_use]
pub fn render(api: &Api) -> String {
    let mut out = String::new();
    let guard = format!(
        "{}H",
        api.prefix.to_ascii_uppercase().replace('_', "") + "_TEISTRO_"
    );
    let _ = writeln!(
        out,
        "/* Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary crates\n * ({}); do not edit. ABI version {}, SDK {}.\n * Every function is documented where it is declared; the description this\n * header was rendered from ships as idl/api.json. */\n#ifndef {guard}\n#define {guard}\n\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n\n#ifdef __cplusplus\nextern \"C\" {{\n#endif\n",
        api.sources.join(", "),
        api.abi_version,
        api.sdk_version
    );
    render_constants(&mut out, api);
    render_enums(&mut out, api);
    for o in &api.opaques {
        let name = c_type_name(&api.prefix, &o.name);
        let _ = writeln!(
            out,
            "{}typedef struct {name} {name};\n",
            block_comment(&o.doc, "")
        );
    }
    // Every struct is forward-declared before the callbacks, whose struct
    // parameters are pointers, and defined afterwards in source order,
    // which defines every nested struct before the struct that holds it.
    for s in &api.structs {
        let name = c_type_name(&api.prefix, &s.name);
        let _ = writeln!(out, "typedef struct {name} {name};");
    }
    let _ = writeln!(out);
    render_callbacks(&mut out, api);
    render_structs(&mut out, api);
    render_functions(&mut out, api);
    render_layout_checks(&mut out, api);
    let _ = writeln!(
        out,
        "#ifdef __cplusplus\n}}\n#endif\n\n#endif /* {guard} */"
    );
    out
}

fn render_constants(out: &mut String, api: &Api) {
    for c in &api.constants {
        let _ = writeln!(
            out,
            "{}#define {} (({}){})\n",
            block_comment(&c.doc, ""),
            c_constant_name(&api.prefix, &c.name),
            c.ty.c_name(),
            c.value
        );
    }
}

fn render_enums(out: &mut String, api: &Api) {
    for e in &api.enums {
        let name = c_type_name(&api.prefix, &e.name);
        let _ = writeln!(out, "{}typedef enum {name} {{", block_comment(&e.doc, ""));
        for v in &e.values {
            let doc = if v.deprecated {
                format!("{}\nDeprecated.", v.doc)
            } else {
                v.doc.clone()
            };
            let _ = writeln!(
                out,
                "{}    {} = {},",
                block_comment(&doc, "    "),
                c_enum_member(&api.prefix, &e.name, &v.name, v.key.as_deref()),
                v.value
            );
        }
        if e.kind.is_some() {
            let _ = writeln!(
                out,
                "    /** A member this build does not know: from a newer library or a runtime registration. */\n    {} = -1,",
                c_enum_member(&api.prefix, &e.name, "Unknown", None)
            );
        }
        let _ = writeln!(out, "}} {name};\n");
    }
}

fn render_callbacks(out: &mut String, api: &Api) {
    for c in &api.callbacks {
        let params: Vec<String> = c
            .params
            .iter()
            .map(|p| format!("{} {}", c_type(api, &p.ty), p.name))
            .collect();
        let _ = writeln!(
            out,
            "{}typedef {} (*{})({});\n",
            block_comment(&c.doc, ""),
            c_type(api, &c.returns),
            c_type_name(&api.prefix, &c.name),
            params.join(", ")
        );
    }
}

fn render_structs(out: &mut String, api: &Api) {
    for s in &api.structs {
        let name = c_type_name(&api.prefix, &s.name);
        let mut doc = s.doc.clone();
        if has_handshake(s) {
            doc.push_str("\nSet `struct_size` to `sizeof` before passing it; the library refuses a size it does not know.");
        }
        let _ = writeln!(out, "{}struct {name} {{", block_comment(&doc, ""));
        for f in &s.fields {
            let (ty, suffix) = match &f.ty {
                TypeRef::Array { of, len } => (c_type(api, of), format!("[{len}]")),
                other => (c_type(api, other), String::new()),
            };
            let linked = f
                .meta
                .enum_name
                .as_deref()
                .map(|e| c_type_name(&api.prefix, e));
            let doc = format!(
                "{}{}",
                field_doc_with(f, DocStyle::Prose, linked.as_deref()),
                c_note(api, f)
            );
            let _ = writeln!(
                out,
                "{}    {ty} {}{suffix};",
                block_comment(&doc, "    "),
                f.name
            );
        }
        let _ = writeln!(out, "}};\n");
    }
}

/// One function's C declaration, without its documentation: what the
/// header states and what the reference quotes, so the two cannot drift.
#[must_use]
pub fn c_signature(api: &Api, f: &FunctionDef) -> String {
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            let qualifier = if p.role == Role::VtableIn || p.role == Role::UserData {
                "/* nullable */ "
            } else {
                ""
            };
            format!("{qualifier}{} {}", c_type(api, &p.ty), p.name)
        })
        .collect();
    let params = if params.is_empty() {
        String::from("void")
    } else {
        params.join(", ")
    };
    let returns = f
        .returns
        .as_ref()
        .map_or_else(|| String::from("void"), |t| c_type(api, t));
    format!("{returns} {}({params});", f.name)
}

fn render_functions(out: &mut String, api: &Api) {
    for f in &api.functions {
        let mut doc = f.doc.clone();
        if let Some(blob) = &f.meta.blob {
            let _ = write!(
                doc,
                "\nThe blob follows the `{blob}` schema of idl/api.json."
            );
        }
        if let Some(safety) = &f.safety {
            let _ = write!(doc, "\nSafety: {safety}");
        }
        let _ = writeln!(out, "{}{}\n", block_comment(&doc, ""), c_signature(api, f));
    }
}

/// `_Static_assert`s of every struct's size on 64-bit targets, so a
/// compiler with other alignment rules refuses the header.
fn render_layout_checks(out: &mut String, api: &Api) {
    let _ = writeln!(
        out,
        "#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L && UINTPTR_MAX == 0xffffffffffffffffu\n/* The sizes the library was built with; a mismatch means a different\n * alignment model, and the header must not be used. */"
    );
    for s in &api.structs {
        if let Ok(layout) = struct_layout(api, s, Target::LP64) {
            let _ = writeln!(
                out,
                "_Static_assert(sizeof({0}) == {1}, \"{0} is {1} bytes on 64-bit targets\");",
                c_type_name(&api.prefix, &s.name),
                layout.size
            );
        }
    }
    let _ = writeln!(out, "#endif\n");
}

/// What C needs told that the type does not say: a flag's values, a bit
/// set's members, an array's count, an optional field's flag.
fn c_note(api: &Api, f: &FieldDef) -> String {
    let mut note = String::new();
    if f.meta.flag {
        note.push_str(" Non-zero for true, zero for false.");
    }
    if let Some(name) = &f.meta.bitset {
        let _ = write!(
            note,
            " A set of `{}`: bit `n` for the member whose value is `n`.",
            c_type_name(&api.prefix, name)
        );
    }
    if let Some(count) = &f.meta.len {
        let _ = write!(note, " Points at `{count}` elements.");
    }
    if let Some(flag) = &f.meta.present_if {
        let _ = write!(note, " Read only when `{flag}` is non-zero.");
    }
    note
}

/// The C spelling of a boundary type.
#[must_use]
pub fn c_type(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { scalar } => scalar.c_name().to_string(),
        TypeRef::Enum { name }
        | TypeRef::Struct { name }
        | TypeRef::Opaque { name }
        | TypeRef::Callback { name } => c_type_name(&api.prefix, name),
        TypeRef::Pointer { to, mutable } => {
            let inner = c_type(api, to);
            if *mutable {
                format!("{inner} *")
            } else {
                format!("const {inner} *")
            }
        }
        TypeRef::Array { of, len } => format!("{}[{len}]", c_type(api, of)),
        TypeRef::Void => String::from("void"),
        TypeRef::Char => String::from("char"),
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::too_many_lines, reason = "one description built by hand")]

    use super::*;
    use crate::model::{
        ConstantDef, EnumDef, EnumValue, FieldDef, FunctionDef, Meta, OpaqueDef, ParamDef, Scalar,
        StructDef, StructRole,
    };

    #[test]
    fn the_header_declares_every_kind_of_item() {
        let api = Api {
            schema: crate::model::SCHEMA.into(),
            abi_version: 1,
            sdk_version: "0.0.0".into(),
            prefix: "ts_".into(),
            sources: vec!["crates/ffi/src/lib.rs".into()],
            constants: vec![ConstantDef {
                name: "TS_ABI_VERSION".into(),
                doc: "The ABI version.".into(),
                ty: Scalar::U32,
                value: 1,
                source: String::new(),
            }],
            enums: vec![EnumDef {
                name: "Graha".into(),
                doc: "The grahas.".into(),
                repr: Scalar::U16,
                kind: Some("graha".into()),
                values: vec![EnumValue {
                    name: "Sun".into(),
                    value: 0,
                    doc: "The Sun".into(),
                    key: Some("SUN".into()),
                    deprecated: false,
                }],
                source: String::new(),
            }],
            opaques: vec![OpaqueDef {
                name: "TsContext".into(),
                doc: "A context.".into(),
                source: String::new(),
            }],
            callbacks: vec![],
            structs: vec![StructDef {
                name: "TsOptions".into(),
                doc: "Options.".into(),
                role: StructRole::Object,
                fields: vec![
                    FieldDef {
                        name: "struct_size".into(),
                        ty: TypeRef::scalar(Scalar::U32),
                        doc: "The size.".into(),
                        meta: Meta::default(),
                    },
                    FieldDef {
                        name: "reserved".into(),
                        ty: TypeRef::Array {
                            of: Box::new(TypeRef::scalar(Scalar::U8)),
                            len: 4,
                        },
                        doc: "Zero.".into(),
                        meta: Meta::default(),
                    },
                    FieldDef {
                        name: "profile".into(),
                        ty: TypeRef::pointer(TypeRef::Char, false),
                        doc: "The profile id.".into(),
                        meta: Meta {
                            nullable: true,
                            ..Meta::default()
                        },
                    },
                ],
                source: String::new(),
            }],
            functions: vec![FunctionDef {
                name: "ts_context_new".into(),
                doc: "Creates a context.".into(),
                safety: Some("Pointers must be valid.".into()),
                params: vec![
                    ParamDef {
                        name: "options".into(),
                        ty: TypeRef::pointer(
                            TypeRef::Struct {
                                name: "TsOptions".into(),
                            },
                            false,
                        ),
                        role: Role::StructIn,
                        meta: Meta::default(),
                    },
                    ParamDef {
                        name: "out_context".into(),
                        ty: TypeRef::pointer(
                            TypeRef::pointer(
                                TypeRef::Opaque {
                                    name: "TsContext".into(),
                                },
                                true,
                            ),
                            true,
                        ),
                        role: Role::HandleOut,
                        meta: Meta::default(),
                    },
                ],
                returns: Some(TypeRef::scalar(Scalar::I32)),
                meta: Meta::default(),
                source: String::new(),
            }],
            blobs: vec![],
        };
        let header = render(&api);
        for expected in [
            "#define TS_ABI_VERSION ((uint32_t)1)",
            "typedef enum ts_graha {",
            "    TS_GRAHA_SUN = 0,",
            "    TS_GRAHA_UNKNOWN = -1,",
            "typedef struct ts_context ts_context;",
            "struct ts_options {",
            "    uint32_t struct_size;",
            "    uint8_t reserved[4];",
            "    const char * profile;",
            "int32_t ts_context_new(const ts_options * options, ts_context * * out_context);",
            " * Safety: Pointers must be valid.",
            "_Static_assert(sizeof(ts_options) == 16, \"ts_options is 16 bytes on 64-bit targets\");",
            "#endif /* TS_TEISTRO_H */",
        ] {
            assert!(
                header.contains(expected),
                "missing {expected:?} in\n{header}"
            );
        }
    }
}
