//! The Dart binding's mechanical layer, rendered from the description:
//! the `dart:ffi` declarations that match the C header name for name, the
//! catalogue as Dart enums, typed value classes over the boundary's
//! structs, the context as a class with a native finaliser, and the
//! result-blob decoders as typed-data views.
//!
//! The same roles drive it as drive the C header and the Node addon, so
//! the three cannot disagree: a flag is a `bool`, a bit set a `Set`, an
//! array of an enum's ids the members themselves, an optional value
//! nullable, and the counts and presence flags a C struct carries never
//! reach the surface.
//!
//! Three files, so a package's parts are found where a Dart reader looks:
//! `catalogue.dart` (the enums), `ffi.dart` (the declarations, the value
//! classes and the context) and `blob.dart` (the decoders).

use std::fmt::Write;

use crate::emit::{DocStyle, field_doc_with, line_comment};
use crate::model::{
    Api, BlobSchema, EnumDef, FieldDef, FunctionDef, OpaqueDef, ParamDef, Role, Scalar,
    SectionKind, SectionSchema, StructDef, StructRole, TypeRef,
};
use crate::names::{binding_type_name, camel, kebab, method_name, pascal, snake};
use crate::rules::{
    FieldRole, Handed, constant_key, constants, constructor, destructor, field_roles,
    has_handshake, methods, pointee_struct, results, returned_scalar, returns_status, status_enum,
};

/// Dart's reserved words, which no identifier may be. The generator
/// renames rather than emitting a file that will not parse (ADR-0007's
/// second Dart defect: Diplomat emitted an enum member called `true`).
const RESERVED: [&str; 24] = [
    "true", "false", "null", "default", "new", "in", "is", "as", "do", "if", "for", "switch",
    "this", "super", "var", "final", "const", "class", "enum", "void", "return", "with", "extends",
    "assert",
];

/// A Dart identifier for a member or a field.
fn identifier(name: &str) -> String {
    let lower = camel(&snake(name));
    if RESERVED.contains(&lower.as_str()) {
        format!("{lower}Value")
    } else {
        lower
    }
}

fn doc(text: &str, indent: &str) -> String {
    line_comment(text, indent, "/// ")
}

fn preamble(api: &Api, ignores: &str) -> String {
    format!(
        "// Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary\n// crates; do not edit. ABI version {}, SDK {}.\n//\n// The description this file was rendered from ships as idl/api.json.\n//\n// The generator lays this file out, so `dart format .` leaves it alone\n// and `cargo xtask check-ffi` can regenerate it on a machine with no\n// Dart toolchain and still compare it byte for byte.\n// dart format off\n{ignores}\n",
        api.abi_version, api.sdk_version
    )
}

// ── The catalogue ──────────────────────────────────────────────────────────

/// Renders `catalogue.dart`: every enum, with the id the C boundary
/// carries and the key every pack, fixture and serialised result uses.
#[must_use]
pub fn catalogue(api: &Api) -> String {
    let mut out = preamble(api, "\n// ignore_for_file: constant_identifier_names\n");
    let _ = writeln!(
        out,
        "/// The ABI these declarations were generated for; the library must agree.\nconst int generatedAbiVersion = {};\n",
        api.abi_version
    );
    for c in constants(api) {
        let _ = writeln!(
            out,
            "{}const int {} = {};\n",
            doc(&c.doc, ""),
            identifier(&camel(&snake(constant_key(c)))),
            c.value
        );
    }
    for e in &api.enums {
        render_enum(&mut out, e);
    }
    out
}

fn render_enum(out: &mut String, e: &EnumDef) {
    let name = binding_type_name(&e.name);
    let catalogued = e.kind.is_some();
    let _ = writeln!(out, "{}enum {name} {{", doc(&e.doc, ""));
    let last = e.values.len().saturating_sub(1);
    for (i, v) in e.values.iter().enumerate() {
        // The same string the TypeScript surface uses, so a member is
        // spelled once across the bindings: its catalogue key when it has
        // one, its variant in kebab case otherwise (`invalid-arg`).
        let key = v.key.clone().unwrap_or_else(|| kebab(&v.name));
        let end = if i == last && !catalogued { ";" } else { "," };
        let doc_text = if v.deprecated {
            format!("{}\n\nDeprecated.", v.doc)
        } else {
            v.doc.clone()
        };
        let _ = writeln!(
            out,
            "{}  {}({}, '{key}'){end}",
            doc(&doc_text, "  "),
            identifier(&v.name),
            v.value
        );
    }
    if catalogued {
        let _ = writeln!(
            out,
            "\n  /// A member this build does not know: from a newer library, or\n  /// registered at run time.\n  unknown(-1, 'UNKNOWN');"
        );
    }
    let kind = e.kind.as_deref().unwrap_or_default();
    let full_key = if catalogued {
        format!(
            "\n\n  /// The full key, as every pack and fixture spells it.\n  String get fullKey => '{kind}.$key';"
        )
    } else {
        String::new()
    };
    let by_id = if catalogued {
        format!(
            "\n\n  /// The member with an id; one this build does not know is\n  /// [unknown], so a `switch` over the result stays exhaustive.\n  static {name} byId(int id) =>\n      values.firstWhere((member) => member.id == id, orElse: () => {name}.unknown);"
        )
    } else {
        format!(
            "\n\n  /// The member with an id.\n  ///\n  /// Throws [ArgumentError] for an id this build does not know, because\n  /// a value outside a closed set is a fault, not a state.\n  static {name} byId(int id) => values.firstWhere(\n        (member) => member.id == id,\n        orElse: () => throw ArgumentError.value(id, 'id', 'not a {name}'),\n      );"
        )
    };
    let _ = writeln!(
        out,
        "\n  const {name}(this.id, this.key);\n\n  /// The id the C boundary carries.\n  final int id;\n\n  /// The key every pack, fixture and serialised result spells it with.\n  final String key;{full_key}{by_id}\n\n  /// The member with a key, or `null` for one this build does not know.\n  static {name}? byKey(String key) {{\n    final wanted = key.contains('.') ? key.split('.').last : key;\n    for (final member in values) {{\n      if (member.key == wanted) return member;\n    }}\n    return null;\n  }}\n}}\n"
    );
}

// ── Types ──────────────────────────────────────────────────────────────────

/// The `dart:ffi` native type of a scalar.
fn native_scalar(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::U8 => "ffi.Uint8",
        Scalar::U16 => "ffi.Uint16",
        Scalar::U32 => "ffi.Uint32",
        Scalar::U64 => "ffi.Uint64",
        Scalar::I8 => "ffi.Int8",
        Scalar::I16 => "ffi.Int16",
        Scalar::I32 => "ffi.Int32",
        Scalar::I64 => "ffi.Int64",
        Scalar::F32 => "ffi.Float",
        Scalar::F64 => "ffi.Double",
        Scalar::Usize => "ffi.Size",
        Scalar::Isize => "ffi.IntPtr",
        Scalar::Bool => "ffi.Bool",
    }
}

/// The Dart type a scalar becomes.
fn dart_scalar(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::F32 | Scalar::F64 => "double",
        Scalar::Bool => "bool",
        _ => "int",
    }
}

/// The C struct's Dart name: `ts_calendar_date` is `TsCalendarDateStruct`,
/// so the value class a consumer uses can be `CalendarDate`.
fn struct_name(rust_name: &str) -> String {
    format!("{}Struct", binding_type_name(rust_name))
}

/// The `dart:ffi` type of a boundary type.
fn native_type(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { scalar } => native_scalar(*scalar).to_string(),
        TypeRef::Enum { name } => api
            .enum_named(name)
            .map_or("ffi.Int32", |e| native_scalar(e.repr))
            .to_string(),
        TypeRef::Struct { name } => struct_name(name),
        TypeRef::Opaque { name } => binding_type_name(name),
        TypeRef::Callback { name } => {
            format!(
                "ffi.Pointer<ffi.NativeFunction<{}Native>>",
                binding_type_name(name)
            )
        }
        TypeRef::Pointer { to, .. } => format!("ffi.Pointer<{}>", native_type(api, to)),
        TypeRef::Array { of, len } => format!("ffi.Array<{}>", {
            let _ = len;
            native_type(api, of)
        }),
        TypeRef::Void => String::from("ffi.Void"),
        TypeRef::Char => String::from("ffi.Char"),
    }
}

/// The Dart type a native type maps to in a looked-up function.
fn dart_type(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { scalar } => dart_scalar(*scalar).to_string(),
        TypeRef::Enum { .. } => String::from("int"),
        TypeRef::Void => String::from("void"),
        other => native_type(api, other),
    }
}

// ── The declarations ───────────────────────────────────────────────────────

/// Renders `ffi.dart`: the structs, the looked-up functions, the value
/// classes and the context.
#[must_use]
pub fn declarations(api: &Api) -> String {
    let mut out = preamble(
        api,
        "\n// ignore_for_file: camel_case_types, non_constant_identifier_names\n// ignore_for_file: constant_identifier_names, unused_field\n\nimport 'dart:ffi' as ffi;\nimport 'dart:typed_data';\n\nimport 'package:ffi/ffi.dart' as pkg_ffi;\n\nimport 'catalogue.dart';\n",
    );
    for o in &api.opaques {
        let _ = writeln!(
            out,
            "{}final class {} extends ffi.Opaque {{}}\n",
            doc(&o.doc, ""),
            binding_type_name(&o.name)
        );
    }
    for c in &api.callbacks {
        render_callback_typedefs(&mut out, api, c);
    }
    for s in &api.structs {
        render_struct(&mut out, api, s);
    }
    render_library(&mut out, api);
    render_exception(&mut out, api);
    for s in api.structs.iter().filter(|s| shown(api, s)) {
        render_value_class(&mut out, api, s);
    }
    for o in &api.opaques {
        render_context(&mut out, api, o);
    }
    render_free_functions(&mut out, api);
    out
}

fn render_callback_typedefs(out: &mut String, api: &Api, c: &crate::model::CallbackDef) {
    let name = binding_type_name(&c.name);
    let natives: Vec<String> = c.params.iter().map(|p| native_type(api, &p.ty)).collect();
    let darts: Vec<String> = c.params.iter().map(|p| dart_type(api, &p.ty)).collect();
    let _ = writeln!(
        out,
        "{}typedef {name}Native = {} Function({});\ntypedef {name}Dart = {} Function({});\n",
        doc(&c.doc, ""),
        native_type(api, &c.returns),
        natives.join(", "),
        dart_type(api, &c.returns),
        darts.join(", ")
    );
}

fn render_struct(out: &mut String, api: &Api, s: &StructDef) {
    let name = struct_name(&s.name);
    let _ = writeln!(
        out,
        "{}final class {name} extends ffi.Struct {{",
        doc(&s.doc, "")
    );
    for f in &s.fields {
        let text = doc(
            &field_doc_with(f, DocStyle::Prose, f.meta.enum_name.as_deref()),
            "  ",
        );
        match &f.ty {
            TypeRef::Scalar { .. } | TypeRef::Enum { .. } => {
                let _ = writeln!(
                    out,
                    "{text}  @{}()\n  external {} {};\n",
                    native_type(api, &f.ty),
                    dart_type(api, &f.ty),
                    identifier(&f.name)
                );
            }
            TypeRef::Array { of, len } => {
                let _ = writeln!(
                    out,
                    "{text}  @ffi.Array({len})\n  external ffi.Array<{}> {};\n",
                    native_type(api, of),
                    identifier(&f.name)
                );
            }
            other => {
                let _ = writeln!(
                    out,
                    "{text}  external {} {};\n",
                    native_type(api, other),
                    identifier(&f.name)
                );
            }
        }
    }
    let _ = writeln!(out, "}}\n");
}

fn typedef_names(f: &FunctionDef) -> (String, String) {
    let base = pascal(&f.name);
    (format!("{base}Native"), format!("{base}Dart"))
}

fn render_library(out: &mut String, api: &Api) {
    for f in &api.functions {
        let (native_name, dart_name) = typedef_names(f);
        let natives: Vec<String> = f.params.iter().map(|p| native_type(api, &p.ty)).collect();
        let darts: Vec<String> = f.params.iter().map(|p| dart_type(api, &p.ty)).collect();
        let returns_native = f
            .returns
            .as_ref()
            .map_or_else(|| String::from("ffi.Void"), |t| native_type(api, t));
        let returns_dart = f
            .returns
            .as_ref()
            .map_or_else(|| String::from("void"), |t| dart_type(api, t));
        let _ = writeln!(
            out,
            "typedef {native_name} = {returns_native} Function({});\ntypedef {dart_name} = {returns_dart} Function({});",
            natives.join(", "),
            darts.join(", ")
        );
    }
    let _ = writeln!(
        out,
        "\n/// The C surface, every entry point looked up once when the library\n/// opens rather than on each call.\nfinal class TeistroLibrary {{\n  /// Looks up every entry point in an open library.\n  TeistroLibrary(this.library)"
    );
    let last = api.functions.len().saturating_sub(1);
    for (i, f) in api.functions.iter().enumerate() {
        let (native_name, dart_name) = typedef_names(f);
        let end = if i == last { ";" } else { "," };
        let lead = if i == 0 { ":" } else { " " };
        let _ = writeln!(
            out,
            "      {lead} {} = library.lookupFunction<{native_name}, {dart_name}>('{}'){end}",
            f.name, f.name
        );
    }
    let _ = writeln!(
        out,
        "\n  /// The open library, for a finaliser that needs its symbols.\n  final ffi.DynamicLibrary library;\n"
    );
    for f in &api.functions {
        let (_, dart_name) = typedef_names(f);
        let _ = writeln!(
            out,
            "{}  final {dart_name} {};\n",
            doc(&f.doc, "  "),
            f.name
        );
    }
    let _ = writeln!(out, "}}\n");
}

fn render_exception(out: &mut String, api: &Api) {
    let Some(status) = status_enum(api) else {
        return;
    };
    let name = binding_type_name(&status.name);
    let _ = writeln!(
        out,
        "/// A failed call: the status and its stable code, the same in every\n/// binding, with the message, field and hint the library gave.\nfinal class TeistroException implements Exception {{\n  /// A failure as the library described it.\n  const TeistroException(\n    this.status,\n    this.message, {{\n    this.detail,\n    this.field,\n    this.hint,\n    this.messageKey,\n    this.providerCode = 0,\n  }});\n\n  /// What to branch on.\n  final {name} status;\n\n  /// The library's own sentence.\n  final String message;\n\n  /// What, more precisely, went wrong.\n  final String? detail;\n\n  /// The field involved.\n  final String? field;\n\n  /// A suggestion (`did you mean ...`).\n  final String? hint;\n\n  /// The localisable message key.\n  final String? messageKey;\n\n  /// The provider's own code when the status is `provider`.\n  final int providerCode;\n\n  /// The stable numeric code.\n  int get code => status.id;\n\n  @override\n  String toString() {{\n    final where = field == null ? '' : ' (field `$field`)';\n    final why = hint == null ? '' : '; $hint';\n    return 'TeistroException [${{status.key}}]: $message$where$why';\n  }}\n}}\n"
    );
}

/// A struct a binding shows as a value class: a plain object or a set of
/// caller-allocated columns, with at least one field of its own. A struct
/// holding an array of structs is described rather than built, because
/// every element's own buffers would have to outlive the call, which is a
/// port adapter's business and not a value class's.
fn shown(api: &Api, s: &StructDef) -> bool {
    matches!(s.role, StructRole::Object | StructRole::Columns)
        && s.fields
            .iter()
            .any(|f| f.name != "struct_size" && !f.name.starts_with("reserved"))
        && !s.fields.iter().zip(field_roles(api, s)).any(|(f, role)| {
            matches!(role, FieldRole::Array { .. })
                && matches!(f.ty.pointee(), Some(TypeRef::Struct { .. }))
        })
}

/// The Dart type of a field, from its role.
fn value_type(api: &Api, field: &FieldDef, role: &FieldRole) -> String {
    let base = match role {
        FieldRole::Flag => String::from("bool"),
        FieldRole::BitSet { enum_name } => format!("Set<{}>", binding_type_name(enum_name)),
        FieldRole::Array { .. } | FieldRole::Column => match &field.meta.enum_name {
            Some(name) => format!("List<{}>", binding_type_name(name)),
            None => format!("List<{}>", dart_scalar(element(field))),
        },
        FieldRole::FixedBytes { .. } => String::from("Uint8List"),
        FieldRole::Text => String::from("String"),
        FieldRole::Nested { name } => binding_type_name(name),
        FieldRole::Optional { .. } => match &field.ty {
            TypeRef::Struct { name } => binding_type_name(name),
            other => plain_value(api, field, other),
        },
        _ => plain_value(api, field, &field.ty),
    };
    if field.meta.nullable || matches!(role, FieldRole::Optional { .. }) {
        format!("{base}?")
    } else {
        base
    }
}

fn plain_value(api: &Api, field: &FieldDef, ty: &TypeRef) -> String {
    if let Some(name) = &field.meta.enum_name {
        return binding_type_name(name);
    }
    match ty {
        TypeRef::Scalar { scalar } => dart_scalar(*scalar).to_string(),
        TypeRef::Enum { name } => binding_type_name(name),
        TypeRef::Pointer { to, .. } if matches!(**to, TypeRef::Char) => String::from("String"),
        _ => {
            let _ = api;
            String::from("int")
        }
    }
}

fn element(field: &FieldDef) -> Scalar {
    field
        .ty
        .pointee()
        .and_then(TypeRef::as_scalar)
        .unwrap_or(Scalar::U8)
}

fn render_value_class(out: &mut String, api: &Api, s: &StructDef) {
    let name = binding_type_name(&s.name);
    let roles = field_roles(api, s);
    let shown_fields: Vec<(&FieldDef, &FieldRole)> = s
        .fields
        .iter()
        .zip(&roles)
        .filter(|(_, role)| role.is_shown())
        .collect();
    let params: Vec<String> = shown_fields
        .iter()
        .map(|(f, role)| {
            let optional = f.meta.nullable || matches!(role, FieldRole::Optional { .. });
            if optional {
                format!("this.{}", identifier(&f.name))
            } else {
                format!("required this.{}", identifier(&f.name))
            }
        })
        .collect();
    let _ = writeln!(
        out,
        "{}final class {name} {{\n  /// A {name} with every field named.\n  const {name}({{{}}});\n",
        doc(&s.doc, ""),
        params.join(", ")
    );
    for (f, role) in &shown_fields {
        let _ = writeln!(
            out,
            "{}  final {} {};\n",
            doc(
                &field_doc_with(f, DocStyle::Prose, f.meta.enum_name.as_deref()),
                "  "
            ),
            value_type(api, f, role),
            identifier(&f.name)
        );
    }
    render_write(out, s, &roles);
    render_read(out, api, s, &roles, &name);
    let _ = writeln!(out, "}}\n");
}

fn render_write(out: &mut String, s: &StructDef, roles: &[FieldRole]) {
    let c = struct_name(&s.name);
    let _ = writeln!(
        out,
        "  /// Writes this value into a C struct the call takes by pointer.\n  /// Whatever the struct points at is allocated in `arena`, which frees it\n  /// when the call returns.\n  void write(ffi.Pointer<{c}> raw, ffi.Allocator arena) => writeInto(raw.ref, arena);\n\n  /// Writes this value into a struct, which may be one held inside\n  /// another rather than one of its own.\n  void writeInto({c} raw, ffi.Allocator arena) {{"
    );
    if has_handshake(s) {
        let _ = writeln!(out, "    raw.structSize = ffi.sizeOf<{c}>();");
    }
    for (f, role) in s.fields.iter().zip(roles) {
        let field = identifier(&f.name);
        let line = match role {
            FieldRole::Handshake | FieldRole::Reserved => continue,
            FieldRole::Flag => format!("raw.{field} = {field} ? 1 : 0;"),
            FieldRole::Count { of } => format!("raw.{field} = {}.length;", identifier(of)),
            FieldRole::Presence { of } => {
                format!("raw.{field} = {} == null ? 0 : 1;", identifier(of))
            }
            FieldRole::BitSet { .. } => {
                format!("raw.{field} = {field}.fold(0, (bits, member) => bits | (1 << member.id));")
            }
            FieldRole::Array { .. } | FieldRole::Column => {
                let native = native_scalar(element(f));
                let value = if f.meta.enum_name.is_some() {
                    format!("{field}[i].id")
                } else {
                    format!("{field}[i]")
                };
                format!(
                    "final {field}Buffer = arena<{native}>({field}.length);\n    for (var i = 0; i < {field}.length; i++) {{\n      {field}Buffer[i] = {value};\n    }}\n    raw.{field} = {field}Buffer;"
                )
            }
            FieldRole::FixedBytes { len } => format!(
                "for (var i = 0; i < {len}; i++) {{\n      raw.{field}[i] = i < {field}.length ? {field}[i] : 0;\n    }}"
            ),
            FieldRole::Text => {
                let source = if f.meta.nullable {
                    format!(
                        // A public field is not promoted by a null check,
                        // so the assertion says what the check proved.
                        "{field} == null\n        ? ffi.nullptr\n        : {field}!.toNativeUtf8(allocator: arena).cast<ffi.Char>()"
                    )
                } else {
                    format!("{field}.toNativeUtf8(allocator: arena).cast<ffi.Char>()")
                };
                format!("raw.{field} = {source};")
            }
            FieldRole::Optional { .. } => match &f.ty {
                TypeRef::Struct { .. } => format!("{field}?.writeInto(raw.{field}, arena);"),
                _ => format!("raw.{field} = {field} ?? 0;"),
            },
            FieldRole::Nested { .. } => format!("{field}.writeInto(raw.{field}, arena);"),
            FieldRole::Value => {
                if f.meta.enum_name.is_some() {
                    if f.meta.nullable {
                        format!("raw.{field} = {field}?.id ?? 0xFFFF;")
                    } else {
                        format!("raw.{field} = {field}.id;")
                    }
                } else {
                    format!("raw.{field} = {field};")
                }
            }
        };
        let _ = writeln!(out, "    {line}");
    }
    let _ = writeln!(out, "  }}\n");
}

fn render_read(out: &mut String, api: &Api, s: &StructDef, roles: &[FieldRole], name: &str) {
    let c = struct_name(&s.name);
    let _ = writeln!(
        out,
        "  /// Reads the value a call filled in.\n  static {name} read(ffi.Pointer<{c}> raw) => readFrom(raw.ref);\n\n  /// Reads a value out of a struct, which may be one held inside another.\n  static {name} readFrom({c} raw) => {name}("
    );
    for (f, role) in s.fields.iter().zip(roles) {
        if !role.is_shown() {
            continue;
        }
        let field = identifier(&f.name);
        let value = match role {
            FieldRole::Flag => format!("raw.{field} != 0"),
            FieldRole::BitSet { enum_name } => {
                let e = binding_type_name(enum_name);
                format!(
                    "{{\n          for (final member in {e}.values)\n            if (raw.{field} & (1 << member.id) != 0) member,\n        }}"
                )
            }
            FieldRole::Array { count } => {
                let read = if let Some(name) = &f.meta.enum_name {
                    format!("{}.byId(raw.{field}[i])", binding_type_name(name))
                } else {
                    format!("raw.{field}[i]")
                };
                format!(
                    "[\n          for (var i = 0; i < raw.{}; i++) {read},\n        ]",
                    identifier(count)
                )
            }
            // A column the caller allocates is filled by the library, not
            // read back into a value class.
            FieldRole::Column => String::from("const []"),
            FieldRole::FixedBytes { len } => format!(
                "Uint8List.fromList([\n          for (var i = 0; i < {len}; i++) raw.{field}[i],\n        ])"
            ),
            FieldRole::Text => {
                let read = format!(
                    "raw.{field} == ffi.nullptr\n            ? null\n            : raw.{field}.cast<pkg_ffi.Utf8>().toDartString()"
                );
                if f.meta.nullable {
                    read
                } else {
                    format!(
                        "(raw.{field} == ffi.nullptr\n            ? null\n            : raw.{field}.cast<pkg_ffi.Utf8>().toDartString()) ??\n            ''"
                    )
                }
            }
            FieldRole::Optional { flag } => match &f.ty {
                TypeRef::Struct { name } => format!(
                    "raw.{} == 0 ? null : {}.readFrom(raw.{field})",
                    identifier(flag),
                    binding_type_name(name)
                ),
                _ => format!("raw.{} == 0 ? null : raw.{field}", identifier(flag)),
            },
            FieldRole::Nested { name } => {
                format!("{}.readFrom(raw.{field})", binding_type_name(name))
            }
            FieldRole::Value => {
                if let Some(enum_name) = &f.meta.enum_name {
                    let e = binding_type_name(enum_name);
                    if f.meta.nullable {
                        format!("raw.{field} == 0xFFFF ? null : {e}.byId(raw.{field})")
                    } else {
                        format!("{e}.byId(raw.{field})")
                    }
                } else {
                    format!("raw.{field}")
                }
            }
            _ => continue,
        };
        let _ = writeln!(out, "        {field}: {value},");
    }
    let _ = writeln!(out, "      );");
    let _ = api;
}

// ── The context ────────────────────────────────────────────────────────────

fn render_context(out: &mut String, api: &Api, opaque: &OpaqueDef) {
    let name = binding_type_name(&opaque.name);
    let handle = format!("ffi.Pointer<{name}>");
    let _ = writeln!(
        out,
        "{}final class Teistro{name} implements ffi.Finalizable {{\n  Teistro{name}._(this._lib, this._handle) {{\n    _finaliser.attach(this, _handle.cast(), detach: this);\n  }}\n\n  final TeistroLibrary _lib;\n  final {handle} _handle;\n  var _disposed = false;\n",
        doc(&opaque.doc, "")
    );
    if let Some(free) = destructor(api, opaque) {
        let _ = writeln!(
            out,
            "  /// Frees the native context when this object is collected, so a\n  /// dropped context releases its memory without a call (ADR-0007).\n  static final _finaliser = ffi.NativeFinalizer(_freeAddress);\n\n  /// The address of `{}`, resolved once when the library opens.\n  static final ffi.Pointer<ffi.NativeFinalizerFunction> _freeAddress =\n      _library!.library.lookup<ffi.NativeFinalizerFunction>('{}');\n",
            free.name, free.name
        );
    }
    if let Some(ctor) = constructor(api, opaque) {
        render_dart_constructor(out, api, ctor, &name);
    }
    render_dart_error_reader(out, api);
    for m in methods(api, opaque) {
        render_dart_method(out, api, opaque, m);
    }
    if let Some(free) = destructor(api, opaque) {
        let _ = writeln!(
            out,
            "  /// Frees the native context now. Using this object afterwards is a\n  /// [StateError]; a context that is never disposed is freed when it is\n  /// collected.\n  void dispose() {{\n    if (_disposed) return;\n    _disposed = true;\n    _finaliser.detach(this);\n    _lib.{}(_handle);\n  }}\n\n  void _alive() {{\n    if (_disposed) {{\n      throw StateError('this context was disposed');\n    }}\n  }}\n",
            free.name
        );
    }
    let _ = writeln!(out, "}}\n");
}

fn render_dart_constructor(out: &mut String, api: &Api, ctor: &FunctionDef, name: &str) {
    let mut params = Vec::new();
    let mut body = String::new();
    let mut args = Vec::new();
    for p in &ctor.params {
        let field = identifier(&p.name);
        match p.role {
            Role::StructIn => {
                let Some(s) = pointee_struct(api, p) else {
                    continue;
                };
                let value = binding_type_name(&s.name);
                params.push(format!("{value}? {field}"));
                let _ = writeln!(
                    body,
                    "      final raw{field} = {field} == null ? ffi.nullptr : arena<{}>();\n      {field}?.write(raw{field}, arena);",
                    struct_name(&s.name)
                );
                args.push(format!("raw{field}"));
            }
            Role::VtableIn | Role::UserData => args.push(String::from("ffi.nullptr")),
            Role::HandleOut => {
                let _ = writeln!(body, "      final out = arena<ffi.Pointer<{name}>>();");
                args.push(String::from("out"));
            }
            Role::StringOut => {
                let Some(s) = pointee_struct(api, p) else {
                    continue;
                };
                let _ = writeln!(
                    body,
                    "      final error = arena<{}>();",
                    struct_name(&s.name)
                );
                args.push(String::from("error"));
            }
            _ => {}
        }
    }
    let _ = writeln!(
        out,
        "{doc}  factory Teistro{name}(TeistroLibrary lib, {{{params}}}) {{\n    rememberLibrary(lib);\n    return pkg_ffi.using((arena) {{\n{body}      final status = lib.{call}({args});\n      if (status != 0) {{\n        final message = error.ref.data == ffi.nullptr\n            ? 'the context could not be built (code $status)'\n            : error.ref.data.cast<pkg_ffi.Utf8>().toDartString();\n        lib.{free}(error);\n        throw TeistroException(Status.byId(status), message);\n      }}\n      return Teistro{name}._(lib, out.value);\n    }});\n  }}\n",
        doc = doc(&ctor.doc, "  "),
        params = params.join(", "),
        call = ctor.name,
        args = args.join(", "),
        free = free_name(api, Role::StringFree)
    );
}

fn render_dart_error_reader(out: &mut String, api: &Api) {
    let Some(reader) = api
        .functions
        .iter()
        .find(|f| f.name.ends_with("_last_error"))
    else {
        return;
    };
    let Some(s) = reader
        .params
        .iter()
        .find(|p| p.role == Role::StructOut)
        .and_then(|p| pointee_struct(api, p))
    else {
        return;
    };
    let _ = writeln!(
        out,
        "  /// Turns a failed call into the exception the library described,\n  /// with its detail, its field and its hint.\n  Never _fail(int status) {{\n    return pkg_ffi.using((arena) {{\n      final raw = arena<{}>();\n      raw.ref.structSize = ffi.sizeOf<{}>();\n      _lib.{}(_handle, raw);\n      String? text(ffi.Pointer<ffi.Char> p) =>\n          p == ffi.nullptr ? null : p.cast<pkg_ffi.Utf8>().toDartString();\n      throw TeistroException(\n        Status.byId(status),\n        text(raw.ref.message) ?? 'the call failed',\n        detail: text(raw.ref.detail),\n        field: text(raw.ref.field),\n        hint: text(raw.ref.hint),\n        messageKey: text(raw.ref.key),\n        providerCode: raw.ref.providerCode,\n      );\n    }});\n  }}\n",
        struct_name(&s.name),
        struct_name(&s.name),
        reader.name
    );
}

/// What a call's parameters become: the Dart parameters it takes, the
/// statements that marshal them into the arena, and the arguments the C
/// call is given. One rule for a method and for a static function,
/// because a role means the same in both.
struct Marshalled {
    params: Vec<String>,
    body: String,
    args: Vec<String>,
}

/// A value parameter: the Dart parameter it becomes and the argument the
/// C call is given, which for an enum is the id behind the member.
fn value_param(p: &ParamDef, field: &str) -> Option<(String, String)> {
    let named = match &p.ty {
        TypeRef::Enum { name } => Some(name.as_str()),
        _ => p.meta.enum_name.as_deref(),
    };
    match (named, &p.ty) {
        (Some(e), _) => Some((
            format!("{} {field}", binding_type_name(e)),
            format!("{field}.id"),
        )),
        (None, TypeRef::Scalar { scalar }) => Some((
            format!("{} {field}", dart_scalar(*scalar)),
            field.to_string(),
        )),
        _ => None,
    }
}

fn marshal(api: &Api, f: &FunctionDef) -> Marshalled {
    let mut m = Marshalled {
        params: Vec::new(),
        body: String::new(),
        args: Vec::new(),
    };
    // The pointer a `len` parameter counts, which the description puts
    // immediately before it.
    let mut counted = String::new();
    for p in &f.params {
        let field = identifier(&p.name);
        match p.role {
            Role::Handle => m.args.push(String::from("_handle")),
            Role::VtableIn | Role::UserData => m.args.push(String::from("ffi.nullptr")),
            Role::Value => {
                if let Some((param, arg)) = value_param(p, &field) {
                    m.params.push(param);
                    m.args.push(arg);
                }
            }
            Role::StructIn => {
                let Some(s) = pointee_struct(api, p) else {
                    continue;
                };
                m.params
                    .push(format!("{} {field}", binding_type_name(&s.name)));
                let _ = writeln!(
                    m.body,
                    "      final raw{field} = arena<{}>();\n      {field}.write(raw{field}, arena);",
                    struct_name(&s.name)
                );
                m.args.push(format!("raw{field}"));
            }
            Role::StructOut => {
                let Some(s) = pointee_struct(api, p) else {
                    continue;
                };
                let c = struct_name(&s.name);
                let size = if has_handshake(s) {
                    format!("\n      {field}.ref.structSize = ffi.sizeOf<{c}>();")
                } else {
                    String::new()
                };
                let _ = writeln!(m.body, "      final {field} = arena<{c}>();{size}");
                m.args.push(field);
            }
            Role::BlobOut | Role::StrOut | Role::StringOut => {
                let Some(s) = pointee_struct(api, p) else {
                    continue;
                };
                let _ = writeln!(
                    m.body,
                    "      final {field} = arena<{}>();",
                    struct_name(&s.name)
                );
                m.args.push(field);
            }
            Role::ScalarOut => {
                let scalar =
                    p.ty.pointee()
                        .and_then(TypeRef::as_scalar)
                        .unwrap_or(Scalar::F64);
                let _ = writeln!(
                    m.body,
                    "      final {field} = arena<{}>();",
                    native_scalar(scalar)
                );
                m.args.push(field);
            }
            Role::StringIn => {
                let native = "toNativeUtf8(allocator: arena).cast<ffi.Char>()";
                let value = if p.meta.nullable {
                    m.params.push(format!("String? {field}"));
                    format!("{field} == null ? ffi.nullptr : {field}.{native}")
                } else {
                    m.params.push(format!("String {field}"));
                    format!("{field}.{native}")
                };
                let _ = writeln!(m.body, "      final raw{field} = {value};");
                m.args.push(format!("raw{field}"));
            }
            Role::BytesIn => {
                m.params.push(format!("Uint8List {field}"));
                let _ = writeln!(
                    m.body,
                    "      final raw{field} = arena<ffi.Uint8>({field}.length);\n      raw{field}.asTypedList({field}.length).setAll(0, {field});"
                );
                counted.clone_from(&field);
                m.args.push(format!("raw{field}"));
            }
            Role::Length => m.args.push(format!("{counted}.length")),
            _ => {}
        }
    }
    m
}

fn render_dart_method(out: &mut String, api: &Api, opaque: &OpaqueDef, m: &FunctionDef) {
    if m.name.ends_with("_last_error") {
        return;
    }
    let method = identifier(&method_name(&api.prefix, &opaque.name, &m.name));
    let call = marshal(api, m);
    let returns = dart_return(api, m);
    let value = dart_value(api, m, "_lib");
    let statement = dart_call(
        api,
        m,
        "_lib",
        &call.args,
        "      if (status != 0) _fail(status);",
    );
    let inner = dart_body(&returns, &call.body, &statement, value.as_ref());
    let _ = writeln!(
        out,
        "{}  {returns} {method}({}) {{\n    _alive();\n  {}\n  }}\n",
        doc(&m.doc, "  "),
        call.params.join(", "),
        inner.replace('\n', "\n  ")
    );
}

/// The Dart type of one thing a call hands back.
fn handed_type(api: &Api, h: &Handed) -> String {
    match h {
        Handed::Returned(scalar) => dart_scalar(*scalar).to_string(),
        Handed::Struct(p) => pointee_struct(api, p)
            .map_or_else(|| String::from("Object"), |s| binding_type_name(&s.name)),
        Handed::Blob(_) => String::from("Uint8List"),
        Handed::Owned(_) | Handed::Lent(_) => String::from("String"),
        Handed::Scalar(p) => {
            p.ty.pointee()
                .and_then(TypeRef::as_scalar)
                .map_or_else(|| String::from("double"), |s| dart_scalar(s).to_string())
        }
    }
}

/// The expression that reads it once the call has returned, given how the
/// enclosing code names the open library.
fn handed_read(api: &Api, h: &Handed, lib: &str) -> String {
    match h {
        Handed::Returned(_) => String::from("value"),
        Handed::Struct(p) => format!(
            "{}.read({})",
            pointee_struct(api, p)
                .map_or_else(|| String::from("Object"), |s| binding_type_name(&s.name)),
            identifier(&p.name)
        ),
        Handed::Blob(p) => format!("_takeBlob({lib}, {})", identifier(&p.name)),
        Handed::Owned(p) => format!("_takeString({lib}, {})", identifier(&p.name)),
        Handed::Lent(p) => format!("_takeStr({})", identifier(&p.name)),
        Handed::Scalar(p) => format!("{}.value", identifier(&p.name)),
    }
}

/// The name a record hands it back under.
fn handed_field(h: &Handed) -> String {
    identifier(&camel(&h.name()))
}

/// The Dart type a call hands back: nothing, the one thing it produces, or
/// a record naming each, which is the object the Node binding returns for
/// the same call under the same names.
fn dart_return(api: &Api, f: &FunctionDef) -> String {
    match results(api, f).as_slice() {
        [] => String::from("void"),
        [one] => handed_type(api, one),
        many => format!(
            "({{{}}})",
            many.iter()
                .map(|h| format!("{} {}", handed_type(api, h), handed_field(h)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// What the call returns, or `None` when it hands nothing back.
fn dart_value(api: &Api, f: &FunctionDef, lib: &str) -> Option<String> {
    match results(api, f).as_slice() {
        [] => None,
        [one] => Some(handed_read(api, one, lib)),
        many => Some(format!(
            "({})",
            many.iter()
                .map(|h| format!("{}: {}", handed_field(h), handed_read(api, h, lib)))
                .collect::<Vec<_>>()
                .join(", ")
        )),
    }
}

/// The statement that makes the call: a status checked, a value bound, or
/// neither when the function hands nothing back.
fn dart_call(api: &Api, f: &FunctionDef, lib: &str, args: &[String], fail: &str) -> String {
    let args = args.join(", ");
    if returns_status(api, f) {
        format!("      final status = {lib}.{}({args});\n{fail}", f.name)
    } else if returned_scalar(f).is_some() {
        format!("      final value = {lib}.{}({args});", f.name)
    } else {
        format!("      {lib}.{}({args});", f.name)
    }
}

/// The body of a call: the arena the marshalling needs, or, when nothing
/// had to be allocated, the call on its own.
fn dart_body(returns: &str, body: &str, call: &str, value: Option<&String>) -> String {
    if body.is_empty() {
        let tail = value.map_or_else(String::new, |v| format!("\n  return {v};"));
        return format!("{}{tail}", call.replace("      ", "  "));
    }
    let tail = value.map_or_else(String::new, |v| format!("\n      return {v};"));
    let (lead, turbofish) = if returns == "void" {
        ("  ", "<void>")
    } else {
        ("  return ", "")
    };
    format!("{lead}pkg_ffi.using{turbofish}((arena) {{\n{body}{call}{tail}\n  }});")
}

/// The library's function that frees what it allocated, by the role of
/// the value it takes, so no emitter spells an entry point by hand.
fn free_name(api: &Api, role: Role) -> String {
    api.functions
        .iter()
        .find(|f| f.params.first().is_some_and(|p| p.role == role))
        .map_or_else(String::new, |f| f.name.clone())
}

/// The static functions and the helpers every call shares.
fn render_free_functions(out: &mut String, api: &Api) {
    let named = |role: StructRole| -> String {
        api.structs
            .iter()
            .find(|s| s.role == role)
            .map_or_else(|| String::from("Object"), |s| struct_name(&s.name))
    };
    let blob = named(StructRole::Blob);
    let owned = named(StructRole::OwnedString);
    let lent = named(StructRole::BorrowedString);
    let free_blob = free_name(api, Role::BlobFree);
    let free_string = free_name(api, Role::StringFree);
    let _ = writeln!(
        out,
        "/// The bytes of a blob the library filled, copied out and the blob\n/// freed, so nothing of the library's outlives the call.\nUint8List _takeBlob(TeistroLibrary lib, ffi.Pointer<{blob}> blob) {{\n  final bytes = Uint8List.fromList(blob.ref.data.asTypedList(blob.ref.len));\n  lib.{free_blob}(blob);\n  return bytes;\n}}\n\n/// The text of a string the library allocated, copied and the string freed.\nString _takeString(TeistroLibrary lib, ffi.Pointer<{owned}> string) {{\n  final text = string.ref.data == ffi.nullptr\n      ? ''\n      : string.ref.data.cast<pkg_ffi.Utf8>().toDartString();\n  lib.{free_string}(string);\n  return text;\n}}\n\n/// The text of a string the library lent, copied before the next call\n/// replaces it.\nString _takeStr(ffi.Pointer<{lent}> str) => str.ref.data == ffi.nullptr\n    ? ''\n    : str.ref.data.cast<pkg_ffi.Utf8>().toDartString();\n\n/// The library every context and static call was opened with, so a\n/// finaliser can find the symbol it frees with.\nTeistroLibrary? _library;\n\n/// Remembers the open library.\nvoid rememberLibrary(TeistroLibrary lib) {{\n  _library ??= lib;\n}}\n"
    );
    for f in api.functions.iter().filter(|f| {
        !f.params.iter().any(|p| {
            matches!(
                p.role,
                Role::Handle | Role::HandleOut | Role::BlobFree | Role::StringFree
            )
        })
    }) {
        render_dart_free_function(out, api, f);
    }
}

/// The Dart name of the function that turns a status into its phrase.
fn message_function_name(api: &Api) -> String {
    crate::rules::message_function(api).map_or_else(
        || String::from("_phrase"),
        |f| identifier(f.name.strip_prefix(&api.prefix).unwrap_or(&f.name)),
    )
}

fn render_dart_free_function(out: &mut String, api: &Api, f: &FunctionDef) {
    let name = identifier(f.name.strip_prefix(&api.prefix).unwrap_or(&f.name));
    let mut call = marshal(api, f);
    call.params.insert(0, String::from("TeistroLibrary lib"));
    // A static call returning a string is the one shape with no arena.
    if matches!(&f.returns, Some(TypeRef::Pointer { to, .. }) if matches!(**to, TypeRef::Char)) {
        let _ = writeln!(
            out,
            "{}String {name}({}) =>\n    lib.{}({}).cast<pkg_ffi.Utf8>().toDartString();\n",
            doc(&f.doc, ""),
            call.params.join(", "),
            f.name,
            call.args.join(", ")
        );
        return;
    }
    let returns = dart_return(api, f);
    let value = dart_value(api, f, "lib");
    let fail = format!(
        "      if (status != 0) {{\n        throw TeistroException(\n          Status.byId(status),\n          {}(lib, Status.byId(status)),\n        );\n      }}",
        message_function_name(api)
    );
    let statement = dart_call(api, f, "lib", &call.args, &fail);
    let _ = writeln!(
        out,
        "{}{returns} {name}({}) {{\n{}\n}}\n",
        doc(&f.doc, ""),
        call.params.join(", "),
        dart_body(&returns, &call.body, &statement, value.as_ref())
    );
}

// ── The decoders ───────────────────────────────────────────────────────────

/// The typed list a column of a scalar decodes into.
fn typed_list(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::U8 | Scalar::Bool => "Uint8List",
        Scalar::U16 => "Uint16List",
        Scalar::U32 => "Uint32List",
        Scalar::U64 => "Uint64List",
        Scalar::I8 => "Int8List",
        Scalar::I16 => "Int16List",
        Scalar::I32 => "Int32List",
        Scalar::I64 => "Int64List",
        Scalar::F32 => "Float32List",
        Scalar::F64 | Scalar::Usize | Scalar::Isize => "Float64List",
    }
}

fn byte_data_getter(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::F64 => "getFloat64",
        Scalar::F32 => "getFloat32",
        Scalar::I8 => "getInt8",
        Scalar::I16 => "getInt16",
        Scalar::I32 => "getInt32",
        Scalar::I64 => "getInt64",
        Scalar::U8 | Scalar::Bool => "getUint8",
        Scalar::U16 => "getUint16",
        _ => "getUint32",
    }
}

/// Renders `blob.dart`: one decoder per result blob over the `TSRB`
/// layout, the columns as views over the bytes rather than copies.
#[must_use]
pub fn decoders(api: &Api) -> String {
    let mut out = preamble(
        api,
        "\n\nimport 'dart:convert';\nimport 'dart:typed_data';\n",
    );
    out.push_str(DECODER_PRELUDE);
    for schema in &api.blobs {
        render_decoder(&mut out, schema);
    }
    out
}

const DECODER_PRELUDE: &str = r"
const int _magic = 0x42525354; // 'TSRB'
const int _version = 1;
const int _headerLength = 32;
const int _entryLength = 16;

/// One section of a blob, as its table of contents describes it.
final class _Section {
  const _Section(this.offset, this.length, this.count);

  final int offset;
  final int length;
  final int count;
}

/// A blob opened for reading: the bytes, a view over them, and the table.
final class _Blob {
  _Blob(this.bytes, this.data, this.sections);

  final Uint8List bytes;
  final ByteData data;
  final Map<int, _Section> sections;

  /// Reads the header and the table, checking every offset.
  factory _Blob.open(Uint8List raw, int schemaId, String schemaName) {
    // A column is read as a typed list over these bytes, and a typed list
    // must start on a multiple of its element's size. A view handed to us
    // at an offset that cannot give that is copied once, here, rather
    // than misread or refused.
    final input = raw.offsetInBytes % 8 == 0
        ? raw
        : Uint8List.fromList(raw);
    final data = ByteData.sublistView(input);
    if (input.lengthInBytes < _headerLength ||
        data.getUint32(0, Endian.little) != _magic) {
      throw const FormatException('not a Teistro result blob');
    }
    final version = data.getUint32(4, Endian.little);
    if (version != _version) {
      throw FormatException(
        'blob layout version $version, this decoder reads version $_version',
      );
    }
    final total = data.getUint32(12, Endian.little);
    if (total != input.lengthInBytes) {
      throw FormatException(
        'the header says $total bytes, ${input.lengthInBytes} were given',
      );
    }
    final id = data.getUint32(16, Endian.little);
    if (id != schemaId) {
      throw FormatException('blob schema $id, expected $schemaId ($schemaName)');
    }
    final count = data.getUint32(8, Endian.little);
    final sections = <int, _Section>{};
    for (var i = 0; i < count; i++) {
      final at = _headerLength + i * _entryLength;
      final section = _Section(
        data.getUint32(at + 4, Endian.little),
        data.getUint32(at + 8, Endian.little),
        data.getUint32(at + 12, Endian.little),
      );
      if (section.offset + section.length > total) {
        throw FormatException(
          'section ${data.getUint32(at, Endian.little)} runs past the end of the blob',
        );
      }
      sections[data.getUint32(at, Endian.little)] = section;
    }
    return _Blob(input, data, sections);
  }

  /// The section with an id, or a [FormatException] naming what is missing.
  _Section section(int id, String name) {
    final found = sections[id];
    if (found == null) {
      throw FormatException('the blob carries no `$name` section');
    }
    return found;
  }

  /// The offset of one column of a column section.
  int columnOffset(_Section at, int index) =>
      at.offset + data.getUint32(at.offset + index * 4, Endian.little);

  /// A bytes section as the UTF-8 text the library wrote.
  String text(_Section at) =>
      utf8.decode(Uint8List.sublistView(bytes, at.offset, at.offset + at.count));
}
";

fn render_decoder(out: &mut String, schema: &BlobSchema) {
    let name = pascal(&schema.name);
    for section in schema
        .sections
        .iter()
        .filter(|s| s.kind == SectionKind::Columns)
    {
        render_column_class(out, &name, section);
    }
    render_decoded_class(out, &name, schema);
    render_decode_function(out, &name, schema);
}

/// A column section as its own class: one typed list per column.
fn render_column_class(out: &mut String, name: &str, section: &SectionSchema) {
    let class = format!("{name}{}", pascal(&section.name));
    let _ = writeln!(
        out,
        "/// The `{}` section of a {name} blob: one typed list per column, each a\n/// view over the blob's bytes rather than a copy.\n///\n/// {}\nfinal class {class} {{\n  const {class}({{",
        section.name, section.doc
    );
    for column in &section.fields {
        let _ = writeln!(out, "    required this.{},", identifier(&column.name));
    }
    let _ = writeln!(out, "    required this.length,\n  }});\n");
    for column in &section.fields {
        let _ = writeln!(
            out,
            "{}  final {} {};\n",
            doc(&column.doc, "  "),
            typed_list(column.scalar),
            identifier(&column.name)
        );
    }
    let _ = writeln!(
        out,
        "  /// The number of rows every column holds.\n  final int length;\n}}\n"
    );
}

/// The decoded blob: a field per fixed value, per column section and per
/// bytes section.
fn render_decoded_class(out: &mut String, name: &str, schema: &BlobSchema) {
    let _ = writeln!(
        out,
        "/// A decoded {name} blob.\n///\n/// {}\nfinal class {name} {{\n  const {name}({{",
        schema.doc
    );
    for section in &schema.sections {
        match section.kind {
            SectionKind::Fixed => {
                for field in section.fields.iter().filter(|f| f.name != "reserved") {
                    let _ = writeln!(out, "    required this.{},", identifier(&field.name));
                }
            }
            SectionKind::Columns | SectionKind::Bytes => {
                let _ = writeln!(out, "    required this.{},", identifier(&section.name));
            }
        }
    }
    let _ = writeln!(out, "  }});\n");
    for section in &schema.sections {
        match section.kind {
            SectionKind::Fixed => {
                for field in section.fields.iter().filter(|f| f.name != "reserved") {
                    let _ = writeln!(
                        out,
                        "{}  final int {};\n",
                        doc(&field.doc, "  "),
                        identifier(&field.name)
                    );
                }
            }
            SectionKind::Columns => {
                let _ = writeln!(
                    out,
                    "{}  final {name}{} {};\n",
                    doc(&section.doc, "  "),
                    pascal(&section.name),
                    identifier(&section.name)
                );
            }
            SectionKind::Bytes => {
                let _ = writeln!(
                    out,
                    "{}  final String {};\n",
                    doc(&section.doc, "  "),
                    identifier(&section.name)
                );
            }
        }
    }
    let _ = writeln!(out, "}}\n");
}

/// The function that reads a blob into that class.
fn render_decode_function(out: &mut String, name: &str, schema: &BlobSchema) {
    let _ = writeln!(
        out,
        "/// Decodes a {name} blob. The columns are views over `bytes`, so the\n/// buffer must outlive the result; a blob of another layout version or\n/// another schema is a [FormatException].\n{name} decode{name}(Uint8List bytes) {{\n  final blob = _Blob.open(bytes, {}, '{}');",
        schema.id, schema.name
    );
    let mut arguments = Vec::new();
    for section in &schema.sections {
        let at = format!("at{}", pascal(&section.name));
        let _ = writeln!(
            out,
            "  final {at} = blob.section({}, '{}');",
            section.id, section.name
        );
        match section.kind {
            SectionKind::Fixed => {
                let mut slot = 0usize;
                for field in &section.fields {
                    if field.name != "reserved" {
                        // A one-byte read takes no endianness, and Dart's
                        // `ByteData` refuses the argument.
                        let endian = if field.scalar.width(8) == 1 {
                            ""
                        } else {
                            ", Endian.little"
                        };
                        arguments.push(format!(
                            "    {}: blob.data.{}({at}.offset + {slot}{endian}),",
                            identifier(&field.name),
                            byte_data_getter(field.scalar)
                        ));
                    }
                    slot += crate::blob::SLOT;
                }
            }
            SectionKind::Columns => {
                let mut columns = Vec::new();
                for (index, column) in section.fields.iter().enumerate() {
                    columns.push(format!(
                        "      {}: {}.sublistView(\n        blob.bytes,\n        blob.columnOffset({at}, {index}),\n        blob.columnOffset({at}, {index}) + {at}.count * {},\n      ),",
                        identifier(&column.name),
                        typed_list(column.scalar),
                        column.scalar.width(8)
                    ));
                }
                arguments.push(format!(
                    "    {}: {name}{}(\n{}\n      length: {at}.count,\n    ),",
                    identifier(&section.name),
                    pascal(&section.name),
                    columns.join("\n")
                ));
            }
            SectionKind::Bytes => {
                arguments.push(format!(
                    "    {}: blob.text({at}),",
                    identifier(&section.name)
                ));
            }
        }
    }
    let _ = writeln!(
        out,
        "  return {name}(\n{}\n  );\n}}\n",
        arguments.join("\n")
    );
}
