//! The Java binding's mechanical layer over the Foreign Function and
//! Memory API (`03-design/java-binding.md`): every enum of the boundary
//! as a Java `enum`, the exception every refusal is raised as, and the
//! raw layer — one `StructLayout` per boundary struct with its padding
//! written out, a handle per field, a descriptor per callback and a
//! method handle per entry point.
//!
//! Java gives every public type a file of its own, so this emitter
//! answers a list of files under the generated source root rather than
//! one text.
//!
//! Only the LP64 layout is written: every target of the platform table
//! is 64-bit, and the JDK ships for none of the others. The hand-written
//! loader refuses an `ADDRESS` layout that is not eight bytes.

mod blob;
mod calls;
mod records;
mod values;

use std::fmt::Write;

use crate::emit::{DocStyle, block_comment, field_doc, reserved};
use crate::layout::{Target, layout_of, struct_layout};
use crate::model::{Api, EnumDef, FieldDef, FunctionDef, Scalar, StructDef, StructRole, TypeRef};
use crate::names::{binding_type_name, c_type_name, camel, screaming};

/// The package every public type is in.
pub const PACKAGE: &str = "com.teispace.teistro";

/// The package of the raw layer.
pub const FFI_PACKAGE: &str = "com.teispace.teistro.ffi";

/// The member a value from a newer library falls into.
const UNKNOWN: &str = "UNKNOWN";

/// One generated source file: its path under the generated source root
/// (`com/teispace/teistro/Graha.java`), and its text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct File {
    /// Where the file goes, relative to the source root.
    pub path: String,
    /// What it says.
    pub text: String,
}

/// Every generated file of the Java binding.
///
/// # Panics
///
/// A description the raw layer cannot express: a struct passed by value
/// to an entry point, which no function of the boundary does, or two
/// members of one enum whose keys upper-case to the same constant.
#[must_use]
pub fn render(api: &Api) -> Vec<File> {
    let dir = PACKAGE.replace('.', "/");
    let mut files = vec![
        File {
            path: format!("{dir}/Member.java"),
            text: member_interfaces(api, "Member"),
        },
        File {
            path: format!("{dir}/Catalogued.java"),
            text: member_interfaces(api, "Catalogued"),
        },
    ];
    files.extend(api.enums.iter().map(|e| File {
        path: format!("{dir}/{}.java", binding_type_name(&e.name)),
        text: render_enum(api, e),
    }));
    files.push(File {
        path: format!("{dir}/TeistroException.java"),
        text: render_exception(api),
    });
    files.extend(values::files(api, &dir));
    files.extend(calls::files(api, &dir));
    files.extend(blob::files(api));
    files.extend(records::files(api));
    files.push(File {
        path: format!("{}/Native.java", FFI_PACKAGE.replace('.', "/")),
        text: render_native(api),
    });
    files
}

// ── Text ───────────────────────────────────────────────────────────────────

/// A Javadoc comment of a boundary item's documentation. The text is
/// HTML: `<`, `>` and `&` are escaped, and a line opening with `@` would
/// be read as a block tag, so its `@` is written as an entity.
fn javadoc(text: &str, indent: &str) -> String {
    let escaped = text
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            if trimmed.starts_with('@') {
                line.replacen('@', "&#64;", 1)
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    block_comment(&escaped, indent)
}

/// A Java string literal.
fn literal(text: &str) -> String {
    let mut out = String::from("\"");
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{:04x}", u32::from(c));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// The header every generated file starts with.
fn preamble(api: &Api, package: &str) -> String {
    format!(
        "// Generated by `cargo xtask gen ffi` from `idl/api.json` (ABI {}, SDK {}).\n// Do not edit: `cargo xtask check-ffi` fails on any difference.\n\npackage {package};\n\n",
        api.abi_version, api.sdk_version
    )
}

/// A field or method name in camel case, renamed when it is a keyword.
fn identifier(name: &str) -> String {
    reserved::renamed(&camel(name), reserved::JAVA, "Value")
}

/// A member's constant: its key upper-cased, as Java names constants. A
/// key that does not start with a letter gains an underscore.
fn constant(key: &str) -> String {
    let upper = key.to_ascii_uppercase();
    if upper
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic())
    {
        upper
    } else {
        format!("_{upper}")
    }
}

// ── The catalogue ──────────────────────────────────────────────────────────

/// `Member` and `Catalogued`, the two interfaces every enum implements.
fn member_interfaces(api: &Api, which: &str) -> String {
    let mut out = preamble(api, PACKAGE);
    if which == "Member" {
        out.push_str("/**\n * An enum of the boundary: the id the C ABI carries, and the key every\n * pack, fixture and serialised result spells the member with.\n */\npublic interface Member {\n    /**\n     * The id the C boundary carries.\n     *\n     * @return the id\n     */\n    int id();\n\n    /**\n     * The key every pack, fixture and serialised result spells.\n     *\n     * @return the key\n     */\n    String key();\n}\n");
    } else {
        out.push_str("/**\n * A member of a catalogue kind, whose members a registry may add to: an id\n * this build does not know reads as the enum's {@code UNKNOWN}, so a\n * caller matching on a result stays exhaustive against a newer library.\n */\npublic interface Catalogued extends Member {\n    /**\n     * The key with its kind, as every pack and fixture spells it\n     * ({@code graha.SUN}).\n     *\n     * @return the full key\n     */\n    String fullKey();\n}\n");
    }
    out
}

/// One enum: its members with their ids and keys, `of` by id and `byKey`
/// by key.
fn render_enum(api: &Api, e: &EnumDef) -> String {
    let name = binding_type_name(&e.name);
    let catalogued = e.kind.is_some();
    let mut out = preamble(api, PACKAGE);
    out.push_str("import java.util.Optional;\n\n");
    out.push_str(&javadoc(&e.doc, ""));
    let interface = if catalogued { "Catalogued" } else { "Member" };
    let _ = writeln!(out, "public enum {name} implements {interface} {{");
    let mut seen: Vec<String> = Vec::new();
    let mut members: Vec<String> = Vec::new();
    for value in &e.values {
        let constant = constant(&value.key);
        assert!(
            !seen.contains(&constant),
            "{name}: two members are both `{constant}` in Java"
        );
        seen.push(constant.clone());
        let mut text = javadoc(
            &if value.deprecated {
                format!(
                    "{}\n\n@deprecated Kept so an old id still reads.",
                    value.doc
                )
            } else {
                value.doc.clone()
            },
            "    ",
        );
        // The `@deprecated` tag must reach Javadoc as a tag.
        text = text.replace("&#64;deprecated", "@deprecated");
        if value.deprecated {
            text.push_str("    @Deprecated\n");
        }
        let _ = write!(
            text,
            "    {constant}({}, {})",
            value.value,
            literal(&value.key)
        );
        members.push(text);
    }
    if catalogued {
        assert!(
            !seen.iter().any(|c| c == UNKNOWN),
            "{name}: a member is already `{UNKNOWN}`"
        );
        members.push(format!(
            "    /** A member this build does not know: from a newer library, or registered at run time. */\n    {UNKNOWN}(-1, {})",
            literal(UNKNOWN)
        ));
    }
    out.push_str(&members.join(",\n\n"));
    out.push_str(";\n\n");
    let _ = writeln!(
        out,
        "    private static final {name}[] MEMBERS = values();\n\n    private final int id;\n    private final String key;\n\n    {name}(int id, String key) {{\n        this.id = id;\n        this.key = key;\n    }}\n\n    @Override\n    public int id() {{\n        return id;\n    }}\n\n    @Override\n    public String key() {{\n        return key;\n    }}\n"
    );
    if let Some(kind) = &e.kind {
        let _ = writeln!(
            out,
            "    @Override\n    public String fullKey() {{\n        return {} + key;\n    }}\n",
            literal(&format!("{kind}."))
        );
        let _ = writeln!(
            out,
            "    /**\n     * The member with an id, or {{@link #{UNKNOWN}}} for one this build does not\n     * know.\n     *\n     * @param id the id the boundary carries\n     * @return the member\n     */\n    public static {name} of(int id) {{\n        for ({name} member : MEMBERS) {{\n            if (member.id == id && member != {UNKNOWN}) {{\n                return member;\n            }}\n        }}\n        return {UNKNOWN};\n    }}\n"
        );
    } else {
        let _ = writeln!(
            out,
            "    /**\n     * The member with an id. The set is closed, so an id outside it is a\n     * fault and not a state.\n     *\n     * @param id the id the boundary carries\n     * @return the member\n     * @throws IllegalArgumentException for an id that is no member\n     */\n    public static {name} of(int id) {{\n        for ({name} member : MEMBERS) {{\n            if (member.id == id) {{\n                return member;\n            }}\n        }}\n        throw new IllegalArgumentException({} + id);\n    }}\n",
            literal(&format!("no {name} has the id "))
        );
    }
    let _ = writeln!(
        out,
        "    /**\n     * The member with a key, or empty for one this build lacks. A full key\n     * ({{@code kind.KEY}}) and a bare one both find it.\n     *\n     * @param key the key\n     * @return the member, if there is one\n     */\n    public static Optional<{name}> byKey(String key) {{\n        String wanted = key.substring(key.lastIndexOf('.') + 1);\n        for ({name} member : MEMBERS) {{\n            if (member.key.equals(wanted){}) {{\n                return Optional.of(member);\n            }}\n        }}\n        return Optional.empty();\n    }}\n}}",
        if catalogued {
            format!(" && member != {UNKNOWN}")
        } else {
            String::new()
        }
    );
    out
}

// ── The exception ──────────────────────────────────────────────────────────

/// The error struct's text fields, which the exception carries: every
/// `char *` but the message, read from the description so a field added
/// there reaches the exception.
fn error_fields(api: &Api) -> Vec<&FieldDef> {
    api.structs
        .iter()
        .find(|s| s.role == StructRole::Error)
        .map(|s| {
            s.fields
                .iter()
                .filter(|f| f.name != "message" && matches!(f.ty.pointee(), Some(TypeRef::Char)))
                .collect()
        })
        .unwrap_or_default()
}

/// `TeistroException`: unchecked, carrying the status, the message and
/// every other text field of the error record.
fn render_exception(api: &Api) -> String {
    let fields = error_fields(api);
    let mut out = preamble(api, PACKAGE);
    out.push_str("import java.util.Objects;\n\n/**\n * A refusal from the library, with everything it said about it.\n *\n * <p>{@link #status()} is the boundary's own code, so a caller may match on\n * it rather than on the message; the other parts are empty strings unless\n * the library named them.\n */\npublic final class TeistroException extends RuntimeException {\n    private static final long serialVersionUID = 1L;\n\n    /** The boundary's status. */\n    private final Status status;\n");
    for f in &fields {
        out.push_str(&javadoc(&f.doc, "    "));
        let _ = writeln!(out, "    private final String {};", identifier(&f.name));
    }
    out.push_str("\n    /**\n     * A refusal as the library recorded it.\n     *\n     * @param status the boundary's status\n     * @param message what the library said\n");
    for f in &fields {
        let _ = writeln!(
            out,
            "     * @param {0} the record's {1}, or an empty string",
            identifier(&f.name),
            f.name
        );
    }
    let params = fields.iter().fold(String::new(), |mut params, f| {
        let _ = write!(params, ", String {}", identifier(&f.name));
        params
    });
    let _ = writeln!(
        out,
        "     */\n    public TeistroException(Status status, String message{params}) {{\n        super(message);\n        this.status = Objects.requireNonNull(status, \"status\");"
    );
    for f in &fields {
        let name = identifier(&f.name);
        let _ = writeln!(
            out,
            "        this.{name} = Objects.requireNonNullElse({name}, \"\");"
        );
    }
    out.push_str("    }\n\n    /**\n     * The boundary's status.\n     *\n     * @return the status\n     */\n    public Status status() {\n        return status;\n    }\n");
    for f in &fields {
        let name = identifier(&f.name);
        let _ = writeln!(
            out,
            "\n    /**\n     * The record's {}, or an empty string.\n     *\n     * @return the {}\n     */\n    public String {name}() {{\n        return {name};\n    }}",
            f.name, f.name
        );
    }
    out.push_str("\n    @Override\n    public String toString() {\n        StringBuilder text = new StringBuilder(\"TeistroException [\").append(status.key()).append(\"] \").append(getMessage());\n");
    for f in &fields {
        let name = identifier(&f.name);
        let _ = writeln!(
            out,
            "        if (!{name}.isEmpty()) {{\n            text.append(\"\\n  {}: \").append({name});\n        }}",
            f.name
        );
    }
    out.push_str("        return text.toString();\n    }\n}\n");
    out
}

// ── The raw layer ──────────────────────────────────────────────────────────

/// The FFM layout of a scalar, little-endian as every target is.
const fn scalar_layout(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::U8 | Scalar::I8 => "JAVA_BYTE",
        Scalar::U16 | Scalar::I16 => "JAVA_SHORT",
        Scalar::U32 | Scalar::I32 => "JAVA_INT",
        Scalar::U64 | Scalar::I64 | Scalar::Usize | Scalar::Isize => "JAVA_LONG",
        Scalar::F32 => "JAVA_FLOAT",
        Scalar::F64 => "JAVA_DOUBLE",
        Scalar::Bool => "JAVA_BOOLEAN",
    }
}

/// The FFM layout of a type as a field or an argument holds it.
fn layout(api: &Api, ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { scalar } => scalar_layout(*scalar).to_string(),
        TypeRef::Enum { name } => api
            .enum_named(name)
            .map_or("JAVA_INT", |e| scalar_layout(e.repr))
            .to_string(),
        TypeRef::Struct { name } => format!("{name}.LAYOUT"),
        TypeRef::Pointer { .. } | TypeRef::Callback { .. } | TypeRef::Opaque { .. } => {
            String::from("ADDRESS")
        }
        TypeRef::Array { of, len } => {
            format!("MemoryLayout.sequenceLayout({len}, {})", layout(api, of))
        }
        TypeRef::Char => String::from("JAVA_BYTE"),
        TypeRef::Void => String::from("/* void */"),
    }
}

/// Whether a field reads as one value through a `VarHandle`: a scalar, an
/// enum, a pointer or a callback, and not a struct or an array held in
/// place.
const fn is_value(ty: &TypeRef) -> bool {
    !matches!(ty, TypeRef::Struct { .. } | TypeRef::Array { .. })
}

/// The Java type a constant is written in: `int` when its value fits.
fn constant_type(value: i64, scalar: Scalar) -> &'static str {
    let wide = matches!(
        scalar,
        Scalar::U64 | Scalar::I64 | Scalar::Usize | Scalar::Isize
    );
    if wide || i32::try_from(value).is_err() {
        "long"
    } else {
        "int"
    }
}

/// `ffi/Native.java`.
fn render_native(api: &Api) -> String {
    let mut out = preamble(api, FFI_PACKAGE);
    out.push_str("import static java.lang.foreign.ValueLayout.ADDRESS;\nimport static java.lang.foreign.ValueLayout.JAVA_BOOLEAN;\nimport static java.lang.foreign.ValueLayout.JAVA_BYTE;\nimport static java.lang.foreign.ValueLayout.JAVA_DOUBLE;\nimport static java.lang.foreign.ValueLayout.JAVA_FLOAT;\nimport static java.lang.foreign.ValueLayout.JAVA_INT;\nimport static java.lang.foreign.ValueLayout.JAVA_LONG;\nimport static java.lang.foreign.ValueLayout.JAVA_SHORT;\n\nimport java.lang.foreign.FunctionDescriptor;\nimport java.lang.foreign.Linker;\nimport java.lang.foreign.MemoryLayout;\nimport java.lang.foreign.StructLayout;\nimport java.lang.foreign.SymbolLookup;\nimport java.lang.invoke.MethodHandle;\nimport java.lang.invoke.VarHandle;\nimport java.util.List;\nimport java.util.Map;\n\n/**\n * The raw layer: the C header's constants, a layout per boundary struct with\n * its padding written out, a descriptor per callback, and a method handle\n * per entry point, named as the header names them. The public API of\n * {@code com.teispace.teistro} is built on this; a caller who needs the\n * boundary itself may use it directly.\n */\npublic final class Native {\n");
    render_constants(&mut out, api);
    for s in &api.structs {
        render_struct(&mut out, api, s);
    }
    render_sizes(&mut out, api);
    render_callbacks(&mut out, api);
    render_handles(&mut out, api);
    out.push_str("}\n");
    out
}

fn render_constants(out: &mut String, api: &Api) {
    for c in &api.constants {
        out.push_str(&javadoc(&c.doc, "    "));
        let ty = constant_type(c.value, c.ty);
        let suffix = if ty == "long" { "L" } else { "" };
        let _ = writeln!(
            out,
            "    public static final {ty} {} = {}{suffix};\n",
            screaming(&c.name),
            c.value
        );
    }
    let _ = writeln!(
        out,
        "    /** The ABI these declarations were generated from; a library that answers otherwise is refused. */\n    public static final int GENERATED_ABI_VERSION = {};\n\n    /** The SDK version these declarations were generated from. */\n    public static final String GENERATED_SDK_VERSION = {};\n\n    /** What a nullable catalogue field holds for none: no member is numbered this high, and {{@code 0}} is a member. */\n    public static final int NO_MEMBER = {};\n",
        api.abi_version,
        literal(&api.sdk_version),
        crate::emit::NO_MEMBER
    );
}

/// A struct's layout, with padding as the C compiler places it, its
/// size and alignment, and a handle and an offset per field.
///
/// The class is named as the boundary crate names the struct
/// (`TsString`): the binding's own name for it may be a JDK type's.
fn render_struct(out: &mut String, api: &Api, s: &StructDef) {
    let name = &s.name;
    let laid = struct_layout(api, s, Target::LP64).unwrap_or_else(|e| unplaced(&s.name, &e));
    let mut members = Vec::new();
    let mut cursor = 0usize;
    for (field, offset) in s.fields.iter().zip(&laid.offsets) {
        if *offset > cursor {
            members.push(format!("MemoryLayout.paddingLayout({})", offset - cursor));
        }
        members.push(format!(
            "{}.withName({})",
            layout(api, &field.ty),
            literal(&field.name)
        ));
        let size = layout_of(api, &field.ty, Target::LP64)
            .unwrap_or_else(|e| unplaced(&format!("{}.{}", s.name, field.name), &e))
            .size;
        cursor = offset + size;
    }
    if laid.size > cursor {
        members.push(format!(
            "MemoryLayout.paddingLayout({})",
            laid.size - cursor
        ));
    }
    out.push_str(&javadoc(
        &format!(
            "{}\n\nThe C layout of `{}`, field for field.",
            s.doc,
            c_type_name(&api.prefix, &s.name)
        ),
        "    ",
    ));
    let _ = writeln!(
        out,
        "    public static final class {name} {{\n        private {name}() {{}}\n\n        /** The layout, padding included. */\n        public static final StructLayout LAYOUT = MemoryLayout.structLayout(\n            {}\n        ).withName({});\n\n        /** The size the C compiler gives the struct. */\n        public static final long SIZE = {};\n\n        /** The struct's alignment. */\n        public static final long ALIGN = {};\n",
        members.join(",\n            "),
        literal(&c_type_name(&api.prefix, &s.name)),
        laid.size,
        laid.align
    );
    for (field, offset) in s.fields.iter().zip(&laid.offsets) {
        let constant = screaming(&field.name);
        let doc = field_doc(field, DocStyle::Prose);
        out.push_str(&javadoc(
            &format!("The offset of `{}`. {doc}", field.name),
            "        ",
        ));
        let _ = writeln!(
            out,
            "        public static final long {constant}_OFFSET = {offset};\n"
        );
        if is_value(&field.ty) {
            let _ = writeln!(
                out,
                "        /** The handle that reads and writes `{}`: coordinates {{@code (MemorySegment, long)}}. */\n        public static final VarHandle {constant} = LAYOUT.varHandle(MemoryLayout.PathElement.groupElement({}));\n",
                field.name,
                literal(&field.name)
            );
        }
    }
    out.push_str("    }\n\n");
}

/// A struct the description cannot lay out, which stops the build: the
/// alternative is a layout that compiles and reads the wrong bytes.
#[expect(
    clippy::panic,
    reason = "a generator that cannot lay a struct out stops the build rather than emitting a wrong layout"
)]
fn unplaced(what: &str, error: &crate::layout::LayoutError) -> ! {
    panic!("{what}: the description gives it no layout: {error:?}")
}

/// Every struct's C name with its size, so a test can hold the layouts
/// FFM built to the description's.
fn render_sizes(out: &mut String, api: &Api) {
    out.push_str("    /** Every boundary struct's layout by its C name, in the description's order. */\n    public static final Map<String, StructLayout> LAYOUTS = Map.ofEntries(\n");
    let rows: Vec<String> = api
        .structs
        .iter()
        .map(|s| {
            format!(
                "        Map.entry({}, {}.LAYOUT)",
                literal(&c_type_name(&api.prefix, &s.name)),
                s.name
            )
        })
        .collect();
    out.push_str(&rows.join(",\n"));
    out.push_str("\n    );\n\n    /** Every boundary struct's size by its C name, as the description computes it. */\n    public static final Map<String, Long> SIZES = Map.ofEntries(\n");
    let rows: Vec<String> = api
        .structs
        .iter()
        .map(|s| {
            format!(
                "        Map.entry({}, {}.SIZE)",
                literal(&c_type_name(&api.prefix, &s.name)),
                s.name
            )
        })
        .collect();
    out.push_str(&rows.join(",\n"));
    out.push_str("\n    );\n\n");
}

/// A descriptor: what a function or callback returns and takes.
fn descriptor(api: &Api, returns: Option<&TypeRef>, params: &[TypeRef]) -> String {
    let args: Vec<String> = params.iter().map(|ty| layout(api, ty)).collect();
    match returns {
        None | Some(TypeRef::Void) => format!("FunctionDescriptor.ofVoid({})", args.join(", ")),
        Some(ty) => {
            let mut all = vec![layout(api, ty)];
            all.extend(args);
            format!("FunctionDescriptor.of({})", all.join(", "))
        }
    }
}

fn render_callbacks(out: &mut String, api: &Api) {
    for c in &api.callbacks {
        out.push_str(&javadoc(&c.doc, "    "));
        let params: Vec<TypeRef> = c.params.iter().map(|p| p.ty.clone()).collect();
        let _ = writeln!(
            out,
            "    public static final FunctionDescriptor {} = {};\n",
            screaming(&binding_type_name(&c.name)),
            descriptor(api, Some(&c.returns), &params)
        );
    }
}

/// Refuses a struct passed by value, which the raw layer cannot express
/// without the platform's aggregate rules; no entry point does.
fn by_value(f: &FunctionDef) {
    let held = f
        .params
        .iter()
        .map(|p| &p.ty)
        .chain(f.returns.iter())
        .any(|ty| matches!(ty, TypeRef::Struct { .. }));
    assert!(!held, "{}: a struct crosses by value", f.name);
}

/// The method handles: one per entry point, looked up in the library the
/// loader opened.
fn render_handles(out: &mut String, api: &Api) {
    out.push_str("    /** Every entry point's name, in the description's order. */\n    public static final List<String> SYMBOLS = List.of(\n");
    let names: Vec<String> = api
        .functions
        .iter()
        .map(|f| format!("        {}", literal(&f.name)))
        .collect();
    out.push_str(&names.join(",\n"));
    out.push_str("\n    );\n\n");
    for f in &api.functions {
        by_value(f);
        out.push_str(&javadoc(&f.doc, "    "));
        let _ = writeln!(out, "    public final MethodHandle {};\n", f.name);
    }
    out.push_str("    /**\n     * Every entry point, bound in a library.\n     *\n     * @param symbols the library's symbols\n     * @throws IllegalStateException naming an entry point the library lacks\n     */\n    // Binding a downcall is restricted: the module is the one consumers grant\n    // native access to (`--enable-native-access=com.teispace.teistro`).\n    @SuppressWarnings(\"restricted\")\n    public Native(SymbolLookup symbols) {\n        Linker linker = Linker.nativeLinker();\n");
    for f in &api.functions {
        let params: Vec<TypeRef> = f.params.iter().map(|p| p.ty.clone()).collect();
        let _ = writeln!(
            out,
            "        {0} = linker.downcallHandle(symbols.find({1}).orElseThrow(() -> missing({1})), {2});",
            f.name,
            literal(&f.name),
            descriptor(api, f.returns.as_ref(), &params)
        );
    }
    out.push_str("    }\n\n    private static IllegalStateException missing(String symbol) {\n        return new IllegalStateException(\"the library has no `\" + symbol + \"`; it is not the build these declarations describe\");\n    }\n");
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, reason = "tests fail by panicking")]

    use super::*;
    use crate::model::{EnumValue, Meta};

    fn toy() -> Api {
        let mut api: Api = serde_json::from_str(
            r#"{"schema":"x","abi_version":3,"sdk_version":"1.2.3","prefix":"ts_","sources":[],
                "constants":[],"enums":[],"opaques":[],"callbacks":[],"structs":[],"functions":[],
                "blobs":[],"records":[]}"#,
        )
        .unwrap();
        api.enums.push(EnumDef {
            name: String::from("Graha"),
            doc: String::from("The grahas <and> more."),
            repr: Scalar::U16,
            kind: Some(String::from("graha")),
            values: vec![EnumValue {
                name: String::from("Sun"),
                value: 0,
                doc: String::from("The Sun"),
                key: String::from("SUN"),
                deprecated: false,
            }],
            source: String::new(),
        });
        api.structs.push(StructDef {
            name: String::from("TsPair"),
            doc: String::from("A pair."),
            role: StructRole::Object,
            fields: vec![
                FieldDef {
                    name: String::from("flag"),
                    ty: TypeRef::scalar(Scalar::U8),
                    doc: String::from("A flag."),
                    meta: Meta::default(),
                },
                FieldDef {
                    name: String::from("native"),
                    ty: TypeRef::scalar(Scalar::F64),
                    doc: String::from("A value."),
                    meta: Meta::default(),
                },
            ],
            source: String::new(),
        });
        api
    }

    #[test]
    fn a_shown_struct_is_a_record_that_checks_what_c_cannot_hold() {
        let files = render(&toy());
        let pair = files
            .iter()
            .find(|f| f.path == "com/teispace/teistro/Pair.java")
            .unwrap();
        // A keyword is renamed, an unsigned byte is carried as an int and
        // checked by the name the caller wrote, and nothing is cast twice.
        assert!(
            pair.text
                .contains("public record Pair(\n        int flag,\n        double nativeValue) {")
        );
        assert!(pair.text.contains("Values.u8(\"flag\", flag)"));
        assert!(pair.text.contains("NATIVE.set(raw, 0L, nativeValue);"));
        assert!(
            pair.text
                .contains("Byte.toUnsignedInt((byte) Native.TsPair.FLAG.get(raw, 0L))")
        );
        assert!(
            files
                .iter()
                .any(|f| f.path == "com/teispace/teistro/Values.java")
        );
    }

    #[test]
    fn a_catalogued_enum_has_its_unknown_and_its_full_key() {
        let files = render(&toy());
        let graha = files
            .iter()
            .find(|f| f.path == "com/teispace/teistro/Graha.java")
            .unwrap();
        assert!(
            graha
                .text
                .contains("public enum Graha implements Catalogued {")
        );
        assert!(graha.text.contains("    SUN(0, \"SUN\")"));
        assert!(graha.text.contains("    UNKNOWN(-1, \"UNKNOWN\");"));
        assert!(graha.text.contains("return \"graha.\" + key;"));
        assert!(graha.text.contains("The grahas &lt;and&gt; more."));
    }

    #[test]
    fn a_layout_writes_its_padding_and_a_keyword_field_is_renamed() {
        let native = render(&toy()).pop().unwrap();
        assert_eq!(native.path, "com/teispace/teistro/ffi/Native.java");
        assert!(native.text.contains(
            "JAVA_BYTE.withName(\"flag\"),\n            MemoryLayout.paddingLayout(7),\n            JAVA_DOUBLE.withName(\"native\")"
        ));
        assert!(native.text.contains("public static final long SIZE = 16;"));
        assert!(
            native
                .text
                .contains("public static final long NATIVE_OFFSET = 8;")
        );
        assert_eq!(identifier("native"), "nativeValue");
        assert_eq!(identifier("lon_deg"), "lonDeg");
        assert_eq!(constant("2ND"), "_2ND");
    }

    #[test]
    fn javadoc_is_html_and_a_leading_at_is_not_a_tag() {
        assert_eq!(
            javadoc("a < b & c\n@unit deg", ""),
            "/**\n * a &lt; b &amp; c\n * &#64;unit deg\n */\n"
        );
        assert_eq!(literal("a\"b\\c\n"), "\"a\\\"b\\\\c\\n\"");
    }
}
