# Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary
# crates; do not edit. ABI version 1, SDK 0.0.0.
#
# The result-blob decoders: one per schema, reading the `TSRB` layout into
# `memoryview` columns over the blob's own bytes rather than copies.
#
# The description this file was rendered from ships as idl/api.json, and
# the generator lays this file out, so `cargo xtask check-ffi` can
# regenerate it on a machine with no Python and still compare it byte for
# byte.

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import Final

_MAGIC: Final = 0x42525354  # 'TSRB'
_VERSION: Final = 1
_HEADER_LENGTH: Final = 32
_ENTRY_LENGTH: Final = 16


class BlobError(ValueError):
    """Bytes that are not a blob this decoder reads."""


@dataclass(frozen=True)
class _Section:
    """One section of a blob, as its table of contents describes it."""

    offset: int
    length: int
    count: int


class _Blob:
    """A blob opened for reading: its bytes and its table of contents."""

    def __init__(self, raw: bytes, schema_id: int, schema_name: str) -> None:
        if len(raw) < _HEADER_LENGTH:
            raise BlobError("not a Teistro result blob: too short for a header")
        magic, version, count, total, identifier = struct.unpack_from(
            "<IIIII", raw, 0
        )
        if magic != _MAGIC:
            raise BlobError("not a Teistro result blob")
        if version != _VERSION:
            raise BlobError(
                f"blob layout version {version}, "
                f"this decoder reads version {_VERSION}"
            )
        if total != len(raw):
            raise BlobError(f"the header says {total} bytes, {len(raw)} were given")
        if identifier != schema_id:
            raise BlobError(
                f"blob schema {identifier}, expected {schema_id} ({schema_name})"
            )
        self.bytes = raw
        self.view = memoryview(raw)
        self.sections: dict[int, _Section] = {}
        for index in range(count):
            at = _HEADER_LENGTH + index * _ENTRY_LENGTH
            if at + _ENTRY_LENGTH > total:
                raise BlobError("the table of contents runs past the end of the blob")
            section_id, offset, length, rows = struct.unpack_from("<IIII", raw, at)
            if offset + length > total:
                raise BlobError(f"section {section_id} runs past the end of the blob")
            self.sections[section_id] = _Section(offset, length, rows)

    def section(self, section_id: int, name: str) -> _Section:
        """The section with an id, or a `BlobError` naming what is missing."""
        found = self.sections.get(section_id)
        if found is None:
            raise BlobError(f"the blob carries no `{name}` section")
        return found

    def fixed(self, at: _Section, slot: int, code: str) -> float:
        """One field of a fixed section, which gives every field a slot."""
        value = struct.unpack_from(f"<{code}", self.bytes, at.offset + slot * 8)[0]
        return float(value)

    def column(self, at: _Section, index: int, width: int, rows: int) -> memoryview:
        """The bytes of one column of a column section.

        The caller casts them to the column's own format code, which it
        knows as a literal; a format passed through here as a string
        would be one a type checker could not follow.
        """
        offset = at.offset + struct.unpack_from(
            "<I", self.bytes, at.offset + index * 4
        )[0]
        end = offset + rows * width
        if end > at.offset + at.length:
            raise BlobError("a column runs past the end of its section")
        return self.view[offset:end]

    def text(self, at: _Section) -> str:
        """A bytes section as the UTF-8 text the library wrote."""
        return self.bytes[at.offset : at.offset + at.count].decode("utf-8")


@dataclass(frozen=True)
class PositionsInstants:
    """The `instants` section of a Positions blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The instants of the request, in order.
    """

    jd: memoryview[float]
    """A Julian day on the request's scale."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PositionsBodies:
    """The `bodies` section of a Positions blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The bodies of the request, in order.
    """

    body: memoryview[int]
    """A body id."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PositionsCells:
    """The `cells` section of a Positions blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    One row per cell, instants outermost; a cell whose status is not zero carries no value.
    """

    lon: memoryview[float]
    """Longitude in degrees, 0 to 360."""

    lat: memoryview[float]
    """Latitude in degrees."""

    dist: memoryview[float]
    """Distance in the provider's unit."""

    lon_speed: memoryview[float]
    """Longitude speed in degrees per day; zero when speeds were not asked for."""

    lat_speed: memoryview[float]
    """Latitude speed in degrees per day."""

    dist_speed: memoryview[float]
    """Distance speed per day."""

    status: memoryview[int]
    """The cell's status code; zero is a value."""

    source: memoryview[int]
    """What computed the cell, packed as the port packs it."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class Positions:
    """A decoded Positions blob.

    Positions over a grid of instants and bodies, instants outermost: cell `i * body_count + j` is instant `i`, body `j`.
    """

    frame_bits: int
    """The frame the values are in, packed as the port packs it."""

    jd_count: int
    """The number of instants."""

    body_count: int
    """The number of bodies."""

    scale: int
    """The time scale of the instants."""

    instants: PositionsInstants
    """The instants of the request, in order."""

    bodies: PositionsBodies
    """The bodies of the request, in order."""

    cells: PositionsCells
    """One row per cell, instants outermost; a cell whose status is not zero carries no value."""

    steps: str
    """UTF-8 JSON: the completion steps applied, in order, each `{"name", "implementation"}`."""

    provenance: str
    """UTF-8 JSON: the provenance envelope of the result, canonical."""


def decode_positions(raw: bytes) -> Positions:
    """Decodes a Positions blob.

    The columns are views over `raw`, so the buffer must outlive the
    result; a blob of another layout version or another schema is a
    `BlobError`.
    """
    blob = _Blob(raw, 1, "positions")
    at_summary = blob.section(1, "summary")
    at_instants = blob.section(2, "instants")
    at_bodies = blob.section(3, "bodies")
    at_cells = blob.section(4, "cells")
    at_steps = blob.section(5, "steps")
    at_provenance = blob.section(6, "provenance")
    return Positions(
        frame_bits=int(blob.fixed(at_summary, 0, "I")),
        jd_count=int(blob.fixed(at_summary, 1, "I")),
        body_count=int(blob.fixed(at_summary, 2, "I")),
        scale=int(blob.fixed(at_summary, 3, "I")),
        instants=PositionsInstants(
            jd=blob.column(at_instants, 0, 8, at_instants.count).cast("d"),
            length=at_instants.count,
        ),
        bodies=PositionsBodies(
            body=blob.column(at_bodies, 0, 2, at_bodies.count).cast("H"),
            length=at_bodies.count,
        ),
        cells=PositionsCells(
            lon=blob.column(at_cells, 0, 8, at_cells.count).cast("d"),
            lat=blob.column(at_cells, 1, 8, at_cells.count).cast("d"),
            dist=blob.column(at_cells, 2, 8, at_cells.count).cast("d"),
            lon_speed=blob.column(at_cells, 3, 8, at_cells.count).cast("d"),
            lat_speed=blob.column(at_cells, 4, 8, at_cells.count).cast("d"),
            dist_speed=blob.column(at_cells, 5, 8, at_cells.count).cast("d"),
            status=blob.column(at_cells, 6, 4, at_cells.count).cast("i"),
            source=blob.column(at_cells, 7, 4, at_cells.count).cast("I"),
            length=at_cells.count,
        ),
        steps=blob.text(at_steps),
        provenance=blob.text(at_provenance),
    )


@dataclass(frozen=True)
class IntlRender:
    """A decoded IntlRender blob.

    A rendered message.
    """

    is_fallback: int
    """Non-zero when a fallback locale answered."""

    is_override: int
    """Non-zero when a runtime override answered."""

    warning_count: int
    """The number of warnings."""

    text: str
    """UTF-8: the plain text, markup stripped."""

    resolved_from: str
    """UTF-8: the locale whose message answered; empty when none had it."""

    warnings: str
    """UTF-8 JSON: an array of strings, one per problem met."""


def decode_intl_render(raw: bytes) -> IntlRender:
    """Decodes a IntlRender blob.

    The columns are views over `raw`, so the buffer must outlive the
    result; a blob of another layout version or another schema is a
    `BlobError`.
    """
    blob = _Blob(raw, 2, "intl_render")
    at_flags = blob.section(1, "flags")
    at_text = blob.section(2, "text")
    at_resolved_from = blob.section(3, "resolved_from")
    at_warnings = blob.section(4, "warnings")
    return IntlRender(
        is_fallback=int(blob.fixed(at_flags, 0, "B")),
        is_override=int(blob.fixed(at_flags, 1, "B")),
        warning_count=int(blob.fixed(at_flags, 2, "I")),
        text=blob.text(at_text),
        resolved_from=blob.text(at_resolved_from),
        warnings=blob.text(at_warnings),
    )


@dataclass(frozen=True)
class ChartsCast:
    """The `cast` section of a Charts blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    One row per chart, in the order the instants were asked for.
    """

    instant: memoryview[float]
    """The instant the chart is cast for, as a Julian day (UTC)."""

    lagna_deg: memoryview[float]
    """The lagna at the instant, in the chart's zodiac, degrees."""

    day_lagna_deg: memoryview[float]
    """The lagna at the sunrise that opened the day, degrees."""

    ayanamsha_offset_deg: memoryview[float]
    """The ayanamsha applied at this instant, degrees; zero for a tropical chart."""

    day_part: memoryview[int]
    """Which arc of its day the instant falls in."""

    day_elapsed: memoryview[float]
    """How far through that arc the instant is, 0 to 1."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class ChartsGrahas:
    """The `grahas` section of a Charts blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    One row per graha per chart, charts outermost: row `i * graha_count + j` is chart `i`, graha `j`, grahas in the catalogue's order. `house_*` is the bhava for "which house is it in"; `placement_*` is the chart's chalit, which is a different question and often a different answer.
    """

    graha: memoryview[int]
    """Which graha."""

    longitude_deg: memoryview[float]
    """Its longitude in the chart's zodiac, degrees."""

    tropical_deg: memoryview[float]
    """Its longitude in the tropical zodiac, degrees."""

    latitude_deg: memoryview[float]
    """Its latitude, degrees."""

    distance_au: memoryview[float]
    """Its distance in astronomical units; zero for a point that has none."""

    speed_deg_per_day: memoryview[float]
    """Its longitude speed, degrees per day; negative when retrograde."""

    house_bhava: memoryview[int]
    """The bhava it stands in, 1 to 12."""

    house_method: memoryview[int]
    """The house system that produced that bhava."""

    house_through: memoryview[float]
    """How far through the bhava it stands, 0 to 1."""

    house_from_madhya_deg: memoryview[float]
    """Its distance from the bhava's madhya, degrees."""

    placement_bhava: memoryview[int]
    """The bhava of the chart's chalit it stands in, 1 to 12."""

    placement_method: memoryview[int]
    """The house system that produced the chalit."""

    placement_through: memoryview[float]
    """How far through that bhava it stands, 0 to 1."""

    placement_from_madhya_deg: memoryview[float]
    """Its distance from that bhava's madhya, degrees."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class ChartsHouses:
    """The `houses` section of a Charts blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The twelve bhavas for "which house is it in", charts outermost: row `i * 12 + j` is chart `i`, bhava `j`, first to twelfth.
    """

    madhya_deg: memoryview[float]
    """The bhava's centre, degrees."""

    sandhi_deg: memoryview[float]
    """The bhava's opening cusp, degrees."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class ChartsChalit:
    """The `chalit` section of a Charts blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The twelve bhavas of each chart's chalit, the same shape as `houses`.
    """

    madhya_deg: memoryview[float]
    """The bhava's centre, degrees."""

    sandhi_deg: memoryview[float]
    """The bhava's opening cusp, degrees."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class ChartsTiming:
    """The `timing` section of a Charts blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    Where in its day each moment falls, in the reckonings the settings named: one row per chart.
    """

    ghati: memoryview[int]
    """The ishtakaal's ghatis since sunrise, 0 to 59."""

    pala: memoryview[int]
    """Its palas, 0 to 59."""

    vipala: memoryview[int]
    """Its vipalas, 0 to 59."""

    ghati_reckoning: memoryview[int]
    """How the ghatis were measured."""

    hora_number: memoryview[int]
    """Which hora of the day holds the instant, 1 to 24."""

    hora_lord: memoryview[int]
    """The graha that rules it."""

    hora_start: memoryview[float]
    """When that hora began, as a Julian day (UTC)."""

    hora_end: memoryview[float]
    """When it ends, as a Julian day (UTC)."""

    hora_reckoning: memoryview[int]
    """How the horas were measured."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class Day:
    """The `day` section, wherever a blob carries it: one column per field, each a view
    over the blob's bytes rather than a copy.

    The day each instant belongs to: its arc, its date and how it was reckoned. One row per row of the blob's own grid.
    """

    sunrise: memoryview[float]
    """The sunrise that opened the day, as a Julian day (UTC)."""

    sunset: memoryview[float]
    """The sunset that closed its daylight, as a Julian day (UTC)."""

    next_sunrise: memoryview[float]
    """The sunrise that closes it, as a Julian day (UTC)."""

    vara: memoryview[int]
    """The weekday the day carries."""

    calendar: memoryview[int]
    """The calendar the date is in."""

    era: memoryview[int]
    """The era the date's year is counted in."""

    year: memoryview[int]
    """The astronomical year; 1 BCE is 0."""

    era_year: memoryview[int]
    """The year as the era counts it."""

    month: memoryview[int]
    """The month, 1 to 12 or 13."""

    day_of_month: memoryview[int]
    """The day of the month."""

    resolution: memoryview[int]
    """How the date was resolved."""

    computed_month: memoryview[int]
    """The engine's month where it differs from the table's; zero otherwise."""

    computed_day: memoryview[int]
    """The engine's day where it differs from the table's; zero otherwise."""

    state_kind: memoryview[int]
    """Whether the day had a sunrise at all."""

    state_polar_kind: memoryview[int]
    """Which polar state it was, when it had none; zero otherwise."""

    state_polar_policy: memoryview[int]
    """Which policy synthesised its bounds, when it had none; zero otherwise."""

    convention_kind: memoryview[int]
    """Which sunrise convention the arc was reckoned by; `0xFF` for a custom altitude."""

    convention_value: memoryview[float]
    """The altitude in degrees when the convention is custom; zero otherwise."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class Charts:
    """A decoded Charts blob.

    A batch of founded charts at one place: the grahas placed, the bhavas under both readings, the zodiac, the day and the timing. Every per-chart section runs charts outermost, and a batch of one is the ordinary case.
    """

    kind: int
    """What kind of chart these are."""

    chart_count: int
    """How many charts the batch holds, and how many rows the `cast`, `day` and `timing` sections each hold."""

    graha_count: int
    """How many grahas each chart holds; the `grahas` section holds `chart_count * graha_count` rows."""

    latitude_deg: float
    """The place's latitude, degrees north."""

    longitude_deg: float
    """The place's longitude, degrees east."""

    altitude_m: float
    """The place's altitude, metres."""

    cast: ChartsCast
    """One row per chart, in the order the instants were asked for."""

    grahas: ChartsGrahas
    """One row per graha per chart, charts outermost: row `i * graha_count + j` is chart `i`, graha `j`, grahas in the catalogue's order. `house_*` is the bhava for "which house is it in"; `placement_*` is the chart's chalit, which is a different question and often a different answer."""

    houses_method: int
    """The system the houses were computed under."""

    houses_source: int
    """The system its cusps came from."""

    houses_reading: int
    """Which bound the houses are read against."""

    chalit_method: int
    """The system the chalit was computed under."""

    chalit_source: int
    """The system its cusps came from."""

    chalit_reading: int
    """Which bound the chalit is read against."""

    houses: ChartsHouses
    """The twelve bhavas for "which house is it in", charts outermost: row `i * 12 + j` is chart `i`, bhava `j`, first to twelfth."""

    chalit: ChartsChalit
    """The twelve bhavas of each chart's chalit, the same shape as `houses`."""

    frame_bits: int
    """The frame the positions were asked for, packed as the port packs it."""

    ayanamsha_kind: int
    """0 for none, 1 for a catalogued ayanamsha, 2 for one the settings define."""

    ayanamsha: int
    """Which catalogued ayanamsha, when the kind is 1."""

    day: Day
    """The day each instant belongs to: its arc, its date and how it was reckoned. One row per row of the blob's own grid."""

    timing: ChartsTiming
    """Where in its day each moment falls, in the reckonings the settings named: one row per chart."""

    model: str
    """UTF-8 text: the solar model that reckoned the days, as it describes itself."""

    steps: str
    """UTF-8 JSON: an array of strings, the completion steps applied in order, each `name:Implementation`. The positions blob carries the same steps as objects and spells the implementation differently (`PASS_THROUGH` against `PassThrough`); which of the two every blob should use is an open question (`03-design/chart-at-the-boundary.md` §8)."""

    provenance: str
    """UTF-8 JSON: the provenance envelope of the result, canonical."""


def decode_charts(raw: bytes) -> Charts:
    """Decodes a Charts blob.

    The columns are views over `raw`, so the buffer must outlive the
    result; a blob of another layout version or another schema is a
    `BlobError`.
    """
    blob = _Blob(raw, 3, "charts")
    at_summary = blob.section(1, "summary")
    at_cast = blob.section(2, "cast")
    at_grahas = blob.section(3, "grahas")
    at_readings = blob.section(4, "readings")
    at_houses = blob.section(5, "houses")
    at_chalit = blob.section(6, "chalit")
    at_zodiac = blob.section(7, "zodiac")
    at_day = blob.section(8, "day")
    at_timing = blob.section(9, "timing")
    at_model = blob.section(10, "model")
    at_steps = blob.section(11, "steps")
    at_provenance = blob.section(12, "provenance")
    return Charts(
        kind=int(blob.fixed(at_summary, 0, "H")),
        chart_count=int(blob.fixed(at_summary, 1, "I")),
        graha_count=int(blob.fixed(at_summary, 2, "I")),
        latitude_deg=blob.fixed(at_summary, 3, "d"),
        longitude_deg=blob.fixed(at_summary, 4, "d"),
        altitude_m=blob.fixed(at_summary, 5, "d"),
        cast=ChartsCast(
            instant=blob.column(at_cast, 0, 8, at_cast.count).cast("d"),
            lagna_deg=blob.column(at_cast, 1, 8, at_cast.count).cast("d"),
            day_lagna_deg=blob.column(at_cast, 2, 8, at_cast.count).cast("d"),
            ayanamsha_offset_deg=blob.column(
                at_cast, 3, 8, at_cast.count
            ).cast("d"),
            day_part=blob.column(at_cast, 4, 1, at_cast.count).cast("B"),
            day_elapsed=blob.column(at_cast, 5, 8, at_cast.count).cast("d"),
            length=at_cast.count,
        ),
        grahas=ChartsGrahas(
            graha=blob.column(at_grahas, 0, 2, at_grahas.count).cast("H"),
            longitude_deg=blob.column(
                at_grahas, 1, 8, at_grahas.count
            ).cast("d"),
            tropical_deg=blob.column(
                at_grahas, 2, 8, at_grahas.count
            ).cast("d"),
            latitude_deg=blob.column(
                at_grahas, 3, 8, at_grahas.count
            ).cast("d"),
            distance_au=blob.column(
                at_grahas, 4, 8, at_grahas.count
            ).cast("d"),
            speed_deg_per_day=blob.column(
                at_grahas, 5, 8, at_grahas.count
            ).cast("d"),
            house_bhava=blob.column(
                at_grahas, 6, 1, at_grahas.count
            ).cast("B"),
            house_method=blob.column(
                at_grahas, 7, 2, at_grahas.count
            ).cast("H"),
            house_through=blob.column(
                at_grahas, 8, 8, at_grahas.count
            ).cast("d"),
            house_from_madhya_deg=blob.column(
                at_grahas, 9, 8, at_grahas.count
            ).cast("d"),
            placement_bhava=blob.column(
                at_grahas, 10, 1, at_grahas.count
            ).cast("B"),
            placement_method=blob.column(
                at_grahas, 11, 2, at_grahas.count
            ).cast("H"),
            placement_through=blob.column(
                at_grahas, 12, 8, at_grahas.count
            ).cast("d"),
            placement_from_madhya_deg=blob.column(
                at_grahas, 13, 8, at_grahas.count
            ).cast("d"),
            length=at_grahas.count,
        ),
        houses_method=int(blob.fixed(at_readings, 0, "H")),
        houses_source=int(blob.fixed(at_readings, 1, "H")),
        houses_reading=int(blob.fixed(at_readings, 2, "B")),
        chalit_method=int(blob.fixed(at_readings, 3, "H")),
        chalit_source=int(blob.fixed(at_readings, 4, "H")),
        chalit_reading=int(blob.fixed(at_readings, 5, "B")),
        houses=ChartsHouses(
            madhya_deg=blob.column(at_houses, 0, 8, at_houses.count).cast("d"),
            sandhi_deg=blob.column(at_houses, 1, 8, at_houses.count).cast("d"),
            length=at_houses.count,
        ),
        chalit=ChartsChalit(
            madhya_deg=blob.column(at_chalit, 0, 8, at_chalit.count).cast("d"),
            sandhi_deg=blob.column(at_chalit, 1, 8, at_chalit.count).cast("d"),
            length=at_chalit.count,
        ),
        frame_bits=int(blob.fixed(at_zodiac, 0, "I")),
        ayanamsha_kind=int(blob.fixed(at_zodiac, 1, "B")),
        ayanamsha=int(blob.fixed(at_zodiac, 2, "H")),
        day=Day(
            sunrise=blob.column(at_day, 0, 8, at_day.count).cast("d"),
            sunset=blob.column(at_day, 1, 8, at_day.count).cast("d"),
            next_sunrise=blob.column(at_day, 2, 8, at_day.count).cast("d"),
            vara=blob.column(at_day, 3, 2, at_day.count).cast("H"),
            calendar=blob.column(at_day, 4, 2, at_day.count).cast("H"),
            era=blob.column(at_day, 5, 2, at_day.count).cast("H"),
            year=blob.column(at_day, 6, 4, at_day.count).cast("i"),
            era_year=blob.column(at_day, 7, 4, at_day.count).cast("i"),
            month=blob.column(at_day, 8, 1, at_day.count).cast("B"),
            day_of_month=blob.column(at_day, 9, 1, at_day.count).cast("B"),
            resolution=blob.column(at_day, 10, 1, at_day.count).cast("B"),
            computed_month=blob.column(at_day, 11, 1, at_day.count).cast("B"),
            computed_day=blob.column(at_day, 12, 1, at_day.count).cast("B"),
            state_kind=blob.column(at_day, 13, 1, at_day.count).cast("B"),
            state_polar_kind=blob.column(
                at_day, 14, 1, at_day.count
            ).cast("B"),
            state_polar_policy=blob.column(
                at_day, 15, 1, at_day.count
            ).cast("B"),
            convention_kind=blob.column(at_day, 16, 1, at_day.count).cast("B"),
            convention_value=blob.column(
                at_day, 17, 8, at_day.count
            ).cast("d"),
            length=at_day.count,
        ),
        timing=ChartsTiming(
            ghati=blob.column(at_timing, 0, 1, at_timing.count).cast("B"),
            pala=blob.column(at_timing, 1, 1, at_timing.count).cast("B"),
            vipala=blob.column(at_timing, 2, 1, at_timing.count).cast("B"),
            ghati_reckoning=blob.column(
                at_timing, 3, 1, at_timing.count
            ).cast("B"),
            hora_number=blob.column(
                at_timing, 4, 1, at_timing.count
            ).cast("B"),
            hora_lord=blob.column(at_timing, 5, 2, at_timing.count).cast("H"),
            hora_start=blob.column(at_timing, 6, 8, at_timing.count).cast("d"),
            hora_end=blob.column(at_timing, 7, 8, at_timing.count).cast("d"),
            hora_reckoning=blob.column(
                at_timing, 8, 1, at_timing.count
            ).cast("B"),
            length=at_timing.count,
        ),
        model=blob.text(at_model),
        steps=blob.text(at_steps),
        provenance=blob.text(at_provenance),
    )


@dataclass(frozen=True)
class PanchangaDays:
    """The `days` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    One row per day: what the day is, beside the `day` section's account of the day it belongs to. Three values a day may not have — the sankranti, Abhijit and Brahma muhurta — carry a presence flag beside them rather than a sentinel, because an absent instant and midnight are both nought.
    """

    window_from: memoryview[float]
    """When the window the day's spans are clipped to begins, as a Julian day (UTC)."""

    window_to: memoryview[float]
    """When the window the day's spans are clipped to ends, as a Julian day (UTC)."""

    month: memoryview[int]
    """The lunar month under the profile's own convention."""

    amanta: memoryview[int]
    """The amanta month: new moon to new moon."""

    purnimanta: memoryview[int]
    """The purnimanta month: full moon to full moon."""

    paksha: memoryview[int]
    """The fortnight the day opens in."""

    month_kind: memoryview[int]
    """Whether the month is ordinary, intercalary or omitted. The month's *name* needs no case for the intercalary one — the Sun stands in the same sign at an adhika month's new moon as at the following nija month's, so `month` names both — and this is the mark beside it."""

    ayana: memoryview[int]
    """Which half of the year the day falls in."""

    disha_shool: memoryview[int]
    """The direction not to travel in, which is the vara's."""

    has_sankranti: memoryview[int]
    """1 when the Sun entered a new sign inside the day, 0 otherwise."""

    sankranti: memoryview[float]
    """When it did, as a Julian day (UTC); zero when it did not, which `has_sankranti` is what distinguishes from midnight."""

    has_abhijit: memoryview[int]
    """1 when the day has an Abhijit muhurta, 0 on a day with no daylight."""

    abhijit_from: memoryview[float]
    """When Abhijit begins, as a Julian day (UTC)."""

    abhijit_to: memoryview[float]
    """When Abhijit ends, as a Julian day (UTC)."""

    abhijit_effective: memoryview[int]
    """1 when Abhijit is effective, which it is on every day but a Wednesday."""

    has_brahma: memoryview[int]
    """1 when the night that ends at this day's sunrise is known, 0 in the polar case."""

    brahma_from: memoryview[float]
    """When Brahma muhurta begins, as a Julian day (UTC)."""

    brahma_to: memoryview[float]
    """When Brahma muhurta ends, as a Julian day (UTC)."""

    moon_window_from: memoryview[float]
    """When the window the Moon's rises and sets were looked for in begins, as a Julian day (UTC)."""

    moon_window_to: memoryview[float]
    """When the window the Moon's rises and sets were looked for in ends, as a Julian day (UTC)."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaCounts:
    """The `counts` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    How many rows of each per-day section belong to each day, in the order the days run. A day's rows begin where the sum of every earlier day's count leaves off.
    """

    tithi: memoryview[int]
    """How many rows of `tithi` belong to this day."""

    nakshatra: memoryview[int]
    """How many rows of `nakshatra` belong to this day."""

    yoga: memoryview[int]
    """How many rows of `yoga` belong to this day."""

    karana: memoryview[int]
    """How many rows of `karana` belong to this day."""

    panchaka: memoryview[int]
    """How many rows of `panchaka` belong to this day."""

    moon_signs: memoryview[int]
    """How many rows of `moon_signs` belong to this day."""

    sun_signs: memoryview[int]
    """How many rows of `sun_signs` belong to this day."""

    kaalas: memoryview[int]
    """How many rows of `kaalas` belong to this day."""

    choghadiya: memoryview[int]
    """How many rows of `choghadiya` belong to this day."""

    horas: memoryview[int]
    """How many rows of `horas` belong to this day."""

    muhurtas: memoryview[int]
    """How many rows of `muhurtas` belong to this day."""

    moon_events: memoryview[int]
    """How many rows of `moon_events` belong to this day."""

    muhurta_yogas: memoryview[int]
    """How many rows of `muhurta_yogas` belong to this day."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaTithi:
    """The `tithi` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The tithis that touch each day.
    """

    member: memoryview[int]
    """Which tithi ran."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaNakshatra:
    """The `nakshatra` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The nakshatras the Moon was in.
    """

    member: memoryview[int]
    """Which nakshatra the Moon was in."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaYoga:
    """The `yoga` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The nitya yogas.
    """

    member: memoryview[int]
    """Which nitya yoga ran."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaKarana:
    """The `karana` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The karanas; half-tithis, so there are three or four on an ordinary day.
    """

    member: memoryview[int]
    """Which karana ran."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaPanchaka:
    """The `panchaka` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    Panchaka, while the Moon is in the last five nakshatras.
    """

    member: memoryview[int]
    """Which panchaka held."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaMoonSigns:
    """The `moon_signs` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The signs the Moon stood in, with when it entered and left each.
    """

    member: memoryview[int]
    """Which sign the Moon was in."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaSunSigns:
    """The `sun_signs` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The signs the Sun stood in; two only on a sankranti day.
    """

    member: memoryview[int]
    """Which sign the Sun was in."""

    whole_from: memoryview[float]
    """When the member itself began, as a Julian day (UTC), whether or not that is inside the day."""

    whole_to: memoryview[float]
    """When the member itself ended, as a Julian day (UTC), whether or not that is inside the day."""

    inside_from: memoryview[float]
    """Where the part inside the day begins: what an almanac row prints."""

    inside_to: memoryview[float]
    """Where the part inside the day ends."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaKaalas:
    """The `kaalas` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The inauspicious eighths of the daylight each day has.
    """

    kaala: memoryview[int]
    """Which one."""

    from_: memoryview[float]
    """When it begins, as a Julian day (UTC)."""

    to: memoryview[float]
    """When it ends, as a Julian day (UTC)."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaChoghadiya:
    """The `choghadiya` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    Eight choghadiya of the daylight and eight of the night, when the day has both.
    """

    choghadiya: memoryview[int]
    """Which choghadiya."""

    lord: memoryview[int]
    """The graha that rules it."""

    from_: memoryview[float]
    """When it begins, as a Julian day (UTC)."""

    to: memoryview[float]
    """When it ends, as a Julian day (UTC)."""

    daytime: memoryview[int]
    """1 when it is one of the eight of the daylight, 0 for one of the night."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaHoras:
    """The `horas` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The twenty-four horas of each day, from sunrise.
    """

    number: memoryview[int]
    """The hora's number, 1 to 24 from sunrise."""

    lord: memoryview[int]
    """The graha that rules it."""

    start: memoryview[float]
    """When it begins, as a Julian day (UTC)."""

    end: memoryview[float]
    """When it ends, as a Julian day (UTC)."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaMuhurtas:
    """The `muhurtas` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The thirty muhurtas of each day: fifteen of the daylight and fifteen of the night that follows it, in order. Abhijit and Brahma muhurta are named in `days` rather than repeated here.
    """

    from_: memoryview[float]
    """When it begins, as a Julian day (UTC)."""

    to: memoryview[float]
    """When it ends, as a Julian day (UTC)."""

    daylight: memoryview[int]
    """1 when it is one of the fifteen of the daylight, 0 for one of the night."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaMoonEvents:
    """The `moon_events` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    Every moonrise and moonset inside each day's moon window, in order.
    """

    kind: memoryview[int]
    """Whether the Moon rose or set."""

    instant: memoryview[float]
    """When, as a Julian day (UTC)."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class PanchangaMuhurtaYogas:
    """The `muhurta_yogas` section of a Panchanga blob: one column per field, each a view
    over the blob's bytes rather than a copy.

    The muhurta yogas that held, with what made each hold. `because_*` is a tagged enum split into a kind and the payload fields of its widest variant, so a `VARA_NAKSHATRA` cause leaves `because_tithi` at zero.
    """

    yoga: memoryview[int]
    """Which yoga."""

    from_: memoryview[float]
    """When it begins, as a Julian day (UTC)."""

    to: memoryview[float]
    """When it ends, as a Julian day (UTC)."""

    because_kind: memoryview[int]
    """What made it hold."""

    because_vara: memoryview[int]
    """The vara that makes it; every cause has one."""

    because_tithi: memoryview[int]
    """The tithi that makes it, when the cause has one; zero otherwise."""

    because_nakshatra: memoryview[int]
    """The nakshatra that makes it; every cause has one."""

    length: int
    """The number of rows every column holds."""


@dataclass(frozen=True)
class Panchanga:
    """A decoded Panchanga blob.

    A batch of daily panchangas at one place: the day, the four moving limbs, the periods, the lunar month, what the Moon and the Sun did, and what the day is said to be. Every per-day list is concatenated across the batch, with `counts` saying how many rows are each day's.
    """

    day_count: int
    """How many days the batch holds, and how many rows the `days`, `counts` and `day` sections each hold."""

    latitude_deg: float
    """The place's latitude, degrees north."""

    longitude_deg: float
    """The place's longitude, degrees east."""

    altitude_m: float
    """The place's altitude, metres."""

    calendar: int
    """The civil calendar the days' dates are read in."""

    lunar_month: int
    """Which lunar-month convention `days.month` leads with."""

    days: PanchangaDays
    """One row per day: what the day is, beside the `day` section's account of the day it belongs to. Three values a day may not have — the sankranti, Abhijit and Brahma muhurta — carry a presence flag beside them rather than a sentinel, because an absent instant and midnight are both nought."""

    counts: PanchangaCounts
    """How many rows of each per-day section belong to each day, in the order the days run. A day's rows begin where the sum of every earlier day's count leaves off."""

    day: Day
    """The day each instant belongs to: its arc, its date and how it was reckoned. One row per row of the blob's own grid."""

    tithi: PanchangaTithi
    """The tithis that touch each day."""

    nakshatra: PanchangaNakshatra
    """The nakshatras the Moon was in."""

    yoga: PanchangaYoga
    """The nitya yogas."""

    karana: PanchangaKarana
    """The karanas; half-tithis, so there are three or four on an ordinary day."""

    panchaka: PanchangaPanchaka
    """Panchaka, while the Moon is in the last five nakshatras."""

    moon_signs: PanchangaMoonSigns
    """The signs the Moon stood in, with when it entered and left each."""

    sun_signs: PanchangaSunSigns
    """The signs the Sun stood in; two only on a sankranti day."""

    kaalas: PanchangaKaalas
    """The inauspicious eighths of the daylight each day has."""

    choghadiya: PanchangaChoghadiya
    """Eight choghadiya of the daylight and eight of the night, when the day has both."""

    horas: PanchangaHoras
    """The twenty-four horas of each day, from sunrise."""

    muhurtas: PanchangaMuhurtas
    """The thirty muhurtas of each day: fifteen of the daylight and fifteen of the night that follows it, in order. Abhijit and Brahma muhurta are named in `days` rather than repeated here."""

    moon_events: PanchangaMoonEvents
    """Every moonrise and moonset inside each day's moon window, in order."""

    muhurta_yogas: PanchangaMuhurtaYogas
    """The muhurta yogas that held, with what made each hold. `because_*` is a tagged enum split into a kind and the payload fields of its widest variant, so a `VARA_NAKSHATRA` cause leaves `because_tithi` at zero."""

    model: str
    """UTF-8 text: the solar model that reckoned the days, as it describes itself."""

    provenance: str
    """UTF-8 JSON: the provenance envelope of the result, canonical."""


def decode_panchanga(raw: bytes) -> Panchanga:
    """Decodes a Panchanga blob.

    The columns are views over `raw`, so the buffer must outlive the
    result; a blob of another layout version or another schema is a
    `BlobError`.
    """
    blob = _Blob(raw, 4, "panchanga")
    at_summary = blob.section(1, "summary")
    at_days = blob.section(2, "days")
    at_counts = blob.section(3, "counts")
    at_day = blob.section(4, "day")
    at_tithi = blob.section(5, "tithi")
    at_nakshatra = blob.section(6, "nakshatra")
    at_yoga = blob.section(7, "yoga")
    at_karana = blob.section(8, "karana")
    at_panchaka = blob.section(9, "panchaka")
    at_moon_signs = blob.section(10, "moon_signs")
    at_sun_signs = blob.section(11, "sun_signs")
    at_kaalas = blob.section(12, "kaalas")
    at_choghadiya = blob.section(13, "choghadiya")
    at_horas = blob.section(14, "horas")
    at_muhurtas = blob.section(15, "muhurtas")
    at_moon_events = blob.section(16, "moon_events")
    at_muhurta_yogas = blob.section(17, "muhurta_yogas")
    at_model = blob.section(18, "model")
    at_provenance = blob.section(19, "provenance")
    return Panchanga(
        day_count=int(blob.fixed(at_summary, 0, "I")),
        latitude_deg=blob.fixed(at_summary, 1, "d"),
        longitude_deg=blob.fixed(at_summary, 2, "d"),
        altitude_m=blob.fixed(at_summary, 3, "d"),
        calendar=int(blob.fixed(at_summary, 4, "H")),
        lunar_month=int(blob.fixed(at_summary, 5, "B")),
        days=PanchangaDays(
            window_from=blob.column(at_days, 0, 8, at_days.count).cast("d"),
            window_to=blob.column(at_days, 1, 8, at_days.count).cast("d"),
            month=blob.column(at_days, 2, 2, at_days.count).cast("H"),
            amanta=blob.column(at_days, 3, 2, at_days.count).cast("H"),
            purnimanta=blob.column(at_days, 4, 2, at_days.count).cast("H"),
            paksha=blob.column(at_days, 5, 2, at_days.count).cast("H"),
            month_kind=blob.column(at_days, 6, 1, at_days.count).cast("B"),
            ayana=blob.column(at_days, 7, 2, at_days.count).cast("H"),
            disha_shool=blob.column(at_days, 8, 2, at_days.count).cast("H"),
            has_sankranti=blob.column(at_days, 9, 1, at_days.count).cast("B"),
            sankranti=blob.column(at_days, 10, 8, at_days.count).cast("d"),
            has_abhijit=blob.column(at_days, 11, 1, at_days.count).cast("B"),
            abhijit_from=blob.column(at_days, 12, 8, at_days.count).cast("d"),
            abhijit_to=blob.column(at_days, 13, 8, at_days.count).cast("d"),
            abhijit_effective=blob.column(
                at_days, 14, 1, at_days.count
            ).cast("B"),
            has_brahma=blob.column(at_days, 15, 1, at_days.count).cast("B"),
            brahma_from=blob.column(at_days, 16, 8, at_days.count).cast("d"),
            brahma_to=blob.column(at_days, 17, 8, at_days.count).cast("d"),
            moon_window_from=blob.column(
                at_days, 18, 8, at_days.count
            ).cast("d"),
            moon_window_to=blob.column(
                at_days, 19, 8, at_days.count
            ).cast("d"),
            length=at_days.count,
        ),
        counts=PanchangaCounts(
            tithi=blob.column(at_counts, 0, 4, at_counts.count).cast("I"),
            nakshatra=blob.column(at_counts, 1, 4, at_counts.count).cast("I"),
            yoga=blob.column(at_counts, 2, 4, at_counts.count).cast("I"),
            karana=blob.column(at_counts, 3, 4, at_counts.count).cast("I"),
            panchaka=blob.column(at_counts, 4, 4, at_counts.count).cast("I"),
            moon_signs=blob.column(at_counts, 5, 4, at_counts.count).cast("I"),
            sun_signs=blob.column(at_counts, 6, 4, at_counts.count).cast("I"),
            kaalas=blob.column(at_counts, 7, 4, at_counts.count).cast("I"),
            choghadiya=blob.column(at_counts, 8, 4, at_counts.count).cast("I"),
            horas=blob.column(at_counts, 9, 4, at_counts.count).cast("I"),
            muhurtas=blob.column(at_counts, 10, 4, at_counts.count).cast("I"),
            moon_events=blob.column(
                at_counts, 11, 4, at_counts.count
            ).cast("I"),
            muhurta_yogas=blob.column(
                at_counts, 12, 4, at_counts.count
            ).cast("I"),
            length=at_counts.count,
        ),
        day=Day(
            sunrise=blob.column(at_day, 0, 8, at_day.count).cast("d"),
            sunset=blob.column(at_day, 1, 8, at_day.count).cast("d"),
            next_sunrise=blob.column(at_day, 2, 8, at_day.count).cast("d"),
            vara=blob.column(at_day, 3, 2, at_day.count).cast("H"),
            calendar=blob.column(at_day, 4, 2, at_day.count).cast("H"),
            era=blob.column(at_day, 5, 2, at_day.count).cast("H"),
            year=blob.column(at_day, 6, 4, at_day.count).cast("i"),
            era_year=blob.column(at_day, 7, 4, at_day.count).cast("i"),
            month=blob.column(at_day, 8, 1, at_day.count).cast("B"),
            day_of_month=blob.column(at_day, 9, 1, at_day.count).cast("B"),
            resolution=blob.column(at_day, 10, 1, at_day.count).cast("B"),
            computed_month=blob.column(at_day, 11, 1, at_day.count).cast("B"),
            computed_day=blob.column(at_day, 12, 1, at_day.count).cast("B"),
            state_kind=blob.column(at_day, 13, 1, at_day.count).cast("B"),
            state_polar_kind=blob.column(
                at_day, 14, 1, at_day.count
            ).cast("B"),
            state_polar_policy=blob.column(
                at_day, 15, 1, at_day.count
            ).cast("B"),
            convention_kind=blob.column(at_day, 16, 1, at_day.count).cast("B"),
            convention_value=blob.column(
                at_day, 17, 8, at_day.count
            ).cast("d"),
            length=at_day.count,
        ),
        tithi=PanchangaTithi(
            member=blob.column(at_tithi, 0, 2, at_tithi.count).cast("H"),
            whole_from=blob.column(at_tithi, 1, 8, at_tithi.count).cast("d"),
            whole_to=blob.column(at_tithi, 2, 8, at_tithi.count).cast("d"),
            inside_from=blob.column(at_tithi, 3, 8, at_tithi.count).cast("d"),
            inside_to=blob.column(at_tithi, 4, 8, at_tithi.count).cast("d"),
            length=at_tithi.count,
        ),
        nakshatra=PanchangaNakshatra(
            member=blob.column(
                at_nakshatra, 0, 2, at_nakshatra.count
            ).cast("H"),
            whole_from=blob.column(
                at_nakshatra, 1, 8, at_nakshatra.count
            ).cast("d"),
            whole_to=blob.column(
                at_nakshatra, 2, 8, at_nakshatra.count
            ).cast("d"),
            inside_from=blob.column(
                at_nakshatra, 3, 8, at_nakshatra.count
            ).cast("d"),
            inside_to=blob.column(
                at_nakshatra, 4, 8, at_nakshatra.count
            ).cast("d"),
            length=at_nakshatra.count,
        ),
        yoga=PanchangaYoga(
            member=blob.column(at_yoga, 0, 2, at_yoga.count).cast("H"),
            whole_from=blob.column(at_yoga, 1, 8, at_yoga.count).cast("d"),
            whole_to=blob.column(at_yoga, 2, 8, at_yoga.count).cast("d"),
            inside_from=blob.column(at_yoga, 3, 8, at_yoga.count).cast("d"),
            inside_to=blob.column(at_yoga, 4, 8, at_yoga.count).cast("d"),
            length=at_yoga.count,
        ),
        karana=PanchangaKarana(
            member=blob.column(at_karana, 0, 2, at_karana.count).cast("H"),
            whole_from=blob.column(at_karana, 1, 8, at_karana.count).cast("d"),
            whole_to=blob.column(at_karana, 2, 8, at_karana.count).cast("d"),
            inside_from=blob.column(
                at_karana, 3, 8, at_karana.count
            ).cast("d"),
            inside_to=blob.column(at_karana, 4, 8, at_karana.count).cast("d"),
            length=at_karana.count,
        ),
        panchaka=PanchangaPanchaka(
            member=blob.column(at_panchaka, 0, 2, at_panchaka.count).cast("H"),
            whole_from=blob.column(
                at_panchaka, 1, 8, at_panchaka.count
            ).cast("d"),
            whole_to=blob.column(
                at_panchaka, 2, 8, at_panchaka.count
            ).cast("d"),
            inside_from=blob.column(
                at_panchaka, 3, 8, at_panchaka.count
            ).cast("d"),
            inside_to=blob.column(
                at_panchaka, 4, 8, at_panchaka.count
            ).cast("d"),
            length=at_panchaka.count,
        ),
        moon_signs=PanchangaMoonSigns(
            member=blob.column(
                at_moon_signs, 0, 2, at_moon_signs.count
            ).cast("H"),
            whole_from=blob.column(
                at_moon_signs, 1, 8, at_moon_signs.count
            ).cast("d"),
            whole_to=blob.column(
                at_moon_signs, 2, 8, at_moon_signs.count
            ).cast("d"),
            inside_from=blob.column(
                at_moon_signs, 3, 8, at_moon_signs.count
            ).cast("d"),
            inside_to=blob.column(
                at_moon_signs, 4, 8, at_moon_signs.count
            ).cast("d"),
            length=at_moon_signs.count,
        ),
        sun_signs=PanchangaSunSigns(
            member=blob.column(
                at_sun_signs, 0, 2, at_sun_signs.count
            ).cast("H"),
            whole_from=blob.column(
                at_sun_signs, 1, 8, at_sun_signs.count
            ).cast("d"),
            whole_to=blob.column(
                at_sun_signs, 2, 8, at_sun_signs.count
            ).cast("d"),
            inside_from=blob.column(
                at_sun_signs, 3, 8, at_sun_signs.count
            ).cast("d"),
            inside_to=blob.column(
                at_sun_signs, 4, 8, at_sun_signs.count
            ).cast("d"),
            length=at_sun_signs.count,
        ),
        kaalas=PanchangaKaalas(
            kaala=blob.column(at_kaalas, 0, 2, at_kaalas.count).cast("H"),
            from_=blob.column(at_kaalas, 1, 8, at_kaalas.count).cast("d"),
            to=blob.column(at_kaalas, 2, 8, at_kaalas.count).cast("d"),
            length=at_kaalas.count,
        ),
        choghadiya=PanchangaChoghadiya(
            choghadiya=blob.column(
                at_choghadiya, 0, 2, at_choghadiya.count
            ).cast("H"),
            lord=blob.column(
                at_choghadiya, 1, 2, at_choghadiya.count
            ).cast("H"),
            from_=blob.column(
                at_choghadiya, 2, 8, at_choghadiya.count
            ).cast("d"),
            to=blob.column(at_choghadiya, 3, 8, at_choghadiya.count).cast("d"),
            daytime=blob.column(
                at_choghadiya, 4, 1, at_choghadiya.count
            ).cast("B"),
            length=at_choghadiya.count,
        ),
        horas=PanchangaHoras(
            number=blob.column(at_horas, 0, 1, at_horas.count).cast("B"),
            lord=blob.column(at_horas, 1, 2, at_horas.count).cast("H"),
            start=blob.column(at_horas, 2, 8, at_horas.count).cast("d"),
            end=blob.column(at_horas, 3, 8, at_horas.count).cast("d"),
            length=at_horas.count,
        ),
        muhurtas=PanchangaMuhurtas(
            from_=blob.column(at_muhurtas, 0, 8, at_muhurtas.count).cast("d"),
            to=blob.column(at_muhurtas, 1, 8, at_muhurtas.count).cast("d"),
            daylight=blob.column(
                at_muhurtas, 2, 1, at_muhurtas.count
            ).cast("B"),
            length=at_muhurtas.count,
        ),
        moon_events=PanchangaMoonEvents(
            kind=blob.column(
                at_moon_events, 0, 1, at_moon_events.count
            ).cast("B"),
            instant=blob.column(
                at_moon_events, 1, 8, at_moon_events.count
            ).cast("d"),
            length=at_moon_events.count,
        ),
        muhurta_yogas=PanchangaMuhurtaYogas(
            yoga=blob.column(
                at_muhurta_yogas, 0, 2, at_muhurta_yogas.count
            ).cast("H"),
            from_=blob.column(
                at_muhurta_yogas, 1, 8, at_muhurta_yogas.count
            ).cast("d"),
            to=blob.column(
                at_muhurta_yogas, 2, 8, at_muhurta_yogas.count
            ).cast("d"),
            because_kind=blob.column(
                at_muhurta_yogas, 3, 1, at_muhurta_yogas.count
            ).cast("B"),
            because_vara=blob.column(
                at_muhurta_yogas, 4, 2, at_muhurta_yogas.count
            ).cast("H"),
            because_tithi=blob.column(
                at_muhurta_yogas, 5, 2, at_muhurta_yogas.count
            ).cast("H"),
            because_nakshatra=blob.column(
                at_muhurta_yogas, 6, 2, at_muhurta_yogas.count
            ).cast("H"),
            length=at_muhurta_yogas.count,
        ),
        model=blob.text(at_model),
        provenance=blob.text(at_provenance),
    )


