//! GENERATED by teistro-spike-a-gen from spikes/02-binding-toolchain/a-ffi/src/lib.rs. Do not edit; run the generator.
#![allow(
    unsafe_code,
    missing_docs,
    missing_debug_implementations,
    unreachable_pub,
    dead_code,
    clippy::all,
    clippy::pedantic,
    reason = "generated glue; the contract is the API description"
)]

use core::cell::Cell;
use core::ffi::{CStr, c_void};
use core::ptr;

use napi::bindgen_prelude::*;
use napi_derive::napi;
use teistro_spike_a_ffi as ffi;

/// The status of every call. `0` is success; everything else names the
/// failure, with the same numbers in every binding.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[napi(string_enum = "kebab-case")]
pub enum Status {
    /// Success.
    Ok,
    /// A null pointer, a wrong `struct_size`, or an enum index outside its
    /// range.
    InvalidArgument,
    /// `dasha_depth` outside `1..=5`.
    DepthOutOfRange,
    /// The Julian Day is NaN or infinite.
    JulianDayNotFinite,
    /// The provider failed; `tsp_context_last_provider_code` has its code.
    Provider,
    /// The provider returned a non-finite longitude.
    PositionNotFinite,
}

impl Status {
    pub fn to_ffi(self) -> i32 {
        match self {
            Status::Ok => 0,
            Status::InvalidArgument => -1,
            Status::DepthOutOfRange => -2,
            Status::JulianDayNotFinite => -3,
            Status::Provider => -4,
            Status::PositionNotFinite => -5,
        }
    }

    pub fn from_ffi(value: i32) -> Option<Self> {
        match value {
            0 => Some(Status::Ok),
            -1 => Some(Status::InvalidArgument),
            -2 => Some(Status::DepthOutOfRange),
            -3 => Some(Status::JulianDayNotFinite),
            -4 => Some(Status::Provider),
            -5 => Some(Status::PositionNotFinite),
            _ => None,
        }
    }

    pub fn to_ffi_enum(self) -> ffi::TspStatus {
        match self {
            Status::Ok => ffi::TspStatus::Ok,
            Status::InvalidArgument => ffi::TspStatus::InvalidArgument,
            Status::DepthOutOfRange => ffi::TspStatus::DepthOutOfRange,
            Status::JulianDayNotFinite => ffi::TspStatus::JulianDayNotFinite,
            Status::Provider => ffi::TspStatus::Provider,
            Status::PositionNotFinite => ffi::TspStatus::PositionNotFinite,
        }
    }
}

/// The ayanamsha catalogue.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[napi(string_enum = "kebab-case")]
pub enum Ayanamsha {
    /// Lahiri (Chitrapaksha), the default.
    Lahiri,
    /// B. V. Raman.
    Raman,
    /// K. S. Krishnamurti.
    Krishnamurti,
}

impl Ayanamsha {
    pub fn to_ffi(self) -> u8 {
        match self {
            Ayanamsha::Lahiri => 0,
            Ayanamsha::Raman => 1,
            Ayanamsha::Krishnamurti => 2,
        }
    }

    pub fn from_ffi(value: u8) -> Option<Self> {
        match value {
            0 => Some(Ayanamsha::Lahiri),
            1 => Some(Ayanamsha::Raman),
            2 => Some(Ayanamsha::Krishnamurti),
            _ => None,
        }
    }

    pub fn to_ffi_enum(self) -> ffi::TspAyanamsha {
        match self {
            Ayanamsha::Lahiri => ffi::TspAyanamsha::Lahiri,
            Ayanamsha::Raman => ffi::TspAyanamsha::Raman,
            Ayanamsha::Krishnamurti => ffi::TspAyanamsha::Krishnamurti,
        }
    }
}

/// Which lunar node the provider is asked for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[napi(string_enum = "kebab-case")]
pub enum NodeKind {
    /// The mean node.
    Mean,
    /// The true node.
    True,
}

impl NodeKind {
    pub fn to_ffi(self) -> u8 {
        match self {
            NodeKind::Mean => 0,
            NodeKind::True => 1,
        }
    }

    pub fn from_ffi(value: u8) -> Option<Self> {
        match value {
            0 => Some(NodeKind::Mean),
            1 => Some(NodeKind::True),
            _ => None,
        }
    }

    pub fn to_ffi_enum(self) -> ffi::TspNodeKind {
        match self {
            NodeKind::Mean => ffi::TspNodeKind::Mean,
            NodeKind::True => ffi::TspNodeKind::True,
        }
    }
}

/// The nine bodies, the index every position column uses.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[napi(string_enum = "kebab-case")]
pub enum Body {
    /// The Sun.
    Sun,
    /// The Moon.
    Moon,
    /// Mars.
    Mars,
    /// Mercury.
    Mercury,
    /// Jupiter.
    Jupiter,
    /// Venus.
    Venus,
    /// Saturn.
    Saturn,
    /// The ascending node.
    Rahu,
    /// The descending node.
    Ketu,
}

impl Body {
    pub fn to_ffi(self) -> u8 {
        match self {
            Body::Sun => 0,
            Body::Moon => 1,
            Body::Mars => 2,
            Body::Mercury => 3,
            Body::Jupiter => 4,
            Body::Venus => 5,
            Body::Saturn => 6,
            Body::Rahu => 7,
            Body::Ketu => 8,
        }
    }

    pub fn from_ffi(value: u8) -> Option<Self> {
        match value {
            0 => Some(Body::Sun),
            1 => Some(Body::Moon),
            2 => Some(Body::Mars),
            3 => Some(Body::Mercury),
            4 => Some(Body::Jupiter),
            5 => Some(Body::Venus),
            6 => Some(Body::Saturn),
            7 => Some(Body::Rahu),
            8 => Some(Body::Ketu),
            _ => None,
        }
    }

    pub fn to_ffi_enum(self) -> ffi::TspBody {
        match self {
            Body::Sun => ffi::TspBody::Sun,
            Body::Moon => ffi::TspBody::Moon,
            Body::Mars => ffi::TspBody::Mars,
            Body::Mercury => ffi::TspBody::Mercury,
            Body::Jupiter => ffi::TspBody::Jupiter,
            Body::Venus => ffi::TspBody::Venus,
            Body::Saturn => ffi::TspBody::Saturn,
            Body::Rahu => ffi::TspBody::Rahu,
            Body::Ketu => ffi::TspBody::Ketu,
        }
    }
}

/// The settings of a context.
#[napi(object)]
#[derive(Clone, Debug)]
pub struct Settings {
    /// The ayanamsha: `0` Lahiri, `1` Raman, `2` Krishnamurti.
    /// Example: 0.
    pub ayanamsha: Ayanamsha,
    /// The lunar node: `0` mean, `1` true.
    /// Example: 0.
    pub node: NodeKind,
    /// Dasha levels to build, `1` to `5`; the tree has `9^depth` leaves.
    /// Range: [1,5]. Example: 3.
    pub dasha_depth: u8,
}

impl Settings {
    pub fn to_ffi(&self) -> ffi::TspSettings {
        ffi::TspSettings {
            struct_size: core::mem::size_of::<ffi::TspSettings>() as u32,
            ayanamsha: self.ayanamsha.to_ffi(),
            node: self.node.to_ffi(),
            dasha_depth: self.dasha_depth,
            reserved: 0,
        }
    }

    pub fn from_ffi(raw: &ffi::TspSettings) -> Result<Self> {
        Ok(Settings {
            ayanamsha: Ayanamsha::from_ffi(raw.ayanamsha)
                .ok_or_else(|| Error::from_reason("unknown ayanamsha value"))?,
            node: NodeKind::from_ffi(raw.node)
                .ok_or_else(|| Error::from_reason("unknown node value"))?,
            dasha_depth: raw.dasha_depth,
        })
    }
}

/// A tropical position, the provider's answer.
#[napi(object)]
#[derive(Clone, Debug)]
pub struct Position {
    /// Tropical ecliptic longitude in degrees; any real number.
    /// Unit: deg. Example: 280.46.
    pub longitude_deg: f64,
    /// Ecliptic latitude in degrees.
    /// Unit: deg. Range: [-90,90]. Example: 0.0.
    pub latitude_deg: f64,
    /// Longitude speed in degrees per day; negative is retrograde.
    /// Unit: deg/day. Example: 0.9856.
    pub speed_deg_per_day: f64,
}

impl Position {
    pub fn to_ffi(&self) -> ffi::TspPosition {
        ffi::TspPosition {
            longitude_deg: self.longitude_deg,
            latitude_deg: self.latitude_deg,
            speed_deg_per_day: self.speed_deg_per_day,
        }
    }
}

/// Turns a non-`Ok` status into a JavaScript error whose message ends
/// with the stable code, `(code -4)`, and the provider's own code when
/// there is one.
fn status_error(status: ffi::TspStatus, provider_code: i32) -> Error {
    // SAFETY: the library returns a static NUL-terminated string.
    let message = unsafe { CStr::from_ptr(ffi::tsp_status_message(status)) }
        .to_string_lossy()
        .into_owned();
    let code = status as i32;
    let detail = if provider_code != 0 {
        format!("; provider code {provider_code}")
    } else {
        String::new()
    };
    Error::from_reason(format!("{message} (code {code}){detail}"))
}

fn check(status: ffi::TspStatus, provider_code: i32) -> Result<()> {
    if status == ffi::TspStatus::Ok {
        Ok(())
    } else {
        Err(status_error(status, provider_code))
    }
}

/// The JavaScript provider, as `TspPositionFn` sees it.
pub type ProviderFn = FunctionRef<FnArgs<(f64, u32)>, Position>;

/// What `user_data` points at while a batch call runs.
pub struct HostSlot {
    pub env: Cell<Option<Env>>,
    pub func: ProviderFn,
    pub error: Cell<Option<String>>,
}

unsafe extern "C" fn tsp_position_fn_trampoline(
    user_data: *mut c_void,
    jd_ut: f64,
    body: u32,
    out_position: *mut ffi::TspPosition,
) -> i32 {
    // SAFETY: `user_data` is the `HostSlot` this module registered in the
    // constructor, alive while the context is.
    let slot = unsafe { &*user_data.cast::<HostSlot>() };
    let Some(env) = slot.env.get() else {
        slot.error
            .set(Some(String::from("provider called outside a batch call")));
        return -1001;
    };
    let called = slot
        .func
        .borrow_back(&env)
        .and_then(|f| f.call((jd_ut, body).into()));
    match called {
        Ok(value) => {
            // SAFETY: the library passes a valid, writable out pointer.
            unsafe { out_position.write(value.to_ffi()) };
            0
        }
        Err(err) => {
            slot.error.set(Some(err.to_string()));
            -1002
        }
    }
}

/// An opaque context: settings plus a provider. Not thread-safe; one per
/// thread, as the architecture requires.
#[napi]
pub struct Context {
    handle: *mut ffi::TspContext,
    host: Option<Box<HostSlot>>,
}

#[napi]
impl Context {
    /// Creates a context. `provider` may be null, which selects the built-in
    /// analytic test provider; otherwise its `position` must be non-null and
    /// `user_data` stays valid until `tsp_context_free`. On success
    /// `*out_context` owns the context.
    #[napi(constructor)]
    pub fn new(
        settings: Settings,
        provider: Option<Function<FnArgs<(f64, u32)>, Position>>,
    ) -> Result<Self> {
        let raw_settings = settings.to_ffi();
        let host = match provider {
            Some(f) => Some(Box::new(HostSlot {
                env: Cell::new(None),
                func: f.create_ref()?,
                error: Cell::new(None),
            })),
            None => None,
        };
        let vtable = ffi::TspProviderVtable {
            struct_size: core::mem::size_of::<ffi::TspProviderVtable>() as u32,
            position: Some(tsp_position_fn_trampoline),
        };
        let (vtable_ptr, user_data): (*const ffi::TspProviderVtable, *mut c_void) = match &host {
            Some(slot) => (
                &raw const vtable,
                ptr::from_ref::<HostSlot>(&**slot).cast_mut().cast(),
            ),
            None => (ptr::null(), ptr::null_mut()),
        };
        let mut handle: *mut ffi::TspContext = ptr::null_mut();

        // SAFETY: every pointer is valid for the call; `user_data` outlives the context.
        let status = unsafe {
            ffi::tsp_context_new(
                &raw const raw_settings,
                vtable_ptr,
                user_data,
                &raw mut handle,
            )
        };
        check(status, 0)?;
        Ok(Context { handle, host })
    }

    /// Copies the context's settings into `out_settings` (its `struct_size`
    /// set by the caller).
    #[napi]
    pub fn settings(&self) -> Result<Settings> {
        // SAFETY: every field of the struct is a plain integer, so zero is a valid value.
        let mut raw: ffi::TspSettings = unsafe { core::mem::zeroed() };
        raw.struct_size = core::mem::size_of::<ffi::TspSettings>() as u32;
        // SAFETY: the handle is live; every pointer is valid for the call.
        let status = unsafe { ffi::tsp_context_settings(self.handle, &raw mut raw) };
        check(status, unsafe {
            ffi::tsp_context_last_provider_code(self.handle)
        })?;
        Settings::from_ffi(&raw)
    }

    /// The code the provider returned on the last `Provider` failure, `0` when
    /// there was none.
    #[napi]
    pub fn last_provider_code(&self) -> Result<i32> {
        // SAFETY: the handle is live; every pointer is valid for the call.
        let value = unsafe { ffi::tsp_context_last_provider_code(self.handle) };

        Ok(value)
    }

    /// The one batch call: computes the chart at `jd_ut` and hands back the
    /// result blob in `out_blob`, which the caller frees with `tsp_blob_free`.
    #[napi]
    pub fn chart_compute(&self, env: Env, jd_ut: f64) -> Result<Buffer> {
        let mut blob = ffi::TspBlob {
            data: ptr::null_mut(),
            len: 0,
            cap: 0,
        };
        if let Some(slot) = &self.host {
            slot.env.set(Some(env));
            slot.error.set(None);
        }
        // SAFETY: the handle is live; every pointer is valid for the call.
        let status = unsafe { ffi::tsp_chart_compute(self.handle, jd_ut, &raw mut blob) };
        if let Some(slot) = &self.host {
            slot.env.set(None);
            if let Some(message) = slot.error.take() {
                return Err(Error::from_reason(format!("provider threw: {message}")));
            }
        }
        check(status, unsafe {
            ffi::tsp_context_last_provider_code(self.handle)
        })?;
        // SAFETY: the descriptor is the Vec the library leaked for us; both sides share the Rust allocator.
        let bytes = unsafe { Vec::from_raw_parts(blob.data, blob.len, blob.cap) };
        Ok(Buffer::from(bytes))
    }
}

impl Drop for Context {
    fn drop(&mut self) {
        // SAFETY: the handle came from the constructor and is dropped once.
        unsafe { ffi::tsp_context_free(self.handle) };
    }
}

/// The ABI version this library implements; a binding refuses to load a
/// library whose version it was not generated for.
#[napi]
pub fn abi_version() -> Result<u32> {
    // SAFETY: plain values in, plain values out.
    let value = ffi::tsp_abi_version();
    Ok(value)
}

/// Writes the default settings (Lahiri, the mean node, three levels) into
/// `out_settings`, whose `struct_size` must already be set by the caller.
///
/// Returns `InvalidArgument` for a null pointer or an unknown size.
#[napi]
pub fn settings_default() -> Result<Settings> {
    // SAFETY: every field of the struct is a plain integer, so zero is a valid value.
    let mut raw: ffi::TspSettings = unsafe { core::mem::zeroed() };
    raw.struct_size = core::mem::size_of::<ffi::TspSettings>() as u32;
    // SAFETY: plain values in, plain values out.
    let status = unsafe { ffi::tsp_settings_default(&raw mut raw) };
    check(status, 0)?;
    Settings::from_ffi(&raw)
}

/// The number of tree nodes a chart of `depth` levels holds, so a caller
/// can size its own structures before decoding.
#[napi]
pub fn chart_node_count(depth: u8) -> Result<u32> {
    // SAFETY: plain values in, plain values out.
    let value = ffi::tsp_chart_node_count(depth);
    Ok(value)
}

/// A static, NUL-terminated English message for a status.
#[napi]
pub fn status_message(status: Status) -> Result<String> {
    // SAFETY: plain values in, plain values out.
    let value = ffi::tsp_status_message(status.to_ffi_enum());
    // SAFETY: the library returns a static NUL-terminated string.
    Ok(unsafe { CStr::from_ptr(value) }
        .to_string_lossy()
        .into_owned())
}
