// Generated by teistro-spike-intl from i18n/en-Latn. Do not edit.
// Keys and parameter shapes only; text comes from packs.

export type Gender = 'm' | 'f' | 'n';
export type GrahaKey = 'graha.SUN' | 'graha.MOON' | 'graha.MARS' | 'graha.MERCURY' | 'graha.JUPITER' | 'graha.VENUS' | 'graha.SATURN' | 'graha.RAHU' | 'graha.KETU' | 'graha.LAGNA';
export type NakshatraKey = 'nakshatra.ASHWINI' | 'nakshatra.BHARANI' | 'nakshatra.KRITTIKA' | 'nakshatra.ROHINI' | 'nakshatra.MRIGASHIRA' | 'nakshatra.ARDRA' | 'nakshatra.PUNARVASU' | 'nakshatra.PUSHYA' | 'nakshatra.ASHLESHA' | 'nakshatra.MAGHA' | 'nakshatra.PURVA_PHALGUNI' | 'nakshatra.UTTARA_PHALGUNI' | 'nakshatra.HASTA' | 'nakshatra.CHITRA' | 'nakshatra.SWATI' | 'nakshatra.VISHAKHA' | 'nakshatra.ANURADHA' | 'nakshatra.JYESHTHA' | 'nakshatra.MULA' | 'nakshatra.PURVA_ASHADHA' | 'nakshatra.UTTARA_ASHADHA' | 'nakshatra.SHRAVANA' | 'nakshatra.DHANISHTHA' | 'nakshatra.SHATABHISHA' | 'nakshatra.PURVA_BHADRAPADA' | 'nakshatra.UTTARA_BHADRAPADA' | 'nakshatra.REVATI';
export type RashiKey = 'rashi.ARIES' | 'rashi.TAURUS' | 'rashi.GEMINI' | 'rashi.CANCER' | 'rashi.LEO' | 'rashi.VIRGO' | 'rashi.LIBRA' | 'rashi.SCORPIO' | 'rashi.SAGITTARIUS' | 'rashi.CAPRICORN' | 'rashi.AQUARIUS' | 'rashi.PISCES';
export type EntityKey = GrahaKey | NakshatraKey | RashiKey;
export type MessageKey = 'sdk.reason.appName' | 'sdk.reason.welcome' | 'sdk.reason.grahaInBhava' | 'sdk.reason.grahaInRashi' | 'sdk.reason.grahaAt' | 'sdk.reason.exactLongitude' | 'sdk.reason.conjunction' | 'sdk.reason.rashiNature' | 'sdk.reason.greeting' | 'sdk.reason.lordship' | 'sdk.reason.occupants' | 'sdk.reason.strength.score' | 'sdk.reason.strength.rank';

export interface EntityForms {
  readonly iast: string;
  readonly name: string;
  readonly prose: string;
  readonly short: string;
  readonly glyph?: string;
  readonly gender?: Gender;
}

export interface Renderer {
  render(key: MessageKey, params?: Readonly<Record<string, unknown>>): string;
  entity(key: EntityKey): EntityForms;
}

export function messages(r: Renderer) {
  return {
    sdk: {
      entity: {
        graha: {
          JUPITER: () => r.entity('graha.JUPITER'),
          KETU: () => r.entity('graha.KETU'),
          LAGNA: () => r.entity('graha.LAGNA'),
          MARS: () => r.entity('graha.MARS'),
          MERCURY: () => r.entity('graha.MERCURY'),
          MOON: () => r.entity('graha.MOON'),
          RAHU: () => r.entity('graha.RAHU'),
          SATURN: () => r.entity('graha.SATURN'),
          SUN: () => r.entity('graha.SUN'),
          VENUS: () => r.entity('graha.VENUS'),
        },
        nakshatra: {
          ANURADHA: () => r.entity('nakshatra.ANURADHA'),
          ARDRA: () => r.entity('nakshatra.ARDRA'),
          ASHLESHA: () => r.entity('nakshatra.ASHLESHA'),
          ASHWINI: () => r.entity('nakshatra.ASHWINI'),
          BHARANI: () => r.entity('nakshatra.BHARANI'),
          CHITRA: () => r.entity('nakshatra.CHITRA'),
          DHANISHTHA: () => r.entity('nakshatra.DHANISHTHA'),
          HASTA: () => r.entity('nakshatra.HASTA'),
          JYESHTHA: () => r.entity('nakshatra.JYESHTHA'),
          KRITTIKA: () => r.entity('nakshatra.KRITTIKA'),
          MAGHA: () => r.entity('nakshatra.MAGHA'),
          MRIGASHIRA: () => r.entity('nakshatra.MRIGASHIRA'),
          MULA: () => r.entity('nakshatra.MULA'),
          PUNARVASU: () => r.entity('nakshatra.PUNARVASU'),
          PURVA_ASHADHA: () => r.entity('nakshatra.PURVA_ASHADHA'),
          PURVA_BHADRAPADA: () => r.entity('nakshatra.PURVA_BHADRAPADA'),
          PURVA_PHALGUNI: () => r.entity('nakshatra.PURVA_PHALGUNI'),
          PUSHYA: () => r.entity('nakshatra.PUSHYA'),
          REVATI: () => r.entity('nakshatra.REVATI'),
          ROHINI: () => r.entity('nakshatra.ROHINI'),
          SHATABHISHA: () => r.entity('nakshatra.SHATABHISHA'),
          SHRAVANA: () => r.entity('nakshatra.SHRAVANA'),
          SWATI: () => r.entity('nakshatra.SWATI'),
          UTTARA_ASHADHA: () => r.entity('nakshatra.UTTARA_ASHADHA'),
          UTTARA_BHADRAPADA: () => r.entity('nakshatra.UTTARA_BHADRAPADA'),
          UTTARA_PHALGUNI: () => r.entity('nakshatra.UTTARA_PHALGUNI'),
          VISHAKHA: () => r.entity('nakshatra.VISHAKHA'),
        },
        rashi: {
          AQUARIUS: () => r.entity('rashi.AQUARIUS'),
          ARIES: () => r.entity('rashi.ARIES'),
          CANCER: () => r.entity('rashi.CANCER'),
          CAPRICORN: () => r.entity('rashi.CAPRICORN'),
          GEMINI: () => r.entity('rashi.GEMINI'),
          LEO: () => r.entity('rashi.LEO'),
          LIBRA: () => r.entity('rashi.LIBRA'),
          PISCES: () => r.entity('rashi.PISCES'),
          SAGITTARIUS: () => r.entity('rashi.SAGITTARIUS'),
          SCORPIO: () => r.entity('rashi.SCORPIO'),
          TAURUS: () => r.entity('rashi.TAURUS'),
          VIRGO: () => r.entity('rashi.VIRGO'),
        },
      },
      reason: {
        appName: () => r.render('sdk.reason.appName'),
        conjunction: (p: { count: number; graha: GrahaKey }) => r.render('sdk.reason.conjunction', p),
        exactLongitude: (p: { longitude: number }) => r.render('sdk.reason.exactLongitude', p),
        grahaAt: (p: { graha: GrahaKey; longitude: number }) => r.render('sdk.reason.grahaAt', p),
        grahaInBhava: (p: { bhava: number; graha: GrahaKey }) => r.render('sdk.reason.grahaInBhava', p),
        grahaInRashi: (p: { graha: GrahaKey; rashi: RashiKey }) => r.render('sdk.reason.grahaInRashi', p),
        greeting: (p: { gender: Gender; name: string }) => r.render('sdk.reason.greeting', p),
        lordship: (p: { bhava: number; graha: GrahaKey }) => r.render('sdk.reason.lordship', p),
        occupants: (p: { grahas: readonly (string | EntityKey)[]; rashi: RashiKey }) => r.render('sdk.reason.occupants', p),
        rashiNature: (p: { rashi: RashiKey }) => r.render('sdk.reason.rashiNature', p),
        strength: {
          rank: (p: { rank: number }) => r.render('sdk.reason.strength.rank', p),
          score: (p: { graha: GrahaKey; score: number }) => r.render('sdk.reason.strength.score', p),
        },
        welcome: () => r.render('sdk.reason.welcome'),
      },
    },
  } as const;
}

export type Messages = ReturnType<typeof messages>;
