//! The 249 horary numbers.

use std::fmt;

use serde::{Deserialize, Serialize};
use teistro_core::{Error, Nas};
use teistro_dasha::{VIMSHOTTARI_LORDS, VIMSHOTTARI_YEARS};

use crate::chain::{Lords, Span, lords};

/// How many numbers the table has: 27 nakshatras × 9 subs, and six more
/// because six subs straddle a sign's end and each half is a number.
const COUNT: usize = 249;

/// Where each number opens, in nanoarcseconds, number 1's first.
const STARTS: [i64; COUNT] = starts();

/// The table, generated by the Reader's own rule: each nakshatra's subs in
/// the Vimshottari order from its lord, a sub a sign's end cuts in two
/// counted twice. Checked when the crate is compiled to come to 249.
#[allow(
    clippy::indexing_slicing,
    reason = "a const fn: an index past the end fails the build"
)]
#[allow(
    clippy::cast_lossless,
    clippy::cast_possible_wrap,
    reason = "`i64::from` is not const, and the values are below 27"
)]
const fn starts() -> [i64; COUNT] {
    let mut starts = [0; COUNT];
    let mut n = 0;
    let mut star = 0;
    while star < 27 {
        let mut at = star as i64 * Nas::PER_NAKSHATRA;
        let mut step = 0;
        while step < VIMSHOTTARI_LORDS.len() {
            let lord = VIMSHOTTARI_LORDS[(star + step) % VIMSHOTTARI_LORDS.len()];
            let end = at + Nas::PER_NAKSHATRA / VIMSHOTTARI_YEARS as i64 * lord.years as i64;
            starts[n] = at;
            n += 1;
            let sign_ends = (at / Nas::PER_SIGN + 1) * Nas::PER_SIGN;
            if sign_ends < end {
                starts[n] = sign_ends;
                n += 1;
            }
            at = end;
            step += 1;
        }
        star += 1;
    }
    assert!(n == COUNT, "the rule gives 249 numbers");
    starts
}

/// A KP horary number, 1 to 249.
///
/// The querent names a number, and the chart is judged with the lagna at
/// the start of that number's arc (KP Reader I): number 1 opens at 0°
/// Aries, number 249 closes at 30° Pisces. Each number is a sub, or the
/// half of one a sign's end falls inside, so its sign, star and sub lords
/// are the same throughout.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(try_from = "u16", into = "u16")]
pub struct KpNumber(u8);

impl KpNumber {
    /// The largest number, 249.
    #[allow(clippy::cast_possible_truncation, reason = "249 fits")]
    pub const MAX: u16 = COUNT as u16;

    /// The number, refusing anything outside 1 to 249.
    ///
    /// # Errors
    ///
    /// `INVALID_ARG` on the field `number` for 0 or anything past 249.
    pub fn new(number: u16) -> Result<KpNumber, Error> {
        u8::try_from(number)
            .ok()
            .filter(|n| (1..=KpNumber::MAX).contains(&u16::from(*n)))
            .map(KpNumber)
            .ok_or_else(|| {
                Error::invalid_arg(format!(
                    "a KP horary number is 1 to {}, not {number}",
                    KpNumber::MAX
                ))
                .with_field("number")
                .with_hint("the 249 table is the Reader's; ask the querent for a number in it")
            })
    }

    /// The number whose arc holds a longitude.
    #[must_use]
    pub fn of(at: Nas) -> KpNumber {
        let opened = STARTS.partition_point(|start| *start <= at.get());
        KpNumber(u8::try_from(opened).unwrap_or(u8::MAX))
    }

    /// Every number, 1 to 249.
    pub fn all() -> impl ExactSizeIterator<Item = KpNumber> {
        (1..=u8::try_from(COUNT).unwrap_or(u8::MAX)).map(KpNumber)
    }

    /// The number itself.
    #[must_use]
    pub const fn get(self) -> u16 {
        self.0 as u16
    }

    /// Where the number's arc opens: the horary lagna.
    #[must_use]
    pub fn start(self) -> Nas {
        opens(usize::from(self.0) - 1)
    }

    /// The arc the number spans, its end the next number's start.
    #[must_use]
    pub fn span(self) -> Span {
        Span {
            start: self.start(),
            end: opens(usize::from(self.0)),
        }
    }

    /// The lords at the number's start, the same throughout its arc down
    /// to the sub.
    #[must_use]
    pub fn lords(self) -> Lords {
        lords(self.start())
    }
}

/// Where the `index`th number opens, 0° again past the last.
fn opens(index: usize) -> Nas {
    Nas::new(STARTS.get(index).copied().unwrap_or(Nas::CIRCLE))
}

impl TryFrom<u16> for KpNumber {
    type Error = Error;

    fn try_from(number: u16) -> Result<KpNumber, Error> {
        KpNumber::new(number)
    }
}

impl From<KpNumber> for u16 {
    fn from(number: KpNumber) -> u16 {
        number.get()
    }
}

impl fmt::Display for KpNumber {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Debug for KpNumber {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "KpNumber({})", self.0)
    }
}
