//! **Pluto**: the one body that is fitted rather than truncated.
//!
//! `cargo xtask pluto` writes both the design page and the generated
//! module; `check-pluto` regenerates them in memory and fails on any
//! difference, so the coefficients a consumer receives are the
//! coefficients the recording produced.
//!
//! # Why this is not part of `ephemgen`
//!
//! Every other body in the built-in ephemeris is a **truncation of a
//! published series**, and `ephemgen` needs 8 MB of VSOP87 and ELP text
//! to emit one. Pluto has no published series to truncate (ADR-0008): its
//! source is `crates/ephemeris-builtin/data/pluto-fit.json`, recorded by
//! `teistro-ephemeris-teimeris-pluto-fit` against the reference engine.
//! Folding it into `ephemgen` would mean nobody could regenerate Pluto
//! without fetching two archives that have nothing to do with it.
//!
//! The separation has a cost, and it is paid rather than hidden: the tier
//! tables' own `DATA_BYTES` does not count Pluto, so the generated module
//! carries the budget assertion for the pair. A tier that grew past its
//! budget *because of Pluto* still fails to compile.

use std::fmt::Write as _;
use std::path::Path;

use serde::Deserialize;

use crate::generated::{Output, check, write};
use crate::measure::{Claim, count, spelled, table};

/// Where the fit is recorded. The number, not the code that produced it.
const SOURCE: &str = "crates/ephemeris-builtin/data/pluto-fit.json";

/// The generated module, and the page that explains it.
const MODULE: &str = "crates/ephemeris-builtin/src/pluto.rs";
const PAGE: &str = "docs/03-design/pluto-measured.md";

/// The tiers, richest last, as the crate's features spell them.
const TIERS: [&str; 3] = ["compact", "standard", "full"];

/// One rung of the interval-against-degree ladder.
#[derive(Debug, Deserialize)]
struct Rung {
    interval_years: f64,
    terms: usize,
    intervals: usize,
    bytes: usize,
    worst_arcsec: f64,
    mean_arcsec: f64,
}

/// The rung a tier takes, with the coefficients it takes.
#[derive(Debug, Deserialize)]
struct Chosen {
    tier: String,
    bound_arcsec: f64,
    interval_years: f64,
    terms: usize,
    intervals: usize,
    start_jd: f64,
    interval_days: f64,
    bytes: usize,
    worst_arcsec: f64,
    coefficients: Vec<f64>,
}

/// The whole recording.
#[derive(Debug, Deserialize)]
struct Fit {
    body: String,
    frame: String,
    fitted_to: String,
    note: String,
    from_jd: f64,
    to_jd: f64,
    engine_profile: String,
    probes_per_interval: usize,
    floor_arcsec: f64,
    rungs: Vec<Rung>,
    chosen: Vec<Chosen>,
}

/// Reads the recording, or says why it could not.
///
/// A missing file is a measurement not yet taken and the pass says so; a
/// file that is present and will not parse is the recording and this
/// reader having drifted apart, and swallowing that would leave a
/// generated module quietly frozen at whatever it last held.
fn recorded(root: &Path) -> Result<Option<Fit>, String> {
    let path = root.join(SOURCE);
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Ok(None);
    };
    serde_json::from_str::<Fit>(&text)
        .map(Some)
        .map_err(|error| {
            format!(
                "{} is recorded but does not parse: {error}. Re-record it with \
             `teistro-ephemeris-teimeris-pluto-fit`, or fix the reader.",
                path.display()
            )
        })
}

/// An arcsecond figure at a readable precision.
fn arcsec(value: f64) -> String {
    if value >= 10.0 {
        format!("{value:.1}")
    } else if value >= 1.0 {
        format!("{value:.2}")
    } else if value >= 0.01 {
        format!("{value:.3}")
    } else {
        format!("{value:.4}")
    }
}

/// Bytes as kilobytes, which is the unit a tier budget is stated in.
fn kilobytes(bytes: usize) -> String {
    #[expect(
        clippy::cast_precision_loss,
        reason = "a table is kilobytes, not petabytes"
    )]
    let value = bytes as f64 / 1024.0;
    if value >= 100.0 {
        format!("{value:.0} KB")
    } else {
        format!("{value:.1} KB")
    }
}

/// The generated module: every tier's coefficients behind its own `cfg`.
fn module(fit: &Fit) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Pluto, fitted. **Generated by `cargo xtask pluto`. Do not edit.**\n\
         //!\n\
         //! Pluto has no VSOP87 series and no analytic theory this SDK can\n\
         //! ship, so it is the one body that is fitted rather than truncated\n\
         //! (ADR-0008). What is fitted is the **heliocentric** vector: Pluto's\n\
         //! motion about the Sun is slow and smooth, where its motion about\n\
         //! the Earth carries the Earth's whole annual orbit as well — and the\n\
         //! Earth already has a theory.\n\
         //!\n\
         //! Fitted against {}, over the span {:.1} to {:.1} on the engine's\n\
         //! `{}` profile, and scored at {} probes an interval placed **off**\n\
         //! the fit's own nodes — a Chebyshev fit is exact at its nodes, so\n\
         //! measuring there would report zero however bad it was. Each tier takes the cheapest rung of\n\
         //! `{PAGE}` meeting its own stated bound. Agreement with a reference\n\
         //! proves consistency and not correctness (ADR-0021); refitting is a\n\
         //! calculation-version change under ADR-0020.\n\
         //!\n\
         //! | tier | bound | interval | terms | blocks | bytes | worst |\n\
         //! |---|---:|---:|---:|---:|---:|---:|",
        fit.fitted_to,
        fit.from_jd,
        fit.to_jd,
        fit.engine_profile,
        count(fit.probes_per_interval),
    );
    for chosen in &fit.chosen {
        let _ = writeln!(
            out,
            "//! | `{}` | {}″ | {:.0} y | {} | {} | {} | {}″ |",
            chosen.tier,
            arcsec(chosen.bound_arcsec),
            chosen.interval_years,
            chosen.terms,
            chosen.intervals,
            kilobytes(chosen.bytes),
            arcsec(chosen.worst_arcsec),
        );
    }
    let _ = writeln!(
        out,
        "\n#![allow(\n    \
         clippy::unreadable_literal,\n    \
         clippy::excessive_precision,\n    \
         clippy::approx_constant,\n    \
         reason = \"a generated table: the digits are the fit's\"\n\
         )]\n\n\
         use crate::chebyshev::Table;\n"
    );
    for chosen in &fit.chosen {
        out.push_str(&tier_module(chosen));
    }
    let _ = writeln!(
        out,
        "/// Pluto's own share of a tier's data budget, bytes.\n\
         ///\n\
         /// The tier tables' `DATA_BYTES` counts the truncated series and\n\
         /// not this, because Pluto is generated by a different pass from a\n\
         /// different source. The assertion below is what keeps that from\n\
         /// being a way to overspend quietly: a tier that broke its budget\n\
         /// *because of Pluto* fails to compile, exactly as one that broke it\n\
         /// because of the Moon does.\n\
         pub const PLUTO_BYTES: usize = PLUTO_COEFFICIENTS.len() * 8;\n\
         \n\
         const _: () = assert!(\n    \
         crate::tables::DATA_BYTES + PLUTO_BYTES <= crate::tables::BUDGET_BYTES,\n    \
         \"this tier's tables and Pluto together are past the tier's budget\"\n\
         );\n"
    );
    out
}

/// One tier's block, behind the same `cfg` the tier tables use.
fn tier_module(chosen: &Chosen) -> String {
    let mut out = String::new();
    let gate = match chosen.tier.as_str() {
        "compact" => {
            "#[cfg(all(feature = \"compact\", not(feature = \"standard\"), not(feature = \"full\")))]"
        }
        "standard" => "#[cfg(all(feature = \"standard\", not(feature = \"full\")))]",
        _ => "#[cfg(feature = \"full\")]",
    };
    let _ = writeln!(
        out,
        "{gate}\n\
         /// Pluto's Chebyshev coefficients, `[interval][component][term]`\n\
         /// flattened: one `static` slice rather than a tree of them, because\n\
         /// a nested table costs a relocation per interval and this is meant\n\
         /// for a consumer counting kilobytes.\n\
         ///\n\
         /// {} intervals of {} days, {} terms a component. Measured worst over\n\
         /// the span: {} arcseconds of geocentric angle, against this tier's\n\
         /// bound of {}.\n\
         pub static PLUTO_COEFFICIENTS: [f64; {}] = [",
        chosen.intervals,
        chosen.interval_days,
        chosen.terms,
        arcsec(chosen.worst_arcsec),
        arcsec(chosen.bound_arcsec),
        chosen.coefficients.len(),
    );
    for interval in chosen.coefficients.chunks(3 * chosen.terms) {
        let row: Vec<String> = interval.iter().map(|value| format!("{value:?}")).collect();
        let _ = writeln!(out, "    {},", row.join(","));
    }
    let _ = writeln!(
        out,
        "];\n\n\
         {gate}\n\
         /// Pluto's fitted table, ready to evaluate.\n\
         pub static PLUTO: Table = Table {{\n    \
         start_jd: {:?},\n    \
         interval_days: {:?},\n    \
         terms: {},\n    \
         coefficients: &PLUTO_COEFFICIENTS,\n\
         }};\n\n\
         {gate}\n\
         /// The worst geocentric angle this tier's fit was measured at over\n\
         /// the span, arcseconds. A published figure rather than a claim.\n\
         pub const PLUTO_WORST_ARCSEC: f64 = {:?};\n",
        chosen.start_jd, chosen.interval_days, chosen.terms, chosen.worst_arcsec,
    );
    out
}

/// The page: the ladder, what each tier took from it, and the floor.
fn page(fit: Option<&Fit>) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Pluto, measured\n");
    let _ = writeln!(
        out,
        "Status: `generated` by `cargo xtask pluto`, gated by `check-pluto`. Do not edit. The numbers are read from `{SOURCE}`, recorded by `teistro-ephemeris-teimeris-pluto-fit` against the reference engine — the number, not the code that produced it.\n"
    );
    let Some(fit) = fit else {
        let _ = writeln!(
            out,
            "**Not yet recorded.** Run the binary above and re-run this pass. Until then the built-in ephemeris refuses Pluto by name, which is what it should do rather than guess.\n"
        );
        return out;
    };
    let _ = writeln!(
        out,
        "{} is the one body in the built-in ephemeris with **no published series to truncate** (ADR-0008). Every other body's tier is a threshold on an existing theory; Pluto's is a choice of how finely to fit it. This page measures that choice.\n",
        fit.body
    );
    let _ = writeln!(
        out,
        "What is fitted is the **heliocentric** vector, in `{}`. Pluto's motion about the Sun is slow and smooth — one circuit in 248 years — and a Chebyshev series is cheap on a smooth function. Its *geocentric* motion is that same slow curve with the Earth's whole annual orbit superimposed, and fitting that would pay for the Earth again at every one of Pluto's blocks, when the Earth already has a theory.\n",
        fit.frame
    );
    let _ = writeln!(out, "> {}\n", fit.note);
    out.push_str(&ladder_section(fit));
    out.push_str(&chosen_section(fit));
    out.push_str(&floor_section(fit));
    out.push_str(&limits_section(fit));
    out
}

fn ladder_section(fit: &Fit) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "## The ladder\n");
    let _ = writeln!(
        out,
        "Every combination of interval length and degree, fitted over the whole span and then probed **off** its own nodes — a Chebyshev fit is exact at its nodes, so measuring there would report zero however bad the fit is.\n"
    );
    let _ = writeln!(out, "| interval | terms | blocks | bytes | worst | mean |");
    let _ = writeln!(out, "|---:|---:|---:|---:|---:|---:|");
    for rung in &fit.rungs {
        let _ = writeln!(
            out,
            "| {:.0} y | {} | {} | {} | {}″ | {}″ |",
            rung.interval_years,
            rung.terms,
            rung.intervals,
            kilobytes(rung.bytes),
            arcsec(rung.worst_arcsec),
            arcsec(rung.mean_arcsec),
        );
    }
    let _ = writeln!(
        out,
        "\nArcseconds of **geocentric angle**, which is what a chart shows: each probe rebuilds the geocentric vector from the fitted heliocentric one and the engine's own Earth, so the figure is what a consumer would see rather than what the fitter would like to report.\n"
    );
    out
}

fn chosen_section(fit: &Fit) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "## What each tier takes\n");
    let _ = writeln!(
        out,
        "**The cheapest rung meeting the tier's own bound**, and not the best rung that fits the budget. Pluto is small enough at every tier that a richer rung would always be affordable, which is exactly why the rule has to be written down: a tier that quietly spent a consumer's bytes on the strength of nothing stated is how a budget stops meaning anything.\n"
    );
    let _ = writeln!(
        out,
        "| tier | bound | interval | terms | blocks | bytes | worst |"
    );
    let _ = writeln!(out, "|---|---:|---:|---:|---:|---:|---:|");
    for chosen in &fit.chosen {
        let _ = writeln!(
            out,
            "| `{}` | {}″ | {:.0} y | {} | {} | {} | {}″ |",
            chosen.tier,
            arcsec(chosen.bound_arcsec),
            chosen.interval_years,
            chosen.terms,
            chosen.intervals,
            kilobytes(chosen.bytes),
            arcsec(chosen.worst_arcsec),
        );
    }
    let _ = writeln!(
        out,
        "\n`compact` and `standard` carry the bounds their own manifest states — an arcminute and an arcsecond. `full` cannot say \"the theory as published\", because for a fitted body there is no published theory, so its bound is the floor the ladder itself reaches.\n"
    );
    let missing: Vec<&str> = TIERS
        .iter()
        .copied()
        .filter(|tier| !fit.chosen.iter().any(|chosen| chosen.tier == *tier))
        .collect();
    if !missing.is_empty() {
        let _ = writeln!(
            out,
            "**{} not chosen**, so the generated module has no coefficients for it and the provider will refuse Pluto there by name.\n",
            missing.join(", ")
        );
    }
    out
}

fn floor_section(fit: &Fit) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "## The floor, and what it is not\n");
    let best = fit
        .rungs
        .iter()
        .filter(|rung| rung.worst_arcsec <= fit.floor_arcsec * 1.001)
        .map(|rung| rung.bytes)
        .min()
        .unwrap_or(0);
    let reaching = fit
        .rungs
        .iter()
        .filter(|rung| rung.worst_arcsec <= fit.floor_arcsec * 1.001)
        .count();
    let _ = writeln!(
        out,
        "The ladder stops improving at **{}″**. {} of its {} rungs reach that figure and none beats it, the cheapest at {}: past that point a finer fit buys nothing at all.\n",
        arcsec(fit.floor_arcsec),
        spelled(reaching),
        count(fit.rungs.len()),
        kilobytes(best),
    );
    let _ = writeln!(
        out,
        "**What the floor is has not been established here, and guessing would be worse than saying so.** A representation error falls without limit as the fit is refined, so a floor is something else: the reference's own resolution for this body, or the precision of the round trip through the port's spherical cell, or the probe's own arithmetic. It bounds what this page can claim — no rung can be shown to be better than {}″ by this measurement, whatever it may be in truth — and it is the reason `full`'s bound is stated against the ladder rather than against a number chosen in advance.\n",
        arcsec(fit.floor_arcsec)
    );
    out
}

fn limits_section(fit: &Fit) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "## The claims this decides\n");
    let claims: Vec<Claim> = fit
        .chosen
        .iter()
        .map(|chosen| Claim {
            rule: format!(
                "`{}`: Pluto inside {}″, the tier's own bound",
                chosen.tier,
                arcsec(chosen.bound_arcsec)
            ),
            verdict: crate::measure::verdict_of(chosen.worst_arcsec <= chosen.bound_arcsec),
            measured: format!(
                "worst {}″ in {}",
                arcsec(chosen.worst_arcsec),
                kilobytes(chosen.bytes)
            ),
        })
        .collect();
    out.push_str(&table(&claims));
    let _ = writeln!(
        out,
        "\nThey hold by construction — the rung was chosen to meet the bound — so the row that would matter is a falsified one, which would mean no rung on the ladder could meet a tier's promise and the promise had to move.\n"
    );
    let _ = writeln!(out, "## What this does not measure\n");
    let _ = writeln!(
        out,
        "**Correctness.** The fit is against {}, so it proves consistency and not truth (ADR-0021). The refit against JPL Horizons or CSPICE before v1 is the one the Moon's bija already owes, and every figure here is republished if it moves.\n",
        fit.fitted_to
    );
    let _ = writeln!(
        out,
        "**Any span but {:.1} to {:.1}.** A Chebyshev table does not degrade outside its fit, it diverges, so the evaluator refuses rather than extrapolates and a wider tier is refitted rather than reused.\n",
        fit.from_jd, fit.to_jd
    );
    let _ = writeln!(
        out,
        "**The rate.** The table's derivative is analytic and exact for the series it holds, and is tested as such; what is *not* measured here is the rate against the engine's, which belongs beside every other body's in `03-design/completion-measured.md`.\n"
    );
    out
}

/// The outputs, or a message and a failing code.
fn outputs(root: &Path) -> Result<Vec<Output>, i32> {
    match recorded(root) {
        Ok(fit) => {
            let mut outputs = vec![Output::new(PAGE, page(fit.as_ref()))];
            if let Some(fit) = fit.as_ref() {
                outputs.push(Output::new(MODULE, module(fit)));
            }
            Ok(outputs)
        }
        Err(message) => {
            eprintln!("{message}");
            Err(1)
        }
    }
}

/// Writes the page and the module.
pub(crate) fn generate(root: &Path) -> i32 {
    match outputs(root) {
        Ok(outputs) => write(root, &outputs),
        Err(code) => code,
    }
}

/// Regenerates both in memory and fails on any difference.
pub(crate) fn check_generated(root: &Path) -> i32 {
    match outputs(root) {
        Ok(outputs) => check(root, &outputs, "cargo xtask pluto"),
        Err(code) => code,
    }
}
