//! The time tasks: `gen time` writes the time crate's tables (the IERS
//! Delta T series, the historical table with its standard errors, the
//! leap-second list) from the data files with their provenance;
//! `check-time` regenerates in memory and compares.

use std::fmt::Write as _;
use std::path::Path;

use serde::Deserialize;
use teistro_calendar::gregorian::fixed_from_gregorian;

use crate::generated::{Output, check, write};

const DELTA_T_DATA: &str = "crates/time/data/delta-t.json";
const LEAP_DATA: &str = "crates/time/data/leap-seconds.json";
const GENERATED: &str = "crates/time/src/generated.rs";
const MJD_EPOCH: f64 = 2_400_000.5;

#[derive(Deserialize)]
struct DeltaTFile {
    iers: Iers,
    morrison_stephenson_2004: Historical,
}

#[derive(Deserialize)]
struct Iers {
    series: String,
    url: String,
    fetched: String,
    derivation: String,
    rows: Vec<(f64, f64, f64)>,
}

#[derive(Deserialize)]
struct Historical {
    source: String,
    rows: Vec<(i32, i32, Option<u32>)>,
}

#[derive(Deserialize)]
struct LeapFile {
    source: String,
    updated: String,
    expires: String,
    rows: Vec<LeapRow>,
}

#[derive(Deserialize)]
struct LeapRow {
    date: String,
    tai_minus_utc: u8,
}

/// The MJD at 0h of an ISO date.
fn mjd_of(date: &str) -> i32 {
    let mut parts = date
        .split('-')
        .map(|p| p.parse::<i32>().expect("a date part"));
    let (y, m, d) = (
        parts.next().expect("year"),
        parts.next().expect("month"),
        parts.next().expect("day"),
    );
    let jd = fixed_from_gregorian(
        y,
        u8::try_from(m).expect("month"),
        u8::try_from(d).expect("day"),
    )
    .jd_at_midnight()
    .expect("a finite day")
    .get();
    #[allow(clippy::cast_possible_truncation, reason = "a whole day count")]
    let mjd = (jd - MJD_EPOCH).round() as i32;
    mjd
}

#[allow(
    clippy::too_many_lines,
    reason = "one generated file, written top to bottom"
)]
fn render(root: &Path) -> Vec<Output> {
    let delta: DeltaTFile = serde_json::from_str(&crate::read(&root.join(DELTA_T_DATA)))
        .expect("a well-formed Delta T file");
    let leap: LeapFile = serde_json::from_str(&crate::read(&root.join(LEAP_DATA)))
        .expect("a well-formed leap-second file");
    assert!(
        delta.iers.rows.windows(2).all(|w| w[0].0 < w[1].0),
        "the IERS rows must ascend"
    );
    assert!(
        leap.rows
            .windows(2)
            .all(|w| w[0].tai_minus_utc < w[1].tai_minus_utc),
        "the leap rows must ascend"
    );

    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! GENERATED by `cargo xtask gen time` from `{DELTA_T_DATA}` and `{LEAP_DATA}`;"
    );
    let _ = writeln!(
        out,
        "//! never hand-edited: `cargo xtask check-time` regenerates and compares."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "#![allow(clippy::unreadable_literal, clippy::excessive_precision, reason = \"generated tables\")]"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "/// The IERS series the table comes from.");
    let _ = writeln!(
        out,
        "pub(crate) const DELTA_T_SOURCE: &str = {:?};",
        format!(
            "{} ({}), fetched {}; {}",
            delta.iers.series, delta.iers.url, delta.iers.fetched, delta.iers.derivation
        )
    );
    let _ = writeln!(
        out,
        "/// Modified Julian Date, Delta T in seconds, its uncertainty in seconds; ascending."
    );
    let _ = writeln!(
        out,
        "pub(crate) static DELTA_T_ROWS: [(f32, f32, f32); {}] = [",
        delta.iers.rows.len()
    );
    for (mjd, seconds, sigma) in &delta.iers.rows {
        let _ = writeln!(out, "    ({mjd:?}, {seconds:?}, {sigma:?}),");
    }
    let _ = writeln!(out, "];");
    let _ = writeln!(
        out,
        "/// The historical table the uncertainties before the IERS era come from."
    );
    let _ = writeln!(
        out,
        "pub(crate) const HISTORICAL_SOURCE: &str = {:?};",
        delta.morrison_stephenson_2004.source
    );
    let _ = writeln!(
        out,
        "/// Year, Delta T in seconds, its standard error in seconds (0 where the table gives none)."
    );
    let _ = writeln!(
        out,
        "pub(crate) static HISTORICAL_ROWS: [(i16, i32, u16); {}] = [",
        delta.morrison_stephenson_2004.rows.len()
    );
    for (year, seconds, sigma) in &delta.morrison_stephenson_2004.rows {
        let _ = writeln!(out, "    ({year}, {seconds}, {}),", sigma.unwrap_or(0));
    }
    let _ = writeln!(out, "];");
    let _ = writeln!(out, "/// The leap-second list.");
    let _ = writeln!(
        out,
        "pub(crate) const LEAP_SOURCE: &str = {:?};",
        leap.source
    );
    let _ = writeln!(out, "/// The date the list was updated.");
    let _ = writeln!(
        out,
        "pub(crate) const LEAP_UPDATED: &str = {:?};",
        leap.updated
    );
    let _ = writeln!(
        out,
        "/// The MJD of the day the list's word expires ({}).",
        leap.expires
    );
    let _ = writeln!(
        out,
        "pub(crate) const LEAP_EXPIRES_MJD: i32 = {};",
        mjd_of(&leap.expires)
    );
    let _ = writeln!(
        out,
        "/// The MJD at 0h UTC of each date a count took effect, and TAI less UTC from then."
    );
    let _ = writeln!(
        out,
        "pub(crate) static LEAP_ROWS: [(i32, u8); {}] = [",
        leap.rows.len()
    );
    for row in &leap.rows {
        let _ = writeln!(
            out,
            "    ({}, {}), // {}",
            mjd_of(&row.date),
            row.tai_minus_utc,
            row.date
        );
    }
    let _ = writeln!(out, "];");
    vec![Output {
        path: GENERATED,
        text: out,
    }]
}

/// Writes the tables.
pub(crate) fn generate(root: &Path) -> i32 {
    write(root, &render(root))
}

/// Regenerates in memory and compares.
pub(crate) fn check_generated(root: &Path) -> i32 {
    check(root, &render(root), "cargo xtask gen time")
}
