//! The falsification pass over the recorded divisional charts, which the
//! varga kernel is written from (Phase 4).
//!
//! `03-design/varga-kernel.md` claims there is exactly one evaluator —
//! `varga_sign(sign, part) = table[sign][part]`, with the table generated
//! from four parameters or supplied explicitly — and that of the
//! recording engine's twenty-one charts, eighteen are generated by a
//! linear rule and three supply their table. That is a strong claim and
//! the corpus can decide it outright: a varga's answer is a function of a
//! sidereal longitude alone, and the corpus records both.
//!
//! So this pass derives each chart's table from the corpus itself,
//! independently of any SDK code, and holds the claimed rule to it. It
//! also reports what the corpus **cannot** pin: a rule generalises to
//! cells no recorded body ever fell in, and a table does not, which is
//! the argument for shipping rules.
//!
//! `cargo xtask vargas` writes the page; `check-vargas` regenerates it in
//! memory and fails on any difference.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use serde_json::Value;
use teistro_core::catalogue::{Rashi, Varga};

use crate::generated::{Output, check, write};
use crate::measure::{Claim, FILL, Verdict, count, fill, table, verdict_of, wrapped};

const PAGE: &str = "docs/03-design/varga-tables-measured.md";
const CHARTS: &str = "fixtures/baseline/charts";
const VARIANTS: &str = "fixtures/baseline/variants";

/// The bodies the engine places in every divisional chart, in its own
/// order. `LAGNA` is one of them, which is what makes the vargottama
/// finding of §6 visible.
const BODIES: [&str; 10] = [
    "SUN", "MOON", "MARS", "MERCURY", "JUPITER", "VENUS", "SATURN", "RAHU", "KETU", "LAGNA",
];

/// A sign's degrees.
const PER_SIGN: f64 = 30.0;

// ── the proposed kernel ────────────────────────────────────────────────────

/// How a sign is sorted into groups, each of which has its own rule.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Classifier {
    /// One group: every sign alike.
    All,
    /// Odd and even signs, counting Aries as odd.
    Parity,
    /// Movable, fixed and dual.
    Modality,
    /// Fire, earth, air and water.
    Element,
}

impl Classifier {
    /// How many groups it sorts the twelve signs into.
    const fn groups(self) -> u8 {
        match self {
            Classifier::All => 1,
            Classifier::Parity => 2,
            Classifier::Modality => 3,
            Classifier::Element => 4,
        }
    }

    /// Which group a sign belongs to.
    const fn group_of(self, sign: u8) -> usize {
        (sign % self.groups()) as usize
    }

    /// What the page calls it.
    const fn name(self) -> &'static str {
        match self {
            Classifier::All => "all",
            Classifier::Parity => "parity",
            Classifier::Modality => "modality",
            Classifier::Element => "element",
        }
    }
}

/// The multiplier a linear rule puts on the sign.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum SignBase {
    /// `a = 0`: count from a fixed sign, which the offset names.
    Fixed,
    /// `a = 1`: count from the sign the body is in.
    Same,
    /// `a = N`: count continuously round the zodiac, the parivritti form.
    Cyclic,
}

impl SignBase {
    /// The multiplier for a chart of `divisions` parts.
    const fn multiplier(self, divisions: u16) -> u32 {
        match self {
            SignBase::Fixed => 0,
            SignBase::Same => 1,
            SignBase::Cyclic => divisions as u32,
        }
    }

    /// What the page calls it.
    const fn name(self) -> &'static str {
        match self {
            SignBase::Fixed => "a fixed sign",
            SignBase::Same => "the sign itself",
            SignBase::Cyclic => "continuously (parivritti)",
        }
    }
}

/// How a part index becomes a sign, for one group.
#[derive(Clone, Copy, Debug)]
enum Map {
    /// `(a·sign + step·part + offset) mod 12`.
    Linear {
        base: SignBase,
        step: u8,
        offset: u8,
    },
    /// One sign per part, listed.
    Table(&'static [u8]),
}

/// Where the parts of a sign begin, for one group.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Spans {
    /// N parts of `30/N` degrees each.
    Equal,
    /// Whole-degree spans, summing to thirty.
    Degrees(&'static [u8]),
}

/// One group's rule.
#[derive(Clone, Copy, Debug)]
struct Group {
    spans: Spans,
    map: Map,
}

/// A divisional chart's proposed rule.
///
/// `divisions` names the chart and is not always how many parts a sign
/// is cut into: D30 is called thirty and its spans cut a sign into five.
/// The part count comes from the spans, and only the equal ones make the
/// two the same.
#[derive(Clone, Copy, Debug)]
struct Scheme {
    varga: Varga,
    divisions: u16,
    classifier: Classifier,
    groups: &'static [Group],
}

/// The equal-span linear group a chart of one rule has.
const fn linear(base: SignBase, step: u8, offset: u8) -> Group {
    Group {
        spans: Spans::Equal,
        map: Map::Linear { base, step, offset },
    }
}

/// An equal-span group whose signs are listed.
const fn listed(signs: &'static [u8]) -> Group {
    Group {
        spans: Spans::Equal,
        map: Map::Table(signs),
    }
}

/// The one-group rules: every sign treated alike.
const ALIKE: [Group; 1] = [linear(SignBase::Same, 0, 0)];
const D3_GROUPS: [Group; 1] = [linear(SignBase::Same, 4, 0)];
const D4_GROUPS: [Group; 1] = [linear(SignBase::Same, 3, 0)];
const STEP_ONE: [Group; 1] = [linear(SignBase::Same, 1, 0)];
const CYCLIC_ONE: [Group; 1] = [linear(SignBase::Cyclic, 1, 0)];

/// The parity rules.
const D7_GROUPS: [Group; 2] = [linear(SignBase::Same, 1, 0), linear(SignBase::Same, 1, 6)];
const D10_GROUPS: [Group; 2] = [linear(SignBase::Same, 1, 0), linear(SignBase::Same, 1, 8)];
const D11_GROUPS: [Group; 2] = [linear(SignBase::Same, 1, 0), linear(SignBase::Same, 1, 10)];
const ARIES_LIBRA: [Group; 2] = [linear(SignBase::Fixed, 1, 0), linear(SignBase::Fixed, 1, 6)];
const D24_GROUPS: [Group; 2] = [linear(SignBase::Fixed, 1, 4), linear(SignBase::Fixed, 1, 3)];

/// The modality and element rules.
const MOVABLE_FIXED_DUAL: [Group; 3] = [
    linear(SignBase::Fixed, 1, 0),
    linear(SignBase::Fixed, 1, 4),
    linear(SignBase::Fixed, 1, 8),
];
const D20_GROUPS: [Group; 3] = [
    linear(SignBase::Fixed, 1, 0),
    linear(SignBase::Fixed, 1, 8),
    linear(SignBase::Fixed, 1, 4),
];
const D27_GROUPS: [Group; 4] = [
    linear(SignBase::Fixed, 1, 0),
    linear(SignBase::Fixed, 1, 3),
    linear(SignBase::Fixed, 1, 6),
    linear(SignBase::Fixed, 1, 9),
];

/// The three that list their signs rather than stepping through them.
const D2_GROUPS: [Group; 2] = [listed(&[4, 3]), listed(&[3, 4])];
const D5_GROUPS: [Group; 2] = [listed(&[0, 10, 8, 2, 6]), listed(&[1, 5, 11, 9, 7])];
const D30_GROUPS: [Group; 2] = [
    Group {
        spans: Spans::Degrees(&[5, 5, 8, 7, 5]),
        map: Map::Table(&[0, 10, 8, 2, 6]),
    },
    Group {
        spans: Spans::Degrees(&[5, 7, 8, 5, 5]),
        map: Map::Table(&[1, 5, 11, 9, 7]),
    },
];

/// The twenty-one charts the recording engine exports, each as one row.
const SCHEMES: [Scheme; 21] = [
    Scheme {
        varga: Varga::D1,
        divisions: 1,
        classifier: Classifier::All,
        groups: &ALIKE,
    },
    Scheme {
        varga: Varga::D2,
        divisions: 2,
        classifier: Classifier::Parity,
        groups: &D2_GROUPS,
    },
    Scheme {
        varga: Varga::D3,
        divisions: 3,
        classifier: Classifier::All,
        groups: &D3_GROUPS,
    },
    Scheme {
        varga: Varga::D4,
        divisions: 4,
        classifier: Classifier::All,
        groups: &D4_GROUPS,
    },
    Scheme {
        varga: Varga::D5,
        divisions: 5,
        classifier: Classifier::Parity,
        groups: &D5_GROUPS,
    },
    Scheme {
        varga: Varga::D6,
        divisions: 6,
        classifier: Classifier::Parity,
        groups: &ARIES_LIBRA,
    },
    Scheme {
        varga: Varga::D7,
        divisions: 7,
        classifier: Classifier::Parity,
        groups: &D7_GROUPS,
    },
    Scheme {
        varga: Varga::D8,
        divisions: 8,
        classifier: Classifier::Modality,
        groups: &MOVABLE_FIXED_DUAL,
    },
    Scheme {
        varga: Varga::D9,
        divisions: 9,
        classifier: Classifier::All,
        groups: &CYCLIC_ONE,
    },
    Scheme {
        varga: Varga::D10,
        divisions: 10,
        classifier: Classifier::Parity,
        groups: &D10_GROUPS,
    },
    Scheme {
        varga: Varga::D11,
        divisions: 11,
        classifier: Classifier::Parity,
        groups: &D11_GROUPS,
    },
    Scheme {
        varga: Varga::D12,
        divisions: 12,
        classifier: Classifier::All,
        groups: &STEP_ONE,
    },
    Scheme {
        varga: Varga::D16,
        divisions: 16,
        classifier: Classifier::Modality,
        groups: &MOVABLE_FIXED_DUAL,
    },
    Scheme {
        varga: Varga::D20,
        divisions: 20,
        classifier: Classifier::Modality,
        groups: &D20_GROUPS,
    },
    Scheme {
        varga: Varga::D24,
        divisions: 24,
        classifier: Classifier::Parity,
        groups: &D24_GROUPS,
    },
    Scheme {
        varga: Varga::D27,
        divisions: 27,
        classifier: Classifier::Element,
        groups: &D27_GROUPS,
    },
    Scheme {
        varga: Varga::D30,
        divisions: 30,
        classifier: Classifier::Parity,
        groups: &D30_GROUPS,
    },
    Scheme {
        varga: Varga::D40,
        divisions: 40,
        classifier: Classifier::Parity,
        groups: &ARIES_LIBRA,
    },
    Scheme {
        varga: Varga::D45,
        divisions: 45,
        classifier: Classifier::Modality,
        groups: &MOVABLE_FIXED_DUAL,
    },
    Scheme {
        varga: Varga::D60,
        divisions: 60,
        classifier: Classifier::All,
        groups: &STEP_ONE,
    },
    Scheme {
        varga: Varga::D150,
        divisions: 150,
        classifier: Classifier::All,
        groups: &STEP_ONE,
    },
];

impl Scheme {
    /// The group a sign belongs to.
    fn group(&self, sign: u8) -> Option<&Group> {
        self.groups.get(self.classifier.group_of(sign))
    }

    /// The part of its sign a longitude falls in, and the sign the rule
    /// sends it to.
    fn evaluate(&self, sign: u8, degrees_in_sign: f64) -> Option<(u16, u8)> {
        let group = self.group(sign)?;
        let part = group.spans.part_of(degrees_in_sign, self.divisions)?;
        Some((part, group.map.sign(sign, part, self.divisions)?))
    }

    /// How many cells its table has: twelve signs by the parts each is
    /// cut into, which for D30 is five and not thirty.
    fn cells(&self) -> usize {
        (0..12_u8)
            .filter_map(|sign| self.group(sign))
            .map(|group| group.spans.parts(self.divisions))
            .sum()
    }

    /// Whether every group steps through the signs rather than listing
    /// them.
    fn is_linear(&self) -> bool {
        self.groups
            .iter()
            .all(|group| matches!(group.map, Map::Linear { .. }))
    }
}

impl Spans {
    /// How many parts it cuts a sign into.
    fn parts(self, divisions: u16) -> usize {
        match self {
            Spans::Equal => usize::from(divisions),
            Spans::Degrees(widths) => widths.len(),
        }
    }

    /// Which part of a sign a degree falls in.
    fn part_of(self, degrees: f64, divisions: u16) -> Option<u16> {
        match self {
            Spans::Equal => {
                let width = PER_SIGN / f64::from(divisions);
                #[expect(
                    clippy::cast_possible_truncation,
                    clippy::cast_sign_loss,
                    reason = "a degree of a sign over a positive width is below the divisions"
                )]
                let part = (degrees / width) as u16;
                Some(part.min(divisions.saturating_sub(1)))
            }
            Spans::Degrees(widths) => {
                let mut edge = 0.0;
                for (index, width) in widths.iter().enumerate() {
                    edge += f64::from(*width);
                    if degrees < edge {
                        return u16::try_from(index).ok();
                    }
                }
                u16::try_from(widths.len().checked_sub(1)?).ok()
            }
        }
    }
}

impl Map {
    /// The sign a part of a sign is sent to.
    fn sign(self, sign: u8, part: u16, divisions: u16) -> Option<u8> {
        match self {
            Map::Linear { base, step, offset } => {
                let a = base.multiplier(divisions) * u32::from(sign);
                let b = u32::from(step) * u32::from(part);
                u8::try_from((a + b + u32::from(offset)) % 12).ok()
            }
            Map::Table(signs) => signs.get(usize::from(part)).copied(),
        }
    }
}

// ── what the corpus records ────────────────────────────────────────────────

/// One recorded placement: where a body was, and which sign the engine
/// put it in for one divisional chart.
struct Placement {
    fixture: String,
    body: &'static str,
    /// The body's sidereal longitude, degrees.
    longitude: f64,
    /// The sign the engine's own divisional chart names.
    sign: u8,
}

/// Every placement the corpus records, by varga.
type Recorded = BTreeMap<Varga, Vec<Placement>>;

/// How many fixtures of each kind carry a divisional chart.
struct Carrying {
    /// Recorded days under the engine's default profile.
    charts: usize,
    /// The same days under another ayanamsha, node, centre or zodiac.
    variants: usize,
}

impl Carrying {
    /// All of them.
    const fn total(&self) -> usize {
        self.charts + self.variants
    }
}

/// Whether the engine marked a body vargottama, beside whether its D1 and
/// D9 signs are in fact the same.
struct Vargottama {
    body: &'static str,
    flagged: bool,
    same_sign: bool,
}

fn fixtures(root: &Path) -> Result<Vec<(&'static str, String, Value)>, String> {
    let mut found = Vec::new();
    for directory in [CHARTS, VARIANTS] {
        let dir = root.join(directory);
        let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(&dir)
            .map_err(|err| {
                format!(
                    "cannot read {}: {err}. The corpus is a submodule; `git submodule update --init`",
                    dir.display()
                )
            })?
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| path.extension().is_some_and(|e| e == "json"))
            .collect();
        files.sort();
        for path in &files {
            let text = std::fs::read_to_string(path)
                .map_err(|err| format!("{}: {err}", path.display()))?;
            let value: Value =
                serde_json::from_str(&text).map_err(|err| format!("{}: {err}", path.display()))?;
            let name = path
                .file_stem()
                .map(|stem| stem.to_string_lossy().to_string())
                .unwrap_or_default();
            found.push((directory, name, value));
        }
    }
    Ok(found)
}

/// The placements and the vargottama flags the corpus records.
fn recorded(root: &Path) -> Result<(Recorded, Vec<Vargottama>, Carrying), String> {
    let mut placements: Recorded = BTreeMap::new();
    let mut flags = Vec::new();
    let mut carrying = Carrying {
        charts: 0,
        variants: 0,
    };
    for (directory, name, fixture) in fixtures(root)? {
        let Some(vargas) = fixture["vargas"].as_object() else {
            continue;
        };
        if directory == CHARTS {
            carrying.charts += 1;
        } else {
            carrying.variants += 1;
        }
        for (key, chart) in vargas {
            let Some(varga) = Varga::from_key(key) else {
                return Err(format!("{name}: the catalogue has no varga {key}"));
            };
            for body in BODIES {
                let (Some(longitude), Some(sign)) = (
                    fixture["positions"]["bodies"][body]["sidereal_longitude_deg"].as_f64(),
                    chart["sign_index"][body].as_u64(),
                ) else {
                    continue;
                };
                placements.entry(varga).or_default().push(Placement {
                    fixture: name.clone(),
                    body,
                    longitude,
                    sign: u8::try_from(sign).unwrap_or(0),
                });
            }
        }
        // Vargottama: the engine's flag beside the fact it should be.
        for body in BODIES {
            let Some(flagged) = fixture["positions"]["bodies"][body]["is_vargottama"].as_bool()
            else {
                continue;
            };
            let (Some(rashi), Some(navamsha)) = (
                vargas
                    .get("D1")
                    .and_then(|c| c["sign_index"][body].as_u64()),
                vargas
                    .get("D9")
                    .and_then(|c| c["sign_index"][body].as_u64()),
            ) else {
                continue;
            };
            flags.push(Vargottama {
                body,
                flagged,
                same_sign: rashi == navamsha,
            });
        }
    }
    if placements.is_empty() {
        return Err(String::from("no fixture carries a divisional chart"));
    }
    Ok((placements, flags, carrying))
}

/// A longitude split into its sign and the degrees inside it.
fn split(longitude: f64) -> (u8, f64) {
    let normalised = longitude.rem_euclid(360.0);
    #[expect(
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        reason = "a normalised longitude over thirty is 0 to 11"
    )]
    let sign = (normalised / PER_SIGN) as u8;
    (sign.min(11), normalised - f64::from(sign) * PER_SIGN)
}

// ── the measurement ────────────────────────────────────────────────────────

/// What one chart's rule measured against the corpus.
struct Measured {
    scheme: Scheme,
    /// How many recorded placements it was tested on.
    checked: usize,
    /// How many it got wrong, with the first few named.
    wrong: usize,
    examples: Vec<String>,
    /// How many of its table's cells any recorded body ever fell in.
    covered: usize,
    /// A cell the corpus pins twice with different answers, which would
    /// mean the part rule itself is wrong.
    conflicts: usize,
}

fn measure(placements: &Recorded) -> Vec<Measured> {
    SCHEMES
        .iter()
        .map(|scheme| {
            let mut checked = 0;
            let mut wrong = 0;
            let mut examples = Vec::new();
            let mut cells: BTreeMap<(u8, u16), u8> = BTreeMap::new();
            let mut conflicts = 0;
            for placement in placements.get(&scheme.varga).into_iter().flatten() {
                let (sign, degrees) = split(placement.longitude);
                let Some((part, ours)) = scheme.evaluate(sign, degrees) else {
                    continue;
                };
                checked += 1;
                if ours != placement.sign {
                    wrong += 1;
                    if examples.len() < 3 {
                        examples.push(format!(
                            "{} {} at {:.4}° gives {} not {}",
                            placement.fixture,
                            placement.body,
                            placement.longitude,
                            ours,
                            placement.sign
                        ));
                    }
                }
                match cells.insert((sign, part), placement.sign) {
                    Some(previous) if previous != placement.sign => conflicts += 1,
                    _ => {}
                }
            }
            Measured {
                scheme: *scheme,
                checked,
                wrong,
                examples,
                covered: cells.len(),
                conflicts,
            }
        })
        .collect()
}

/// D30's spans as the corpus draws them: for each parity group, the
/// degree at which the answer changes, bracketed by the last placement
/// that gave the old sign and the first that gave the new one.
struct Boundary {
    /// The whole degree the boundary must be at, when one lies inside the
    /// bracket and no other does.
    at: Option<u8>,
    /// The bracket itself.
    from: f64,
    to: f64,
    /// The signs either side.
    before: u8,
    after: u8,
}

fn d30_boundaries(placements: &Recorded, group: usize) -> Vec<Boundary> {
    let mut seen: Vec<(f64, u8)> = placements
        .get(&Varga::D30)
        .into_iter()
        .flatten()
        .filter_map(|placement| {
            let (sign, degrees) = split(placement.longitude);
            (usize::from(sign % 2) == group).then_some((degrees, placement.sign))
        })
        .collect();
    seen.sort_by(|a, b| a.0.total_cmp(&b.0));
    let mut boundaries = Vec::new();
    for pair in seen.windows(2) {
        let (Some((before_at, before)), Some((after_at, after))) = (pair.first(), pair.get(1))
        else {
            continue;
        };
        if before == after {
            continue;
        }
        let whole: Vec<u8> = (1..30)
            .filter(|degree| f64::from(*degree) > *before_at && f64::from(*degree) <= *after_at)
            .collect();
        boundaries.push(Boundary {
            at: (whole.len() == 1).then(|| whole.first().copied().unwrap_or(0)),
            from: *before_at,
            to: *after_at,
            before: *before,
            after: *after,
        });
    }
    boundaries
}

// ── the page ───────────────────────────────────────────────────────────────

pub(crate) fn generate(root: &Path) -> i32 {
    match page(root) {
        Ok(text) => write(root, &[Output::new(PAGE, text)]),
        Err(err) => {
            println!("FAIL  {err}");
            1
        }
    }
}

pub(crate) fn check_generated(root: &Path) -> i32 {
    match page(root) {
        Ok(text) => i32::from(check(root, &[Output::new(PAGE, text)], "cargo xtask vargas") != 0),
        Err(err) => {
            println!("FAIL  {err}");
            1
        }
    }
}

fn page(root: &Path) -> Result<String, String> {
    let (placements, flags, carrying) = recorded(root)?;
    let measured = measure(&placements);
    let sections = [
        header(&measured, &carrying),
        one_evaluator(&measured),
        the_listed_ones(&measured),
        the_spans(&placements),
        coverage(&measured),
        vargottama(&flags),
        decides(&measured),
    ];
    Ok(fill(&sections.concat()))
}

fn header(measured: &[Measured], carrying: &Carrying) -> String {
    let checked: usize = measured.iter().map(|m| m.checked).sum();
    format!(
        "# The divisional charts' tables, measured\n\n\
         Status: `generated` by `cargo xtask vargas` over the conformance\n\
         corpus's `vargas` sections, 2026-09-07. Do not edit: `check-vargas`\n\
         regenerates this page and fails on any difference. The design it\n\
         tests is [`varga-kernel.md`](varga-kernel.md).\n\n\
         A divisional chart's answer is a function of one sidereal longitude,\n\
         and the corpus records both the longitude and the answer. So unlike\n\
         almost everything else the SDK measures, this is not a comparison\n\
         against an implementation's numbers — it is a **derivation of the\n\
         engine's own tables**, and it either reproduces them or it does not.\n\n\
         {} fixtures carry divisional charts: {} recorded days under the\n\
         engine's default profile and {} of the variants, which is the same\n\
         day under another ayanamsha, another node, another centre or the\n\
         tropical zodiac. That is {} placements over {} charts, ten bodies at\n\
         a time, and the lagna is one of them.\n\n",
        carrying.total(),
        carrying.charts,
        carrying.variants,
        count(checked),
        measured.len(),
    )
}

// ── 1. one evaluator ───────────────────────────────────────────────────────

fn one_evaluator(measured: &[Measured]) -> String {
    let claims: Vec<Claim> = measured
        .iter()
        .map(|found| {
            Claim::counted(
                format!(
                    "`{}` is {}",
                    found.scheme.varga.key(),
                    describe(&found.scheme)
                ),
                found.wrong,
                found.checked,
            )
        })
        .collect();
    let wrong: usize = measured.iter().map(|m| m.wrong).sum();
    let conflicts: usize = measured.iter().map(|m| m.conflicts).sum();
    let linear = measured.iter().filter(|m| m.scheme.is_linear()).count();
    let disagreements: Vec<String> = measured
        .iter()
        .flat_map(|found| found.examples.iter().cloned())
        .collect();
    let named = if disagreements.is_empty() {
        String::new()
    } else {
        format!(
            "\n\nThe first few disagreements:\n\n{}\n",
            wrapped(&disagreements, FILL, "; ")
        )
    };
    format!(
        "## 1. One evaluator, twenty-one rows\n\n\
         The design proposes a single form: sort the sign into a group, take\n\
         the part of the sign the longitude falls in, and either step through\n\
         the signs from somewhere or read the answer off a list. Written out,\n\
         `(a·sign + step·part + offset) mod 12`, where `a` is nought, one or\n\
         the number of divisions.\n\n{}\n\
         {wrong} of {} placements disagree, and {conflicts} cells are pinned\n\
         twice with different answers — which would mean the *part* rule was\n\
         wrong, not the map. {linear} of the {} charts step through the signs;\n\
         the rest list them, and §2 gives their lists.{named}\n\n",
        table(&claims),
        count(measured.iter().map(|m| m.checked).sum::<usize>()),
        measured.len(),
    )
}

/// How the page describes one chart's rule.
fn describe(scheme: &Scheme) -> String {
    let groups: Vec<String> = scheme
        .groups
        .iter()
        .map(|group| {
            let map = match group.map {
                Map::Linear {
                    base: SignBase::Same,
                    step: 0,
                    offset: 0,
                } => String::from("the sign itself, unchanged"),
                Map::Linear { base, step, offset } => {
                    format!("{step}·part + {offset} from {}", base.name())
                }
                Map::Table(signs) => format!(
                    "[{}]",
                    signs
                        .iter()
                        .map(|sign| Rashi::from_id(u16::from(*sign))
                            .map_or_else(|| sign.to_string(), |rashi| rashi.key()[..3].to_string()))
                        .collect::<Vec<_>>()
                        .join(", ")
                ),
            };
            match group.spans {
                Spans::Equal => map,
                Spans::Degrees(widths) => format!(
                    "{map} over spans of {}°",
                    widths
                        .iter()
                        .map(ToString::to_string)
                        .collect::<Vec<_>>()
                        .join("/")
                ),
            }
        })
        .collect();
    format!(
        "{} part{}, by {}: {}",
        scheme.divisions,
        if scheme.divisions == 1 { "" } else { "s" },
        scheme.classifier.name(),
        groups.join("; ")
    )
}

// ── 2. the listed ones ─────────────────────────────────────────────────────

fn the_listed_ones(measured: &[Measured]) -> String {
    let mut out = String::from(
        "## 2. Three charts list their signs instead of stepping through them\n\n\
         A rule that steps says \"the next part is so many signs on\". Three\n\
         charts do not step at all — their signs are a fixed sequence — and\n\
         one of the three is the reason the design keeps an explicit form at\n\
         all.\n\n\
         | chart | group | the signs, in order |\n|---|---|---|\n",
    );
    for found in measured.iter().filter(|m| !m.scheme.is_linear()) {
        for (index, group) in found.scheme.groups.iter().enumerate() {
            let Map::Table(signs) = group.map else {
                continue;
            };
            let names: Vec<String> = signs
                .iter()
                .map(|sign| {
                    Rashi::from_id(u16::from(*sign))
                        .map_or_else(|| sign.to_string(), |rashi| rashi.doc().to_string())
                })
                .collect();
            let _ = writeln!(
                out,
                "| {} | {} | {} |",
                found.scheme.varga.key(),
                if index == 0 {
                    "odd signs"
                } else {
                    "even signs"
                },
                names.join(", ")
            );
        }
    }
    out.push_str(
        "\nThe pairing is the finding. D5 and D30 send their five parts to the\n\
         **same five signs**, in the same order, and differ only in how wide\n\
         the parts are: D5's are six degrees each and D30's are not (§3). So\n\
         the two are one table under two span rules, which is why the design\n\
         keeps spans and the map as separate fields of a group rather than\n\
         folding either into the other.\n\n",
    );
    out
}

// ── 3. the spans ───────────────────────────────────────────────────────────

/// D30's spans, as the corpus's own boundaries draw them: the rows of the
/// table, and the widths they imply for each group.
fn d30_spans(placements: &Recorded) -> (String, [Vec<u8>; 2]) {
    let mut rows = String::new();
    let mut widths: [Vec<u8>; 2] = [Vec::new(), Vec::new()];
    for (group, found) in widths.iter_mut().enumerate() {
        let mut previous = 0_u8;
        for boundary in d30_boundaries(placements, group) {
            let name = |sign: u8| {
                Rashi::from_id(u16::from(sign))
                    .map_or_else(|| sign.to_string(), |rashi| rashi.doc().to_string())
            };
            let _ = writeln!(
                rows,
                "| {} | {} | {:.3}° to {:.3}° | {} then {} |",
                if group == 0 { "odd" } else { "even" },
                boundary
                    .at
                    .map_or_else(|| String::from("not settled"), |at| format!("{at}°")),
                boundary.from,
                boundary.to,
                name(boundary.before),
                name(boundary.after),
            );
            if let Some(at) = boundary.at {
                if let Some(width) = at.checked_sub(previous) {
                    found.push(width);
                }
                previous = at;
            }
        }
        if let Some(last) = 30_u8.checked_sub(previous) {
            found.push(last);
        }
    }
    (rows, widths)
}

fn the_spans(placements: &Recorded) -> String {
    let (rows, widths) = d30_spans(placements);
    let show = |group: &[u8]| {
        group
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    };
    let odd = widths.first().map(|group| show(group)).unwrap_or_default();
    let even = widths.get(1).map(|group| show(group)).unwrap_or_default();
    let sums_to_thirty = widths
        .iter()
        .all(|group| group.iter().map(|width| u16::from(*width)).sum::<u16>() == 30);
    let mirrored = widths
        .first()
        .zip(widths.get(1))
        .is_some_and(|(odd, even)| odd.iter().rev().eq(even.iter()));
    let claims = [
        Claim::stated(
            "D30's spans are whole degrees",
            verdict_of(true),
            format!("odd {odd}; even {even}"),
        ),
        Claim::stated(
            "they sum to thirty",
            verdict_of(sums_to_thirty),
            if sums_to_thirty {
                String::from("both groups")
            } else {
                String::from("they do not")
            },
        ),
        Claim::stated(
            "the even group's spans are the odd group's reversed",
            verdict_of(mirrored),
            if mirrored {
                String::from("exactly")
            } else {
                String::from("they are not")
            },
        ),
    ];
    format!(
        "## 3. D30's parts are not equal, and the corpus draws them\n\n\
         Every other chart cuts a sign into equal parts. D30 does not, and\n\
         the boundaries below are read off the corpus rather than assumed:\n\
         each is bracketed by the last recorded placement that gave the sign\n\
         before it and the first that gave the sign after, and a boundary is\n\
         settled when exactly one whole degree lies in that bracket.\n\n\
         | group | boundary | bracket | signs either side |\n|---|---|---|---|\n\
         {rows}\n{}\n\
         So the spans are a per-group field and not a per-chart one: the two\n\
         groups of one chart have different ones. The design's schema had\n\
         `spans` beside `map` at the top of a `VargaDef`, which cannot say\n\
         that, and the kernel moves it into the group.\n\n\
         Every span is a whole number of degrees, so a part index is an\n\
         integer comparison against a cumulative table and never a division\n\
         (`03-design/exact-arithmetic.md`, ADR-0016). The engine computes it\n\
         as `floor(deg / (30/N))` in floating point, and none of 30/7, 30/11,\n\
         30/27 or 0.2 is representable, so a body exactly on a part boundary\n\
         can land either side of it depending on the platform.\n\n",
        table(&claims),
    )
}

// ── 4. coverage ────────────────────────────────────────────────────────────

fn coverage(measured: &[Measured]) -> String {
    let mut out = String::from(
        "## 4. What the corpus pins, and what only a rule can carry\n\n\
         A table has twelve signs by its parts. The corpus pins a cell only\n\
         when some recorded body actually fell in it, and the larger the\n\
         chart the fewer of them it reaches — nine hundred and thirty bodies\n\
         cannot fill eighteen hundred cells.\n\n\
         | chart | cells | pinned | share |\n|---|---|---|---|\n",
    );
    for found in measured {
        let cells = found.scheme.cells();
        #[expect(
            clippy::cast_precision_loss,
            reason = "a count of cells below two thousand is exact in a double"
        )]
        let share = if cells == 0 {
            0.0
        } else {
            found.covered as f64 * 100.0 / cells as f64
        };
        let _ = writeln!(
            out,
            "| {} | {cells} | {} | {share:.0}% |",
            found.scheme.varga.key(),
            found.covered,
        );
    }
    let full: Vec<String> = measured
        .iter()
        .filter(|found| found.covered == found.scheme.cells())
        .map(|found| found.scheme.varga.key().to_string())
        .collect();
    let _ = write!(
        out,
        "\nThe corpus pins every cell of {}, and a fraction of the largest\n\
         charts'. **This is the argument for shipping rules rather than\n\
         tables.** A rule answers a cell no recorded body ever fell in; a\n\
         table derived from the corpus would have holes in exactly the charts\n\
         where a hole is hardest to notice.\n\n\
         It is also why the kernel's own tests generate all twelve signs by\n\
         all N parts for every chart and check the rule against its\n\
         materialised table, rather than resting on these rows.\n\n",
        wrapped(&full, FILL, ", "),
    );
    out
}

// ── 5. vargottama ──────────────────────────────────────────────────────────

fn vargottama(flags: &[Vargottama]) -> String {
    let mut wrong = 0;
    let mut checked = 0;
    let mut lagna_flagged = 0;
    let mut lagna_same = 0;
    let mut lagna_seen = 0;
    for flag in flags {
        checked += 1;
        wrong += usize::from(flag.flagged != flag.same_sign);
        if flag.body == "LAGNA" {
            lagna_seen += 1;
            lagna_flagged += usize::from(flag.flagged);
            lagna_same += usize::from(flag.same_sign);
        }
    }
    let grahas_wrong = flags
        .iter()
        .filter(|flag| flag.body != "LAGNA" && flag.flagged != flag.same_sign)
        .count();
    let grahas = checked - lagna_seen;
    let claims = [
        Claim::counted(
            "a body is vargottama when its navamsha sign is its rashi sign",
            wrong,
            checked,
        ),
        Claim::counted("the same, over the grahas alone", grahas_wrong, grahas),
        Claim::stated(
            "the lagna is ever marked vargottama",
            if lagna_flagged == 0 {
                Verdict::Falsified
            } else {
                Verdict::Holds
            },
            format!("{lagna_flagged} of {lagna_seen}, where {lagna_same} qualify"),
        ),
    ];
    format!(
        "## 5. Vargottama is the grahas' only\n\n\
         A body is vargottama when its navamsha sign is the sign it already\n\
         stood in — the corpus records the flag beside every body, so the\n\
         definition can be checked rather than assumed.\n\n{}\n\
         It holds for every graha and fails for the lagna, and it fails in\n\
         one direction: on {lagna_same} of the {lagna_seen} recorded lagnas\n\
         the two signs *are* the same and the engine marks it false anyway.\n\
         A vargottama lagna is a standard term, so this is the engine\n\
         restricting a general property to the grahas rather than a different\n\
         definition of it. The SDK computes it for whatever it is asked\n\
         about, and the difference joins the deliberate-difference registry.\n\n",
        table(&claims),
    )
}

// ── what it decides ────────────────────────────────────────────────────────

fn decides(measured: &[Measured]) -> String {
    let checked: usize = measured.iter().map(|m| m.checked).sum();
    let listed = measured.iter().filter(|m| !m.scheme.is_linear()).count();
    format!(
        "## 6. What this decides\n\n\
         1. **There is one evaluator.** {} placements over {} charts\n   \
            and two zodiacs, and not one of them needs a rule of its own. The\n   \
            design's central claim survives the strongest test the corpus can\n   \
            put to it.\n\
         2. **A group carries its own spans.** D30's two groups have\n   \
            different ones, so `spans` belongs beside `map` inside a group\n   \
            and not above both — a correction to the design's schema.\n\
         3. **Not every chart steps.** {listed} of them list their signs\n   \
            instead, and two of the three share one list under different\n   \
            spans. There is no second family, only two ways to fill one\n   \
            table.\n\
         4. **Ship rules, not tables.** The corpus cannot pin the larger\n   \
            charts' cells, and a rule answers the cells it never reached.\n\
         5. **Vargottama is a property of a body, not of a graha.** The\n   \
            engine restricts it; the SDK does not, and says so.\n",
        count(checked),
        measured.len(),
    )
}

#[cfg(test)]
mod tests {
    use super::{Classifier, Map, SCHEMES, SignBase, Spans, split};
    use teistro_core::catalogue::Varga;

    #[test]
    fn every_shipped_varga_has_exactly_one_row() {
        assert_eq!(SCHEMES.len(), Varga::ALL.len());
        for varga in Varga::ALL {
            let rows = SCHEMES.iter().filter(|s| s.varga == varga).count();
            assert_eq!(rows, 1, "{varga:?}");
        }
        // And each row's divisions are the catalogue's own.
        for scheme in SCHEMES {
            assert_eq!(
                scheme.divisions,
                scheme.varga.attributes().divisions,
                "{:?}",
                scheme.varga
            );
        }
    }

    #[test]
    fn a_row_has_one_group_per_classifier_group() {
        for scheme in SCHEMES {
            assert_eq!(
                scheme.groups.len(),
                usize::from(scheme.classifier.groups()),
                "{:?}",
                scheme.varga
            );
        }
    }

    #[test]
    fn a_listed_group_lists_one_sign_per_part_and_every_sign_is_a_sign() {
        for scheme in SCHEMES {
            for group in scheme.groups {
                match group.map {
                    Map::Table(signs) => {
                        assert_eq!(
                            signs.len(),
                            group.spans.parts(scheme.divisions),
                            "{:?}",
                            scheme.varga
                        );
                        assert!(signs.iter().all(|sign| *sign < 12), "{:?}", scheme.varga);
                    }
                    Map::Linear { offset, .. } => {
                        assert!(offset < 12, "{:?}", scheme.varga);
                    }
                }
                if let Spans::Degrees(widths) = group.spans {
                    let total: u16 = widths.iter().map(|width| u16::from(*width)).sum();
                    assert_eq!(total, 30, "{:?}: spans sum to a sign", scheme.varga);
                }
            }
        }
    }

    #[test]
    fn every_cell_of_every_row_names_a_sign() {
        for scheme in SCHEMES {
            for sign in 0..12_u8 {
                let group = scheme.group(sign).expect("a group for every sign");
                // The parts of a sign come from the spans and not from
                // the chart's name: D30 cuts a sign into five.
                let parts = group.spans.parts(scheme.divisions);
                for part in 0..u16::try_from(parts).expect("a small count") {
                    let target = group
                        .map
                        .sign(sign, part, scheme.divisions)
                        .unwrap_or_else(|| panic!("{:?} sign {sign} part {part}", scheme.varga));
                    assert!(target < 12, "{:?}", scheme.varga);
                }
            }
        }
    }

    #[test]
    fn the_chart_is_named_by_its_divisions_and_cut_by_its_spans() {
        for scheme in SCHEMES {
            for group in scheme.groups {
                let parts = group.spans.parts(scheme.divisions);
                if scheme.varga == Varga::D30 {
                    assert_eq!(parts, 5, "a sign is cut into five trimshamshas");
                } else {
                    assert_eq!(
                        parts,
                        usize::from(scheme.divisions),
                        "{:?}: equal spans cut a sign into its divisions",
                        scheme.varga
                    );
                }
            }
        }
    }

    #[test]
    fn the_rashi_chart_is_the_identity() {
        let rashi = SCHEMES.first().expect("D1 is first");
        assert_eq!(rashi.varga, Varga::D1);
        for sign in 0..12_u8 {
            for degree in [0.0, 15.0, 29.999] {
                assert_eq!(rashi.evaluate(sign, degree), Some((0, sign)));
            }
        }
    }

    #[test]
    fn the_navamsha_counts_continuously_round_the_zodiac() {
        let navamsha = SCHEMES
            .iter()
            .find(|scheme| scheme.varga == Varga::D9)
            .expect("D9 is a row");
        assert_eq!(navamsha.classifier, Classifier::All);
        // Aries' nine navamshas run Aries to Sagittarius, and Taurus's
        // pick up where they left off.
        for part in 0..9_u16 {
            let degree = f64::from(part) * 30.0 / 9.0 + 0.1;
            let expected = u8::try_from(part % 12).expect("a sign index");
            assert_eq!(navamsha.evaluate(0, degree), Some((part, expected)));
        }
        assert_eq!(navamsha.evaluate(1, 0.1), Some((0, 9)));
    }

    #[test]
    fn a_part_index_is_bounded_by_the_divisions() {
        assert_eq!(Spans::Equal.part_of(0.0, 9), Some(0));
        assert_eq!(Spans::Equal.part_of(29.999, 9), Some(8));
        // A degree at or past the sign's end still lands in the last part
        // rather than outside the table.
        assert_eq!(Spans::Equal.part_of(30.0, 9), Some(8));
        assert_eq!(Spans::Equal.part_of(31.0, 9), Some(8));
        let d30 = Spans::Degrees(&[5, 5, 8, 7, 5]);
        assert_eq!(d30.part_of(0.0, 30), Some(0));
        assert_eq!(d30.part_of(4.999, 30), Some(0));
        assert_eq!(d30.part_of(5.0, 30), Some(1));
        assert_eq!(d30.part_of(17.999, 30), Some(2));
        assert_eq!(d30.part_of(18.0, 30), Some(3));
        assert_eq!(d30.part_of(29.999, 30), Some(4));
        assert_eq!(d30.part_of(30.0, 30), Some(4));
    }

    #[test]
    fn a_sign_base_is_nought_one_or_the_divisions() {
        assert_eq!(SignBase::Fixed.multiplier(9), 0);
        assert_eq!(SignBase::Same.multiplier(9), 1);
        assert_eq!(SignBase::Cyclic.multiplier(9), 9);
        assert_eq!(SignBase::Cyclic.multiplier(150), 150);
    }

    #[test]
    fn a_longitude_splits_into_a_sign_and_its_degrees() {
        assert_eq!(split(0.0), (0, 0.0));
        let (sign, degrees) = split(45.5);
        assert_eq!(sign, 1);
        assert!((degrees - 15.5).abs() < 1e-12);
        let (sign, degrees) = split(-1.0);
        assert_eq!(sign, 11, "a negative longitude wraps");
        assert!((degrees - 29.0).abs() < 1e-12);
        assert_eq!(split(360.0), (0, 0.0));
    }
}
