// Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary
// crates; do not edit. ABI version 1, SDK 0.0.0.
//
// The description this file was rendered from ships as idl/api.json.
//
// The generator lays this file out, so `dart format .` leaves it alone
// and `cargo xtask check-ffi` can regenerate it on a machine with no
// Dart toolchain and still compare it byte for byte.
// dart format off


import 'dart:convert';
import 'dart:typed_data';


const int _magic = 0x42525354; // 'TSRB'
const int _version = 1;
const int _headerLength = 32;
const int _entryLength = 16;

/// One section of a blob, as its table of contents describes it.
final class _Section {
  const _Section(this.offset, this.length, this.count);

  final int offset;
  final int length;
  final int count;
}

/// A blob opened for reading: the bytes, a view over them, and the table.
final class _Blob {
  _Blob(this.bytes, this.data, this.sections);

  final Uint8List bytes;
  final ByteData data;
  final Map<int, _Section> sections;

  /// Reads the header and the table, checking every offset.
  factory _Blob.open(Uint8List raw, int schemaId, String schemaName) {
    // A column is read as a typed list over these bytes, and a typed list
    // must start on a multiple of its element's size. A view handed to us
    // at an offset that cannot give that is copied once, here, rather
    // than misread or refused.
    final input = raw.offsetInBytes % 8 == 0
        ? raw
        : Uint8List.fromList(raw);
    final data = ByteData.sublistView(input);
    if (input.lengthInBytes < _headerLength ||
        data.getUint32(0, Endian.little) != _magic) {
      throw const FormatException('not a Teistro result blob');
    }
    final version = data.getUint32(4, Endian.little);
    if (version != _version) {
      throw FormatException(
        'blob layout version $version, this decoder reads version $_version',
      );
    }
    final total = data.getUint32(12, Endian.little);
    if (total != input.lengthInBytes) {
      throw FormatException(
        'the header says $total bytes, ${input.lengthInBytes} were given',
      );
    }
    final id = data.getUint32(16, Endian.little);
    if (id != schemaId) {
      throw FormatException('blob schema $id, expected $schemaId ($schemaName)');
    }
    final count = data.getUint32(8, Endian.little);
    final sections = <int, _Section>{};
    for (var i = 0; i < count; i++) {
      final at = _headerLength + i * _entryLength;
      final section = _Section(
        data.getUint32(at + 4, Endian.little),
        data.getUint32(at + 8, Endian.little),
        data.getUint32(at + 12, Endian.little),
      );
      if (section.offset + section.length > total) {
        throw FormatException(
          'section ${data.getUint32(at, Endian.little)} runs past the end of the blob',
        );
      }
      sections[data.getUint32(at, Endian.little)] = section;
    }
    return _Blob(input, data, sections);
  }

  /// The section with an id, or a [FormatException] naming what is missing.
  _Section section(int id, String name) {
    final found = sections[id];
    if (found == null) {
      throw FormatException('the blob carries no `$name` section');
    }
    return found;
  }

  /// The offset of one column of a column section.
  int columnOffset(_Section at, int index) =>
      at.offset + data.getUint32(at.offset + index * 4, Endian.little);

  /// A bytes section as the UTF-8 text the library wrote.
  String text(_Section at) =>
      utf8.decode(Uint8List.sublistView(bytes, at.offset, at.offset + at.count));
}
/// The `instants` section of a Positions blob: one typed list per column, each a
/// view over the blob's bytes rather than a copy.
///
/// The instants of the request, in order.
final class PositionsInstants {
  const PositionsInstants({
    required this.jd,
    required this.length,
  });

  /// A Julian day on the request's scale.
  final Float64List jd;

  /// The number of rows every column holds.
  final int length;
}

/// The `bodies` section of a Positions blob: one typed list per column, each a
/// view over the blob's bytes rather than a copy.
///
/// The bodies of the request, in order.
final class PositionsBodies {
  const PositionsBodies({
    required this.body,
    required this.length,
  });

  /// A body id.
  final Uint16List body;

  /// The number of rows every column holds.
  final int length;
}

/// The `cells` section of a Positions blob: one typed list per column, each a
/// view over the blob's bytes rather than a copy.
///
/// One row per cell, instants outermost; a cell whose status is not zero carries no value.
final class PositionsCells {
  const PositionsCells({
    required this.lon,
    required this.lat,
    required this.dist,
    required this.lonSpeed,
    required this.latSpeed,
    required this.distSpeed,
    required this.status,
    required this.source,
    required this.length,
  });

  /// Longitude in degrees, 0 to 360.
  final Float64List lon;

  /// Latitude in degrees.
  final Float64List lat;

  /// Distance in the provider's unit.
  final Float64List dist;

  /// Longitude speed in degrees per day; zero when speeds were not asked for.
  final Float64List lonSpeed;

  /// Latitude speed in degrees per day.
  final Float64List latSpeed;

  /// Distance speed per day.
  final Float64List distSpeed;

  /// The cell's status code; zero is a value.
  final Int32List status;

  /// What computed the cell, packed as the port packs it.
  final Uint32List source;

  /// The number of rows every column holds.
  final int length;
}

/// A decoded Positions blob.
///
/// Positions over a grid of instants and bodies, instants outermost: cell `i * body_count + j` is instant `i`, body `j`.
final class Positions {
  const Positions({
    required this.frameBits,
    required this.jdCount,
    required this.bodyCount,
    required this.scale,
    required this.instants,
    required this.bodies,
    required this.cells,
    required this.steps,
    required this.provenance,
  });

  /// The frame the values are in, packed as the port packs it.
  final int frameBits;

  /// The number of instants.
  final int jdCount;

  /// The number of bodies.
  final int bodyCount;

  /// The time scale of the instants.
  final int scale;

  /// The instants of the request, in order.
  final PositionsInstants instants;

  /// The bodies of the request, in order.
  final PositionsBodies bodies;

  /// One row per cell, instants outermost; a cell whose status is not zero carries no value.
  final PositionsCells cells;

  /// UTF-8 JSON: the completion steps applied, in order, each `{"name", "implementation"}`.
  final String steps;

  /// UTF-8 JSON: the provenance envelope of the result, canonical.
  final String provenance;

}

/// Decodes a Positions blob. The columns are views over `bytes`, so the
/// buffer must outlive the result; a blob of another layout version or
/// another schema is a [FormatException].
Positions decodePositions(Uint8List bytes) {
  final blob = _Blob.open(bytes, 1, 'positions');
  final atSummary = blob.section(1, 'summary');
  final atInstants = blob.section(2, 'instants');
  final atBodies = blob.section(3, 'bodies');
  final atCells = blob.section(4, 'cells');
  final atSteps = blob.section(5, 'steps');
  final atProvenance = blob.section(6, 'provenance');
  return Positions(
    frameBits: blob.data.getUint32(atSummary.offset + 0, Endian.little),
    jdCount: blob.data.getUint32(atSummary.offset + 8, Endian.little),
    bodyCount: blob.data.getUint32(atSummary.offset + 16, Endian.little),
    scale: blob.data.getUint32(atSummary.offset + 24, Endian.little),
    instants: PositionsInstants(
      jd: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atInstants, 0),
        blob.columnOffset(atInstants, 0) + atInstants.count * 8,
      ),
      length: atInstants.count,
    ),
    bodies: PositionsBodies(
      body: Uint16List.sublistView(
        blob.bytes,
        blob.columnOffset(atBodies, 0),
        blob.columnOffset(atBodies, 0) + atBodies.count * 2,
      ),
      length: atBodies.count,
    ),
    cells: PositionsCells(
      lon: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 0),
        blob.columnOffset(atCells, 0) + atCells.count * 8,
      ),
      lat: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 1),
        blob.columnOffset(atCells, 1) + atCells.count * 8,
      ),
      dist: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 2),
        blob.columnOffset(atCells, 2) + atCells.count * 8,
      ),
      lonSpeed: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 3),
        blob.columnOffset(atCells, 3) + atCells.count * 8,
      ),
      latSpeed: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 4),
        blob.columnOffset(atCells, 4) + atCells.count * 8,
      ),
      distSpeed: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 5),
        blob.columnOffset(atCells, 5) + atCells.count * 8,
      ),
      status: Int32List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 6),
        blob.columnOffset(atCells, 6) + atCells.count * 4,
      ),
      source: Uint32List.sublistView(
        blob.bytes,
        blob.columnOffset(atCells, 7),
        blob.columnOffset(atCells, 7) + atCells.count * 4,
      ),
      length: atCells.count,
    ),
    steps: blob.text(atSteps),
    provenance: blob.text(atProvenance),
  );
}

/// A decoded IntlRender blob.
///
/// A rendered message.
final class IntlRender {
  const IntlRender({
    required this.isFallback,
    required this.isOverride,
    required this.warningCount,
    required this.text,
    required this.resolvedFrom,
    required this.warnings,
  });

  /// Non-zero when a fallback locale answered.
  final int isFallback;

  /// Non-zero when a runtime override answered.
  final int isOverride;

  /// The number of warnings.
  final int warningCount;

  /// UTF-8: the plain text, markup stripped.
  final String text;

  /// UTF-8: the locale whose message answered; empty when none had it.
  final String resolvedFrom;

  /// UTF-8 JSON: an array of strings, one per problem met.
  final String warnings;

}

/// Decodes a IntlRender blob. The columns are views over `bytes`, so the
/// buffer must outlive the result; a blob of another layout version or
/// another schema is a [FormatException].
IntlRender decodeIntlRender(Uint8List bytes) {
  final blob = _Blob.open(bytes, 2, 'intl_render');
  final atFlags = blob.section(1, 'flags');
  final atText = blob.section(2, 'text');
  final atResolvedFrom = blob.section(3, 'resolved_from');
  final atWarnings = blob.section(4, 'warnings');
  return IntlRender(
    isFallback: blob.data.getUint8(atFlags.offset + 0),
    isOverride: blob.data.getUint8(atFlags.offset + 8),
    warningCount: blob.data.getUint32(atFlags.offset + 16, Endian.little),
    text: blob.text(atText),
    resolvedFrom: blob.text(atResolvedFrom),
    warnings: blob.text(atWarnings),
  );
}

/// The `grahas` section of a Chart blob: one typed list per column, each a
/// view over the blob's bytes rather than a copy.
///
/// One row per graha, in the catalogue's order. `house_*` is the bhava for "which house is it in"; `placement_*` is the chart's chalit, which is a different question and often a different answer.
final class ChartGrahas {
  const ChartGrahas({
    required this.graha,
    required this.longitudeDeg,
    required this.tropicalDeg,
    required this.latitudeDeg,
    required this.distanceAu,
    required this.speedDegPerDay,
    required this.houseBhava,
    required this.houseMethod,
    required this.houseThrough,
    required this.houseFromMadhyaDeg,
    required this.placementBhava,
    required this.placementMethod,
    required this.placementThrough,
    required this.placementFromMadhyaDeg,
    required this.length,
  });

  /// Which graha.
  final Uint16List graha;

  /// Its longitude in the chart's zodiac, degrees.
  final Float64List longitudeDeg;

  /// Its longitude in the tropical zodiac, degrees.
  final Float64List tropicalDeg;

  /// Its latitude, degrees.
  final Float64List latitudeDeg;

  /// Its distance in astronomical units; zero for a point that has none.
  final Float64List distanceAu;

  /// Its longitude speed, degrees per day; negative when retrograde.
  final Float64List speedDegPerDay;

  /// The bhava it stands in, 1 to 12.
  final Uint8List houseBhava;

  /// The house system that produced that bhava.
  final Uint16List houseMethod;

  /// How far through the bhava it stands, 0 to 1.
  final Float64List houseThrough;

  /// Its distance from the bhava's madhya, degrees.
  final Float64List houseFromMadhyaDeg;

  /// The bhava of the chart's chalit it stands in, 1 to 12.
  final Uint8List placementBhava;

  /// The house system that produced the chalit.
  final Uint16List placementMethod;

  /// How far through that bhava it stands, 0 to 1.
  final Float64List placementThrough;

  /// Its distance from that bhava's madhya, degrees.
  final Float64List placementFromMadhyaDeg;

  /// The number of rows every column holds.
  final int length;
}

/// The `houses` section of a Chart blob: one typed list per column, each a
/// view over the blob's bytes rather than a copy.
///
/// The twelve bhavas for "which house is it in": one row per bhava, first to twelfth.
final class ChartHouses {
  const ChartHouses({
    required this.madhyaDeg,
    required this.sandhiDeg,
    required this.length,
  });

  /// The bhava's centre, degrees.
  final Float64List madhyaDeg;

  /// The bhava's opening cusp, degrees.
  final Float64List sandhiDeg;

  /// The number of rows every column holds.
  final int length;
}

/// The `chalit` section of a Chart blob: one typed list per column, each a
/// view over the blob's bytes rather than a copy.
///
/// The twelve bhavas of the chart's chalit, the same shape as `houses`.
final class ChartChalit {
  const ChartChalit({
    required this.madhyaDeg,
    required this.sandhiDeg,
    required this.length,
  });

  /// The bhava's centre, degrees.
  final Float64List madhyaDeg;

  /// The bhava's opening cusp, degrees.
  final Float64List sandhiDeg;

  /// The number of rows every column holds.
  final int length;
}

/// The day the instant belongs to: its arc, its date and how it was reckoned.
final class Day {
  const Day({
    required this.sunrise,
    required this.sunset,
    required this.nextSunrise,
    required this.vara,
    required this.part,
    required this.elapsed,
    required this.calendar,
    required this.era,
    required this.year,
    required this.eraYear,
    required this.month,
    required this.dayOfMonth,
    required this.resolution,
    required this.computedMonth,
    required this.computedDay,
    required this.conventionKind,
    required this.conventionValue,
  });

  /// The sunrise that opened the day, as a Julian day (UTC).
  final double sunrise;

  /// The sunset that closed its daylight, as a Julian day (UTC).
  final double sunset;

  /// The sunrise that closes it, as a Julian day (UTC).
  final double nextSunrise;

  /// The weekday the day carries.
  final int vara;

  /// Which arc of the day the instant falls in.
  final int part;

  /// How far through that arc the instant is, 0 to 1.
  final double elapsed;

  /// The calendar the date is in.
  final int calendar;

  /// The era the date's year is counted in.
  final int era;

  /// The astronomical year; 1 BCE is 0.
  final int year;

  /// The year as the era counts it.
  final int eraYear;

  /// The month, 1 to 12 or 13.
  final int month;

  /// The day of the month.
  final int dayOfMonth;

  /// How the date was resolved.
  final int resolution;

  /// The engine's month where it differs from the table's; zero otherwise.
  final int computedMonth;

  /// The engine's day where it differs from the table's; zero otherwise.
  final int computedDay;

  /// Which sunrise convention the arc was reckoned by; `0xFF` for a custom altitude.
  final int conventionKind;

  /// The altitude in degrees when the convention is custom; zero otherwise.
  final double conventionValue;

}

/// A decoded Chart blob.
///
/// A founded chart: the grahas placed, the bhavas under both readings, the zodiac, the day and the timing.
final class Chart {
  const Chart({
    required this.instant,
    required this.kind,
    required this.lagnaDeg,
    required this.dayLagnaDeg,
    required this.latitudeDeg,
    required this.longitudeDeg,
    required this.altitudeM,
    required this.grahaCount,
    required this.grahas,
    required this.housesMethod,
    required this.housesSource,
    required this.housesReading,
    required this.chalitMethod,
    required this.chalitSource,
    required this.chalitReading,
    required this.houses,
    required this.chalit,
    required this.frameBits,
    required this.offsetDeg,
    required this.ayanamshaKind,
    required this.ayanamsha,
    required this.day,
    required this.ghati,
    required this.pala,
    required this.vipala,
    required this.ghatiReckoning,
    required this.horaNumber,
    required this.horaLord,
    required this.horaStart,
    required this.horaEnd,
    required this.horaReckoning,
    required this.model,
    required this.steps,
    required this.provenance,
  });

  /// The instant the chart is cast for, as a Julian day (UTC).
  final double instant;

  /// What kind of chart this is.
  final int kind;

  /// The lagna at the instant, in the chart's zodiac, degrees.
  final double lagnaDeg;

  /// The lagna at the sunrise that opened the day, degrees.
  final double dayLagnaDeg;

  /// The place's latitude, degrees north.
  final double latitudeDeg;

  /// The place's longitude, degrees east.
  final double longitudeDeg;

  /// The place's altitude, metres.
  final double altitudeM;

  /// How many rows the `grahas` section holds.
  final int grahaCount;

  /// One row per graha, in the catalogue's order. `house_*` is the bhava for "which house is it in"; `placement_*` is the chart's chalit, which is a different question and often a different answer.
  final ChartGrahas grahas;

  /// The system the houses were computed under.
  final int housesMethod;

  /// The system its cusps came from.
  final int housesSource;

  /// Which bound the houses are read against.
  final int housesReading;

  /// The system the chalit was computed under.
  final int chalitMethod;

  /// The system its cusps came from.
  final int chalitSource;

  /// Which bound the chalit is read against.
  final int chalitReading;

  /// The twelve bhavas for "which house is it in": one row per bhava, first to twelfth.
  final ChartHouses houses;

  /// The twelve bhavas of the chart's chalit, the same shape as `houses`.
  final ChartChalit chalit;

  /// The frame the positions were asked for, packed as the port packs it.
  final int frameBits;

  /// The ayanamsha applied, degrees; zero for a tropical chart.
  final double offsetDeg;

  /// 0 for none, 1 for a catalogued ayanamsha, 2 for one the settings define.
  final int ayanamshaKind;

  /// Which catalogued ayanamsha, when the kind is 1.
  final int ayanamsha;

  /// The day the instant belongs to: its arc, its date and how it was reckoned.
  final Day day;

  /// The ishtakaal's ghatis since sunrise, 0 to 59.
  final int ghati;

  /// Its palas, 0 to 59.
  final int pala;

  /// Its vipalas, 0 to 59.
  final int vipala;

  /// How the ghatis were measured.
  final int ghatiReckoning;

  /// Which hora of the day holds the instant, 1 to 24.
  final int horaNumber;

  /// The graha that rules it.
  final int horaLord;

  /// When that hora began, as a Julian day (UTC).
  final double horaStart;

  /// When it ends, as a Julian day (UTC).
  final double horaEnd;

  /// How the horas were measured.
  final int horaReckoning;

  /// UTF-8 text: the solar model that reckoned the day, as it describes itself.
  final String model;

  /// UTF-8 JSON: the completion steps applied, in order, each `{"name", "implementation"}`.
  final String steps;

  /// UTF-8 JSON: the provenance envelope of the result, canonical.
  final String provenance;

}

/// Decodes a Chart blob. The columns are views over `bytes`, so the
/// buffer must outlive the result; a blob of another layout version or
/// another schema is a [FormatException].
Chart decodeChart(Uint8List bytes) {
  final blob = _Blob.open(bytes, 3, 'chart');
  final atSummary = blob.section(1, 'summary');
  final atGrahas = blob.section(2, 'grahas');
  final atReadings = blob.section(3, 'readings');
  final atHouses = blob.section(4, 'houses');
  final atChalit = blob.section(5, 'chalit');
  final atZodiac = blob.section(6, 'zodiac');
  final atDay = blob.section(7, 'day');
  final atTiming = blob.section(8, 'timing');
  final atModel = blob.section(9, 'model');
  final atSteps = blob.section(10, 'steps');
  final atProvenance = blob.section(11, 'provenance');
  return Chart(
    instant: blob.data.getFloat64(atSummary.offset + 0, Endian.little),
    kind: blob.data.getUint16(atSummary.offset + 8, Endian.little),
    lagnaDeg: blob.data.getFloat64(atSummary.offset + 16, Endian.little),
    dayLagnaDeg: blob.data.getFloat64(atSummary.offset + 24, Endian.little),
    latitudeDeg: blob.data.getFloat64(atSummary.offset + 32, Endian.little),
    longitudeDeg: blob.data.getFloat64(atSummary.offset + 40, Endian.little),
    altitudeM: blob.data.getFloat64(atSummary.offset + 48, Endian.little),
    grahaCount: blob.data.getUint32(atSummary.offset + 56, Endian.little),
    grahas: ChartGrahas(
      graha: Uint16List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 0),
        blob.columnOffset(atGrahas, 0) + atGrahas.count * 2,
      ),
      longitudeDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 1),
        blob.columnOffset(atGrahas, 1) + atGrahas.count * 8,
      ),
      tropicalDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 2),
        blob.columnOffset(atGrahas, 2) + atGrahas.count * 8,
      ),
      latitudeDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 3),
        blob.columnOffset(atGrahas, 3) + atGrahas.count * 8,
      ),
      distanceAu: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 4),
        blob.columnOffset(atGrahas, 4) + atGrahas.count * 8,
      ),
      speedDegPerDay: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 5),
        blob.columnOffset(atGrahas, 5) + atGrahas.count * 8,
      ),
      houseBhava: Uint8List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 6),
        blob.columnOffset(atGrahas, 6) + atGrahas.count * 1,
      ),
      houseMethod: Uint16List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 7),
        blob.columnOffset(atGrahas, 7) + atGrahas.count * 2,
      ),
      houseThrough: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 8),
        blob.columnOffset(atGrahas, 8) + atGrahas.count * 8,
      ),
      houseFromMadhyaDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 9),
        blob.columnOffset(atGrahas, 9) + atGrahas.count * 8,
      ),
      placementBhava: Uint8List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 10),
        blob.columnOffset(atGrahas, 10) + atGrahas.count * 1,
      ),
      placementMethod: Uint16List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 11),
        blob.columnOffset(atGrahas, 11) + atGrahas.count * 2,
      ),
      placementThrough: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 12),
        blob.columnOffset(atGrahas, 12) + atGrahas.count * 8,
      ),
      placementFromMadhyaDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atGrahas, 13),
        blob.columnOffset(atGrahas, 13) + atGrahas.count * 8,
      ),
      length: atGrahas.count,
    ),
    housesMethod: blob.data.getUint16(atReadings.offset + 0, Endian.little),
    housesSource: blob.data.getUint16(atReadings.offset + 8, Endian.little),
    housesReading: blob.data.getUint8(atReadings.offset + 16),
    chalitMethod: blob.data.getUint16(atReadings.offset + 24, Endian.little),
    chalitSource: blob.data.getUint16(atReadings.offset + 32, Endian.little),
    chalitReading: blob.data.getUint8(atReadings.offset + 40),
    houses: ChartHouses(
      madhyaDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atHouses, 0),
        blob.columnOffset(atHouses, 0) + atHouses.count * 8,
      ),
      sandhiDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atHouses, 1),
        blob.columnOffset(atHouses, 1) + atHouses.count * 8,
      ),
      length: atHouses.count,
    ),
    chalit: ChartChalit(
      madhyaDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atChalit, 0),
        blob.columnOffset(atChalit, 0) + atChalit.count * 8,
      ),
      sandhiDeg: Float64List.sublistView(
        blob.bytes,
        blob.columnOffset(atChalit, 1),
        blob.columnOffset(atChalit, 1) + atChalit.count * 8,
      ),
      length: atChalit.count,
    ),
    frameBits: blob.data.getUint32(atZodiac.offset + 0, Endian.little),
    offsetDeg: blob.data.getFloat64(atZodiac.offset + 8, Endian.little),
    ayanamshaKind: blob.data.getUint8(atZodiac.offset + 16),
    ayanamsha: blob.data.getUint16(atZodiac.offset + 24, Endian.little),
    day: Day(
      sunrise: blob.data.getFloat64(atDay.offset + 0, Endian.little),
      sunset: blob.data.getFloat64(atDay.offset + 8, Endian.little),
      nextSunrise: blob.data.getFloat64(atDay.offset + 16, Endian.little),
      vara: blob.data.getUint16(atDay.offset + 24, Endian.little),
      part: blob.data.getUint8(atDay.offset + 32),
      elapsed: blob.data.getFloat64(atDay.offset + 40, Endian.little),
      calendar: blob.data.getUint16(atDay.offset + 48, Endian.little),
      era: blob.data.getUint16(atDay.offset + 56, Endian.little),
      year: blob.data.getInt32(atDay.offset + 64, Endian.little),
      eraYear: blob.data.getInt32(atDay.offset + 72, Endian.little),
      month: blob.data.getUint8(atDay.offset + 80),
      dayOfMonth: blob.data.getUint8(atDay.offset + 88),
      resolution: blob.data.getUint8(atDay.offset + 96),
      computedMonth: blob.data.getUint8(atDay.offset + 104),
      computedDay: blob.data.getUint8(atDay.offset + 112),
      conventionKind: blob.data.getUint8(atDay.offset + 120),
      conventionValue: blob.data.getFloat64(atDay.offset + 128, Endian.little),
    ),
    ghati: blob.data.getUint8(atTiming.offset + 0),
    pala: blob.data.getUint8(atTiming.offset + 8),
    vipala: blob.data.getUint8(atTiming.offset + 16),
    ghatiReckoning: blob.data.getUint8(atTiming.offset + 24),
    horaNumber: blob.data.getUint8(atTiming.offset + 32),
    horaLord: blob.data.getUint16(atTiming.offset + 40, Endian.little),
    horaStart: blob.data.getFloat64(atTiming.offset + 48, Endian.little),
    horaEnd: blob.data.getFloat64(atTiming.offset + 56, Endian.little),
    horaReckoning: blob.data.getUint8(atTiming.offset + 64),
    model: blob.text(atModel),
    steps: blob.text(atSteps),
    provenance: blob.text(atProvenance),
  );
}

