// Generated by `cargo xtask gen ffi` from the Teistro SDK's boundary
// crates; do not edit. ABI version 1, SDK 0.0.0.
//
// The description this file was rendered from ships as idl/api.json.
//
// The generator lays this file out, so `dart format .` leaves it alone
// and `cargo xtask check-ffi` can regenerate it on a machine with no
// Dart toolchain and still compare it byte for byte.
// dart format off

/// The JSON records that cross as text inside a result blob — a result's provenance, a positions result's completion steps — typed, with a decoder from their canonical JSON. Rendered from the `records` of idl/api.json, which schemars reads from serde's own description of the Rust types.
library;

/// A pair from a two-item JSON array, each item by its own decoder.
(A, B) _pair<A, B>(Object? json, A Function(Object?) first, B Function(Object?) second) {
  final items = json! as List<Object?>;
  return (first(items[0]), second(items[1]));
}

/// Everything that reproduces a result.
final class Provenance {
  /// A Provenance with every field named.
  const Provenance({required this.appliedConventions, required this.calculationVersion, required this.calendar, required this.catalogueVersion, required this.confidence, required this.contentHash, required this.deviation, required this.fallbacksUsed, required this.inputHash, required this.moduleVersions, required this.packs, required this.profile, required this.provider, required this.sdkVersion, required this.settingsHash, required this.time, required this.warnings});

  /// A Provenance from its JSON.
  factory Provenance.fromJson(Map<String, Object?> json) => Provenance(
        appliedConventions: [for (final item in json['applied_conventions']! as List<Object?>) Convention.fromJson(item! as Map<String, Object?>)],
        calculationVersion: (json['calculation_version']! as num).toInt(),
        calendar: json['calendar'] == null ? null : CalendarResolution.fromJson(json['calendar']! as Map<String, Object?>),
        catalogueVersion: (json['catalogue_version']! as num).toInt(),
        confidence: Confidence.fromJson(json['confidence']),
        contentHash: json['content_hash']! as String,
        deviation: json['deviation'] == null ? null : Deviation.fromJson(json['deviation']! as Map<String, Object?>),
        fallbacksUsed: [for (final item in json['fallbacks_used']! as List<Object?>) Fallback.fromJson(item! as Map<String, Object?>)],
        inputHash: json['input_hash']! as String,
        moduleVersions: [for (final item in json['module_versions']! as List<Object?>) _pair(item, (a) => a! as String, (b) => Version.fromJson(b! as Map<String, Object?>))],
        packs: [for (final item in json['packs']! as List<Object?>) PackStamp.fromJson(item! as Map<String, Object?>)],
        profile: json['profile']! as String,
        provider: ProviderStamp.fromJson(json['provider']! as Map<String, Object?>),
        sdkVersion: Version.fromJson(json['sdk_version']! as Map<String, Object?>),
        settingsHash: json['settings_hash']! as String,
        time: TimeStamp.fromJson(json['time']! as Map<String, Object?>),
        warnings: [for (final item in json['warnings']! as List<Object?>) ProvenanceWarning.fromJson(item! as Map<String, Object?>)],
      );

  /// The conventions applied.
  final List<Convention> appliedConventions;

  /// The calculation version (ADR-0020).
  final int calculationVersion;

  /// The calendar resolution, when a calendar took part.
  final CalendarResolution? calendar;

  /// The catalogue version.
  final int catalogueVersion;

  /// The confidence.
  final Confidence confidence;

  /// The hash of the canonical serialisation of the value.
  final String contentHash;

  /// A classical model's deviation, when one answered.
  final Deviation? deviation;

  /// The fallbacks used.
  final List<Fallback> fallbacksUsed;

  /// The hash of the input.
  final String inputHash;

  /// The versions of the modules that took part.
  final List<(String, Version)> moduleVersions;

  /// The packs.
  final List<PackStamp> packs;

  /// The profile id.
  final String profile;

  /// The provider.
  final ProviderStamp provider;

  /// The SDK's version.
  final Version sdkVersion;

  /// The hash of the resolved settings.
  final String settingsHash;

  /// What the time layer applied.
  final TimeStamp time;

  /// The warnings.
  final List<ProvenanceWarning> warnings;
}

/// One completion step and who did it.
final class Step {
  /// A Step with every field named.
  const Step({required this.implementation, required this.name});

  /// A Step from its JSON.
  factory Step.fromJson(Map<String, Object?> json) => Step(
        implementation: Implementation.fromJson(json['implementation']),
        name: json['name']! as String,
      );

  /// Who computed it.
  final Implementation implementation;

  /// The step's name.
  final String name;
}

/// A convention the SDK had to choose to terminate.
final class Convention {
  /// A Convention with every field named.
  const Convention({required this.knob, required this.reason, required this.value});

  /// A Convention from its JSON.
  factory Convention.fromJson(Map<String, Object?> json) => Convention(
        knob: json['knob']! as String,
        reason: json['reason']! as String,
        value: json['value']! as String,
      );

  /// The knob.
  final String knob;

  /// Why.
  final String reason;

  /// The value applied.
  final String value;
}

/// How a calendar date was resolved (`docs/03-design/calendar-bikram-sambat.md`).
sealed class CalendarResolution {
  const CalendarResolution();

  /// A CalendarResolution from its JSON, by its `kind`.
  factory CalendarResolution.fromJson(Map<String, Object?> json) => switch (json['kind']) {
        'DEFINED' => CalendarResolutionDefined.fromJson(json),
        'TABULAR' => CalendarResolutionTabular.fromJson(json),
        'COMPUTED' => CalendarResolutionComputed.fromJson(json),
        'DIVERGENT' => CalendarResolutionDivergent.fromJson(json),
        final other => throw FormatException('not a CalendarResolution: kind $other'),
      };

  /// Which variant this is, as the wire's `kind` names it.
  String get kind;
}

/// A mathematical definition; exact by construction.
final class CalendarResolutionDefined extends CalendarResolution {
  /// A CalendarResolutionDefined with every field named.
  const CalendarResolutionDefined();

  /// A CalendarResolutionDefined from its JSON.
  factory CalendarResolutionDefined.fromJson(Map<String, Object?> json) => const CalendarResolutionDefined();

  @override
  String get kind => 'DEFINED';
}

/// From the authority's published table.
final class CalendarResolutionTabular extends CalendarResolution {
  /// A CalendarResolutionTabular with every field named.
  const CalendarResolutionTabular({required this.authority, required this.edition});

  /// A CalendarResolutionTabular from its JSON.
  factory CalendarResolutionTabular.fromJson(Map<String, Object?> json) => CalendarResolutionTabular(
        authority: json['authority']! as String,
        edition: json['edition']! as String,
      );

  /// The authority.
  final String authority;

  /// The table's edition.
  final String edition;

  @override
  String get kind => 'TABULAR';
}

/// Computed outside the table's range.
final class CalendarResolutionComputed extends CalendarResolution {
  /// A CalendarResolutionComputed with every field named.
  const CalendarResolutionComputed({required this.model});

  /// A CalendarResolutionComputed from its JSON.
  factory CalendarResolutionComputed.fromJson(Map<String, Object?> json) => CalendarResolutionComputed(
        model: json['model']! as String,
      );

  /// The rule or model.
  final String model;

  @override
  String get kind => 'COMPUTED';
}

/// Inside the range and the two disagree; the table was followed.
final class CalendarResolutionDivergent extends CalendarResolution {
  /// A CalendarResolutionDivergent with every field named.
  const CalendarResolutionDivergent({required this.computed, required this.model, required this.tabular});

  /// A CalendarResolutionDivergent from its JSON.
  factory CalendarResolutionDivergent.fromJson(Map<String, Object?> json) => CalendarResolutionDivergent(
        computed: MonthDay.fromJson(json['computed']! as Map<String, Object?>),
        model: json['model']! as String,
        tabular: MonthDay.fromJson(json['tabular']! as Map<String, Object?>),
      );

  /// The computed month and day.
  final MonthDay computed;

  /// The rule or model that computed the other answer.
  final String model;

  /// The table's month and day.
  final MonthDay tabular;

  @override
  String get kind => 'DIVERGENT';
}

/// Whether every row that took part is verified (ADR-0018).
enum Confidence {
  /// Every table row used is verified.
  verified('VERIFIED'),
  /// At least one traditional row took part.
  unverified('UNVERIFIED');

  const Confidence(this.key);

  /// The key, as the wire writes it.
  final String key;

  /// The Confidence a key names.
  static Confidence fromJson(Object? json) => values.firstWhere(
        (value) => value.key == json,
        orElse: () => throw FormatException('not a Confidence: $json'),
      );
}

/// A classical model answered rather than the modern one.
final class Deviation {
  /// A Deviation with every field named.
  const Deviation({required this.detail, required this.model});

  /// A Deviation from its JSON.
  factory Deviation.fromJson(Map<String, Object?> json) => Deviation(
        detail: json['detail']! as String,
        model: json['model']! as String,
      );

  /// What it changed.
  final String detail;

  /// The model (`SURYA_SIDDHANTA`).
  final String model;
}

/// A fallback that was used.
final class Fallback {
  /// A Fallback with every field named.
  const Fallback({required this.reason, required this.what});

  /// A Fallback from its JSON.
  factory Fallback.fromJson(Map<String, Object?> json) => Fallback(
        reason: json['reason']! as String,
        what: json['what']! as String,
      );

  /// Why.
  final String reason;

  /// What fell back.
  final String what;
}

/// A semantic version.
final class Version {
  /// A Version with every field named.
  const Version({required this.major, required this.minor, required this.patch});

  /// A Version from its JSON.
  factory Version.fromJson(Map<String, Object?> json) => Version(
        major: (json['major']! as num).toInt(),
        minor: (json['minor']! as num).toInt(),
        patch: (json['patch']! as num).toInt(),
      );

  /// Major.
  final int major;

  /// Minor.
  final int minor;

  /// Patch.
  final int patch;
}

/// A pack that took part.
final class PackStamp {
  /// A PackStamp with every field named.
  const PackStamp({required this.hash, required this.id, required this.version});

  /// A PackStamp from its JSON.
  factory PackStamp.fromJson(Map<String, Object?> json) => PackStamp(
        hash: json['hash']! as String,
        id: json['id']! as String,
        version: json['version']! as String,
      );

  /// Its content hash.
  final String hash;

  /// The pack id.
  final String id;

  /// Its version.
  final String version;
}

/// What the provider was.
final class ProviderStamp {
  /// A ProviderStamp with every field named.
  const ProviderStamp({required this.dataHashes, required this.dataVersion, required this.flagsUsed, required this.frame, required this.name, required this.tier, required this.version});

  /// A ProviderStamp from its JSON.
  factory ProviderStamp.fromJson(Map<String, Object?> json) => ProviderStamp(
        dataHashes: [for (final item in json['data_hashes']! as List<Object?>) _pair(item, (a) => a! as String, (b) => b! as String)],
        dataVersion: json['data_version']! as String,
        flagsUsed: [for (final item in json['flags_used']! as List<Object?>) item! as String],
        frame: json['frame']! as String,
        name: json['name']! as String,
        tier: json['tier'] == null ? null : json['tier']! as String,
        version: json['version']! as String,
      );

  /// The hashes of the data files it read.
  final List<(String, String)> dataHashes;

  /// What identifies its data.
  final String dataVersion;

  /// The flags actually used, as names.
  final List<String> flagsUsed;

  /// The frame it returned, as its key.
  final String frame;

  /// The provider's name.
  final String name;

  /// The tier, when the provider has tiers.
  final String? tier;

  /// Its version.
  final String version;
}

/// What the time layer applied.
final class TimeStamp {
  /// A TimeStamp with every field named.
  const TimeStamp({required this.deltaTModel, required this.deltaTSeconds, required this.leapTable, required this.timeBasisApplied, required this.tzdbVersion, required this.uncertaintySeconds});

  /// A TimeStamp from its JSON.
  factory TimeStamp.fromJson(Map<String, Object?> json) => TimeStamp(
        deltaTModel: json['delta_t_model']! as String,
        deltaTSeconds: (json['delta_t_seconds']! as num).toDouble(),
        leapTable: json['leap_table']! as String,
        timeBasisApplied: json['time_basis_applied'] == null ? null : json['time_basis_applied']! as String,
        tzdbVersion: json['tzdb_version']! as String,
        uncertaintySeconds: json['uncertainty_seconds'] == null ? null : (json['uncertainty_seconds']! as num).toDouble(),
      );

  /// The Delta T model's key.
  final String deltaTModel;

  /// Delta T in seconds at the instant.
  final double deltaTSeconds;

  /// The leap-second table version.
  final String leapTable;

  /// What was applied when tzdb had no rule (`LMT before 1880` and the like).
  final String? timeBasisApplied;

  /// The tzdb version.
  final String tzdbVersion;

  /// Delta T's uncertainty in seconds for deep-time instants.
  final double? uncertaintySeconds;
}

/// A warning: a code, and a message key with slots for localisation.
final class ProvenanceWarning {
  /// A ProvenanceWarning with every field named.
  const ProvenanceWarning({required this.code, required this.key, required this.slots});

  /// A ProvenanceWarning from its JSON.
  factory ProvenanceWarning.fromJson(Map<String, Object?> json) => ProvenanceWarning(
        code: json['code']! as String,
        key: json['key'] == null ? null : json['key']! as String,
        slots: [for (final item in json['slots']! as List<Object?>) _pair(item, (a) => a! as String, (b) => b! as String)],
      );

  /// The stable code (`DEPRECATED_KEY`).
  final String code;

  /// The message key, when there is one.
  final String? key;

  /// The slots.
  final List<(String, String)> slots;
}

/// Who computed a step.
enum Implementation {
  /// The provider's declared override.
  native('NATIVE'),
  /// The SDK's own routine.
  sdk('SDK'),
  /// Nothing to do: the provider returned the requested frame.
  passThrough('PASS_THROUGH');

  const Implementation(this.key);

  /// The key, as the wire writes it.
  final String key;

  /// The Implementation a key names.
  static Implementation fromJson(Object? json) => values.firstWhere(
        (value) => value.key == json,
        orElse: () => throw FormatException('not a Implementation: $json'),
      );
}

/// A month and a day inside a year, for a divergence report.
final class MonthDay {
  /// A MonthDay with every field named.
  const MonthDay({required this.day, required this.month});

  /// A MonthDay from its JSON.
  factory MonthDay.fromJson(Map<String, Object?> json) => MonthDay(
        day: (json['day']! as num).toInt(),
        month: (json['month']! as num).toInt(),
      );

  /// The day, 1-based.
  final int day;

  /// The month, 1-based.
  final int month;
}
