// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

final class _PositionFfi extends ffi.Struct {
  @ffi.Double()
  external double longitudeDeg;
  @ffi.Double()
  external double latitudeDeg;
  @ffi.Double()
  external double speedDegPerDay;
}

/// A tropical position, the provider's answer.
final class Position {
  // ignore: public_member_api_docs
  double longitudeDeg;
  // ignore: public_member_api_docs
  double latitudeDeg;
  // ignore: public_member_api_docs
  double speedDegPerDay;

  // ignore: public_member_api_docs
  Position({required this.longitudeDeg, required this.latitudeDeg, required this.speedDegPerDay});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  Position._fromFfi(_PositionFfi ffi) :
    longitudeDeg = ffi.longitudeDeg,
    latitudeDeg = ffi.latitudeDeg,
    speedDegPerDay = ffi.speedDegPerDay;

  // ignore: unused_element
  _PositionFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_PositionFfi>();
    struct.longitudeDeg = longitudeDeg;
    struct.latitudeDeg = latitudeDeg;
    struct.speedDegPerDay = speedDegPerDay;
    return struct;
  }


  @override
  bool operator ==(Object other) =>
      other is Position &&
      other.longitudeDeg == longitudeDeg &&
      other.latitudeDeg == latitudeDeg &&
      other.speedDegPerDay == speedDegPerDay;

  @override
  int get hashCode => Object.hashAll([
        longitudeDeg,
        latitudeDeg,
        speedDegPerDay,
      ]);
}

// dart format on
