//! The Dart layer: `dart:ffi` declarations that match the C header name
//! for name, a typed surface over them (enums, value classes, the context
//! with a host provider through `NativeCallable`), and the blob decoder as
//! typed-data views. One file, generated from the same description as the
//! Node glue, so the two bindings cannot disagree.

use std::fmt::Write;

use crate::common::{
    DocStyle, binding_name, callback_shape, constructor, destructor, field_doc, is_free_function,
    is_object, is_read_by_host, is_visible, is_written_by_host, line_comment, message_function,
    method_name, methods, pointee_struct, provider_callback, provider_code_function,
    provider_type_name, returned_scalar, returns_status, snake, status_enum,
};
use crate::model::{
    Api, CallbackDef, ColumnDef, EnumDef, FieldDef, FunctionDef, Role, StructDef, TypeRef, camel,
    pascal, strip_prefix,
};

const RESERVED: [&str; 12] = [
    "true", "false", "null", "default", "new", "in", "is", "as", "do", "if", "for", "switch",
];

fn doc(text: &str, indent: &str) -> String {
    line_comment(text, indent, "/// ")
}

/// A Dart identifier for an enum variant: lower camel, and safe when it is
/// a reserved word (`True` becomes `trueValue`).
fn variant(name: &str) -> String {
    let lower = camel(&snake(name));
    if RESERVED.contains(&lower.as_str()) {
        format!("{lower}Value")
    } else {
        lower
    }
}

/// The `dart:ffi` native type of a boundary type.
fn native(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { name } => match name.as_str() {
            "u8" => "ffi.Uint8",
            "u16" => "ffi.Uint16",
            "u32" => "ffi.Uint32",
            "u64" => "ffi.Uint64",
            "i8" => "ffi.Int8",
            "i16" => "ffi.Int16",
            "i32" => "ffi.Int32",
            "i64" => "ffi.Int64",
            "f32" => "ffi.Float",
            "f64" => "ffi.Double",
            "usize" => "ffi.Size",
            "bool" => "ffi.Bool",
            _ => "ffi.IntPtr",
        }
        .to_string(),
        TypeRef::Enum { .. } => String::from("ffi.Int32"),
        TypeRef::Struct { name } | TypeRef::Opaque { name } => name.clone(),
        TypeRef::Callback { name } => format!("ffi.Pointer<ffi.NativeFunction<{name}Native>>"),
        TypeRef::Pointer { to, .. } => format!("ffi.Pointer<{}>", native(to)),
        TypeRef::Void => String::from("ffi.Void"),
        TypeRef::Char => String::from("ffi.Char"),
    }
}

/// The Dart type a native type maps to.
fn dart(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { name } => match name.as_str() {
            "f32" | "f64" => "double",
            "bool" => "bool",
            _ => "int",
        }
        .to_string(),
        TypeRef::Enum { .. } => String::from("int"),
        TypeRef::Void => String::from("void"),
        other => native(other),
    }
}

/// Renders `generated.dart`.
pub(crate) fn render(api: &Api) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// GENERATED by teistro-spike-a-gen from {}. Do not edit; run the generator.\n//\n// ignore_for_file: camel_case_types, non_constant_identifier_names\n// ignore_for_file: constant_identifier_names, unused_field\n\nimport 'dart:ffi' as ffi;\nimport 'dart:typed_data';\n\nimport 'package:ffi/ffi.dart' as pkg_ffi;\n\n/// The ABI version this file was generated for; the library must agree.\nconst int generatedAbiVersion = {};\n",
        api.source, api.abi_version
    );
    for e in &api.enums {
        render_enum(&mut out, api, e);
    }
    for o in &api.opaques {
        let _ = writeln!(
            out,
            "{}final class {} extends ffi.Opaque {{}}\n",
            doc(&o.doc, ""),
            o.name
        );
    }
    for c in &api.callbacks {
        render_callback_typedefs(&mut out, c);
    }
    for s in &api.structs {
        render_struct(&mut out, s);
    }
    render_library(&mut out, api);
    render_exception(&mut out, api);
    for s in api.structs.iter().filter(|s| is_object(s)) {
        render_value_class(&mut out, api, s);
    }
    if let Some((_, _, c)) = provider_callback(api) {
        render_provider_typedef(&mut out, api, c);
    }
    for o in &api.opaques {
        render_context(&mut out, api, &o.name);
    }
    for f in api.functions.iter().filter(|f| is_free_function(f)) {
        render_free_function(&mut out, api, f);
    }
    render_decoder(&mut out, api);
    out
}

fn render_enum(out: &mut String, api: &Api, e: &EnumDef) {
    let name = binding_name(api, &e.name);
    let _ = writeln!(out, "{}enum {name} {{", doc(&e.doc, ""));
    let last = e.values.len().saturating_sub(1);
    for (i, v) in e.values.iter().enumerate() {
        let end = if i == last { ";" } else { "," };
        let _ = writeln!(
            out,
            "{}  {}({}){end}",
            doc(&v.doc, "  "),
            variant(&v.name),
            v.value
        );
    }
    let _ = writeln!(
        out,
        "\n  const {name}(this.value);\n\n  /// The C discriminant.\n  final int value;\n\n  /// The variant with a given discriminant.\n  static {name} fromValue(int value) => switch (value) {{"
    );
    for v in &e.values {
        let _ = writeln!(out, "        {} => {name}.{},", v.value, variant(&v.name));
    }
    let _ = writeln!(
        out,
        "        _ => throw ArgumentError.value(value, 'value', 'unknown {name}'),\n      }};\n}}\n"
    );
}

fn render_callback_typedefs(out: &mut String, c: &CallbackDef) {
    let natives: Vec<String> = c.params.iter().map(|p| native(&p.ty)).collect();
    let darts: Vec<String> = c.params.iter().map(|p| dart(&p.ty)).collect();
    let _ = writeln!(
        out,
        "{}typedef {}Native = {} Function({});\ntypedef {}Dart = {} Function({});\n",
        doc(&c.doc, ""),
        c.name,
        native(&c.returns),
        natives.join(", "),
        c.name,
        dart(&c.returns),
        darts.join(", ")
    );
}

fn render_struct(out: &mut String, s: &StructDef) {
    let _ = writeln!(
        out,
        "{}final class {} extends ffi.Struct {{",
        doc(&s.doc, ""),
        s.name
    );
    for f in &s.fields {
        let text = doc(&field_doc(f, DocStyle::Prose), "  ");
        match &f.ty {
            TypeRef::Scalar { .. } => {
                let _ = writeln!(
                    out,
                    "{text}  @{}()\n  external {} {};\n",
                    native(&f.ty),
                    dart(&f.ty),
                    f.name
                );
            }
            other => {
                let _ = writeln!(out, "{text}  external {} {};\n", native(other), f.name);
            }
        }
    }
    let _ = writeln!(out, "}}\n");
}

fn typedef_names(f: &FunctionDef) -> (String, String) {
    let base = pascal(&f.name);
    (format!("_Native{base}"), format!("_Dart{base}"))
}

fn render_library(out: &mut String, api: &Api) {
    for f in &api.functions {
        let (native_name, dart_name) = typedef_names(f);
        let natives: Vec<String> = f.params.iter().map(|p| native(&p.ty)).collect();
        let darts: Vec<String> = f.params.iter().map(|p| dart(&p.ty)).collect();
        let returns_native = f
            .returns
            .as_ref()
            .map_or_else(|| String::from("ffi.Void"), native);
        let returns_dart = f
            .returns
            .as_ref()
            .map_or_else(|| String::from("void"), dart);
        let _ = writeln!(
            out,
            "typedef {native_name} = {returns_native} Function({});\ntypedef {dart_name} = {returns_dart} Function({});",
            natives.join(", "),
            darts.join(", ")
        );
    }
    let _ = writeln!(
        out,
        "\n/// The C surface, every entry point looked up once.\nfinal class TspLibrary {{\n  TspLibrary(ffi.DynamicLibrary library)"
    );
    let last = api.functions.len().saturating_sub(1);
    for (i, f) in api.functions.iter().enumerate() {
        let (native_name, dart_name) = typedef_names(f);
        let end = if i == last { ";" } else { "," };
        let lead = if i == 0 { ":" } else { " " };
        let _ = writeln!(
            out,
            "      {lead} {} = library.lookupFunction<{native_name}, {dart_name}>('{}'){end}",
            f.name, f.name
        );
    }
    let _ = writeln!(out);
    for f in &api.functions {
        let (_, dart_name) = typedef_names(f);
        let _ = writeln!(
            out,
            "{}  final {dart_name} {};\n",
            doc(&f.doc, "  "),
            f.name
        );
    }
    let _ = writeln!(out, "}}\n");
}

fn render_exception(out: &mut String, api: &Api) {
    let Some(status) = status_enum(api) else {
        return;
    };
    let status_name = binding_name(api, &status.name);
    let message = message_function(api).map_or_else(
        || String::from("'failure'"),
        |f| format!("lib.{}(status).cast<pkg_ffi.Utf8>().toDartString()", f.name),
    );
    let _ = writeln!(
        out,
        "/// A failed call: the status the library returned, its message, and the\n/// provider's own code when the provider failed.\nfinal class TeistroException implements Exception {{\n  const TeistroException(this.status, this.message, {{this.providerCode = 0}});\n\n  /// What to branch on.\n  final {status_name} status;\n\n  /// The library's own sentence.\n  final String message;\n\n  /// The provider's code, `0` unless the provider failed.\n  final int providerCode;\n\n  /// The stable numeric code of the status.\n  int get code => status.value;\n\n  @override\n  String toString() => 'TeistroException(${{status.value}}): $message'\n      '${{providerCode != 0 ? ' (provider code $providerCode)' : ''}}';\n}}\n\nvoid _check(TspLibrary lib, int status, {{int providerCode = 0}}) {{\n  if (status == 0) return;\n  throw TeistroException({status_name}.fromValue(status), {message}, providerCode: providerCode);\n}}\n"
    );
}

fn dart_field_type(api: &Api, f: &FieldDef) -> String {
    f.meta
        .enum_name
        .as_ref()
        .map_or_else(|| dart(&f.ty), |e| binding_name(api, e))
}

fn render_value_class(out: &mut String, api: &Api, s: &StructDef) {
    let name = binding_name(api, &s.name);
    let visible: Vec<&FieldDef> = s.fields.iter().filter(|f| is_visible(f)).collect();
    let params: Vec<String> = visible
        .iter()
        .map(|f| format!("required this.{}", camel(&f.name)))
        .collect();
    let _ = writeln!(
        out,
        "{}final class {name} {{\n  const {name}({{{}}});\n",
        doc(&s.doc, ""),
        params.join(", ")
    );
    for f in &visible {
        let _ = writeln!(
            out,
            "{}  final {} {};\n",
            doc(&field_doc(f, DocStyle::Prose), "  "),
            dart_field_type(api, f),
            camel(&f.name)
        );
    }
    if is_written_by_host(api, s) {
        let _ = writeln!(out, "  void _write(ffi.Pointer<{}> raw) {{", s.name);
        for f in &s.fields {
            let value = if f.meta.role.as_deref() == Some("struct_size") {
                format!("ffi.sizeOf<{}>()", s.name)
            } else if !is_visible(f) {
                String::from("0")
            } else if f.meta.enum_name.is_some() {
                format!("{}.value", camel(&f.name))
            } else {
                camel(&f.name)
            };
            let _ = writeln!(out, "    raw.ref.{} = {value};", f.name);
        }
        let _ = writeln!(out, "  }}\n");
    }
    if is_read_by_host(api, s) {
        let _ = writeln!(
            out,
            "  static {name} _read(ffi.Pointer<{}> raw) => {name}(",
            s.name
        );
        for f in &visible {
            let value = f.meta.enum_name.as_ref().map_or_else(
                || format!("raw.ref.{}", f.name),
                |e| format!("{}.fromValue(raw.ref.{})", binding_name(api, e), f.name),
            );
            let _ = writeln!(out, "        {}: {value},", camel(&f.name));
        }
        let _ = writeln!(out, "      );");
    }
    let _ = writeln!(out, "}}\n");
}

fn render_provider_typedef(out: &mut String, api: &Api, c: &CallbackDef) {
    let Some(shape) = callback_shape(c) else {
        return;
    };
    let args: Vec<String> = shape
        .args
        .iter()
        .map(|p| format!("{} {}", dart(&p.ty), camel(&p.name)))
        .collect();
    let _ = writeln!(
        out,
        "{}typedef {} = {} Function({});\n",
        doc(&c.doc, ""),
        provider_type_name(api, c),
        binding_name(api, shape.out),
        args.join(", ")
    );
}

fn render_context(out: &mut String, api: &Api, opaque: &str) {
    let name = binding_name(api, opaque);
    let provider = provider_callback(api);
    let opaque_doc = api
        .opaques
        .iter()
        .find(|o| o.name == opaque)
        .map(|o| o.doc.clone())
        .unwrap_or_default();
    let _ = writeln!(out, "{}final class {name} {{", doc(&opaque_doc, ""));
    if let Some(ctor) = constructor(api) {
        render_dart_constructor(out, api, ctor, &name, opaque);
    }
    let _ = writeln!(
        out,
        "  final TspLibrary _lib;\n  late final ffi.Pointer<{opaque}> _handle;"
    );
    if let Some((_, _, c)) = provider {
        if let Some(shape) = callback_shape(c) {
            let params: Vec<String> = c
                .params
                .iter()
                .map(|p| format!("{} {}", dart(&p.ty), camel(&p.name)))
                .collect();
            let args: Vec<String> = shape.args.iter().map(|p| camel(&p.name)).collect();
            let _ = writeln!(
                out,
                "  ffi.NativeCallable<{0}Native>? _callable;\n  int _token = 0;\n\n  static int _nextToken = 1;\n  static final Map<int, {1}> _providers = {{}};\n\n  static int _trampoline({2}) {{\n    final provider = _providers[{3}.address];\n    if (provider == null) return -1001;\n    provider({4})._write({5});\n    return 0;\n  }}\n",
                c.name,
                provider_type_name(api, c),
                params.join(", "),
                camel(
                    c.params
                        .iter()
                        .find(|p| p.role == Role::UserData)
                        .map_or("userData", |p| p.name.as_str())
                ),
                args.join(", "),
                camel(&shape.out_param.name)
            );
        }
    }
    for m in methods(api) {
        render_dart_method(out, api, m, opaque, provider.is_some());
    }
    if let Some(free) = destructor(api) {
        let _ = writeln!(
            out,
            "  /// Frees the native context; the object must not be used afterwards.\n  void dispose() {{\n    _lib.{}(_handle);\n    _callable?.close();\n    _providers.remove(_token);\n  }}",
            free.name
        );
    }
    let _ = writeln!(out, "}}\n");
}

fn render_dart_constructor(
    out: &mut String,
    api: &Api,
    ctor: &FunctionDef,
    name: &str,
    opaque: &str,
) {
    let mut params = Vec::new();
    let mut body = String::new();
    let mut args = Vec::new();
    let mut frees = Vec::new();
    for p in &ctor.params {
        match p.role {
            Role::StructIn => {
                let Some(s) = pointee_struct(p) else { continue };
                params.push(format!("{} {}", binding_name(api, s), p.name));
                let _ = writeln!(
                    body,
                    "    final raw_{0} = pkg_ffi.calloc<{1}>();\n    {0}._write(raw_{0});",
                    p.name, s
                );
                args.push(format!("raw_{}", p.name));
                frees.push(format!("raw_{}", p.name));
            }
            Role::VtableIn => {
                let Some((vtable, field, c)) = provider_callback(api) else {
                    continue;
                };
                params.push(format!("{{{}? provider}}", provider_type_name(api, c)));
                let _ = writeln!(
                    body,
                    "    ffi.Pointer<{0}> vtable = ffi.nullptr;\n    ffi.Pointer<ffi.Void> userData = ffi.nullptr;\n    if (provider != null) {{\n      _token = _nextToken++;\n      _providers[_token] = provider;\n      _callable = ffi.NativeCallable<{1}Native>.isolateLocal(_trampoline, exceptionalReturn: -1002);\n      vtable = pkg_ffi.calloc<{0}>();\n      vtable.ref.struct_size = ffi.sizeOf<{0}>();\n      vtable.ref.{2} = _callable!.nativeFunction;\n      userData = ffi.Pointer<ffi.Void>.fromAddress(_token);\n    }}",
                    vtable.name, c.name, field.name
                );
                args.push(String::from("vtable"));
            }
            Role::UserData => args.push(String::from("userData")),
            Role::HandleOut => {
                let _ = writeln!(
                    body,
                    "    final out = pkg_ffi.calloc<ffi.Pointer<{opaque}>>();"
                );
                args.push(String::from("out"));
            }
            _ => {}
        }
    }
    let free_lines: Vec<String> = frees
        .iter()
        .map(|f| format!("    pkg_ffi.calloc.free({f});"))
        .collect();
    let _ = writeln!(
        out,
        "{}  {name}(TspLibrary lib, {}) : _lib = lib {{\n{body}    final status = lib.{}({});\n    _handle = out.value;\n    pkg_ffi.calloc.free(out);\n{}\n    if (vtable != ffi.nullptr) pkg_ffi.calloc.free(vtable);\n    _check(lib, status);\n  }}\n",
        doc(&ctor.doc, "  "),
        params.join(", "),
        ctor.name,
        args.join(", "),
        free_lines.join("\n")
    );
}

fn render_dart_method(
    out: &mut String,
    api: &Api,
    m: &FunctionDef,
    opaque: &str,
    has_provider: bool,
) {
    let method = camel(&method_name(api, opaque, m));
    let mut params = Vec::new();
    let mut args = Vec::new();
    let mut body = String::new();
    let mut returns = String::from("void");
    let mut finish = String::new();
    let provider_code = match provider_code_function(api) {
        Some(f) if has_provider => format!("_lib.{}(_handle)", f.name),
        _ => String::from("0"),
    };
    for p in &m.params {
        match p.role {
            Role::Handle => args.push(String::from("_handle")),
            Role::Value => {
                params.push(format!("{} {}", dart(&p.ty), camel(&p.name)));
                args.push(camel(&p.name));
            }
            Role::StructOut => {
                let Some(s) = pointee_struct(p) else { continue };
                let _ = writeln!(
                    body,
                    "    final raw = pkg_ffi.calloc<{s}>();\n    raw.ref.struct_size = ffi.sizeOf<{s}>();"
                );
                args.push(String::from("raw"));
                returns = binding_name(api, s);
                finish = format!(
                    "    if (status != 0) {{\n      pkg_ffi.calloc.free(raw);\n      _check(_lib, status, providerCode: {provider_code});\n    }}\n    final value = {returns}._read(raw);\n    pkg_ffi.calloc.free(raw);\n    return value;"
                );
            }
            Role::BlobOut => {
                let Some(s) = pointee_struct(p) else { continue };
                let free = api
                    .functions
                    .iter()
                    .find(|f| f.params.iter().any(|q| q.role == Role::BlobInOut))
                    .map(|f| f.name.clone())
                    .unwrap_or_default();
                let _ = writeln!(body, "    final blob = pkg_ffi.calloc<{s}>();");
                args.push(String::from("blob"));
                returns = String::from("Uint8List");
                finish = format!(
                    "    if (status != 0) {{\n      pkg_ffi.calloc.free(blob);\n      _check(_lib, status, providerCode: {provider_code});\n    }}\n    final bytes = Uint8List.fromList(blob.ref.data.asTypedList(blob.ref.len));\n    _lib.{free}(blob);\n    pkg_ffi.calloc.free(blob);\n    return bytes;"
                );
            }
            _ => {}
        }
    }
    let call = if returns_status(m) {
        if finish.is_empty() {
            finish = format!("    _check(_lib, status, providerCode: {provider_code});");
        }
        format!("    final status = _lib.{}({});", m.name, args.join(", "))
    } else {
        if let Some(scalar) = returned_scalar(m) {
            returns = dart(&TypeRef::Scalar {
                name: scalar.to_string(),
            });
        }
        format!("    return _lib.{}({});", m.name, args.join(", "))
    };
    let _ = writeln!(
        out,
        "{}  {returns} {method}({}) {{\n{body}{call}\n{finish}\n  }}\n",
        doc(&m.doc, "  "),
        params.join(", ")
    );
}

fn render_free_function(out: &mut String, api: &Api, f: &FunctionDef) {
    let name = camel(&strip_prefix(&f.name, &api.prefix));
    let mut params = vec![String::from("TspLibrary lib")];
    let mut args = Vec::new();
    let mut body = String::new();
    let mut returns = String::from("void");
    let mut finish = String::new();
    for p in &f.params {
        match p.role {
            Role::Value => {
                if let TypeRef::Enum { name: e } = &p.ty {
                    params.push(format!("{} {}", binding_name(api, e), camel(&p.name)));
                    args.push(format!("{}.value", camel(&p.name)));
                } else {
                    params.push(format!("{} {}", dart(&p.ty), camel(&p.name)));
                    args.push(camel(&p.name));
                }
            }
            Role::StructOut => {
                let Some(s) = pointee_struct(p) else { continue };
                let _ = writeln!(
                    body,
                    "  final raw = pkg_ffi.calloc<{s}>();\n  raw.ref.struct_size = ffi.sizeOf<{s}>();"
                );
                args.push(String::from("raw"));
                returns = binding_name(api, s);
                finish = format!(
                    "  if (status != 0) {{\n    pkg_ffi.calloc.free(raw);\n    _check(lib, status);\n  }}\n  final value = {returns}._read(raw);\n  pkg_ffi.calloc.free(raw);\n  return value;"
                );
            }
            _ => {}
        }
    }
    let call = if returns_status(f) {
        if finish.is_empty() {
            finish = String::from("  _check(lib, status);");
        }
        format!("  final status = lib.{}({});", f.name, args.join(", "))
    } else if message_function(api).is_some_and(|m| m.name == f.name) {
        returns = String::from("String");
        format!(
            "  return lib.{}({}).cast<pkg_ffi.Utf8>().toDartString();",
            f.name,
            args.join(", ")
        )
    } else {
        if let Some(scalar) = returned_scalar(f) {
            returns = dart(&TypeRef::Scalar {
                name: scalar.to_string(),
            });
        }
        format!("  return lib.{}({});", f.name, args.join(", "))
    };
    let _ = writeln!(
        out,
        "{}{returns} {name}({}) {{\n{body}{call}\n{finish}\n}}\n",
        doc(&f.doc, ""),
        params.join(", ")
    );
}

fn typed_list(c: &ColumnDef) -> &'static str {
    match c.ty.as_str() {
        "u8" => "Uint8List",
        "i8" => "Int8List",
        "u16" => "Uint16List",
        "i16" => "Int16List",
        "u32" => "Uint32List",
        "i32" => "Int32List",
        "i64" => "Int64List",
        "u64" => "Uint64List",
        "f32" => "Float32List",
        _ => "Float64List",
    }
}

fn byte_data_getter(ty: &str) -> &'static str {
    match ty {
        "f64" => "getFloat64",
        "f32" => "getFloat32",
        "i32" => "getInt32",
        "i64" => "getInt64",
        "u8" => "getUint8",
        _ => "getUint32",
    }
}

fn render_decoder(out: &mut String, api: &Api) {
    for s in api.blob.sections.iter().filter(|s| s.kind == "columns") {
        let class = format!("{}Columns", pascal(&s.name));
        let _ = writeln!(
            out,
            "/// The `{}` section as typed-data views over the blob's bytes.\nfinal class {class} {{",
            s.name
        );
        let params: Vec<String> = s
            .fields
            .iter()
            .map(|f| format!("required this.{}", camel(&f.name)))
            .collect();
        let _ = writeln!(
            out,
            "  const {class}({{{}, required this.length}});\n",
            params.join(", ")
        );
        for f in &s.fields {
            let _ = writeln!(out, "  final {} {};", typed_list(f), camel(&f.name));
        }
        let _ = writeln!(out, "  final int length;\n}}\n");
    }
    let _ = writeln!(
        out,
        "/// A decoded chart blob; the columns share the blob's bytes.\nfinal class DecodedChart {{"
    );
    let mut ctor_params = Vec::new();
    let mut fields = Vec::new();
    for s in &api.blob.sections {
        if s.kind == "fixed" {
            for f in s.fields.iter().filter(|f| f.name != "reserved") {
                ctor_params.push(format!("required this.{}", camel(&f.name)));
                fields.push(format!(
                    "  final {} {};",
                    dart(&TypeRef::Scalar { name: f.ty.clone() }),
                    camel(&f.name)
                ));
            }
        } else {
            ctor_params.push(format!("required this.{}", camel(&s.name)));
            fields.push(format!(
                "  final {}Columns {};",
                pascal(&s.name),
                camel(&s.name)
            ));
        }
    }
    let _ = writeln!(
        out,
        "  const DecodedChart({{{}}});\n\n{}\n}}\n",
        ctor_params.join(", "),
        fields.join("\n")
    );
    let _ = writeln!(
        out,
        "const int _blobMagic = {};\nconst int _blobVersion = {};\n\n/// Decodes a chart blob. The typed lists are views, not copies, so the\n/// bytes must outlive the result.\nDecodedChart decodeChart(Uint8List bytes) {{\n  final data = ByteData.sublistView(bytes);\n  if (data.getUint32(0, Endian.little) != _blobMagic) {{\n    throw const FormatException('not a TSPB blob');\n  }}\n  final version = data.getUint32(4, Endian.little);\n  if (version != _blobVersion) {{\n    throw FormatException('blob version $version, expected $_blobVersion');\n  }}\n  final sectionCount = data.getUint32(8, Endian.little);\n  final offsets = <int, int>{{}};\n  final counts = <int, int>{{}};\n  for (var i = 0; i < sectionCount; i++) {{\n    final at = 32 + i * 16;\n    final id = data.getUint32(at, Endian.little);\n    offsets[id] = data.getUint32(at + 4, Endian.little);\n    counts[id] = data.getUint32(at + 12, Endian.little);\n  }}\n  int offsetOf(int id) => offsets[id] ?? (throw FormatException('section $id is missing'));\n  final base = bytes.offsetInBytes;",
        api.blob.magic, api.blob.version
    );
    let mut ctor_args = Vec::new();
    for s in &api.blob.sections {
        if s.kind == "fixed" {
            let mut at = 0usize;
            let _ = writeln!(out, "  final s{} = offsetOf({});", s.id, s.id);
            for f in &s.fields {
                if f.name != "reserved" {
                    ctor_args.push(format!(
                        "    {}: data.{}(s{} + {at}, Endian.little),",
                        camel(&f.name),
                        byte_data_getter(&f.ty),
                        s.id
                    ));
                }
                at += f.width();
            }
        } else {
            let _ = writeln!(
                out,
                "  final s{0} = offsetOf({0});\n  final n{0} = counts[{0}] ?? 0;",
                s.id
            );
            let mut columns = Vec::new();
            for (i, f) in s.fields.iter().enumerate() {
                columns.push(format!(
                    "      {}: {}.view(bytes.buffer, base + s{} + data.getUint32(s{} + {}, Endian.little), n{}),",
                    camel(&f.name),
                    typed_list(f),
                    s.id,
                    s.id,
                    i * 4,
                    s.id
                ));
            }
            ctor_args.push(format!(
                "    {}: {}Columns(\n{}\n      length: n{},\n    ),",
                camel(&s.name),
                pascal(&s.name),
                columns.join("\n"),
                s.id
            ));
        }
    }
    let _ = writeln!(
        out,
        "  return DecodedChart(\n{}\n  );\n}}\n",
        ctor_args.join("\n")
    );
    if let Some(dasha) = api
        .blob
        .sections
        .iter()
        .find(|s| s.fields.iter().any(|f| f.name == "parent"))
    {
        let name = camel(&dasha.name);
        let _ = writeln!(
            out,
            "/// One period with its sub-periods, built from the rows.\nfinal class DashaNode {{\n  DashaNode({{required this.lord, required this.level, required this.startJd, required this.endJd}});\n\n  final int lord;\n  final int level;\n  final double startJd;\n  final double endJd;\n  final List<DashaNode> children = [];\n}}\n\n/// Builds the nested tree eagerly from the parent links.\nList<DashaNode> {name}Tree(DecodedChart chart) {{\n  final rows = chart.{name};\n  final nodes = List<DashaNode?>.filled(rows.length, null);\n  final roots = <DashaNode>[];\n  for (var i = 0; i < rows.length; i++) {{\n    final node = DashaNode(lord: rows.lord[i], level: rows.level[i], startJd: rows.startJd[i], endJd: rows.endJd[i]);\n    nodes[i] = node;\n    final parent = rows.parent[i];\n    if (parent < 0) {{\n      roots.add(node);\n    }} else {{\n      nodes[parent]!.children.add(node);\n    }}\n  }}\n  return roots;\n}}"
        );
    }
}
