//! The Node glue: a napi-rs module generated from the description. Every
//! decision is driven by parameter roles, never by function names, so a new
//! entry point in the ABI crate reaches JavaScript by re-running the
//! generator.

use std::fmt::Write;

use crate::common::{
    DocStyle, binding_name, callback_shape, constructor, destructor, field_doc, is_free_function,
    is_object, is_read_by_host, is_visible, is_written_by_host, line_comment, message_function,
    method_name, methods, pointee_opaque, pointee_struct, provider_callback,
    provider_code_function, returned_scalar, returns_status, snake, status_enum,
};
use crate::model::{
    Api, CallbackDef, EnumDef, FunctionDef, Role, StructDef, TypeRef, strip_prefix,
};

/// Renders `generated.rs` for the napi crate.
pub(crate) fn render(api: &Api) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! GENERATED by teistro-spike-a-gen from {}. Do not edit; run the generator.\n#![allow(\n    unsafe_code,\n    missing_docs,\n    missing_debug_implementations,\n    unreachable_pub,\n    dead_code,\n    clippy::all,\n    clippy::pedantic,\n    reason = \"generated glue; the contract is the API description\"\n)]\n\nuse core::cell::Cell;\nuse core::ffi::{{CStr, c_void}};\nuse core::ptr;\n\nuse napi::bindgen_prelude::*;\nuse napi_derive::napi;\nuse teistro_spike_a_ffi as ffi;\n",
        api.source
    );
    for e in &api.enums {
        render_enum(&mut out, api, e);
    }
    for s in api.structs.iter().filter(|s| is_object(s)) {
        render_object(&mut out, api, s);
    }
    if let Some(status) = status_enum(api) {
        render_status(&mut out, api, status);
    }
    if let Some((_, _, callback)) = provider_callback(api) {
        render_trampoline(&mut out, api, callback);
    }
    for o in &api.opaques {
        render_class(&mut out, api, &o.name);
    }
    for f in api.functions.iter().filter(|f| is_free_function(f)) {
        render_free_function(&mut out, api, f);
    }
    out
}

fn doc(text: &str, indent: &str) -> String {
    line_comment(text, indent, "/// ")
}

fn rust_scalar(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { name } => name.clone(),
        _ => String::from("f64"),
    }
}

fn rust_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Scalar { name } => name.clone(),
        TypeRef::Enum { name }
        | TypeRef::Struct { name }
        | TypeRef::Opaque { name }
        | TypeRef::Callback { name } => {
            format!("ffi::{name}")
        }
        TypeRef::Pointer { to, mutable } => {
            let inner = rust_type(to);
            if *mutable {
                format!("*mut {inner}")
            } else {
                format!("*const {inner}")
            }
        }
        TypeRef::Void => String::from("c_void"),
        TypeRef::Char => String::from("core::ffi::c_char"),
    }
}

/// A call into the ABI crate, wrapped in `unsafe` only when the entry point
/// carries a Safety contract.
fn call(f: &FunctionDef, args: &[String]) -> String {
    let inner = format!("ffi::{}({})", f.name, args.join(", "));
    if f.safety.is_some() {
        format!("unsafe {{ {inner} }}")
    } else {
        inner
    }
}

fn trampoline_name(c: &CallbackDef) -> String {
    format!("{}_trampoline", snake(&c.name))
}

fn render_enum(out: &mut String, api: &Api, e: &EnumDef) {
    let name = binding_name(api, &e.name);
    let _ = writeln!(
        out,
        "{}#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n#[napi(string_enum = \"kebab-case\")]\npub enum {name} {{",
        doc(&e.doc, "")
    );
    for v in &e.values {
        let _ = writeln!(out, "{}    {},", doc(&v.doc, "    "), v.name);
    }
    let _ = writeln!(
        out,
        "}}\n\nimpl {name} {{\n    pub fn to_ffi(self) -> {} {{\n        match self {{",
        e.repr
    );
    for v in &e.values {
        let _ = writeln!(out, "            {name}::{} => {},", v.name, v.value);
    }
    let _ = writeln!(
        out,
        "        }}\n    }}\n\n    pub fn from_ffi(value: {}) -> Option<Self> {{\n        match value {{",
        e.repr
    );
    for v in &e.values {
        let _ = writeln!(out, "            {} => Some({name}::{}),", v.value, v.name);
    }
    let _ = writeln!(
        out,
        "            _ => None,\n        }}\n    }}\n\n    pub fn to_ffi_enum(self) -> ffi::{} {{\n        match self {{",
        e.name
    );
    for v in &e.values {
        let _ = writeln!(
            out,
            "            {name}::{} => ffi::{}::{},",
            v.name, e.name, v.name
        );
    }
    let _ = writeln!(out, "        }}\n    }}\n}}\n");
}

fn render_object(out: &mut String, api: &Api, s: &StructDef) {
    let name = binding_name(api, &s.name);
    let _ = writeln!(
        out,
        "{}#[napi(object)]\n#[derive(Clone, Debug)]\npub struct {name} {{",
        doc(&s.doc, "")
    );
    for f in s.fields.iter().filter(|f| is_visible(f)) {
        let ty = f
            .meta
            .enum_name
            .as_ref()
            .map_or_else(|| rust_scalar(&f.ty), |e| binding_name(api, e));
        let _ = writeln!(
            out,
            "{}    pub {}: {ty},",
            doc(&field_doc(f, DocStyle::Prose), "    "),
            f.name
        );
    }
    let _ = writeln!(out, "}}\n");
    let written = is_written_by_host(api, s);
    let read = is_read_by_host(api, s);
    if !written && !read {
        return;
    }
    let _ = writeln!(out, "impl {name} {{");
    if written {
        let _ = writeln!(
            out,
            "    pub fn to_ffi(&self) -> ffi::{0} {{\n        ffi::{0} {{",
            s.name
        );
        for f in &s.fields {
            let value = if f.meta.role.as_deref() == Some("struct_size") {
                format!("core::mem::size_of::<ffi::{}>() as u32", s.name)
            } else if !is_visible(f) {
                String::from("0")
            } else if f.meta.enum_name.is_some() {
                format!("self.{}.to_ffi()", f.name)
            } else {
                format!("self.{}", f.name)
            };
            let _ = writeln!(out, "            {}: {value},", f.name);
        }
        let _ = writeln!(out, "        }}\n    }}\n");
    }
    if read {
        let _ = writeln!(
            out,
            "    pub fn from_ffi(raw: &ffi::{}) -> Result<Self> {{\n        Ok({name} {{",
            s.name
        );
        for f in s.fields.iter().filter(|f| is_visible(f)) {
            let value = f.meta.enum_name.as_ref().map_or_else(
                || format!("raw.{}", f.name),
                |e| {
                    format!(
                        "{}::from_ffi(raw.{}).ok_or_else(|| Error::from_reason(\"unknown {} value\"))?",
                        binding_name(api, e),
                        f.name,
                        f.name
                    )
                },
            );
            let _ = writeln!(out, "            {}: {value},", f.name);
        }
        let _ = writeln!(out, "        }})\n    }}");
    }
    let _ = writeln!(out, "}}\n");
}

fn render_status(out: &mut String, api: &Api, status: &EnumDef) {
    let message = message_function(api).map_or_else(
        || String::from("        let message = String::from(\"failure\");"),
        |f| {
            format!(
                "        // SAFETY: the library returns a static NUL-terminated string.\n        let message = unsafe {{ CStr::from_ptr(ffi::{}(status)) }}.to_string_lossy().into_owned();",
                f.name
            )
        },
    );
    let _ = writeln!(
        out,
        "/// Turns a non-`Ok` status into a JavaScript error whose message ends\n/// with the stable code, `(code -4)`, and the provider's own code when\n/// there is one.\nfn status_error(status: ffi::{0}, provider_code: i32) -> Error {{\n{message}\n        let code = status as i32;\n        let detail = if provider_code != 0 {{ format!(\"; provider code {{provider_code}}\") }} else {{ String::new() }};\n        Error::from_reason(format!(\"{{message}} (code {{code}}){{detail}}\"))\n}}\n\nfn check(status: ffi::{0}, provider_code: i32) -> Result<()> {{\n    if status == ffi::{0}::Ok {{ Ok(()) }} else {{ Err(status_error(status, provider_code)) }}\n}}\n",
        status.name
    );
}

/// The JavaScript side of a callback: a `Function` reference held in a slot
/// the C `user_data` points at, called on the thread that entered the
/// batch call.
fn render_trampoline(out: &mut String, api: &Api, c: &CallbackDef) {
    let Some(shape) = callback_shape(c) else {
        return;
    };
    let arg_types: Vec<String> = shape.args.iter().map(|p| rust_scalar(&p.ty)).collect();
    let arg_names: Vec<String> = shape.args.iter().map(|p| p.name.clone()).collect();
    let params: Vec<String> = c
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, rust_type(&p.ty)))
        .collect();
    let _ = writeln!(
        out,
        "/// The JavaScript provider, as `{}` sees it.\npub type ProviderFn = FunctionRef<FnArgs<({})>, {}>;\n\n/// What `user_data` points at while a batch call runs.\npub struct HostSlot {{\n    pub env: Cell<Option<Env>>,\n    pub func: ProviderFn,\n    pub error: Cell<Option<String>>,\n}}\n\nunsafe extern \"C\" fn {}({}) -> {} {{\n    // SAFETY: `user_data` is the `HostSlot` this module registered in the\n    // constructor, alive while the context is.\n    let slot = unsafe {{ &*user_data.cast::<HostSlot>() }};\n    let Some(env) = slot.env.get() else {{\n        slot.error.set(Some(String::from(\"provider called outside a batch call\")));\n        return -1001;\n    }};\n    let called = slot.func.borrow_back(&env).and_then(|f| f.call(({}).into()));\n    match called {{\n        Ok(value) => {{\n            // SAFETY: the library passes a valid, writable out pointer.\n            unsafe {{ {}.write(value.to_ffi()) }};\n            0\n        }}\n        Err(err) => {{\n            slot.error.set(Some(err.to_string()));\n            -1002\n        }}\n    }}\n}}\n",
        c.name,
        arg_types.join(", "),
        binding_name(api, shape.out),
        trampoline_name(c),
        params.join(", "),
        rust_type(&c.returns),
        arg_names.join(", "),
        shape.out_param.name
    );
}

fn render_class(out: &mut String, api: &Api, opaque: &str) {
    let name = binding_name(api, opaque);
    let has_provider =
        constructor(api).is_some_and(|f| f.params.iter().any(|p| p.role == Role::VtableIn));
    let opaque_doc = api
        .opaques
        .iter()
        .find(|o| o.name == opaque)
        .map(|o| o.doc.clone())
        .unwrap_or_default();
    let _ = writeln!(
        out,
        "{}#[napi]\npub struct {name} {{\n    handle: *mut ffi::{opaque},\n{}}}\n\n#[napi]\nimpl {name} {{",
        doc(&opaque_doc, ""),
        if has_provider {
            "    host: Option<Box<HostSlot>>,\n"
        } else {
            ""
        }
    );
    if let Some(ctor) = constructor(api) {
        render_constructor(out, api, ctor, &name);
    }
    for m in methods(api) {
        render_method(out, api, m, opaque, has_provider);
    }
    let _ = writeln!(out, "}}\n");
    if let Some(free) = destructor(api) {
        let _ = writeln!(
            out,
            "impl Drop for {name} {{\n    fn drop(&mut self) {{\n        // SAFETY: the handle came from the constructor and is dropped once.\n        unsafe {{ ffi::{}(self.handle) }};\n    }}\n}}\n",
            free.name
        );
    }
}

fn render_constructor(out: &mut String, api: &Api, ctor: &FunctionDef, name: &str) {
    let mut params = Vec::new();
    let mut setup = String::new();
    let mut args = Vec::new();
    let mut has_provider = false;
    for p in &ctor.params {
        match p.role {
            Role::StructIn => {
                let Some(s) = pointee_struct(p) else { continue };
                params.push(format!("{}: {}", p.name, binding_name(api, s)));
                let _ = writeln!(setup, "        let raw_{0} = {0}.to_ffi();", p.name);
                args.push(format!("&raw const raw_{}", p.name));
            }
            Role::VtableIn => {
                let Some((vtable, field, callback)) = provider_callback(api) else {
                    continue;
                };
                let Some(shape) = callback_shape(callback) else {
                    continue;
                };
                has_provider = true;
                let arg_types: Vec<String> =
                    shape.args.iter().map(|p| rust_scalar(&p.ty)).collect();
                params.push(format!(
                    "provider: Option<Function<FnArgs<({})>, {}>>",
                    arg_types.join(", "),
                    binding_name(api, shape.out)
                ));
                let _ = writeln!(
                    setup,
                    "        let host = match provider {{\n            Some(f) => Some(Box::new(HostSlot {{ env: Cell::new(None), func: f.create_ref()?, error: Cell::new(None) }})),\n            None => None,\n        }};\n        let vtable = ffi::{0} {{\n            struct_size: core::mem::size_of::<ffi::{0}>() as u32,\n            {1}: Some({2}),\n        }};\n        let (vtable_ptr, user_data): (*const ffi::{0}, *mut c_void) = match &host {{\n            Some(slot) => (&raw const vtable, ptr::from_ref::<HostSlot>(&**slot).cast_mut().cast()),\n            None => (ptr::null(), ptr::null_mut()),\n        }};",
                    vtable.name,
                    field.name,
                    trampoline_name(callback)
                );
                args.push(String::from("vtable_ptr"));
            }
            Role::UserData => args.push(String::from("user_data")),
            Role::HandleOut => {
                let opaque = pointee_opaque(p).unwrap_or_default();
                let _ = writeln!(
                    setup,
                    "        let mut handle: *mut ffi::{opaque} = ptr::null_mut();"
                );
                args.push(String::from("&raw mut handle"));
            }
            _ => {}
        }
    }
    let _ = writeln!(
        out,
        "{}    #[napi(constructor)]\n    pub fn new({}) -> Result<Self> {{\n{setup}\n        // SAFETY: every pointer is valid for the call; `user_data` outlives the context.\n        let status = {};\n        check(status, 0)?;\n        Ok({name} {{ handle{} }})\n    }}\n",
        doc(&ctor.doc, "    "),
        params.join(", "),
        call(ctor, &args),
        if has_provider { ", host" } else { "" }
    );
}

/// The zeroed, size-stamped out struct a call fills in.
fn zeroed_out_struct(s: &str) -> String {
    format!(
        "        // SAFETY: every field of the struct is a plain integer, so zero is a valid value.\n        let mut raw: ffi::{s} = unsafe {{ core::mem::zeroed() }};\n        raw.struct_size = core::mem::size_of::<ffi::{s}>() as u32;\n"
    )
}

fn render_method(out: &mut String, api: &Api, m: &FunctionDef, opaque: &str, has_provider: bool) {
    let method = method_name(api, opaque, m);
    let mut params = Vec::new();
    let mut args = Vec::new();
    let mut setup = String::new();
    let mut returns = String::from("()");
    let mut finish = String::from("        Ok(())");
    let mut needs_env = false;
    for p in &m.params {
        match p.role {
            Role::Handle => args.push(String::from("self.handle")),
            Role::Value => {
                params.push(format!("{}: {}", p.name, rust_scalar(&p.ty)));
                args.push(p.name.clone());
            }
            Role::StructOut => {
                let Some(s) = pointee_struct(p) else { continue };
                setup.push_str(&zeroed_out_struct(s));
                args.push(String::from("&raw mut raw"));
                returns = binding_name(api, s);
                finish = format!("        {returns}::from_ffi(&raw)");
            }
            Role::BlobOut => {
                let Some(s) = pointee_struct(p) else { continue };
                let _ = writeln!(
                    setup,
                    "        let mut blob = ffi::{s} {{ data: ptr::null_mut(), len: 0, cap: 0 }};"
                );
                args.push(String::from("&raw mut blob"));
                returns = String::from("Buffer");
                needs_env = has_provider;
                finish = String::from(
                    "        // SAFETY: the descriptor is the Vec the library leaked for us; both sides share the Rust allocator.\n        let bytes = unsafe { Vec::from_raw_parts(blob.data, blob.len, blob.cap) };\n        Ok(Buffer::from(bytes))",
                );
            }
            _ => {}
        }
    }
    if !returns_status(m) {
        if let Some(scalar) = returned_scalar(m) {
            returns = scalar.to_string();
            finish = String::from("        Ok(value)");
        }
    }
    let provider_code = match provider_code_function(api) {
        Some(f) if returns_status(m) && has_provider => {
            format!("unsafe {{ ffi::{}(self.handle) }}", f.name)
        }
        _ => String::from("0"),
    };
    let env_param = if needs_env { "env: Env, " } else { "" };
    let env_set = if needs_env {
        "        if let Some(slot) = &self.host { slot.env.set(Some(env)); slot.error.set(None); }\n"
    } else {
        ""
    };
    let env_clear = if needs_env {
        "        if let Some(slot) = &self.host {\n            slot.env.set(None);\n            if let Some(message) = slot.error.take() { return Err(Error::from_reason(format!(\"provider threw: {message}\"))); }\n        }\n"
    } else {
        ""
    };
    let call = if returns_status(m) {
        format!(
            "        let status = {};\n{env_clear}        check(status, {provider_code})?;",
            call(m, &args)
        )
    } else {
        format!("        let value = {};\n{env_clear}", call(m, &args))
    };
    let _ = writeln!(
        out,
        "{}    #[napi]\n    pub fn {method}(&self, {env_param}{}) -> Result<{returns}> {{\n{setup}{env_set}        // SAFETY: the handle is live; every pointer is valid for the call.\n{call}\n{finish}\n    }}\n",
        doc(&m.doc, "    "),
        params.join(", ")
    );
}

fn render_free_function(out: &mut String, api: &Api, f: &FunctionDef) {
    let name = strip_prefix(&f.name, &api.prefix);
    let mut params = Vec::new();
    let mut args = Vec::new();
    let mut setup = String::new();
    let mut returns = String::from("()");
    let mut finish = String::from("        Ok(())");
    for p in &f.params {
        match p.role {
            Role::Value => {
                if let TypeRef::Enum { name: e } = &p.ty {
                    params.push(format!("{}: {}", p.name, binding_name(api, e)));
                    args.push(format!("{}.to_ffi_enum()", p.name));
                } else {
                    params.push(format!("{}: {}", p.name, rust_scalar(&p.ty)));
                    args.push(p.name.clone());
                }
            }
            Role::StructOut => {
                let Some(s) = pointee_struct(p) else { continue };
                setup.push_str(&zeroed_out_struct(s));
                args.push(String::from("&raw mut raw"));
                returns = binding_name(api, s);
                finish = format!("        {returns}::from_ffi(&raw)");
            }
            _ => {}
        }
    }
    let call = if returns_status(f) {
        format!(
            "        let status = {};\n        check(status, 0)?;",
            call(f, &args)
        )
    } else if message_function(api).is_some_and(|m| m.name == f.name) {
        returns = String::from("String");
        finish = String::from(
            "        // SAFETY: the library returns a static NUL-terminated string.\n        Ok(unsafe { CStr::from_ptr(value) }.to_string_lossy().into_owned())",
        );
        format!("        let value = {};", call(f, &args))
    } else {
        if let Some(scalar) = returned_scalar(f) {
            returns = scalar.to_string();
        }
        finish = String::from("        Ok(value)");
        format!("        let value = {};", call(f, &args))
    };
    let _ = writeln!(
        out,
        "{}#[napi]\npub fn {name}({}) -> Result<{returns}> {{\n{setup}    // SAFETY: plain values in, plain values out.\n{call}\n{finish}\n}}\n",
        doc(&f.doc, ""),
        params.join(", ")
    );
}
